Repository truenas/documentation, pull requests merged in 2021-08, with the labels that each got.

#999 DOCS-2342: TrueNAS 12.0-U5 Release Notes
  content/ReleaseNotes/CORE/12.0-U5.md
Labels: Work In Progress

#1009 DOCS-2404: Cloud Sync Exclude Files Example
  static/includes/TasksCloudSyncAddFields.md.part
Labels: Work In Progress

#1008 DOCS-1508: TCCloudSecurity
  content/TrueCommand/Recommendations/TCCloudSecurity.md
Labels: New Article

#1001 DOCS-2369: Combine TrueCommand VM Deploy Instructions Into Main Insta…
  content/TrueCommand/TCGettingStarted/Install/VMDeploy.md
  content/TrueCommand/TCGettingStarted/Install/_index.md
Labels: File Moved

#1021 TC Docs: Remove empty articles.
  content/TrueCommand/Alerts/AlertManage.md
  content/TrueCommand/Reports/Creation.md
  content/TrueCommand/TCGettingStarted/ConfigureAlert.md
  content/TrueCommand/TCGettingStarted/CreateReport.md
  content/TrueCommand/TCGettingStarted/_index.md
Labels: File Moved

#1023 DOCS-2225 (vCenter Plugin): Document Fibre Channel options in Datastore article
  content/CORE/Solutions/Integrations/VMware/TrueNASvCenterPlugin/Datastore.md
  static/images/vCenterPlugin/VMFSDatastoreSettings.png
Labels: Work In Progress

#1038 DOCS-2480: Upload new vCenter images
  static/images/vCenterPlugin/DatastoreList.png
  static/images/vCenterPlugin/RBACRoles.png
  static/images/vCenterPlugin/VMFSDatastoreSettings.png
Labels: Work In Progress

#1041 DOCS-2223: Write vCenter 3.4.0 Release Notes
  content/ReleaseNotes/vCenterPlugin/3.4.0.md
Labels: Work In Progress
