Repository truenas/documentation, pull requests merged in 2022-05, with the labels that each got.

#1337 DOCS-3655-Review-ZFS-terminology-content
  content/References/ConceptsAndTerms.md
Labels: Technical Writer Review (MJ)

#1339 improved some sentences in L2ARC
  content/References/L2ARC.md
Labels: Technical Writer Review (MJ)

#1350 Docs-3579 Update Pools Articles
  content/CORE/CORETutorials/DirectoryServices/ActiveDirectory.md
  content/CORE/CORETutorials/JailsPluginsVMs/Jails/SettingUpJailStorage.md
  content/CORE/CORETutorials/Sharing/SMB/ManagingSMBShares.md
  content/CORE/CORETutorials/Sharing/SMB/SMBShare.md
  content/CORE/CORETutorials/Storage/Pools/Datasets.md
  content/CORE/CORETutorials/Storage/Pools/ManagingPools.md
  content/CORE/CORETutorials/Storage/Pools/Permissions.md
  content/CORE/CORETutorials/Storage/Pools/PoolCreate.md
  content/CORE/CORETutorials/Storage/Pools/StorageEncryption.md
  content/CORE/CORETutorials/Storage/Pools/Zvols.md
  content/CORE/CORETutorials/Storage/Snapshots.md
  content/CORE/GettingStarted/Applications.md
  content/CORE/UIReference/Storage/Disks/DisksScreens.md
  content/CORE/UIReference/Storage/Pools/Datasets.md
  content/CORE/UIReference/Storage/Pools/DatasetsScreen.md
  content/CORE/UIReference/Storage/Pools/Permissions.md
  content/CORE/UIReference/Storage/Pools/PoolsScreens.md
  content/CORE/UIReference/Storage/Pools/StorageEncryption.md
  content/CORE/UIReference/Storage/Pools/Zvols.md
  content/CORE/UIReference/Storage/Pools/ZvolsScreen.md
  content/_includes/TNHardwareGuide.md
  static/images/CORE/13.0/AddDatasetAdvancedOptions.png
  static/images/CORE/13.0/AddDatasetAdvancedOptionsScreen2.png
  static/images/CORE/13.0/AddDatasetAdvancedOptionsScreenBottom.png
  static/images/CORE/13.0/AddDatasetAdvancedOptionsTop.png
  static/images/CORE/13.0/AddDatasetBasicOptionsScreen.png
  static/images/CORE/13.0/AddVdevsScreen.png
  static/images/CORE/13.0/AddZvolAdvancedOptionScreen.png
  static/images/CORE/13.0/CreateImportPoolScreen.png
  static/images/CORE/13.0/CreatePoolScreen.png
  static/images/CORE/13.0/DatasetEditPermissionsScreen.png
  static/images/CORE/13.0/PoolStatusScreen.png
  static/images/CORE/13.0/StorageDiskEditPoolDiskScreen.png
  static/images/CORE/13.0/StoragePoolsActionOptions.png
  static/images/CORE/13.0/StoragePoolsEditACLBottom.png
  static/images/CORE/13.0/StoragePoolsEditACLTop.png
  static/images/CORE/13.0/StoragePoolsEditPermissionsScreen.png
  static/images/CORE/13.0/StoragePoolsScreen.png
Labels: Technical Writer Review (TR)

#1353 Docs-3586 Update SLOG Overprovisioning Article
  content/CORE/CORETutorials/Storage/Pools/SLOGOverprovision.md
  static/images/CORE/13.0/SystemAdvancedScreen.png
Labels: Technical Writer Review (TR)

#1355 Docs-3588 Update VMware-Snapshots Article
  content/CORE/CORETutorials/Storage/VMware-Snapshots.md
  content/CORE/UIReference/Storage/VMware-SnapshotsScreen.md
Labels: Technical Writer Review (TR)

#1358 Docs-3590 Update Storage Disks Articles
  content/CORE/CORETutorials/Storage/Disks/DiskReplace.md
  content/CORE/CORETutorials/Storage/Disks/DiskWipe.md
  content/CORE/CORETutorials/Storage/ImportDisk.md
  content/CORE/UIReference/Storage/Disks/DiskWipe.md
  content/CORE/UIReference/Storage/Disks/DisksScreens.md
  static/images/CORE/13.0/StorageDiskInformationScreen.png
  static/images/CORE/13.0/StorageDisksEditScreen.png
  static/images/CORE/13.0/StorageDisksScreen.png
  static/images/CORE/13.0/StorageImportDiskScreen.png
Labels: Technical Writer Review (TR)

#1357 Docs-3587 Update Snapshots Articles
  content/CORE/CORETutorials/Storage/Snapshots.md
  content/CORE/UIReference/Storage/Snapshots.md
  content/CORE/UIReference/Storage/SnapshotsScreen.md
  content/_includes/BrowsingSnapshotCollections1.md
  content/_includes/BrowsingSnapshotCollections2.md
  content/_includes/SnapshotsIntroSnippet.md
  content/_includes/SnapshotsSnippet.md
  static/images/CORE/13.0/AddSnapShotScreen.png
  static/images/CORE/13.0/DatasetRollbackFromSnapshot.png
  static/images/CORE/13.0/StorageSnapshoExpandedtInfoScreen.png
  static/images/CORE/13.0/StorageSnapshotsScreen.png
Labels: Technical Writer Review (TR)

#1364 Docs-3559 Update Plugins Articles
  content/CORE/CORETutorials/JailsPluginsVMs/Plugins/CreatingCustomPlugin.md
  content/CORE/CORETutorials/JailsPluginsVMs/Plugins/ManagingPlugins.md
  content/CORE/UIReference/JailsPluginsVMs/Plugins/PluginsScreens.md
  content/_includes/JailNetworkPropertiesFields.md
  content/_includes/JailsBasicPropertiesFields.md
  static/images/CORE/13.0/PluginDetailScreen.png
  static/images/CORE/13.0/PluginsAddScreen.png
  static/images/CORE/13.0/PluginsAdvancedAddBasicProperties.png
  static/images/CORE/13.0/PluginsAdvancedAddCustomProperties.png
  static/images/CORE/13.0/PluginsAdvancedAddJailProperties.png
  static/images/CORE/13.0/PluginsAdvancedAddNetworkProperties.png
  static/images/CORE/13.0/PluginsScreen.png
Labels: Technical Writer Review (TR)

#1365 Docs-3570 Update Fibre Channel Articles
  content/CORE/CORETutorials/Sharing/iSCSI/SettingUpFibreChannel.md
  content/CORE/UIReference/Sharing/iSCSI/FibreChannel.md
  static/images/CORE/13.0/FibreChannelAssoicatedTargetsScreen.png
  static/images/CORE/13.0/FibreChannelPortConnectedInitiators12U8.png
  static/images/CORE/13.0/FibreChannelPortsScreen.png
  static/images/CORE/13.0/FibreChannelPortsScreenExpanded.png
Labels: Technical Writer Review (TR)

#1368 Docs-3732 Update Contacting Support Snippet
  static/includes/General/iXsystemsSupportContact.html.part
Labels: Technical Writer Review (TR)

#1359 DOCS-3604 CORE 13.0 Reorganization - Update the Replications Task Article
  content/CORE/CORETutorials/JailsPluginsVMs/Plugins/ManagingPlugins.md
  content/CORE/CORETutorials/Tasks/CreatingPeriodicSnapshotTasks.md
  content/CORE/CORETutorials/Tasks/CreatingReplicationTasks/AdvancedReplication.md
  content/CORE/CORETutorials/Tasks/CreatingReplicationTasks/LocalReplication.md
  content/CORE/CORETutorials/Tasks/CreatingReplicationTasks/RemoteReplication.md
  content/CORE/CORETutorials/Tasks/CreatingReplicationTasks/TroubleshootingTips.md
  content/CORE/CORETutorials/Tasks/CreatingReplicationTasks/_index.md
  content/CORE/CORETutorials/Tasks/ReplicationTasks/Advanced.md
  content/CORE/CORETutorials/Tasks/ReplicationTasks/LocalReplication.md
  content/CORE/CORETutorials/Tasks/ReplicationTasks/Remote.md
  content/CORE/CORETutorials/Tasks/ReplicationTasks/TroubleshootingTips.md
  content/CORE/CORETutorials/Tasks/ReplicationTasks/_index.md
  content/CORE/UIReference/Storage/Snapshots.md
  content/CORE/UIReference/Tasks/ReplicationTasks.md
  content/CORE/UIReference/Tasks/ReplicationTasks/Advanced.md
  content/CORE/UIReference/Tasks/ReplicationTasks/Remote.md
  content/CORE/UIReference/Tasks/ReplicationTasks/TroubleshootingTips.md
  content/CORE/UIReference/Tasks/ReplicationTasks/_index.md
  content/SCALE/SCALEUIReference/DataProtection/PeriodicSnapshotTasksSCALE.md
  static/images/CORE/12.0/TasksReplicationTasksAddLocalSourceRemoteDestWeeklyCustomLife.png
  static/includes/Reference/TasksReplicationAddAdvancedFields.md.part
  static/includes/Reference/TasksReplicationAddWizardFields.md.part
Labels: Technical Writer Review (MJ)

#1345 DOCS-3600 Update Rsync Task Article
  content/CORE/CORETutorials/Services/ConfiguringRsync.md
  content/CORE/CORETutorials/Tasks/CreatingRsyncTasks.md
  content/CORE/CORETutorials/Tasks/Rsync.md
  content/CORE/UIReference/Tasks/Rsync.md
Labels: Technical Writer Review (MJ)

#1347 DOCS-3597 Update Cron Job Article
  content/CORE/CORETutorials/Tasks/CreatingCronJobs.md
  content/CORE/CORETutorials/Tasks/CronJobs.md
  content/CORE/UIReference/Tasks/CronJobs.md
  static/includes/Reference/TasksCronJobsAddFields.md.part
Labels: Technical Writer Review (MJ)

#1344 DOCS-3595 Update Advanced Scheduler Snippet
  content/CORE/CORETutorials/Tasks/UsingAdvancedScheduler.md
  content/CORE/UIReference/Tasks/AdvancedScheduler.md
Labels: Technical Writer Review (MJ)

#1349 DOCS-3602 Update SMART Test Article
  content/CORE/CORETutorials/Services/ConfigureDynamicDNS.md
  content/CORE/CORETutorials/Services/ConfigureUPS.md
  content/CORE/CORETutorials/Services/ConfiguringFTP.md
  content/CORE/CORETutorials/Services/ConfiguringLLDP.md
  content/CORE/CORETutorials/Services/ConfiguringOpenVPN.md
  content/CORE/CORETutorials/Services/ConfiguringS3.md
  content/CORE/CORETutorials/Services/ConfiguringSMART.md
  content/CORE/CORETutorials/Services/ConfiguringSNMP.md
  content/CORE/CORETutorials/Services/ConfiguringSSH.md
  content/CORE/CORETutorials/Services/ConfiguringTFTP.md
  content/CORE/CORETutorials/Services/FTPTFTP.md
  content/CORE/CORETutorials/Services/S3forMinIO.md
  content/CORE/CORETutorials/Tasks/RunningSMARTTests.md
  content/CORE/UIReference/Services/DynamicDNSScreen.md
  content/CORE/UIReference/Services/FTPScreen.md
  content/CORE/UIReference/Services/LLDPScreen.md
  content/CORE/UIReference/Services/NFSScreen.md
  content/CORE/UIReference/Services/OpenVPNScreen.md
  content/CORE/UIReference/Services/S3Screen.md
  content/CORE/UIReference/Services/SMARTScreen.md
  content/CORE/UIReference/Services/SMBScreen.md
  content/CORE/UIReference/Services/SNMPScreen.md
  content/CORE/UIReference/Services/ServicesSSH.md
  content/CORE/UIReference/Services/TFTPScreen.md
  content/CORE/UIReference/Services/UPSScreen.md
  content/CORE/UIReference/Services/WebDAVScreen.md
  content/CORE/UIReference/Tasks/SMARTTests.md
Labels: Technical Writer Review (MJ)

#1348 DOCS-3598 Update Tasks Initial Shutdown Scripts Article
  content/CORE/CORETutorials/Tasks/CreatingInitShutdownScripts.md
  content/CORE/CORETutorials/Tasks/InitShutdownScripts.md
  content/CORE/UIReference/Tasks/InitShutdownScripts.md
Labels: Technical Writer Review (MJ)

#1356 DOCS-3596 CORE 13.0 Reorganization - Update Task Article
  content/CORE/CORETutorials/Tasks/_index.md
Labels: Technical Writer Review (MJ)

#1376 DOCS-3767-Update-smartctl.8-manpage-link
  content/CORE/CORETutorials/Tasks/RunningSMARTTests.md
  content/CORE/UIReference/Storage/Disks/DisksScreens.md
  content/SCALE/SCALEUIReference/DataProtection/SMARTTestsSCALE.md
  content/SCALE/SCALEUIReference/Storage/DisksSCALE.md
  static/includes/Reference/TasksSMARTAddFields.md.part
Labels: Work In Progress
