Repository truenas/documentation, pull requests merged in 2022-08, with the labels that each got.

#1449 DOCS-4068: Add TC 2.1 singlehtml build to archive and bump TC documen…
  content/Archive.md
  content/_index.md
Labels: TC 2.2 Docs

#1448 DOCS-2833: TC 2.2 Release Notes
  content/TrueCommand/TCReleaseNotes.md
Labels: TC 2.2 Docs

#1450 DOCS-2833: Add data backup warning to release notes.
  content/TrueCommand/TCGettingStarted/Install/UpdateDocker.md
  content/TrueCommand/TCReleaseNotes.md
Labels: TC 2.2 Docs

#1424 DOCS-3867: TrueCommand 2.2 & SCALE Clustering Documentation
  content/SCALE/GettingStarted/ClusterPreparation.md
  content/SCALE/SCALETutorials/Storage/_index.md
  content/SCALE/SCALEUIReference/Network/_index.md
  content/SCALE/SCALEUIReference/Storage/_index.md
  content/Solutions/Integrations/SMBClustering.md
  content/TrueCommand/Clustering/ClusterVolumes.md
  content/TrueCommand/Clustering/ManageClusters.md
  content/TrueCommand/Clustering/MountingClusterVolumes.md
  content/TrueCommand/Clustering/_index.md
  content/TrueCommand/Clusters.md
  content/TrueCommand/SystemManagement/MultiSystems.md
  content/_includes/ClusterIntro.md
  content/_includes/ClusterRequirements.md
  content/_includes/ClusterSetup.md
  content/_includes/ClusterTypes.md
  content/_includes/ClusterWarnings.md
  static/images/TrueCommand/2.2/ClusterCard.png
  static/images/TrueCommand/2.2/ClusterCardwithVolume.png
  static/images/TrueCommand/2.2/ClustersClusterVolumeExpanded.png
  static/images/TrueCommand/2.2/ClustersClusterVolumeExpandedCreateShare.png
  static/images/TrueCommand/2.2/ClustersClusterVolumeExpandedShareOptions.png
  static/images/TrueCommand/2.2/ClustersCreateVolumeConfirmation.png
  static/images/TrueCommand/2.2/ClustersCreateVolumeDetails.png
  static/images/TrueCommand/2.2/ClustersScreen.png
  static/images/TrueCommand/2.2/ConfigureClusterActiveDirectory.png
  static/images/TrueCommand/2.2/ConfigureClusterReview.png
  static/images/TrueCommand/2.2/ConfigureClusterSMBNetwork.png
  static/images/TrueCommand/2.2/CreateClusterReview.png
  static/images/TrueCommand/2.2/CreateClusterSystems.png
  static/images/TrueCommand/2.2/CreateClusterSystemsNetwork.png
  static/images/TrueCommand/2.2/WindowsFileExplorereAccessClusterShare.png
  static/images/TrueCommand/2.2/WindowsServerDNSManagerReverseLookupZones.png
  static/images/TrueCommand/2.2/WindowsServerDNSManagerReverseLookupZonesPointers.png
  static/images/TrueCommand/2.2/WindowsServerDNSManagerReverseLookupZonesPointersAdd.png
  static/images/TrueCommand/2.2/WindowsServerManagerToolsDNS.png
Labels: TC 2.2 Docs, Technical Writer Review (MJ)

#1451 DOCS-3910: Link to previous version downloads
  content/TrueNASUpgrades/_index.md
Labels: Work In Progress

#1431 Docs-3943 TC 2.2 Update SAML Article and Fix Image Links
  content/TrueCommand/Administration/Settings/SAML.md
  content/TrueCommand/Administration/Settings/SAMLAD.md
  content/TrueCommand/Administration/Settings/SAMLGA.md
  static/images/SAML/OpenPowershellTypeInvokeCommand.png
  static/images/SAML/TC2.2-EditPropertiesEndpointsEnterTrustedURLSLO.png
  static/images/SAML/TC2.2PowershellInvokeCommand.png
  static/images/SAML/TC2.2SAMLSettings.png
Labels: TC 2.2 Docs, Technical Writer Review (TR)

#1464 DOCS-4114: Add disk quantity guidance to the hardware guide.
  content/_includes/TNHardwareGuide.md
Labels: Technical Writer Review (TR)

#1462 DOCS-4115: Add description and link to Software Status page
  content/CORE/COREReleaseNotes.md
  content/SCALE/SCALEReleaseNotes.md
  content/_includes/SoftwareStatusPage.md
  content/_includes/TNLifecycle.md
Labels: Technical Writer Review (TR)

#1468 DOCS-3748 core 13 post reorg update directory services articles
  content/CORE/CORETutorials/DirectoryServices/ActiveDirectory.md
  content/CORE/CORETutorials/DirectoryServices/Kerberos.md
  content/CORE/CORETutorials/DirectoryServices/LDAP.md
  content/CORE/CORETutorials/DirectoryServices/NIS.md
  content/CORE/UIReference/DirectoryServices/ADScreen.md
  content/CORE/UIReference/DirectoryServices/IdmapScreen.md
  content/CORE/UIReference/DirectoryServices/KerberosScreens.md
  content/CORE/UIReference/DirectoryServices/LDAPScreen.md
  content/CORE/UIReference/DirectoryServices/NISScreen.md
Labels: Review (TM)

#1472 Docs-4112 Reorganize iSCSI Shares Articles
  content/SCALE/SCALETutorials/Shares/iSCSI/AddingISCSIShares.md
  content/SCALE/SCALETutorials/Shares/iSCSI/IncreaseISCSIStorage.md
  content/SCALE/SCALETutorials/Shares/iSCSI/UsingISCSIShares.md
  content/SCALE/SCALETutorials/Shares/iSCSI/_index.md
  content/SCALE/SCALEUIReference/Shares/iSCSI/iSCSISharesScreens.md
  static/images/SCALE/22.02/AddiSCSITargetScreen.png
  static/images/SCALE/22.02/BlockiSCSIShareTargetsWidgetToolbar.png
  static/images/SCALE/22.02/SharingISCSIAssociatedTargetsAdd.png
  static/images/SCALE/22.02/SharingISCSIExtentsAddScreentop.png
  static/images/SCALE/22.02/SharingISCSIExtentsEditScreenBottom.png
  static/images/SCALE/22.02/SharingISCSIInitiatorsAddScreen.png
  static/images/SCALE/22.02/SharingScreenWithiSCSIShareAdded.png
  static/images/SCALE/22.02/SharingiSCSIAssociatedTargetsScreen.png
  static/images/SCALE/22.02/SharingiSCSIAuthAccessAddScreen.png
  static/images/SCALE/22.02/SharingiSCSIAuthAccessNoAuthAccess.png
  static/images/SCALE/22.02/SharingiSCSIAuthorizedAccessScreen.png
  static/images/SCALE/22.02/SharingiSCSIExtentAddFilename.png
  static/images/SCALE/22.02/SharingiSCSIExtentsScreen.png
  static/images/SCALE/22.02/SharingiSCSIInitiatorsGroupsScreen.png
  static/images/SCALE/22.02/SharingiSCSIPortalsAddScreen.png
  static/images/SCALE/22.02/SharingiSCSIPortalsScreen.png
  static/images/SCALE/22.02/SharingiSCSITargetGlobalConfigurationScreen.png
  static/images/SCALE/22.02/SharingiSCSITargetsScreen.png
  static/images/SCALE/22.02/iSCSINoTargetsScreen.png
  static/images/SCALE/22.02/iSCSIWizardConfirmOptionsScreen.png
  static/images/SCALE/22.02/iSCSIWizardCreateBlockDeviceAddFileType.png
  static/images/SCALE/22.02/iSCSIWizardCreateBlockDeviceAddNewDevice.png
  static/images/SCALE/22.02/iSCSIWizardCreateBlockDeviceScreen.png
  static/images/SCALE/22.02/iSCSIWizardInitiatorScreen.png
  static/images/SCALE/22.02/iSCSIWizardPortalCreateNewDiscoveryAuthenticationGroup.png
  static/images/SCALE/22.02/iSCSIWizardPortalScreen.png
Labels: Review (TM)

#1476 DOCS-3650: The SCALE Dashboard Tour Video
  content/SCALE/GettingStarted/FirstTimeLogin.md
Labels: Review (TM)

#1477 Docs-3430 Reorganize NFS Articles
  content/SCALE/SCALETutorials/Shares/NFS/AddingNFSShares.md
  content/SCALE/SCALETutorials/Shares/NFS/_index.md
  content/SCALE/SCALEUIReference/Shares/NFS/NFSServiceScreen.md
  content/SCALE/SCALEUIReference/Shares/NFS/NFSSharesScreens.md
  content/SCALE/SCALEUIReference/Shares/NFS/_index.md
  static/images/SCALE/22.02/AddNFSAdvancedOptionsAccessSettings.png
  static/images/SCALE/22.02/AddNFSBasicOptionsScreen.png
  static/images/SCALE/22.02/NFSShareWidgetDeleteDialog.png
  static/images/SCALE/22.02/NFSShareWidgetNoShare.png
  static/images/SCALE/22.02/NFSShareWidgetWithShare.png
  static/images/SCALE/22.02/NFSWidgetOptions.png
  static/images/SCALE/22.02/ServicesNFSSettingsScreen.png
  static/images/SCALE/22.02/SharingNFSDeleteDialog.png
  static/images/SCALE/22.02/SharingNFSDetailScreenOptions.png
  static/images/SCALE/22.02/SharingNFSEnableServiceDialog.png
  static/images/SCALE/22.02/SharingNFSWidgetWithShare.png
Labels: Review (TM)

#1474 Docs-3050 13.0-U2 Release Notes
  content/CORE/COREReleaseNotes.md
Labels: Technical Writer Review (TR)
