Repository truenas/documentation, pull requests merged in 2022-03, with the labels that each got.

#1290 DOCS-3211 Document new + Add a backup credential button
  content/SCALE/DataProtection/Cloud Sync Tasks/_index.md
Labels: Technical Writer Review

#1292 DOCS-3156 Review Notices Articles and remove content that no longer applies to 13.0
  content/Archive.md
  content/CORE/Notices/9.3to9.10UpgradeFAQ.md
  content/CORE/Notices/MicrosoftLDAPDefaults2020.md
  content/CORE/Notices/PersistentL2ARCin12.0.md
  content/CORE/Notices/PoolCorrupt2020.md
  content/CORE/Notices/RecommendedUpdateforZFS.md
  content/CORE/Notices/ScrubResilverAdjustments.md
  content/CORE/System/Update/_index.md
Labels: Technical Writer Review

#1294 Docs 3212 update scale min io article with recent changes
  content/SCALE/Apps/MinIOClustersSCALE.md
  static/images/SCALE/22.02/AppsConfirmOptionsMinio.png
  static/images/SCALE/22.02/AppsContainerEntrypointsMinIO.png
  static/images/SCALE/22.02/AppsContainerEnvironmentVariablesMinIO.png
  static/images/SCALE/22.02/AppsContainerImagesMinIO.png
  static/images/SCALE/22.02/AppsLaunchDockerImage.png
  static/images/SCALE/22.02/AppsMinIOAdvancedDNSSettings.png
  static/images/SCALE/22.02/AppsMinIOApplicationName.png
  static/images/SCALE/22.02/AppsMinIOConfiguration.png
  static/images/SCALE/22.02/AppsMinIOConfiguration2.png
  static/images/SCALE/22.02/AppsMinIOEnvironmentalVariables.png
  static/images/SCALE/22.02/AppsMinIOStorage.png
  static/images/SCALE/22.02/AppsMinIOWorkloadConfiguration.png
  static/images/SCALE/22.02/AppsScalingUpgradePolicyMinIO.png
  static/images/SCALE/22.02/AppsStorageMinIO.png
Labels: Technical Writer Review (TR)

#1301 DOCS-3229: SCALE 22.02 Add Dataset Form Change
  content/SCALE/Storage/Pools/DatasetsSCALE.md
  static/images/SCALE/22.02/SCALE22DatasetOptions.png
  static/images/SCALE/SCALEDatasetOptions.png
Labels: Technical Writer Review (TR)

#1299 DOCS-2254: Organize TrueCommand 2.0 Image Fies
  content/TrueCommand/Administration/Settings/_index.md
  content/TrueCommand/SystemManagement/SingleSystem/ConfigBackups.md
  content/TrueCommand/SystemManagement/SingleSystem/TrueCommandSharing.md
  content/TrueCommand/SystemManagement/SingleSystem/TrueCommandSnapshots.md
  content/TrueCommand/SystemManagement/SingleSystem/TrueCommandStorageManagement.md
  content/TrueCommand/SystemManagement/SingleSystem/_index.md
  content/TrueCommand/TCGettingStarted/ConnectingTrueNAS.md
  content/TrueCommand/TCGettingStarted/Install/_index.md
  static/images/TrueCommand/2.0/TC20AdministrationAbout.png
  static/images/TrueCommand/2.0/TC20AdministrationCertificates.png
  static/images/TrueCommand/2.0/TC20NewSystemCreds.png
  static/images/TrueCommand/2.0/TC20TrueCommandBackupStats.png
  static/images/TrueCommand/2.0/TC20TrueCommandConfigBackups.png
  static/images/TrueCommand/2.0/TC20TrueCommandCreateNFS (1).png
  static/images/TrueCommand/2.0/TC20TrueCommandCreateNFS.png
  static/images/TrueCommand/2.0/TC20TrueCommandCreateOneTimeSnapshot.png
  static/images/TrueCommand/2.0/TC20TrueCommandCreateSnapshotTask.png
  static/images/TrueCommand/2.0/TC20TrueCommandDatasetsForm.png
  static/images/TrueCommand/2.0/TC20TrueCommandDeleteBackups.png
  static/images/TrueCommand/2.0/TC20TrueCommandNFSCustom.png
  static/images/TrueCommand/2.0/TC20TrueCommandNFSProfile.png
  static/images/TrueCommand/2.0/TC20TrueCommandRestoreDatabase.png
  static/images/TrueCommand/2.0/TC20TrueCommandSMBCustom.png
  static/images/TrueCommand/2.0/TC20TrueCommandSMBProfile.png
  static/images/TrueCommand/2.0/TC20TrueCommandSelectPool.png
  static/images/TrueCommand/2.0/TC20TrueCommandSingleSystemDashboard.png
  static/images/TrueCommand/2.0/TC20TrueCommandTimezone.png
  static/images/TrueCommand/2.0/TC20TrueCommandViewShares.png
  static/images/TrueCommand/2.0/TC20TrueCommandViewSnapshots.png
  static/images/TrueCommand/2.0/TC20TrueCommandZvolsForm.png
Labels: Technical Writer Review (TR)

#1305 DOCS-3226: New System/Advanced/Replication Feature 13.0
  content/CORE/System/Advanced.md
  static/images/CORE/13.0/SystemAdvanced13.png
  static/includes/Reference/SystemAdvancedFields.md.part
Labels: 13.0 Documentation

#1309 DOCS-3227: Update Services Article SNMP Options
  content/CORE/Services/SNMP.md
  static/images/CORE/13.0/SNMPOptions13.png
  static/includes/Reference/ServicesSNMPFields.md.part
Labels: 13.0 Documentation

#1307 DOCS-3428: Update CORE Dataset Advanced Options image and text
  content/CORE/Storage/Pools/Datasets.md
  static/images/CORE/12.0-U8/COREAdvancedDatasetOptions.png
Labels: Technical Writer Review (MJ)

#1306 DOCS-3448: Remove TrueChart Known Issue from Angelfish release notes
  content/ReleaseNotes/SCALE/22.02.0.1.md
  content/ReleaseNotes/SCALE/22.02.0.md
Labels: Technical Writer Review (MJ)

#1303 DOCS-3353 SCALE 22.02 Update Shares and Services Articles with Warning about Spaces in Path Name
  content/SCALE/Shares/_index.md
Labels: Technical Writer Review (MJ)

#1310 DOCS-3227: SCALE Update Services Article SNMP
  content/SCALE/SystemSettings/ServicesSCALE.md
  static/images/SCALE/22.02/SCALESNMPOptions.png
  static/includes/Reference/SCALEServicesSNMPFields.md.part
Labels: Technical Writer Review (MJ)

#1313 DOCS-3220: Update Unlocking Replicated Dataset
  content/SCALE/Storage/Pools/EncryptionSCALE.md
  content/_includes/ReplicatedEncryptedUnlock.md
Labels: Technical Writer Review (MJ)
