Repository truenas/documentation, pull requests merged in 2022-10, with the labels that each got.

#1558 Docs 3816 docs hub improve article relationships core part6
  content/CORE/API/_index.md
  content/CORE/CORETutorials/Network/IPMI.md
  content/CORE/CORETutorials/Network/Interfaces/BridgeCreate.md
  content/CORE/CORETutorials/Network/Interfaces/LAGGCreate.md
  content/CORE/CORETutorials/Network/Interfaces/VLANCreate.md
  content/CORE/CORETutorials/UpdatingTrueNAS/UpdatingENTERPRISE.md
  content/CORE/CORETutorials/UpdatingTrueNAS/UpdatingSoftwareforaMajorVersion.md
  content/CORE/UIReference/Accounts/Groups.md
  content/CORE/UIReference/Network/GlobalConfigScreen.md
  content/CORE/UIReference/Network/IPMIScreen.md
  content/CORE/UIReference/Network/InterfacesScreen.md
  content/CORE/UIReference/Network/NetworkSummary.md
  content/CORE/UIReference/Network/NetworkSummaryScreen.md
  content/CORE/UIReference/Network/StaticRoutesScreen.md
  content/CORE/UIReference/ReportingGraphs.md
  content/CORE/UIReference/System/Advanced.md
  content/CORE/UIReference/System/AlertServices.md
  content/CORE/UIReference/System/AlertSettings.md
  content/CORE/UIReference/System/CloudCredentials.md
  content/CORE/UIReference/System/General.md
  content/CORE/UIReference/System/NTPServers.md
  content/CORE/UIReference/System/Reporting.md
  content/CORE/UIReference/System/Update.md
Labels: Technical Writer Review (TR)

#1553 DOCS-3617 Create Docs page for CLI on TrueNAS SCALE
  content/SCALE/SCALETutorials/TrueNASCLIShell/_index.md
  static/images/SCALE/TrueNASCLIlaunch.png
  static/images/SCALE/TrueNASCLInetworkinterfacequery.png
  static/images/SCALE/TrueNASCLIstoragedatasetquery.png
  static/images/SCALE/TrueNASCLIstoragepoolquery.png
  static/images/SCALE/TrueNASCLIsystemupdatemanualpath.png
  static/images/SCALE/TrueNASCLIupdateinterfacealiases.png
Labels: Technical Writer Review (CD)

#1556 Docs-4214 Update General Settings Articles
  content/SCALE/SCALETutorials/Credentials/BackupCredentials/AddCloudCredentials.md
  content/SCALE/SCALETutorials/SystemSettings/AdvancedSettings.md
  content/SCALE/SCALETutorials/SystemSettings/GeneralSettings.md
  content/SCALE/SCALETutorials/SystemSettings/GeneralSettings/GeneralSettings.md
  content/SCALE/SCALETutorials/SystemSettings/GeneralSettings/GetSupportSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/GeneralSettings/ManageSysConfigSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/GeneralSettings/_index.md
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettings.md
  content/SCALE/SCALEUIReference/SystemSettings/EnclosureScreensSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/GeneralSettings.md
  content/SCALE/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/_index.md
  content/_includes/UsingTrueNASCommunityAndSocialMedia.md
  static/images/SCALE/22.02/EnclosureChangeEnclosureLabel.png
  static/images/SCALE/22.02/SystemGeneralAddNTPServer.png
  static/images/SCALE/22.02/SystemGeneralGuiSettings.png
  static/images/SCALE/22.02/SystemGeneralLocalizationSettings.png
  static/images/SCALE/22.02/SystemGeneralResetConfiguration.png
  static/images/SCALE/22.02/SystemGeneralSaveConfiguration.png
  static/images/SCALE/22.02/SystemGeneralScreen.png
  static/images/SCALE/22.02/SystemGeneralSupportWidget.png
  static/images/SCALE/22.02/SystemGeneralUploadConfig.png
  static/images/SCALE/22.02/ViewEnclosureDiskDetailsMini.png
  static/images/SCALE/22.02/ViewEnclosureFrontViewR20.png
  static/images/SCALE/22.02/ViewEnclosureMainDashboard.png
  static/images/SCALE/22.02/ViewEnclosureR20SelectDisk.png
  static/images/SCALE/22.02/ViewEnclosureRearViewR20.png
  static/images/SCALE/22.02/ViewEnclosureScreenMini.png
Labels: Technical Writer Review (CD)

#1561 Docs 4285 fix broken links on docs hub
  content/CORE/COREPreviousVersion.md
  content/CORE/CORETutorials/UpdatingTrueNAS/UpdatingSoftwareforaMajorVersion.md
  content/CORE/UIReference/Storage/Disks/DisksScreens.md
  content/SCALE/SCALETutorials/SystemSettings/Services/FTPServiceSCALE.md
Labels: Technical Writer Review (TR)

#1559 Docs 3816 docs hub improve article relationships core part7
  content/CORE/CORETutorials/Storage/ImportDisk.md
  content/CORE/CORETutorials/Storage/Pools/Permissions.md
  content/CORE/UIReference/Storage/Pools/DatasetsScreen.md
Labels: Technical Writer Review (MJ)

#1575 Update CloudSyncTasksScreensSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
Labels: Technical Writer Review (CD)
