Repository truenas/documentation, pull requests merged in 2022-11, with the labels that each got.

#1574 Mini E and E+ EOL
  content/Hardware/LegacyHardware/TrueNASMinis/MiniBSG(Legacy).md
  content/Hardware/LegacyHardware/TrueNASMinis/MiniEE+HUG.md
  content/Hardware/LegacyHardware/TrueNASMinis/MiniEE+XOOBM.md
  content/Hardware/Mini/MiniBSG.md
  content/Hardware/Mini/MiniNetworkPortIDs.md
Labels: File Moved

#1569 Docs 4286 docs create section on tc cloud setup
  content/TrueCommand/SystemManagement/MultiSystems.md
  content/TrueCommand/TCGettingStarted/AdminAccounts.md
  content/TrueCommand/TCGettingStarted/ConnectingTrueNAS.md
  content/TrueCommand/TCGettingStarted/Install/InstallTCCloud.md
  content/TrueCommand/TCGettingStarted/Install/InstallTCDocker.md
  content/TrueCommand/TCGettingStarted/Install/Migrate.md
  content/TrueCommand/TCGettingStarted/Install/UpdateDocker.md
  content/TrueCommand/TCGettingStarted/Install/_index.md
  content/TrueCommand/TCGettingStarted/InterfaceOverview.md
  content/TrueCommand/TCGettingStarted/UserAccounts.md
  content/_includes/TCBrowserExceptions.md
Labels: Technical Writer Review (MJ)

#1580 DOCS-3599 Create Docs Examples of Creating API Key ACLs
  content/SCALE/SCALETutorials/TopToolbar/ManagingAPIKeys.md
  static/images/SCALE/CreateAPIKeyInShell.png
Labels: Technical Writer Review (MJ)

#1586 DOCS-3895: expand SMART test results descriptions
  content/SCALE/SCALEUIReference/Storage/Disks/DisksScreens.md
  static/images/SCALE/22.02/DiskScreenWithDiskExpanded.png
  static/images/SCALE/22.02/SMARTResultsScreen.png
Labels: Technical Writer Review (CD)

#1587 DOCS-4162: add note about UID 0
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersScale.md
  content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
  content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensScale.md
Labels: Technical Writer Review (CD)

#1589 DOCS-4355 Reincorporate Mini E+ Back Into Hardware Docs
  content/Hardware/LegacyHardware/ExpansionShelves/_index.md
  content/Hardware/LegacyHardware/FNCertified/_index.md
  content/Hardware/LegacyHardware/FNMini/MiniE+BSG.md
  content/Hardware/LegacyHardware/FNMini/MiniFamilyBSG2.0.md
  content/Hardware/LegacyHardware/MSeriesGen2/_index.md
  content/Hardware/LegacyHardware/MiniSeries/FreeNAS Minis (2nd Gen)/FreeNASMiniBMCWatchdog.md
  content/Hardware/LegacyHardware/MiniSeries/FreeNAS Minis (2nd Gen)/FreeNASMiniClockSignals.md
  content/Hardware/LegacyHardware/MiniSeries/FreeNAS Minis (2nd Gen)/FreeNASMiniHeatTroubleshoot.md
  content/Hardware/LegacyHardware/MiniSeries/FreeNAS Minis (2nd Gen)/MiniFamilyBSG2.0.md
  content/Hardware/LegacyHardware/MiniSeries/FreeNAS Minis (2nd Gen)/_index.md
  content/Hardware/LegacyHardware/MiniSeries/TrueNAS Minis (3rd Gen)/MiniBSG(Legacy).md
  content/Hardware/LegacyHardware/MiniSeries/TrueNAS Minis (3rd Gen)/MiniEHUG.md
  content/Hardware/LegacyHardware/MiniSeries/TrueNAS Minis (3rd Gen)/MiniEOOBM.md
  content/Hardware/LegacyHardware/MiniSeries/TrueNAS Minis (3rd Gen)/_index.md
  content/Hardware/LegacyHardware/MiniSeries/_index.md
  content/Hardware/LegacyHardware/TrueNASMinis/MiniEE+HUG.md
  content/Hardware/LegacyHardware/TrueNASMinis/MiniEE+XOOBM.md
  content/Hardware/Mini/MiniBSG.md
  content/Hardware/Mini/MiniE+HUG.md
  content/Hardware/Mini/MiniE+XOOBM.md
  content/Hardware/_index.md
Labels: Technical Writer Review (CD)

#1584 Docs 4286 docs create section on tc cloud setup
  content/TrueCommand/TCGettingStarted/ConnectingTrueNAS.md
  content/TrueCommand/TCGettingStarted/Install/InstallTCCloud.md
  content/TrueCommand/TCGettingStarted/Install/InstallTCDocker.md
  content/_includes/TCCloudConnectSystems.md
Labels: Technical Writer Review (TR)

#1594 DOCS-3500: add case-sensitive creds text
  content/TrueCommand/Administration/Users.md
  content/TrueCommand/TCGettingStarted/AdminAccounts.md
Labels: Technical Writer Review (TR)

#1595 DOCS-3508: rework initial section of CORE > SCALE migration article
  content/SCALE/GettingStarted/Migrate/MigratingFromCORE.md
Labels: Technical Writer Review (TR)
