Repository truenas/documentation, pull requests merged in 2022-12, with the labels that each got.

#1607 Add Networking Guides to Docs Hub
  content/Hardware/MSeries/MSeriesHANetworking.md
  content/Hardware/XSeries/XSeriesHANetworking.md
Labels: Technical Writer Review (MJ)

#1603 DOCS-3371 SCALE 22.12 Update First Time Login Article
  content/SCALE/GettingStarted/FirstTimeLogin.md
  content/SCALE/SCALETutorials/Storage/Disks/WipingDisks.md
  content/SCALE/SCALETutorials/TopToolbar/ManagingAPIKeys.md
  content/SCALE/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  content/SCALE/SCALEUIReference/TopToolbar/Settings/APIKeysScreen.md
  content/SCALE/SCALEUIReference/TopToolbar/Settings/WebUIPreferences.md
  content/SCALE/SCALEUIReference/TopToolbar/Settings/_index.md
  content/SCALE/SCALEUIReference/TopToolbar/TasksScreens.md
  content/SCALE/SCALEUIReference/TopToolbar/_index.md
  content/_includes/ChangeLoggedInUserPassword.md
  content/_includes/Jobs.md
  content/_includes/StatusOfTrueCommand.md
  content/_includes/TaskManagerScale.md
  static/images/SCALE/APIKeysAdd.png
  static/images/SCALE/APIKeysDelete.png
  static/images/SCALE/APIKeysEdit.png
  static/images/SCALE/APIKeysScreen.png
  static/images/SCALE/ChangeLoggedInUserPassword.png
  static/images/SCALE/JobsAbort.png
  static/images/SCALE/JobsMenu.png
  static/images/SCALE/TasksFailed.png
  static/images/SCALE/TasksScreen.png
Labels: Technical Writer Review (MJ)

#1605 DOCS-4030-Jira-tickets-private-attachment-section
  content/Contributing/IssueReporting/_index.md
  static/images/Contribute/newjiraattachments.png
Labels: Technical Writer Review (MJ)

#1612 DOCS-3418 SCALE 22.12 Update the SMB Share Articles
  content/References/ACLPrimer.md
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShares.md
  content/SCALE/SCALEUIReference/Shares/SMB/SMBSharesScreens.md
  content/SCALE/SCALEUIReference/Storage/Pools/DatasetsScreensScale.md
  static/images/SCALE/22.12/SMBACLEditor.png
  static/images/SCALE/22.12/SMBServiceStatusAfterFirstShareAdded.png
  static/images/SCALE/22.12/SMBServiceWidgetFirstShare.png
  static/images/SCALE/22.12/SMBShareACLScreen.png
  static/images/SCALE/22.12/SMBShareScreenNoShare.png
  static/images/SCALE/22.12/SharingSMBOptions.png
  static/images/SCALE/22.12/SharingSMBScreen.png
  static/images/SCALE/22.12/SharingSMBServiceStatusScreen.png
Labels: Technical Writer Review (CD)

#1615 DOCS-3352 SCALE 22.12 Update Shares - iSCSI screen changes
  content/Contributing/IssueReporting/_index.md
  content/SCALE/SCALETutorials/Shares/iSCSI/AddingISCSIShares.md
  content/SCALE/SCALEUIReference/Shares/iSCSI/iSCSISharesScreens.md
  static/images/Contribute/newjiraattachments.png
  static/images/SCALE/22.12/AddiSCSITargetScreen.png
  static/images/SCALE/22.12/SharingISCSIAssociatedTargetsAdd.png
  static/images/SCALE/22.12/SharingISCSIExtentsAddScreentop.png
  static/images/SCALE/22.12/SharingISCSIInitiatorsAddScreen.png
  static/images/SCALE/22.12/SharingISCSIManualTargetGlobalConfigSCALE.png
  static/images/SCALE/22.12/SharingScreenWithiSCSIShareAdded.png
  static/images/SCALE/22.12/SharingiSCSIAuthAccessAddScreen.png
  static/images/SCALE/22.12/SharingiSCSIInitiatorsGroupsScreen.png
  static/images/SCALE/22.12/SharingiSCSIPortalsAddScreen.png
  static/images/SCALE/22.12/iSCSINoTargetsScreen.png
Labels: Technical Writer Review (CD)

#1616 DOCS-3383 SCALE 22.12 Update 2FA Article
  content/SCALE/SCALETutorials/Credentials/2FASCALE.md
  content/SCALE/SCALEUIReference/Credentials/2FAScreenSCALE.md
  static/images/SCALE/2fabluefinscreen.png
Labels: Technical Writer Review (CD)

#1618 DOCS-3402 SCALE 22.12 Update Certificate Article
  content/SCALE/SCALETutorials/Credentials/Certificates/AddCAsSCALE.md
  content/SCALE/SCALETutorials/Credentials/Certificates/AddCSRsSCALE.md
  content/SCALE/SCALETutorials/Credentials/Certificates/CertificatesSCALE.md
  content/SCALE/SCALEUIReference/Credentials/Certificates/ACMEDNSAuthScreensSCALE.md
  content/SCALE/SCALEUIReference/Credentials/Certificates/CAScreensSCALE.md
  content/SCALE/SCALEUIReference/Credentials/Certificates/CSRScreensSCALE.md
  content/SCALE/SCALEUIReference/Credentials/Certificates/CertificatesScreensSCALE.md
Labels: Technical Writer Review (CD)

#1619 DOCS-4372 SED Disc Encryption Guide in Documents not correct
  content/CORE/CORETutorials/Storage/SED.md
Labels: Technical Writer Review (CD)

#1621 DOCS-3537: 13.0 Accounts articles updates
  content/CORE/CORETutorials/SettingUpUsersAndGroups.md
  content/CORE/UIReference/Accounts/Groups.md
  content/CORE/UIReference/Accounts/Users.md
  content/CORE/UIReference/Accounts/_index.md
  content/CORE/UIReference/Storage/Pools/COREQuotaScreens.md
  content/CORE/UIReference/Storage/Pools/DatasetsScreen.md
  content/_includes/CORERequiredFields.md
  static/images/CORE/13.0/EditGroupQuotasExpandedView.png
  static/images/CORE/13.0/EditGroupQuotasNoGroups.png
  static/images/CORE/13.0/SetGroupQuotasScreen.png
  static/images/CORE/13.0/SetUserQuotasScreen.png
  static/images/CORE/13.0/UserQuotasRootUserExpanded.png
  static/images/CORE/13.0/UserQuotasScreenNoQuotas.png
Labels: Technical Writer Review (CD), 13.0

#1625 DOCS-4267: Rework CORE Jail/Plugin Update instructions
  content/CORE/CORETutorials/JailsPluginsVMs/Jails/ManagingJails.md
  content/CORE/CORETutorials/JailsPluginsVMs/UpdateJailsPlugins.md
  static/images/CORE/13.0/JailsUpgrade.png
  static/images/CORE/13.0/MinioJailUpdateNone.png
  static/images/CORE/13.0/MinioJailpkg.png
Labels: Technical Writer Review (CD), 13.0

#1623 DOCS-3749: Review CORE Tutorials for Jails, Plugins, VMs
  content/CORE/CORETutorials/JailsPluginsVMs/Jails/CreatingJails.md
  content/CORE/CORETutorials/JailsPluginsVMs/Jails/InstallingJailSoftware.md
  content/CORE/CORETutorials/JailsPluginsVMs/VirtualMachines/CreatingBasicVM.md
  static/images/CORE/13.0/JailsAddNetworking.png
Labels: Technical Writer Review (CD), 13.0

#1624 DOCS-4332: SCALE 22.12 Update VMWare Snapshot Articles
  content/SCALE/SCALETutorials/DataProtection/CreatingVMwareSnapshots.md
  content/SCALE/SCALETutorials/DataProtection/PeriodicSnapshotTasksSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/VMwareSnapshotsScreen.md
  static/images/SCALE/22.12/emptyvmwaresnapshotadd.png
  static/images/SCALE/22.12/vmwareaddsnapshottask.png
  static/images/SCALE/22.12/vmwarefetchdatastore.png
  static/images/SCALE/22.12/vmwaresavesnaptask.png
  static/images/SCALE/22.12/vmwaresnapshottask.png
Labels: Bluefin Docs, Technical Writer Review (TR)

#1583 Integrate Spotlight support community tutorial into the Docs Hub
  content/SCALE/SCALETutorials/CommunityRecommends/SpotlightSupportSamba/Pastedimage20221021020856.png
  content/SCALE/SCALETutorials/CommunityRecommends/SpotlightSupportSamba/Pastedimage20221024004224.png
  content/SCALE/SCALETutorials/CommunityRecommends/SpotlightSupportSamba/Pastedimage20221024004241.png
  content/SCALE/SCALETutorials/CommunityRecommends/SpotlightSupportSamba/Pastedimage20221107154856.png
  content/SCALE/SCALETutorials/CommunityRecommends/SpotlightSupportSamba/index.md
  content/SCALE/SCALETutorials/CommunityRecommends/_index.md
Labels: Technical Writer Review (CD)

#1629 DOCS-4314: SCALE 22.12 System Updates Warning
  content/SCALE/GettingStarted/Install/InstallingSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/UpdateSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/UpdateScreensSCALE.md
Labels: Bluefin Docs, Technical Writer Review (TR)

#1634 DOCS-3760: Quick style review of CORE Community articles.
  content/CORE/CORETutorials/CommunityGuides/ACLPermissionsJails.md
  content/CORE/CORETutorials/CommunityGuides/ETCHostsPersistence.md
  content/CORE/CORETutorials/CommunityGuides/LegacyReplication.md
  content/CORE/CORETutorials/CommunityGuides/OpenVPN.md
Labels: Technical Writer Review (TR), 13.0

#1626 Docs 3384 update zvol articles
  content/SCALE/SCALETutorials/Storage/Pools/AddManageZvols.md
  content/SCALE/SCALEUIReference/Storage/Pools/Datasets/ZvolsScreensScale.md
  content/_includes/EncryptionSettings.md
  static/images/SCALE/22.12/AddZvolAdvancedOptionsBlockSize.png
  static/images/SCALE/22.12/AddZvolBasicOptions1.png
  static/images/SCALE/22.12/AddZvolBasicOptions2.png
  static/images/SCALE/22.12/AddZvolEncryptionOptionsKey.png
  static/images/SCALE/22.12/DatasetsScreenWithZvolWidgets.png
  static/images/SCALE/22.12/DeleteZvolWindow.png
  static/images/SCALE/22.12/ZvolDetailsWidget.png
  static/images/SCALE/22.12/ZvolSpaceManagementWidget.png
Labels: Technical Writer Review (TR)

#1636 DOCS-4388: Update Dedup in SCALE /pools/poolsscreens/
  content/SCALE/SCALEUIReference/Storage/Pools/PoolsScreens.md
Labels: Technical Writer Review (TR)

#1635 Docs 3545 update service article ups content
  content/SCALE/SCALETutorials/Network/Interfaces/SettingUpLAGG.md
  content/SCALE/SCALETutorials/SystemSettings/Services/UPSServicesSCALE.md
  content/SCALE/SCALEUIReference/Shares/SMB/SMBSharesScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/UPSServicesScreenSCALE.md
  static/images/SCALE/22.12/AddInterfaceLAGGSelected.png
  static/images/SCALE/22.12/AddInterfaceLinkAggregationType.png
  static/images/SCALE/22.12/DeleteSMBShareDialog.png
  static/images/SCALE/22.12/SMBServiceWidgetFirstShare.png
  static/images/SCALE/22.12/UPSServicesMtrOptions.png
  static/images/SCALE/22.12/UPSServicesSlOptions.png
Labels: Technical Writer Review (TR)

#1627 Docs 4361 update permissions articles
  content/SCALE/SCALETutorials/Storage/Pools/PermissionsSCALE.md
  static/images/SCALE/22.12/ChangeACLTypeWarning.png
  static/images/SCALE/22.12/EditACLScreen.png
  static/images/SCALE/22.12/EditDatasetAdvancedACLOptions.png
  static/images/SCALE/22.12/SMBACLEditor.png
  static/images/SCALE/22.12/SelectAPresetACL.png
  static/images/SCALE/22.12/SelectAPresetACLNFSv4.png
Labels: Technical Writer Review (TR)

#1637 DOCS-4387 Documentation on DocHub conflicts with TrueNAS about S3 replication
  content/CORE/CORETutorials/Tasks/CreatingCloudSyncTasks.md
Labels: Technical Writer Review (CD)

#1633 Docs 3389 update snapshots articles
  content/References/ACLPrimer.md
  content/SCALE/SCALETutorials/Shares/iSCSI/AddingISCSIShares.md
  content/SCALE/SCALETutorials/Storage/CreatingSnapshots.md
  content/SCALE/SCALETutorials/Storage/Pools/Datasets/AddManageZvols.md
  content/SCALE/SCALETutorials/Storage/Pools/Datasets/CreatingSnapshots.md
  content/SCALE/SCALETutorials/Storage/Pools/Datasets/DatasetsSCALE.md
  content/SCALE/SCALETutorials/Storage/Pools/Datasets/EncryptionSCALE.md
  content/SCALE/SCALETutorials/Storage/Pools/Datasets/ManageQuotas.md
  content/SCALE/SCALETutorials/Storage/Pools/Datasets/PermissionsSCALE.md
  content/SCALE/SCALETutorials/Storage/Pools/Datasets/_index.md
  content/SCALE/SCALEUIReference/Storage/Pools/Datasets/CapacitySettingsSCALE.md
  content/SCALE/SCALEUIReference/Storage/Pools/Datasets/DatasetsScreensScale.md
  content/SCALE/SCALEUIReference/Storage/Pools/Datasets/EditACLScreens.md
  content/SCALE/SCALEUIReference/Storage/Pools/Datasets/EncryptionUISCALE.md
  content/SCALE/SCALEUIReference/Storage/Pools/Datasets/ImportDataScreenSCALE.md
  content/SCALE/SCALEUIReference/Storage/Pools/Datasets/QuotaScreens.md
  content/SCALE/SCALEUIReference/Storage/Pools/Datasets/SnapshotsScreens.md
  content/SCALE/SCALEUIReference/Storage/Pools/Datasets/ZvolsScreensScale.md
  content/SCALE/SCALEUIReference/Storage/SnapshotsScreens.md
  static/images/SCALE/22.12/AddSnapshotScreen.png
  static/images/SCALE/22.12/CloneToDatasetDialog.png
  static/images/SCALE/22.12/DatasetRollbackFromSnapshotWindow.png
  static/images/SCALE/22.12/DeleteMultipleSnapshotsWindow.png
  static/images/SCALE/22.12/DeleteSnapshotDialog.png
  static/images/SCALE/22.12/SnapshotsScreenBatachOperations.png
  static/images/SCALE/22.12/SnapshotsScreenExpandedSnapshot.png
  static/images/SCALE/22.12/SnapshotsScreenNoSnapshotsAvailable.png
  static/images/SCALE/22.12/SnapshotsScreenShowingExtraColumns.png
  static/images/SCALE/22.12/SnapshotsScreenWithAllSnapshots.png
Labels: Technical Writer Review (TR)

#1640 Docs 3653 scale 22.12 update rsync task article
  content/SCALE/SCALETutorials/DataProtection/RsyncTasksSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/ConfigRsyncServiceSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/RsyncTasksScreensSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/RsyncServicesScreenSCALE.md
  static/images/SCALE/22.12/AddRsyncModuleAccess.png
  static/images/SCALE/22.12/AddRsyncModuleGeneral.png
  static/images/SCALE/22.12/AddRsyncModuleOtherOptions.png
  static/images/SCALE/22.12/AddRsyncTaskAdvSched.png
  static/images/SCALE/22.12/AddRsyncTaskNoTasks.png
  static/images/SCALE/22.12/AddRsyncTaskSchedOpt.png
  static/images/SCALE/22.12/AddRsyncTaskSourceRemoteModule.png
  static/images/SCALE/22.12/AddRsyncTaskSourceRemoteSSHDir.png
  static/images/SCALE/22.12/AddRsyncTaskSourceRemoteSSHKeychain.png
  static/images/SCALE/22.12/ServicesRsyncConf.png
  static/images/SCALE/22.12/ServicesRsyncCreateModule.png
  static/images/SCALE/22.12/ServicesRsyncModuleCreated.png
  static/images/SCALE/22.12/ServicesRsyncModuleDetails.png
  static/images/SCALE/22.12/ServicesRsyncOn.png
  static/includes/SCALE/SCALEAdvancedScheduler.md.part
Labels: Technical Writer Review (TR)

#1641 Docs-4367 Update Install and ConsoleSetup Articles
  content/SCALE/GettingStarted/Install/ConsoleSetupMenuScale.md
  content/SCALE/GettingStarted/Install/InstallingSCALE.md
  static/images/SCALE/22.12/SCALEInstallerConsoleSetupAdminAccount.png
  static/images/SCALE/22.12/SCALEInstallerConsoleSetupAdminPassword.png
Labels: Technical Writer Review (TR)

#1628 Docs 3439 scale 22.02 reorg update directory services articles
  content/CORE/CORETutorials/SettingUpUsersAndGroups.md
  content/CORE/UIReference/DirectoryServices/NISScreen.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/_index.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/ActiveDirectory.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/Idmap.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/KerberosKeytab.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/KerberosRealms.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/KerberosSettings.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/LDAP.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/_index.md
  static/images/SCALE/22.02/DirectoryServicesActiveDirectoryForm.png
  static/images/SCALE/22.02/DirectoryServicesIdmapForm.png
  static/images/SCALE/22.02/DirectoryServicesKerberosKeytabForm.png
  static/images/SCALE/22.02/DirectoryServicesKerberosRealmsForm.png
  static/images/SCALE/22.02/DirectoryServicesKerberosSettingsForm.png
  static/images/SCALE/22.02/DirectoryServicesLDAPForm.png
  static/images/SCALE/22.02/DirectoryServicesScreenDisabled.png
  static/images/SCALE/22.02/DirectoryServicesScreenEnabled.png
Labels: Technical Writer Review (CD)

#1643 Docs-3349 Update Cloud Sync Tasks Articles
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddCloudSyncTasks.md
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/CloudSyncTaskGoogleDrive.md
  content/SCALE/SCALETutorials/Storage/Datasets/EncryptionSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  static/images/SCALE/22.12/AddCloudSyncTaskTransferRemoteSettings.png
  static/images/SCALE/22.12/AddGoogleDriveCloudSyncTask.png
Labels: Technical Writer Review (TR)

#1646 DOCS-4368 Document bulk update for Apps
  content/SCALE/SCALETutorials/Apps/UsingApps.md
  static/images/SCALE/22.12/UpgradeAppBulk.png
  static/images/SCALE/22.12/UpgradeAppSingle.png
Labels: Technical Writer Review (CD)

#1650 DOCS-4177 SCALE 22.12 Certificates - Adapt or Port "Let's Encrypt" t…
  content/SCALE/SCALETutorials/Credentials/Certificates/SettingUpLetsEncryptCertificates.md
  static/images/SCALE/22.12/LetsEncryptACMECertificate.png
  static/images/SCALE/22.12/LetsEncryptAcmeDNSAuthenticator.png
  static/images/SCALE/22.12/LetsEncryptCSR.png
Labels: Technical Writer Review (CD)

#1645 Docs 4391 update user articles
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
  static/images/SCALE/22.12/AddUser-UserIDAndGroupSettings.png
  static/images/SCALE/22.12/AddUserDirPermsAuthSettings.png
  static/images/SCALE/22.12/AddUserIdentificationSettings.png
  static/images/SCALE/22.12/RootLoginAlert.png
  static/images/SCALE/22.12/UserScreenUserDetails.png
  static/images/SCALE/22.12/UserScreenWithBuiltinUsers.png
  static/images/SCALE/22.12/UsersScreen.png
Labels: Technical Writer Review (TR)

#1651 DOCS-4386 Reproduction of app host path issues
  content/SCALE/SCALETutorials/Apps/UsingApps.md
  content/SCALE/SCALEUIReference/Apps/AppsScreensSCALE.md
  static/images/SCALE/22.12/AppsAdvancedSettingsKubernetesSettings.png
Labels: Technical Writer Review (CD)

#1652 Docs 3991 create storj cloud sync tutorial
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddStorjCloudSyncTask.md
  static/images/SCALE/22.12/AddStorjCloudCredential.png
  static/images/SCALE/22.12/AddingStorjCloudCredential.png
  static/images/SCALE/22.12/CloudCredentialsVerified.png
  static/images/SCALE/22.12/CloudSyncTaskSelectStorjBucket.png
  static/images/SCALE/22.12/CloudSyncTaskSelectStorjCloudCredential.png
  static/images/SCALE/22.12/StorjAccessManagementScreen.png
  static/images/SCALE/22.12/StorjAddBucket.png
  static/images/SCALE/22.12/StorjAddNewBucket.png
  static/images/SCALE/22.12/StorjBucketAdded.png
  static/images/SCALE/22.12/StorjCreateABucketScreen.png
  static/images/SCALE/22.12/StorjCreateAccessDownloadedEncryptionPassphrase.png
  static/images/SCALE/22.12/StorjCreateAccessEncryptionDialog.png
  static/images/SCALE/22.12/StorjCreateAccessSelectBuckets.png
  static/images/SCALE/22.12/StorjCreateAccessSelectDuration.png
  static/images/SCALE/22.12/StorjCreateAccessSelectEncryptionOptions.png
  static/images/SCALE/22.12/StorjCreateAccessWindow.png
  static/images/SCALE/22.12/StorjCreateNewTrueNASAccount.png
  static/images/SCALE/22.12/StorjCreateS3Access.png
  static/images/SCALE/22.12/StorjEncryptYourBucketScreen.png
  static/images/SCALE/22.12/StorjGenerateAPassphraseScreen.png
  static/images/SCALE/22.12/StorjMainDashboard.png
  static/images/SCALE/22.12/StorjNewBucketScreen.png
  static/images/SCALE/22.12/StorjSignInScreen.png
Labels: Technical Writer Review (CD)

#1560 DOCS-3246 Update TC LDAP docs for 2.1.1 and 2.2
  content/TrueCommand/Administration/LDAPServers.md
  static/images/TrueCommand/AddLDAPServer.png
Labels: Technical Writer Review (MJ)

#1663 Docs-4403 Update First Time Login Article
  content/SCALE/GettingStarted/FirstTimeLogin.md
  content/SCALE/GettingStarted/Install/InstallingSCALE.md
  content/_includes/RootLoginDeprecatedSCALE.md
  static/images/SCALE/22.12/CreateAdminAccountAtFirstTimeLogin.png
Labels: Technical Writer Review (TR)

#1661 Docs-4402 Update Storj Cloud Sync Task Article - Added Using Add New Bucket Instructions
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddStorjCloudSyncTask.md
Labels: Technical Writer Review (CD)

#1664 Update Security.md
  content/Solutions/Optimizations/Security.md
Labels: Technical Writer Review (CD)

#1665 Adjust Path for Edit this Page link
  config.toml
Labels: Technical Writer Review (CD)

#1666 DOCS-4406: Add Passphrase length limit
  content/CORE/CORETutorials/Storage/Pools/StorageEncryption.md
  content/SCALE/SCALETutorials/Storage/Datasets/EncryptionSCALE.md
Labels: Technical Writer Review (CD)

#1671 Docs 4309 correct active directory articles
  content/CORE/UIReference/DirectoryServices/ADScreen.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigADSCALE.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigIDmapSCALE.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigKerberosSCALE.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigLDAPSCALE.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/_index.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/ActiveDirectory.md
  static/images/SCALE/22.12/ActiveDirectoryAdvancedOptions.png
  static/images/SCALE/22.12/ActiveDirectoryBasicOptions.png
Labels: Technical Writer Review (CD)

#1679 DOCS-4296: Update docs regarding SMB WORM preset
  content/SCALE/SCALEUIReference/Shares/SMB/SMBSharesScreens.md
Labels: Work In Progress
