Repository truenas/documentation, pull requests merged in 2022-09, with the labels that each got.

#1506 Add remaining TrueCommand 2022 tentative release scheduling
  content/TrueCommand/TCReleaseNotes.md
Labels: Technical Writer Review (TR)

#1510 Docs-3449 SCALE 22.02 Update Local User Article Content
  content/SCALE/SCALETutorials/Credentials/LocalGroups.md
  content/SCALE/SCALETutorials/Credentials/LocalUsers.md
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersScale.md
  content/SCALE/SCALETutorials/Virtualization/AccessingNASFromVM.md
  content/SCALE/SCALEUIReference/Credentials/LocalGroups.md
  content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensScale.md
  static/images/SCALE/22.02/AddUserDirPermsAuthSettings.png
  static/images/SCALE/22.02/AddUserIdentificationSettings.png
  static/images/SCALE/22.02/AddUserUserIDAndGroupsSettings.png
  static/images/SCALE/22.02/LocalUserDetailsSCALE.png
  static/images/SCALE/22.02/LocalUsersBuilt-InUsersSCALE.png
  static/images/SCALE/22.02/LocalUsersSCALE.png
Labels: Technical Writer Review (TR)

#1513 DOCS-3171: Scale 2FA Video
  content/SCALE/SCALETutorials/Credentials/2FASCALE.md
Labels: Technical Writer Review (TR)

#1541 DOCS-4257: Add Boot Pool selection screen
  content/SCALE/GettingStarted/Migrate/MigratingFromCORE.md
  static/images/SCALE/ScaleSelectBootDrive.png
Labels: Technical Writer Review (MJ)

#1543 DOCS-3088: SCALE BlueFin nightly train switch
  content/SCALE/SCALETutorials/SystemSettings/UpdateSCALE.md
  static/images/SCALE/22.02/SaleUpdateTrain.png
  static/images/SCALE/22.02/ScaleTrainSelection.png
  static/images/SCALE/22.02/ScaleUpdateTrain.png
Labels: Technical Writer Review (MJ)

#1539 Docs 2940 scale 22.02 reorg and update replication articles
  content/SCALE/SCALETutorials/DataProtection/AddReplicationSCALE.md
  content/SCALE/SCALETutorials/DataProtection/Replication.md
  content/SCALE/SCALETutorials/DataProtection/Replication/LocalReplicationSCALE.md
  content/SCALE/SCALETutorials/DataProtection/Replication/RemoteReplicationSCALE.md
  content/SCALE/SCALETutorials/DataProtection/Replication/UnlockReplicationEncryptedDatasetZvol.md
  content/SCALE/SCALETutorials/DataProtection/Replication/UseAdvancedReplicationSCALE.md
  content/SCALE/SCALETutorials/DataProtection/Replication/_index.md
  content/SCALE/SCALEUIReference/DataProtection/ReplicationScreensSCALE.md
  static/images/SCALE/22.02/AddReplicationTaskDestinationLocOnThisSystem.png
  static/images/SCALE/22.02/AddReplicationTaskEncyptionHexOption.png
  static/images/SCALE/22.02/AddReplicationTaskSSHOptions.png
  static/images/SCALE/22.02/AddReplicationTaskSnapshotOptions.png
  static/images/SCALE/22.02/AddReplicationTaskSourceLocOnThisSystem.png
  static/images/SCALE/22.02/AddReplicationTaskWhenRunOnceCustomLifetime.png
  static/images/SCALE/22.02/AdvancedAddRepTaskSnapshotsAndSchedule.png
  static/images/SCALE/22.02/AdvancedAddRepTaskSourceAndDestination.png
  static/images/SCALE/22.02/AdvancedAddReplicationTaskDestinationOptions.png
  static/images/SCALE/22.02/AdvancedAddReplicationTaskGeneralTransportLocal.png
  static/images/SCALE/22.02/AdvancedAddReplicationTaskGeneralTransportSSH+NETCAT.png
  static/images/SCALE/22.02/AdvancedAddReplicationTaskGeneralTransportSSH.png
  static/images/SCALE/22.02/AdvancedAddReplicationTaskScheduleOptions.png
  static/images/SCALE/22.02/AdvancedAddReplicationTaskSnapshotOptions.png
  static/images/SCALE/22.02/ReplicationAndPeriodicSnapshotTasksWidgets.png
  static/images/SCALE/22.02/ReplicationTaskDeleteDialog.png
  static/images/SCALE/22.02/ReplicationTaskDetails.png
  static/images/SCALE/22.02/ReplicationTaskRunNowDialog.png
  static/images/SCALE/22.02/ReplicationTasksListNoTasks.png
  static/images/SCALE/22.02/ReplicationTasksListScreen.png
  static/images/SCALE/22.02/ReplicationTasksWidgetNoTasks.png
  static/images/SCALE/22.02/ReplicationWizardCreateSSHConnection.png
  static/images/SCALE/22.02/ReplicationWizardWhatAndWhere.png
  static/images/SCALE/22.02/ReplicationWizardWhatAndWhereTaskName.png
  static/images/SCALE/22.02/ReplicationWizardWhen.png
  static/images/SCALE/22.02/RestoreReplicationTaskWindow.png
Labels: Technical Writer Review (TR)

#1547 DOCS-4137: Email Alert Services Clarification
  content/SCALE/SCALETutorials/TopToolbar/SettingUpSystemEmail.md
Labels: Technical Writer Review (MJ)

#1536 Docs-4188 SCALE 22.02 Updated Periodic Snapshot Task Articles
  content/SCALE/SCALETutorials/DataProtection/PeriodicSnapshotTasksSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/PeriodicSnapshotTasksScreensSCALE.md
  static/images/SCALE/22.02/AddPeriodicSnapshotTaskScreen.png
  static/images/SCALE/22.02/DataProtectPeriodicSnapshotTasksDetailsNoTasks.png
  static/images/SCALE/22.02/DataProtectionPeriodicSnapshotTasksDetails.png
  static/images/SCALE/22.02/DataProtectionPeriodicSnapshotTasksList.png
  static/images/SCALE/22.02/EditPeriodicSnapshotTaskScreen.png
  static/images/SCALE/22.02/PeriodicSnapshotTaskLog.png
  static/images/SCALE/22.02/PeriodicSnapshotTaskWidget.png
  static/images/SCALE/22.02/PeriodicSnapshotTaskWidgetNoTasks.png
Labels: Technical Writer Review (TR)

#1534 Docs 3228 scale 22.02 update or create certificates articles
  content/SCALE/SCALETutorials/Credentials/Certificates/AddACMESCALE.md
  content/SCALE/SCALETutorials/Credentials/Certificates/AddCAsSCALE.md
  content/SCALE/SCALETutorials/Credentials/Certificates/AddCSRsSCALE.md
  content/SCALE/SCALETutorials/Credentials/Certificates/CertificatesSCALE.md
  content/SCALE/SCALETutorials/Credentials/Certificates/_index.md
  content/SCALE/SCALEUIReference/Credentials/Certificates/ACMEDNSAuthScreensSCALE.md
  content/SCALE/SCALEUIReference/Credentials/Certificates/CAScreensSCALE.md
  content/SCALE/SCALEUIReference/Credentials/Certificates/CSRScreensSCALE.md
  content/SCALE/SCALEUIReference/Credentials/Certificates/CertificatesScreensSCALE.md
  content/SCALE/SCALEUIReference/Credentials/Certificates/_index.md
  static/images/SCALE/22.02/ACMEDNSAuthenticatorWidgetNoAuthtenticators.png
  static/images/SCALE/22.02/AddCACertificateOptionsRSAType.png
  static/images/SCALE/22.02/AddCACertificateSubject.png
  static/images/SCALE/22.02/AddCAConfirmOptions.png
  static/images/SCALE/22.02/AddCAExtraConstraintsAllExpanded.png
  static/images/SCALE/22.02/AddCAExtraConstraintsImportCA.png
  static/images/SCALE/22.02/AddCAIdentifierAndType.png
  static/images/SCALE/22.02/AddCSRCertificateOptionsRSAType.png
  static/images/SCALE/22.02/AddCSRCertificateSubject.png
  static/images/SCALE/22.02/AddCSRConfirmOptions.png
  static/images/SCALE/22.02/AddCSRExtraConstraintsAllExpanded.png
  static/images/SCALE/22.02/AddCSRExtraConstraintsImportCSR.png
  static/images/SCALE/22.02/AddCSRIdentifierAndType.png
  static/images/SCALE/22.02/AddCertificateCertifcateSubject.png
  static/images/SCALE/22.02/AddCertificateCertificateOptions.png
  static/images/SCALE/22.02/AddCertificateConfirmOptions.png
  static/images/SCALE/22.02/AddCertificateExtraConstraintsInternalCert.png
  static/images/SCALE/22.02/AddCertificateIdentifierAndTypeInternalCert.png
  static/images/SCALE/22.02/AddCertificateImportCertOptions.png
  static/images/SCALE/22.02/AddCertificateImportCertificateOptions.png
  static/images/SCALE/22.02/AddCertificateImportExtraConstraints.png
  static/images/SCALE/22.02/AddCertificateWizard.png
  static/images/SCALE/22.02/AddDNSAuthenticatorCloudflare.png
  static/images/SCALE/22.02/AddDNSAuthenticatorRoute53Type.png
  static/images/SCALE/22.02/CertificateAuthoritiesWidgetNoCAs.png
  static/images/SCALE/22.02/CertificateSigningRequestWidgetNoCSR.png
  static/images/SCALE/22.02/CertificatesWidget.png
  static/images/SCALE/22.02/CredentialsCertificatesScreen.png
  static/images/SCALE/22.02/EditCertificateScreen.png
Labels: Technical Writer Review (CD)

#1529 Docs 4240 scale 22.02 update smb, nfs articles
  content/SCALE/SCALETutorials/SystemSettings/Services/NFSServiceSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/OpenVPNSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/S3ServiceSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/SMARTServicesSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/SMBServiceSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/SSHServiceSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/WebDAVServiceSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/_index.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/DDNSServiceScreenSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/OpenVPNScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/SMBServicesScreen.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/SNMPServiceScreenSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/_index.md
Labels: Technical Writer Review (CD)

#1551 DOCS-3460: Access minimalize running tasks-SCALE
  content/_includes/TaskManagerScale.md
Labels: Work In Progress
