Repository truenas/documentation, pull requests merged in 2022-06, with the labels that each got.

#1379 DOCS-3767: Update DisksSCALE.md
  content/CORE/UIReference/Storage/Disks/DisksScreens.md
  content/SCALE/SCALEUIReference/DataProtection/SMARTTestsSCALE.md
  content/SCALE/SCALEUIReference/Storage/DisksSCALE.md
  static/includes/Reference/TasksSMARTAddFields.md.part
Labels: Work In Progress

#1380 DOCS-3772: Add NAS-116493-to-the-known-issues
  content/CORE/COREReleaseNotes.md
Labels: Technical Writer Review (TR)

#1377 DOCS-3301: Document Fix Credential Button and UI Function
  content/SCALE/SCALEUIReference/DataProtection/Cloud Sync Tasks/_index.md
  static/images/SCALE/DataProtectionCloudSyncInvalidAlert.png
  static/images/SCALE/DataProtectionCloudSyncInvalidFix.png
Labels: Technical Writer Review (TR)

#1366 TC-1904: TC-2.2-Update-the-DOCS-and-Images-of-Pool/Dataset
  content/TrueCommand/SystemManagement/SingleSystem/TrueCommandSharing.md
  static/images/TrueCommand/2.2/TC22addnfsshare.png
  static/images/TrueCommand/2.2/TC_22_ViewShares.png
  static/images/TrueCommand/2.2/forimages.md
  static/images/TrueCommand/2.2/tc22addsmbshare.png
Labels: TC 2.2 Docs, Technical Writer Review (MJ)

#1389 fix missing quotation mark
  content/CORE/GettingStarted/Applications.md
Labels: Technical Writer Review (MJ)

#1391 Update ConfiguringFTP.md
  content/CORE/CORETutorials/Services/ConfiguringFTP.md
Labels: Technical Writer Review (MJ)

#1401 SCALE 22.02 Update TFTP Services
  content/SCALE/SCALEUIReference/SystemSettings/ServicesSCALE.md
  static/images/SCALE/22.02/ServicesTFTPSCALE.png
  static/includes/Reference/ServicesTFTPFields.md.part
Labels: Technical Writer Review (MJ)
