Repository truenas/documentation, pull requests merged in 2022-01, with the labels that each got.

#1203 DOCS-2722: TC 2.1 Release Notes
  content/ReleaseNotes/TrueCommand/2.1.md
Labels: TC 2.1 Docs

#1229 DOCS-3053: Update System Settings > General
  content/SCALE/SystemSettings/GeneralSettings.md
Labels: Work In Progress

#1232 DOCS-3062: Add Scale Migration Page
  content/SCALE/GettingStarted/InstallingSCALE.md
  content/SCALE/GettingStarted/MigratingFromCORE.md
Labels: New Article
