Repository truenas/documentation, pull requests merged in 2023-12, with the labels that each got.

#2337 Pd 850 update core disk replace.md article
  content/CORE/CORETutorials/Storage/Disks/DiskReplace.md
Labels: Review (TM)

#2341 Pd 775 core 13.1 update screenshots and content
  content/CORE/CORETutorials/JailsPluginsVMs/Plugins/ManagingPlugins.md
  content/CORE/CORETutorials/JailsPluginsVMs/Plugins/MinIOPlugin.md
  content/CORE/CORETutorials/JailsPluginsVMs/Plugins/PlexPlugin.md
  content/CORE/CORETutorials/JailsPluginsVMs/Plugins/_index.md
  content/CORE/CORETutorials/Sharing/SMB/SMBShare.md
  content/CORE/GettingStarted/Applications.md
  content/CORE/GettingStarted/DataBackups.md
  content/CORE/GettingStarted/LoggingIn.md
  content/CORE/UIReference/TopMenu/Alerts.md
  content/CORE/UIReference/TopMenu/TaskManager.md
  content/CORE/UIReference/TopMenu/UIPreferences.md
  content/CORE/UIReference/TopMenu/_index.md
  content/_includes/COREPlexPlugin.md
  content/_includes/CORETopMenu.md
  static/images/CORE/System/UIBugReport.png
  words-to-ignore.txt
Labels: Version Specific, Review (TM)

#2349 Fix incorrect links
  content/TrueCommand/AdminGuide/_index.md
  content/TrueCommand/UserGuide/_index.md
Labels: Review (TM)

#2348 24.04 top-level Parallelism review - SCALE Tutorials
  content/SCALE/GettingStarted/Configure/UIConfigurationSCALE.md
  content/SCALE/SCALETutorials/Apps/_index.md
  content/SCALE/SCALETutorials/ConfigReportsScale.md
  content/SCALE/SCALETutorials/Credentials/_index.md
  content/SCALE/SCALETutorials/Dashboard/_index.md
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddCloudSyncTasks.md
  content/SCALE/SCALETutorials/DataProtection/_index.md
  content/SCALE/SCALETutorials/Datasets/AddManageZvols.md
  content/SCALE/SCALETutorials/Datasets/CreatingSnapshots.md
  content/SCALE/SCALETutorials/Datasets/DatasetsSCALE.md
  content/SCALE/SCALETutorials/Datasets/EncryptionSCALE.md
  content/SCALE/SCALETutorials/Datasets/ManageQuotas.md
  content/SCALE/SCALETutorials/Datasets/ManageSnapshotsSCALE.md
  content/SCALE/SCALETutorials/Datasets/PermissionsSCALE.md
  content/SCALE/SCALETutorials/Datasets/_index.md
  content/SCALE/SCALETutorials/Network/_index.md
  content/SCALE/SCALETutorials/Shares/_index.md
  content/SCALE/SCALETutorials/Shares/iSCSI/AddingISCSIShares.md
  content/SCALE/SCALETutorials/Storage/CreatePoolWizard.md
  content/SCALE/SCALETutorials/Storage/Disks/ReplacingDisks.md
  content/SCALE/SCALETutorials/Storage/Disks/SEDScale.md
  content/SCALE/SCALETutorials/Storage/Disks/SLOGOverprovisionSCALE.md
  content/SCALE/SCALETutorials/Storage/Disks/WipingDisks.md
  content/SCALE/SCALETutorials/Storage/Disks/_index.md
  content/SCALE/SCALETutorials/Storage/FusionPoolsScale.md
  content/SCALE/SCALETutorials/Storage/ImportPoolScale.md
  content/SCALE/SCALETutorials/Storage/ManagePoolsScale.md
  content/SCALE/SCALETutorials/Storage/Pools/Disks/_index.md
  content/SCALE/SCALETutorials/Storage/Pools/_index.md
  content/SCALE/SCALETutorials/Storage/_index.md
  content/SCALE/SCALETutorials/SystemSettings/_index.md
  content/SCALE/SCALETutorials/TopToolbar/_index.md
  content/SCALE/SCALETutorials/Virtualization/_index.md
  content/SCALE/SCALEUIReference/Storage/Pools/DisksScreen.md
Labels: Technical Writer Review (MJ)

#2345 SCALE 24.04: UI Reference Guide parallelism review
  content/SCALE/SCALETutorials/DataProtection/ScrubTasksSCALE.md
  content/SCALE/SCALETutorials/Datasets/DatasetsSCALE.md
  content/SCALE/SCALETutorials/Datasets/EncryptionSCALE.md
  content/SCALE/SCALEUIReference/Datasets/CapacitySettingsSCALE.md
  content/SCALE/SCALEUIReference/Datasets/EditACLScreens.md
  content/SCALE/SCALEUIReference/Datasets/EncryptionUISCALE.md
  content/SCALE/SCALEUIReference/Datasets/QuotaScreens.md
  content/SCALE/SCALEUIReference/Datasets/SnapshotsScreens.md
  content/SCALE/SCALEUIReference/Datasets/ZvolsScreensScale.md
  content/SCALE/SCALEUIReference/Datasets/_index.md
  content/SCALE/SCALEUIReference/ReportingScreensSCALE.md
  content/SCALE/SCALEUIReference/SCALEDashboard.md
  content/SCALE/SCALEUIReference/Storage/Datasets/_index.md
  content/SCALE/SCALEUIReference/Storage/DevicesScreensSCALE.md
  content/SCALE/SCALEUIReference/Storage/DisksScreen.md
  content/SCALE/SCALEUIReference/Storage/PoolCreateWizardScreens.md
  content/SCALE/SCALEUIReference/Storage/Pools/_index.md
  content/SCALE/SCALEUIReference/Storage/_index.md
  content/SCALE/SCALEUIReference/TopToolbar/_index.md
  content/SCALE/SCALEUIReference/VirtualizationScreens.md
Labels: Technical Writer Review (MJ)

#2350 PD-767: Add 23.10.1 note about zfs block cloning
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific

#2344 23.10 UI Reference check - Top Menu/Settings update
  content/SCALEUIReference/SCALEDashboard.md
  content/SCALEUIReference/TopToolbar/Settings/_index.md
Labels: Version Specific, Technical Writer Review (MJ)

#2342 Adjust a couple screenshots used by 23.10 docs
  static/images/SCALE/22.12/DashboardMainScreenSCALE.png
  static/images/SCALE/22.12/DashboardSystemInfoWidgetSCALE.png
Labels: Version Specific, Technical Writer Review (MJ)

#2340 PD-890: 13.0-U6.1 release note
  content/GettingStarted/COREReleaseNotes.md
Labels: Version Specific, Technical Writer Review (MJ)

#2352 Add NAS issue link to U6.1
  content/GettingStarted/COREReleaseNotes.md
Labels: Version Specific

#2355 Update release schedules
  data/properties/core-releases.yaml
  data/properties/scale-releases.yaml
Labels: Technical Writer Review (MJ)

#2354 Pd 539 tc 3.0 create replication management tutorial
  content/TrueCommand/UserGuide/ReplicationManagement.md
  static/images/TrueCommand/Dashboard/TopBar.png
  static/images/TrueCommand/Replication/NewReplicationTaskConfirmScreen.png
  static/images/TrueCommand/Replication/NewReplicationTaskSchedulerScreen.png
  static/images/TrueCommand/Replication/NewReplicationTaskSourcesScreen.png
  static/images/TrueCommand/Replication/NewReplicationTaskTargetScreen.png
  static/images/TrueCommand/Replication/ReplicationManagementScreenWithTasks.png
  words-to-ignore.txt
Labels: Review (TM)

#2358 PD-291 Update Asigra Solutions Article, Plugin and Jails Articles
  content/CORE/CORETutorials/JailsPluginsVMs/Jails/CreatingJails.md
  content/CORE/CORETutorials/JailsPluginsVMs/Jails/ManagingJails.md
  content/CORE/CORETutorials/JailsPluginsVMs/Jails/_index.md
  content/CORE/CORETutorials/JailsPluginsVMs/Plugins/_index.md
  content/Solutions/Integrations/AsigraPlugin.md
Labels: Review (TM)

#2364 Add simple conditional notice for content tracking nightly/early releases
  layouts/partials/page-header.html
  static/custom.css
Labels: Technical Writer Review (MJ)

#2361 Pd 913 review core debug file content
  content/CORE/CORETutorials/Getting Support.md
  content/_includes/CreateDebugCORE.md
  content/_includes/CreateJiraSuggestion.md
  layouts/partials/site-footer.html
  layouts/partials/site-header.html
  static/images/CORE/System/GenerateDebugFile.png
  static/images/Contribute/JiraCreateBottom.png
  static/images/Contribute/JiraSuggestionCreate.png
  static/images/Contribute/JiraSummaryDescription.png
  words-to-ignore.txt
Labels: Review (TM)

#2366 PD-781 Add Description Front Matter
  content/References/ACLPrimer.md
  content/References/ConceptsAndTerms.md
  content/References/Copyrights.md
  content/References/DefaultPorts.md
  content/References/IPMIFAQ.md
  content/References/L2ARC.md
  content/References/SLOG.md
  content/References/SMB.md
  content/References/ZFSCapacityCalculator.md
  content/References/ZFSCapacityGraph.md
  content/References/ZFSDeduplication.md
  content/References/ZFSPrimer.md
  content/References/ZILandSLOG.md
  content/References/_index.md
  content/References/dRAIDprimer.md
Labels: Review (TM)

#2370 Rename 3.0.0-RC.1 to 3.0.0
  content/TrueCommand/TCGettingStarted/TCReleaseNotes.md
Labels: Version Specific

#2372 Pd 682 update screenshots on true nas core virtualized with es xi page
  content/Solutions/Integrations/VMware/DeployTNinVMWare.md
  static/images/VMWareESXi/AddNextcloudEnterApplicationName.png
  static/images/VMWareESXi/DatastoreBrowserWithNewDirectories.png
  static/images/VMWareESXi/EditSettingsNewHardDiskRow.png
  static/images/VMWareESXi/EditSettingsNewHardDiskSettings.png
  static/images/VMWareESXi/EditTrueNASSettingsExample.png
  static/images/VMWareESXi/EditVMAddHardDiskOptions.png
  static/images/VMWareESXi/LoginScreen.png
  static/images/VMWareESXi/NameNewDirectory.png
  static/images/VMWareESXi/SelectDatastoreBrowser.png
  static/images/VMWareESXi/StorageDatastoresTab.png
  static/images/VMWareESXi/TrueNAS13ReleaseConsoleSetup.png
  static/images/VMWareESXi/TrueNASConsoleSetup.png
  static/images/VMWareESXi/TrueNASVMDetails.png
  static/images/VMWareESXi/UploadISOfile.png
  static/images/VMWareESXi/UploadTrueNasISOFile.png
  static/images/VMWareESXi/VMWareTrueNASVMCreated.png
  static/images/VMWareESXi/VMWareVMAdded.png
  static/images/VMWareESXi/VMWizardAddHardDisk.png
  static/images/VMWareESXi/VMWizardCreateNew.png
  static/images/VMWareESXi/VMWizardCustomizeSettings.png
  static/images/VMWareESXi/VMWizardReadyToComplete.png
  static/images/VMWareESXi/VMWizardSelectCreationType.png
  static/images/VMWareESXi/VMWizardSelectNameAndGuestOS.png
  static/images/VMWareESXi/VMWizardSelectStorage.png
  static/images/VMWareESXi/VirtualMachinesScreen.png
Labels: Technical Writer Review (MJ)

#2326 Pd 759 TC_3.0.0-RC1 docs
  content/TrueCommand/AdminGuide/Admin/LDAPServers.md
  content/TrueCommand/AdminGuide/Admin/_index.md
  content/TrueCommand/TCGettingStarted/InitialConfig.md
  content/TrueCommand/TCGettingStarted/Install/InstallTCDocker.md
  content/TrueCommand/TCGettingStarted/TCReleaseNotes.md
  content/_includes/TCAdminPage.md
  static/api/tc_rest_api.html
  static/images/TrueCommand/Administration/AdministrationAboutWidget.png
  static/images/TrueCommand/Administration/AdministrationConfigurationWidget.png
  static/images/TrueCommand/Administration/AdministrationScreen.png
  static/images/TrueCommand/Administration/ConfigurationScreenGeneralSSLAlertOptions.png
  words-to-ignore.txt
Labels: Version Specific

#2375 Add Veeam References to MinIO Enterprise app
  content/SCALE/SCALETutorials/Apps/EnterpriseApps/MinIO/_index.md
Labels: Technical Writer Review (MJ)

#2381 Pd 912 prepare community notice about upcoming apps framework changes
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
Labels: Technical Writer Review (MJ)

#2383 PD-762 (TC 2.3 branch): update version switcher to add 3.0 branch
  layouts/partials/docs-nav.html
Labels: Version Specific

#2384 PD-762 (13.0): update version switcher to add 3.0 branch
  layouts/partials/docs-nav.html
Labels: Version Specific

#2385 PD-762 (23.10 branch): update version switcher to add 3.0 branch
  layouts/partials/docs-nav.html
Labels: Version Specific

#2386 PD-762 (22.12 branch): update version switcher to add 3.0 branch
  layouts/partials/docs-nav.html
Labels: Version Specific

#2387 (23.10) Add known issue for large custom app catalogs
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific
