Repository truenas/documentation, pull requests merged in 2023-02, with the labels that each got.

#1727 PD-76 Document Large Number behavior in TrueNAS SCALE
  content/SCALE/SCALEUIReference/Reporting/ReportingScreensSCALE.md
  content/SCALE/SCALEUIReference/Storage/Datasets/DatasetsScreensScale.md
  content/SCALE/SCALEUIReference/Storage/StorageDashboardScreen.md
Labels: Technical Writer Review (CD)

#1723 Pd-57 scale 22.12 update smart test article
  content/SCALE/SCALETutorials/DataProtection/SMARTTestsSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/SMARTServicesSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/SMARTTestsScreensSCALE.md
  content/SCALE/SCALEUIReference/Storage/Pools/DevicesScreensSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/SMARTServicesScreen.md
  static/images/SCALE/22.12/DataProtectionAddSMARTTestSCALE.png
  static/images/SCALE/22.12/DataProtectionEditSMARTTestSCALE.png
  static/images/SCALE/22.12/DataProtectionSMARTTestAdvancedSchedSCALE.png
  static/images/SCALE/22.12/DataProtectionSMARTTestWidgetSCALE.png
  static/images/SCALE/22.12/DataProtectionSMARTTestsAllSCALE.png
  static/images/SCALE/22.12/DataProtectionSMARTTestsListSCALE.png
  static/images/SCALE/22.12/DeleteSMARTTest.png
  static/images/SCALE/22.12/SMARTSystemServicesGeneralOptionsSCALE.png
  static/images/SCALE/22.12/SMARTSystemServicesSCALE.png
  static/images/SCALE/22.12/SMARTSystemServicesStoppedSCALE.png
  static/images/SCALE/22.12/SmartTestsWidgetNoTests.png
  static/images/SCALE/22.12/StorageDashDisksButtonSCALE.png
  static/images/SCALE/22.12/StorageDisksExpandedSCALE.png
  static/images/SCALE/22.12/StorageDisksListedSCALE.png
  static/images/SCALE/22.12/StorageDisksManualTestSCALE.png
  static/images/SCALE/22.12/StorageDisksSelectedSCALE.png
  static/includes/SCALE/SCALEAdvancedScheduler.md.part
Labels: Technical Writer Review (TR)

#1720 Pd 83 scale 22.12 update i scsi article content with bluefin changes
  content/SCALE/SCALETutorials/Shares/iSCSI/AddingISCSIShares.md
  content/SCALE/SCALETutorials/Shares/iSCSI/IncreaseISCSIStorage.md
  content/SCALE/SCALETutorials/Shares/iSCSI/UsingISCSIShares.md
  content/SCALE/SCALEUIReference/Shares/iSCSI/iSCSISharesScreens.md
  static/images/SCALE/22.12/DatasetEditZvolListingSizeSCALE.png
  static/images/SCALE/22.12/DatasetZvolListingSCALE.png
  static/images/SCALE/22.12/FileLUNsEditExtent.png
  static/images/SCALE/22.12/FileLUNsEditExtent2.png
  static/images/SCALE/22.12/FileLUNsEditExtent3.png
  static/images/SCALE/22.12/ShellFileLUNExpandSCALE.png
  static/images/SCALE/22.12/iSCSIBlockSharesWidget.png
  static/images/SCALE/22.12/iSCSIManualAddAssocAuthTargets.png
  static/images/SCALE/22.12/iSCSIManualAddAuthAccess.png
  static/images/SCALE/22.12/iSCSIManualAddExtentDevice.png
  static/images/SCALE/22.12/iSCSIManualAddExtentFile.png
  static/images/SCALE/22.12/iSCSIManualAddInitiators.png
  static/images/SCALE/22.12/iSCSIManualAddPortalNoAuth.png
  static/images/SCALE/22.12/iSCSIManualAddTargets.png
  static/images/SCALE/22.12/iSCSIManualNoAuthAccess.png
  static/images/SCALE/22.12/iSCSIManualTargetGlobalConfig.png
  static/images/SCALE/22.12/iSCSINoTargetsScreen.png
  static/images/SCALE/22.12/iSCSISystemServicesSCALE.png
  static/images/SCALE/22.12/iSCSIWizardConfirm.png
  static/images/SCALE/22.12/iSCSIWizardCreateDevice.png
  static/images/SCALE/22.12/iSCSIWizardCreateFile.png
  static/images/SCALE/22.12/iSCSIWizardInitiator.png
  static/images/SCALE/22.12/iSCSIWizardPortalChap.png
  static/images/SCALE/22.12/iSCSIWizardPortalNoAuth.png
Labels: Technical Writer Review (TR)

#1722 Update EditACLScreens.md
  content/References/ACLPrimer.md
  content/SCALE/SCALETutorials/Storage/Datasets/PermissionsSCALE.md
  content/SCALE/SCALEUIReference/Storage/Datasets/EditACLScreens.md
  static/images/SCALE/22.12/ACLEditorSettings.png
  static/images/SCALE/22.12/CreateCustomACL.png
  static/images/SCALE/22.12/EditACLNFSv4AccessControlEntrySettings.png
  static/images/SCALE/22.12/EditACLNFSv4BasicPermissionsOptions.png
  static/images/SCALE/22.12/EditACLNSFv4AdvancedFlagsOptions.png
  static/images/SCALE/22.12/EditACLNSFv4AdvancedPermissionsOptions.png
  static/images/SCALE/22.12/EditACLNSFv4BasicFlagsOptions.png
  static/images/SCALE/22.12/EditACLPOSIXAccessControlEntrySettings.png
  static/images/SCALE/22.12/EditACLScreenNFSv4Type.png
  static/images/SCALE/22.12/EditPermissionsUnixPermissionsEditor.png
  static/images/SCALE/22.12/NFS4SelectAPresetACLWindow.png
  static/images/SCALE/22.12/PosixSelectAPresetACLWindow.png
  static/images/SCALE/22.12/ViewDatasetPermissionsWidget.png
  static/images/SCALE/22.12/ViewRootDatasetPermissionsWidget.png
Labels: Technical Writer Review (CD)

#1732 PD-80 Update Getting Started SetUpStorage.md Article
  content/SCALE/GettingStarted/Install/SetUpStorageScale.md
Labels: Technical Writer Review (CD)

#1721 StoringData: update missing right arrow icon
  content/CORE/GettingStarted/StoringData.md
Labels: Technical Writer Review (TR)

#1728 Pd-30 SCALE 22.12 system boot environment UI changes
  content/SCALE/SCALETutorials/SystemSettings/ManageBootEnvironSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/SystemBootScreensSCALE.md
  static/images/SCALE/22.12/ActivateBootEnvironmentSCALE.png
  static/images/SCALE/22.12/AddBootEnvironmentSCALE.png
  static/images/SCALE/22.12/BootEnvironmentBatchListingSCALE.png
  static/images/SCALE/22.12/BootEnvironmentListingSCALE.png
  static/images/SCALE/22.12/BootPoolStatsSettingsSCALE.png
  static/images/SCALE/22.12/BootPoolStatusAttachDiskSCALE.png
  static/images/SCALE/22.12/BootPoolStatusListingSCALE.png
  static/images/SCALE/22.12/BootPoolStatusReplaceDiskSCALE.png
  static/images/SCALE/22.12/CloneBootEnvironmentSCALE.png
  static/images/SCALE/22.12/DeleteBootEnvironmentSCALE.png
  static/images/SCALE/22.12/KeepBootEnvironmentSCALE.png
  static/images/SCALE/22.12/RenameBootEnvironmentSCALE.png
  static/images/SCALE/22.12/ScrubBootPoolNowSCALE.png
  static/images/SCALE/22.12/UnkeepBootEnvironmentSCALE.png
Labels: Technical Writer Review (TR)

#1729 Pd 20 update console setup menu article content
  content/SCALE/GettingStarted/Install/ConsoleSetupMenuScale.md
  static/images/SCALE/22.12/CSMEditInterface.png
  static/images/SCALE/22.12/CSMEditInterfaceSettings.png
  static/images/SCALE/22.12/CSMEditNetworkSettings.png
  static/images/SCALE/22.12/CSMEditStaticRoute.png
  static/images/SCALE/22.12/ConsoleSetupMenuSCALE.png
Labels: Technical Writer Review (TR)

#1719 Update hugo-extended version used for external build tests
  .github/workflows/build-external-contrib.yml
Labels: Technical Writer Review (TR)

#1713 PD-79 (docs-4405): Replace Commento with Jira Issue Collector and Call to Action section
  content/_includes/WhatsNew.md
  layouts/_default/baseof.html
  layouts/partials/commento.html
  layouts/partials/head.html
  layouts/partials/page-footer.html
  layouts/partials/page-header.html
  layouts/partials/site-header.html
Labels: Technical Writer Review (TR), Can be merged

#1738 Quick update to References index.
  content/References/_index.md
Labels: Technical Writer Review (CD), Can be merged

#1741 Add shortcode for TrueNAS Enterprise admonition boxes
  layouts/shortcodes/enterprise.html
  static/custom.css
Labels: Can be merged

#1730 MERGE ON FEB 14 PD-143 Update System Settings - Advanced Articles
  content/SCALE/SCALETutorials/SystemSettings/Advanced/AdvancedSettings.md
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  content/_includes/AdvancedSettingsWarningSCALE.md
  static/images/SCALE/22.12/AddCronJobScreen.png
  static/images/SCALE/22.12/AddInitShutdownScriptConfigScreen.png
  static/images/SCALE/22.12/AddSysctlConfigScreen.png
  static/images/SCALE/22.12/AdvancedSystemStorageWidget.png
  static/images/SCALE/22.12/ChangingAdvancedSettingsWarning.png
  static/images/SCALE/22.12/SystemAdvancedScreen.png
  static/images/SCALE/22.12/SystemAdvancedSettingsSessionsWidget.png
  static/images/SCALE/22.12/SystemStorageConfigScreen.png
Labels: Technical Writer Review (CD)

#1744 PD-120 create enterprise alerts article
  content/SCALE/SCALEUIReference/TopToolbar/Alerts/AlertSettingsScreen.md
  static/images/SCALE/22.12/AlertSettingsCertificates.png
  static/images/SCALE/22.12/AlertSettingsClustering.png
  static/images/SCALE/22.12/AlertSettingsDirectoryServices.png
  static/images/SCALE/22.12/AlertSettingsHA1.png
  static/images/SCALE/22.12/AlertSettingsHA2.png
  static/images/SCALE/22.12/AlertSettingsHardware.png
  static/images/SCALE/22.12/AlertSettingsKMIP.png
  static/images/SCALE/22.12/AlertSettingsNetwork.png
  static/images/SCALE/22.12/AlertSettingsPlugins.png
  static/images/SCALE/22.12/AlertSettingsReporting.png
  static/images/SCALE/22.12/AlertSettingsScreen.png
  static/images/SCALE/22.12/AlertSettingsSharing.png
  static/images/SCALE/22.12/AlertSettingsStorage.png
  static/images/SCALE/22.12/AlertSettingsStorage1.png
  static/images/SCALE/22.12/AlertSettingsStorage2.png
  static/images/SCALE/22.12/AlertSettingsSystem.png
  static/images/SCALE/22.12/AlertSettingsSystem1.png
  static/images/SCALE/22.12/AlertSettingsSystem2.png
  static/images/SCALE/22.12/AlertSettingsTasks.png
  static/images/SCALE/22.12/AlertSettingsTasks1.png
  static/images/SCALE/22.12/AlertSettingsTasks2.png
  static/images/SCALE/22.12/AlertSettingsUPS.png
Labels: Can be merged

#1724 PD-112: getting started create UI config article
  content/SCALE/GettingStarted/Install/ConsoleSetupMenuScale.md
  content/SCALE/GettingStarted/Install/InstallEnterpriseHASCALE.md
  content/SCALE/GettingStarted/Install/InstallPrepEnterprise.md
  content/SCALE/GettingStarted/Install/InstallPrepHomeUsers.md
  content/SCALE/GettingStarted/Install/InstallPrepNonEnterprise.md
  content/SCALE/GettingStarted/Install/InstallingSCALE.md
  content/SCALE/GettingStarted/Install/SetUpBackupScale.md
  content/SCALE/GettingStarted/Install/SetUpSharing.md
  content/SCALE/GettingStarted/Install/UIConfigurationSCALE.md
  content/SCALE/GettingStarted/Install/_index.md
  content/SCALE/SCALETutorials/Network/ConfigureStaticRoutes.md
  content/SCALE/SCALETutorials/Network/Interfaces/ManagingInterfaces.md
  content/SCALE/SCALETutorials/Network/Interfaces/SettingUpStaticIPs.md
  content/_includes/DirectoryServicesInstallRequirementsSCALE.md
  content/_includes/NetworkInstallRequirementsSCALE.md
  content/_includes/SCALEInstallerProcedure.md
  content/_includes/SMTPInstallRequirementsSCALE.md
  static/images/SCALE/22.12/EditInterfaceAddAliasesHA.png
  static/images/SCALE/22.12/EditInterfaceFailoveSettingsrHA.png
  static/images/SCALE/22.12/EditInterfaceInterfaceSettingsHA.png
  static/images/SCALE/22.12/FailoverServiceScreen.png
  static/images/SCALE/22.12/FailoverSyncToPeerDialog.png
  static/images/SCALE/22.12/HAMainDashboard.png
Labels: Can be merged

#1746 PD-81 SCALE 22.12.0 SMB Share Article UI and Tutorial Content
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShadowCopies.md
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShares.md
  content/SCALE/SCALETutorials/SystemSettings/Services/SMBServiceSCALE.md
  content/SCALE/SCALEUIReference/Shares/SMB/SMBSharesScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/SMBServicesScreen.md
  static/images/SCALE/22.12/SMBServiceOptionsSCALE.png
  static/images/SCALE/22.12/SMBShareACLScreen.png
  static/images/SCALE/22.12/SharingSMBWidget.png
Labels: Technical Writer Review (CD)

#1749 Directory-services-taglist-fix SCALE
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/ActiveDirectory.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/Idmap.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/KerberosKeytab.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/KerberosRealms.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/KerberosSettings.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/LDAP.md
Labels: Can be merged

#1731 PD-44 SCALE 22.12.1 Release Notes
  content/SCALE/SCALE22.12.md
Labels: Can be merged

#1751 PD-170: TC 2.0 relnotes alias update
  content/_includes/TCReleaseNotes/2.0-Beta.md
  content/_includes/TCReleaseNotes/2.0.md
Labels: Can be merged

#1750 PD-189: typo fix for install guide/data sharing article.
  content/SCALE/GettingStarted/Install/SetUpSharing.md
Labels: Technical Writer Review (CD), Can be merged

#1754 22.12.1 release notes: add replication known issue
  content/SCALE/SCALE22.12.md
Labels: Technical Writer Review (CD), Can be merged

#1745 Pd-157 describe ha graceful shutdown within power options content scale enterprise
  content/SCALE/SCALETutorials/TopToolbar/ShutDownSCALEHA.md
  static/images/SCALE/22.12/PowerButtonSCALE.png
Labels: Ready to merge

#1748 PD-112 Update SetUpBackupSCALE.md Article
  content/SCALE/GettingStarted/Install/SetUpBackupScale.md
Labels: Technical Writer Review (TR), Ready to merge

#1747 PD-115 Create Update HA SCALE Article
  content/SCALE/SCALETutorials/SystemSettings/UpdateHASCALE.md
  content/SCALE/SCALETutorials/SystemSettings/UpdateSCALE.md
Labels: Technical Writer Review (TR), Ready to merge

#1761 Add fix version to Replication known issue.
  content/SCALE/SCALE22.12.md
Labels: Technical Writer Review (CD), Ready to merge

#1757 Refresh Solutions index
  content/Solutions/_index.md
Labels: Ready to merge

#1763 Pd 172 update view enclosure article for mini r and r30
  content/SCALE/SCALEUIReference/SystemSettings/EnclosureScreensSCALE.md
Labels: Technical Writer Review (CD), Ready to merge

#1766 Resync LDAP bug ticket title with Jira
  content/CORE/COREReleaseNotes.md
Labels: Technical Writer Review (CD)

#1764 PD-192 Update TNHardwareGuide Snippet
  content/_includes/TNHardwareGuide.md
Labels: Technical Writer Review (CD), Ready to merge
