Repository truenas/documentation, pull requests merged in 2023-08, with the labels that each got.

#2045 PD-511 Content Updates to the Update Articles
  content/SCALE/SCALETutorials/SystemSettings/UpdateHASCALE.md
  content/SCALE/SCALETutorials/SystemSettings/UpdateSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/UpdateScreensSCALE.md
  static/images/SCALE/23.10/ApplyPendingUdates.png
  static/images/SCALE/23.10/ManualUpdateScreen.png
  static/images/SCALE/23.10/RestartAfterUpdate.png
  static/images/SCALE/23.10/SaveConfigSettingsWindow.png
  static/images/SCALE/23.10/SystemUpdateScreenAvailableUpdate.png
Labels: Version Specific, Technical Writer Review (DP)

#2062 PD-597: Create MinIO Enterprise mnmd tutorial
  content/SCALE/SCALETutorials/Apps/CommunityApps/MinIOApp/_index.md
  content/SCALE/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md
  content/SCALE/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseSNMD.md
  content/SCALE/SCALETutorials/Apps/EnterpriseApps/MinIO/_index.md
  content/_includes/MinIOEnterpriseStorageConfig.md
  content/_includes/MinIoEnterpriseConfig1.md
  static/images/SCALE/23.10/InstallMinIOAddMultiModeConfigExample.png
  static/images/SCALE/23.10/InstallMinIOAddMultiModeMNMD.png
  static/images/SCALE/23.10/InstallMinIOEnterpriseNetworkConfig.png
  static/images/SCALE/23.10/InstallMinIOEnterpriseResourcesConfig.png
  static/images/SCALE/23.10/InstallMinIOEnterpriseStorageConfig.png
  static/images/SCALE/23.10/InstallMinIOLogSearchEnterHostPaths.png
  words-to-ignore.txt
Labels: Review (TM)

#2065 PD-581: 23.10 app updates
  content/SCALE/SCALETutorials/Apps/CommunityApps/ddns-updater.md
  content/SCALE/SCALEUIReference/Apps/AppsScreensSCALE.md
  static/images/SCALE/23.10/AppsPodShellScreen.png
  static/images/SCALE/23.10/InstalledAppsScreenWithApps.png
  static/images/SCALE/23.10/WebDAVPodLogsScreen.png
Labels: Review (TM)

#2034 PD-552: cli article style and template update
  content/SCALE/SCALECLIReference/Account/CLIgroup.md
  content/SCALE/SCALECLIReference/Account/CLIuser.md
  content/SCALE/SCALECLIReference/Account/_index.md
  content/SCALE/SCALECLIReference/App/_index.md
  content/SCALE/SCALECLIReference/Auth/_index.md
  content/SCALE/SCALECLIReference/Directory Service/_index.md
  content/SCALE/SCALECLIReference/Filesystem/_index.md
  content/SCALE/SCALECLIReference/Network/_index.md
  content/SCALE/SCALECLIReference/Service/_index.md
  content/SCALE/SCALECLIReference/Sharing/_index.md
  content/SCALE/SCALECLIReference/Storage/_index.md
  content/SCALE/SCALECLIReference/System/_index.md
  content/SCALE/SCALECLIReference/Task/CloudSync/_index.md
  content/SCALE/SCALECLIReference/Task/_index.md
  content/SCALE/SCALECLIReference/_index.md
  content/_includes/CLI/AccountGroupProperties.md
  content/_includes/CLI/AccountUserProperties.md
  content/_includes/CLI/CLICommandWIP.md
  content/_includes/CLI/SCALECLIGetHelp.md
  content/_includes/CLI/SCALECLIIntroduction.md
Labels: Version Specific, Technical Writer Review (DP)

#2054 PD-349 Sessions Namespace and PD-351 Two_Factor Namespace
  content/SCALE/SCALECLIReference/Auth/CLISessions.md
  content/SCALE/SCALECLIReference/Auth/CLITwoFactor.md
Labels: Technical Writer Review (MJ)

#2076 PD-606 Remove WebDAV CLI Content
  content/SCALECLIReference/Service/CLIDynDNS/_index.md
  content/SCALECLIReference/Service/CLIOpenVPN/_index.md
  content/SCALECLIReference/Service/CLIRsync/_index.md
  content/SCALECLIReference/Service/CLIRsyncMod/_index.md
  content/SCALECLIReference/Service/CLIS3/_index.md
  content/SCALECLIReference/Service/CLITFTP/_index.md
  content/SCALECLIReference/Service/CLIWebDav/_index.md
  content/SCALECLIReference/Service/_index.md
  content/SCALECLIReference/Sharing/_index.md
Labels: Version Specific, Review (TM)

#2074 PD-312: 23.10-BETA.1 Release Notes
  content/GettingStarted/23.10Upgrades.md
  content/GettingStarted/Migrate/MigratingFromCORE.md
  content/GettingStarted/SCALEReleaseNotes.md
  content/GettingStarted/UserAgreements/SoftwareDevelopmentLifeCycleSCALE.md
  content/SCALETutorials/SystemSettings/UpdateSCALE.md
  content/SCALETutorials/Virtualization/_index.md
  content/SCALEUIReference/DataProtection/_index.md
  content/SCALEUIReference/Storage/_index.md
  content/_includes/23.10FeatureList.md
  content/_includes/ISOUpgrades.md
  content/_includes/LifecycleTable.md
  content/_includes/ManualUpdates.md
  content/_includes/ReleaseScheduleWarning.md
  content/_includes/SoftwareStatusPage.md
  content/_index.md
  layouts/partials/page-header.html
  static/includes/General/MenuNav.md.part
  static/includes/General/TNQualityLifecycle.html.part
  words-to-ignore.txt
Labels: Version Specific, Technical Writer Review (MJ)

#2059 PD-616: Add Docs Hub Version Switching (23.10 Cobia)
  content/404Error.md
  content/CORE/_index.md
  content/Contributing/IssueReporting/PrereleaseUserFeedback.md
  content/SCALE/SCALECLIReference/Auth/CLITwoFactor.md
  content/SCALE/_index.md
  content/TrueCommand/_index.md
  content/_index.md
  i18n/en.yaml
  jenkins/update-scale-next
  layouts/partials/docs-nav.html
  layouts/partials/reading-time.html
  layouts/partials/search-form.html
  layouts/partials/site-header.html
  layouts/shortcodes/children.html
  static/custom.css
  static/images/SCALE/23.10/NewLeaveFeedback.png
  static/ixsystems_logo_130_30.svg
Labels: Version Specific, Technical Writer Review (DP)

#2080 PD-628 Add Migration Instructions for Deprecated Services
  content/GettingStarted/Migrate/MigrateCOREHAtoSCALEHA.md
  content/GettingStarted/Migrate/MigratePrep.md
  content/GettingStarted/Migrate/MigratePrepEnterprise.md
  content/GettingStarted/Migrate/MigratingFromCORE.md
  content/GettingStarted/Migrate/_index.md
  content/_includes/MigrateCOREtoSCALEWarning.md
  content/_includes/MigrateCoreServicesToCobia.md
  content/_includes/MigrateCoreServicesToCobiaEnterprise.md
Labels: Version Specific, Review (TM)

#2084 Pd 623 update data protection widget content
  content/SCALECLIReference/Account/CLIuser.md
  content/SCALECLIReference/Auth/CLISessions.md
  content/SCALEUIReference/Storage/Datasets/DatasetsScreensScale.md
  words-to-ignore.txt
Labels: Version Specific, Review (TM)

#2087 Add note about zfs dataset legacy mountpoint property to release notes
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific

#2085 Pd 436 document sharing nfs namespace
  content/SCALECLIReference/Sharing/CLINFS.md
Labels: Technical Writer Review (DP)

#2092 23.10 Branch Hugo testing cleanup
  content/GettingStarted/Configure/FirstTimeLogin.md
  content/GettingStarted/Install/ConsoleSetupMenuScale.md
  content/SCALETutorials/Shares/SMB/SetUpBasicTimeMachineSMBShare.md
  content/_includes/Jobs.md
  content/_includes/NetworkBridgeSCALE.md
  static/images/SCALE/23.10/AddAlertServiceEmailScreen.png
  static/images/SCALE/23.10/JobsAbort.png
  static/images/SCALE/23.10/JobsMenu.png
  static/images/SCALE/23.10/TimeoutDialog.png
  static/images/SCALE/23.10/TopToolbar.png
Labels: Technical Writer Review (MJ)

#2093 23.10: Update Storage Dashboard image
  content/SCALETutorials/Storage/Pools/ManagePoolsScale.md
  content/SCALETutorials/Storage/_index.md
  static/images/SCALE/22.12/StorageDashboardWithPool.png
  static/images/SCALE/23.10/StorageDashboardWithPool.png
Labels: Version Specific

#2094 Update Full Name descriptions
  content/SCALECLIReference/Account/CLIuser.md
  content/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
  content/_includes/CLI/AccountUserProperties.md
Labels: Technical Writer Review (MJ)

#2091 Pd 446 document storage snapshot namespace
  content/SCALECLIReference/Storage/CLISnapshot.md
Labels: Technical Writer Review (DP)

#2096 Pd 473 create task snapshot article content
  content/SCALECLIReference/Task/CLISnapshotTask.md
Labels: Technical Writer Review (DP)

#2098 23.10 - remove obsolete community tutorials
  content/SCALETutorials/CommunityRecommends/SpotlightSupportSamba/index.md
  content/SCALETutorials/CommunityRecommends/_index.md
  content/SCALETutorials/CommunityRecommends/hardened-backup-repository-for-veeam/_index.md
Labels: Version Specific

#2099 Remove obsolete community tutorials
  content/SCALE/SCALETutorials/CommunityRecommends/SpotlightSupportSamba/index.md
  content/SCALE/SCALETutorials/CommunityRecommends/_index.md
  content/SCALE/SCALETutorials/CommunityRecommends/hardened-backup-repository-for-veeam/_index.md
Labels: File Moved

#2078 PD-347 SCALE CLI - Create Network IPMI Article
  content/SCALECLIReference/Network/CLIIPMI.md
Labels: Technical Writer Review (MJ), Technical Writer Review (DP)

#2095 PD-348 SCALE CLI - Create Auth Api_key Namespace Content
  content/SCALECLIReference/Auth/CLIApiKey.md
Labels: Technical Writer Review (MJ)

#2077 PD-440 CLI Disk Namespace
  content/SCALECLIReference/Storage/CLIDisk.md
  content/_includes/CLI/HintInteractiveArgsEditor.md
Labels: Technical Writer Review (MJ)

#2106 PD-653: Update TrueNAS Config Backup content
  content/TrueCommand/SystemManagement/TrueNASConfigManage.md
  content/TrueCommand/TCGettingStarted/InitialConfig.md
Labels: Version Specific

#2107 PD-570: Add iX portal 2FA copy
  content/TrueCommand/TCGettingStarted/Install/InstallTCCloud.md
Labels: Version Specific, Technical Writer Review (MJ)

#2113 PD-661: Create PermissionsHierarchy snippet and update multiple artic…
  content/TrueCommand/Administration/Systems.md
  content/TrueCommand/Administration/Users.md
  content/TrueCommand/TCGettingStarted/UserAccounts.md
  content/_includes/TCPermissionsHierarchy.md
Labels: Version Specific

#2110 PD-596: TC 2.3.4 release notes
  content/TrueCommand/TCReleaseNotes.md
  words-to-ignore.txt
Labels: Version Specific, Technical Writer Review (DP)

#2111 PD-660: Update 23.10-BETA.1 for syslog behavior change
  content/GettingStarted/SCALEReleaseNotes.md
  content/SCALETutorials/SystemSettings/Advanced/ManageSysLogsSCALE.md
  content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  static/images/SCALE/23.10/AdvancedSystemSettingsSyslogWidget.png
  static/images/SCALE/23.10/SyslogConfigScreen.png
Labels: Version Specific

#2123 PD-428 CLI Services SMART Namespace
  content/SCALECLIReference/Service/CLISMART/_index.md
  content/SCALECLIReference/Storage/CLIDisk.md
Labels: Technical Writer Review (MJ)

#2115 Pd 464 cli guide document system truenas namespace
  content/SCALECLIReference/System/CLITruenas.md
  content/SCALECLIReference/Task/CLISnapshotTask.md
Labels: Technical Writer Review (MJ)
