Repository truenas/documentation, pull requests merged in 2023-09, with the labels that each got.

#2133 Pd 627 update email articles
  content/GettingStarted/Configure/FirstTimeLogin.md
  content/SCALETutorials/SystemSettings/General/GeneralSettings.md
  content/SCALETutorials/SystemSettings/General/SettingUpSystemEmail.md
  content/SCALETutorials/SystemSettings/_index.md
  content/SCALETutorials/TopToolbar/SettingUpSystemEmail.md
  content/SCALETutorials/TopToolbar/_index.md
  content/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  content/SCALEUIReference/TopToolbar/Alerts/EmailScreens.md
  content/SCALEUIReference/TopToolbar/_index.md
  content/_includes/AlertsSCALE.md
  content/_includes/ChangeLoggedInUserPassword.md
  content/_includes/DirectoryServicesMonitor.md
  content/_includes/EmailOptions.md
  content/_includes/EmailOptionsGmail.md
  content/_includes/EmailOptionsSMTP.md
  content/_includes/Jobs.md
  content/_includes/StatusOfTrueCommand.md
  content/_includes/TopToolbar.md
  static/images/SCALE/22.12/EmailGmailAllow.png
  static/images/SCALE/22.12/EmailGmailAuthorization.png
  static/images/SCALE/22.12/EmailGmailChooseAccount.png
  static/images/SCALE/22.12/EmailGmailOAuthConfigurationScreen1.png
  static/images/SCALE/22.12/EmailGmailOAuthConfigurationScreen2.png
  static/images/SCALE/22.12/EmailGmailSignIn.png
  static/images/SCALE/22.12/EmailSMTPConfigurationScreen.png
  static/images/SCALE/23.10/EditAlertServiceEmailScreen.png
  static/images/SCALE/23.10/EmailGmailAllow.png
  static/images/SCALE/23.10/EmailGmailAuthorization.png
  static/images/SCALE/23.10/EmailGmailChooseAccount.png
  static/images/SCALE/23.10/EmailOptionsGmailOAuth.png
  static/images/SCALE/23.10/EmailOptionsGmailOAuthApplied.png
  static/images/SCALE/23.10/EmailOptionsSMTP.png
  static/images/SCALE/23.10/EmailWidget.png
  words-to-ignore.txt
Labels: Review (TM)

#2140 Patch for scale 22.12 id 584
  jenkins/update-22.12
Labels: Version Specific

#2128 PD-618: Update DOCSNAV for 13.0, 22.12, and 2.3 branches and start setting up master as nightly dev tracking branch
  content/CORE/_index.md
  content/SCALE/_index.md
  layouts/partials/docs-nav.html
  layouts/shortcodes/section-cards.html
  words-to-ignore.txt
Labels: Version Specific

#2138 Pd 646 create snippet for shares do not use a pool for share
  content/SCALECLIReference/Sharing/CLINFS.md
  content/SCALECLIReference/Sharing/CLISMB.md
  content/SCALETutorials/Shares/AddingNFSShares.md
  content/SCALETutorials/Shares/SMB/AddSMBShares.md
  content/_includes/CreateDatasetSCALE.md
  content/_includes/ShareDatasetsNotPools.md
  content/_includes/SharingPrereqs.md
  words-to-ignore.txt
Labels: Version Specific, Review (TM)

#2127 Pd 450 cli guide document system config namespace
  content/SCALECLIReference/System/CLIConfig.md
  content/SCALECLIReference/System/CLITruenas.md
  content/SCALETutorials/SystemSettings/General/ManageSysConfigSCALE.md
Labels: Technical Writer Review (MJ)

#2137 PD-553: Review Storage Pool Dashboard and Creation UI Reference and Tutorial articles for dRAID feature
  content/GettingStarted/Configure/SetUpStorageScale.md
  content/GettingStarted/Install/InstallEnterpriseHASCALE.md
  content/GettingStarted/Install/InstallingSCALE.md
  content/SCALETutorials/Shares/SMB/AddSMBHomeShare.md
  content/SCALETutorials/Storage/Datasets/CreatingSnapshots.md
  content/SCALETutorials/Storage/Datasets/EncryptionSCALE.md
  content/SCALETutorials/Storage/Pools/CreatePoolScale.md
  content/SCALETutorials/Storage/Pools/CreatePoolWizard.md
  content/SCALEUIReference/Storage/Datasets/EncryptionUISCALE.md
  content/SCALEUIReference/Storage/Pools/DevicesScreensSCALE.md
  content/SCALEUIReference/Storage/Pools/PoolCreateWizardScreens.md
  content/SCALEUIReference/Storage/Pools/PoolManagerScreens.md
  content/SCALEUIReference/Storage/_index.md
  content/_includes/COREMigratesList.md
  content/_includes/MinIODatasetRequirements.md
  content/_includes/PoolCreationWizardCommonSettings.md
  content/_includes/TNHardwareGuide.md
  static/images/SCALE/23.10/StorageDashboardNoPools.png
  static/images/SCALE/23.10/StorageDashboardWithPool.png
  words-to-ignore.txt
Labels: Version Specific, Technical Writer Review (MJ)

#2134 PD-553: Write basic dRAID primer
  content/References/ZFSPrimer.md
  content/References/dRAIDprimer.md
  static/images/Reference/dRAIDandraidz.png
  static/images/Reference/raidzdRAIDSimplified.png
  words-to-ignore.txt
Labels: Technical Writer Review (MJ)

#2157 Fix 13.0 release notes link from home page
  content/_index.md
Labels: Version Specific

#2162 (13.0) PD-696: Add Deprecations.md and some initial population
  content/GettingStarted/COREReleaseNotes.md
  content/GettingStarted/Deprecations.md
Labels: Version Specific

#2175 PD-704: fix up TC 2.3 home page links
  content/Administration/Admin/LDAPServers.md
  content/Alerts/_index.md
  content/Recommendations/TCCloudSecurity.md
  content/SystemManagement/_index.md
  content/TCGettingStarted/InitialConfig.md
  content/_index.md
  words-to-ignore.txt
Labels: Version Specific

#2174 PD-704: 13.0 branch cross references fixes
  content/API/_index.md
  content/CORETutorials/_index.md
  content/CoreSecurityReports/_index.md
  content/_index.md
Labels: Version Specific

#2166 PD-431 CLI Service SSH
  content/SCALECLIReference/Service/CLISSH/_index.md
Labels: Technical Writer Review (MJ)

#2196 PD-729 (Backport to 23.10)
  content/_includes/COREMigratesList.md
Labels: Version Specific

#2198 (23.10) Update 23.10-RC.1 SCALEReleaseNotes.md
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific
