Repository truenas/documentation, pull requests merged in 2023-07, with the labels that each got.

#2013 PD-556: 22.12.3.2 Release Notes
  content/SCALE/SCALE22.12.md
Labels: Version Specific

#2014 Pd 391 user feedback tutorial
  content/Contributing/IssueReporting/PrereleaseUserFeedback.md
  content/SCALE/SCALEReleaseNotes.md
  content/SCALE/SCALEUIReference/TopToolbar/_index.md
  content/_includes/FeedbackWindow.md
  content/_includes/NewLeaveFeedback.md
  static/images/SCALE/22.02/TopToolbar.png
  static/images/SCALE/23.10/FeedbackIcon.png
  static/images/SCALE/23.10/FeedbackWindow.png
  static/images/SCALE/23.10/NewLeaveFeedback.png
  static/images/SCALE/23.10/TopToolbar.png
  words-to-ignore.txt
Labels: Version Specific

#2011 Pd 393 23.10 updates to storage articles
  content/SCALE/SCALETutorials/Storage/Pools/CreatePoolScale.md
  content/SCALE/SCALETutorials/Storage/Pools/CreatePoolWizard.md
  content/SCALE/SCALETutorials/Storage/Pools/ImportPoolScale.md
  content/SCALE/SCALETutorials/Storage/Pools/ManagePoolsScale.md
  content/SCALE/SCALETutorials/Storage/Pools/_index.md
  content/SCALE/SCALEUIReference/Storage/Pools/DevicesScreensSCALE.md
  content/SCALE/SCALEUIReference/Storage/Pools/Disks/_index.md
  content/SCALE/SCALEUIReference/Storage/Pools/PoolCreateWizardScreens.md
  content/SCALE/SCALEUIReference/Storage/Pools/PoolManagerScreens.md
  content/SCALE/SCALEUIReference/Storage/Pools/_index.md
  content/SCALE/SCALEUIReference/Storage/StorageDashboardScreen.md
  content/_includes/PoolCreationWizardCommonSettings.md
  content/_includes/StoragePoolsIntroScale.md
  static/images/SCALE/23.10/LeaveFeedbackWindow.png
  static/images/SCALE/23.10/PoolCreationWizard.png
  static/images/SCALE/23.10/PoolCreationWizardCacheScreen.png
  static/images/SCALE/23.10/PoolCreationWizardDataScreen.png
  static/images/SCALE/23.10/PoolCreationWizardDedupScreen.png
  static/images/SCALE/23.10/PoolCreationWizardGenInfoExportedPool.png
  static/images/SCALE/23.10/PoolCreationWizardGenInfoNonUniqueSerialNums.png
  static/images/SCALE/23.10/PoolCreationWizardGeneralInfo.png
  static/images/SCALE/23.10/PoolCreationWizardLogScreen.png
  static/images/SCALE/23.10/PoolCreationWizardManualSelectionScreen.png
  static/images/SCALE/23.10/PoolCreationWizardMetadataScreen.png
  static/images/SCALE/23.10/PoolCreationWizardReviewScreen.png
  static/images/SCALE/23.10/PoolCreationWizardSpareScreen.png
Labels: Version Specific, Technical Writer Review (DP)

#2000 PD-550: 13.0-U5.2 hotpatch release notes
  content/CORE/COREReleaseNotes.md
  words-to-ignore.txt
Labels: Version Specific

#2017 Pd 58 scale 23.10 apps article updates
  content/SCALE/GettingStarted/Configure/VMandAppConfigSCALE.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/InstallWGEasyApp.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/MinIOClustersSCALE/MinioManualUpdate.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/_index.md
  content/SCALE/SCALETutorials/Apps/UsingCatalogs.md
  content/SCALE/SCALETutorials/Apps/UsingCustomApp.md
  content/SCALE/SCALETutorials/Apps/_index.md
  content/SCALE/SCALEUIReference/Apps/AppsScreensSCALE.md
  content/SCALE/SCALEUIReference/Apps/InstallCustomAppScreens.md
  content/SCALE/SCALEUIReference/Apps/LaunchDockerImageScreens.md
  static/images/SCALE/23.10/AddCatalogWarning.png
  static/images/SCALE/23.10/AppUpdateWindow.png
  static/images/SCALE/23.10/AppsAddCatalogScreen.png
  static/images/SCALE/23.10/AppsCatalogExpandedViewWithOptions.png
  static/images/SCALE/23.10/AppsCatalogScreen.png
  static/images/SCALE/23.10/AppsChoosePodWindow.png
  static/images/SCALE/23.10/AppsChoosePoolForApps.png
  static/images/SCALE/23.10/AppsDeleteAppDialog.png
  static/images/SCALE/23.10/AppsDiscoverScreen.png
  static/images/SCALE/23.10/AppsDiscoverScreenFilterCategoryOptions.png
  static/images/SCALE/23.10/AppsDiscoverScreenFilterOptions.png
  static/images/SCALE/23.10/AppsDiscoverScreenHeaderAndSearch.png
  static/images/SCALE/23.10/AppsEditCatalogScreen.png
  static/images/SCALE/23.10/AppsInstallWizardSectionTOC.png
  static/images/SCALE/23.10/AppsInstalledAppsScreenNoApps.png
  static/images/SCALE/23.10/AppsInstalledAppsSettingOptions.png
  static/images/SCALE/23.10/AppsNextcloudInstallScreen.png
  static/images/SCALE/23.10/AppsTruenasCatalogSummaryWindow.png
  static/images/SCALE/23.10/AppsUnsetPoolDialog.png
  static/images/SCALE/23.10/InstallCustomAppAddHostPathVol.png
  static/images/SCALE/23.10/InstallCustomAppAddMemoryBackedVol.png
  static/images/SCALE/23.10/InstallCustomAppAddPortalConfiguration.png
  static/images/SCALE/23.10/InstallCustomAppAddResourceLimits.png
  static/images/SCALE/23.10/InstallCustomAppAddStorageVolumes.png
  static/images/SCALE/23.10/InstallCustomAppAddWorkloadDetails.png
  static/images/SCALE/23.10/InstallCustomAppApplicationName.png
  static/images/SCALE/23.10/InstallCustomAppContainerEntrypoint.png
  static/images/SCALE/23.10/InstallCustomAppContainerEnvironmentVariables.png
  static/images/SCALE/23.10/InstallCustomAppContainerImages.png
  static/images/SCALE/23.10/InstallCustomAppNetworking.png
  static/images/SCALE/23.10/InstallCustomAppNetworkingAddExternalInterfaces.png
  static/images/SCALE/23.10/InstallCustomAppNetworkingDNSConfig.png
  static/images/SCALE/23.10/InstallCustomAppPortForwarding.png
  static/images/SCALE/23.10/InstallCustomAppScalingUpgradePolicy.png
  static/images/SCALE/23.10/InstallCustomAppScreenNameAndImage.png
  static/images/SCALE/23.10/InstallCustomAppScreenStorage.png
  static/images/SCALE/23.10/InstallCustomAppSearchInputFields.png
  static/images/SCALE/23.10/InstallCustomAppTOC.png
  static/images/SCALE/23.10/InstalledAppScreenApplicationInfoWidget.png
  static/images/SCALE/23.10/InstalledAppsBulkActions.png
  static/images/SCALE/23.10/InstalledAppsHistoryWidget.png
  static/images/SCALE/23.10/InstalledAppsNotesWidget.png
  static/images/SCALE/23.10/InstalledAppsScreenContainersWidget.png
  static/images/SCALE/23.10/InstalledAppsStatus.png
  static/images/SCALE/23.10/KubernetesSettingsScreenBottom.png
  static/images/SCALE/23.10/KubernetesSettingsScreenTop.png
Labels: Technical Writer Review (DP)

#2020 PD-402: Add Debug Kernel checkbox to SCALE docs
  content/SCALE/GettingStarted/Configure/UIConfigurationSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Advanced/AdvancedSettings.md
  content/SCALE/SCALETutorials/SystemSettings/Advanced/_index.md
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  content/_includes/AdvancedSettingsWarningSCALE.md
  static/images/SCALE/23.10/SystemSettingsAdvancedKernel.png
Labels: Version Specific, Technical Writer Review (MJ)

#2022 PD-394 23.10 Updates to TFTP App Article
  content/SCALE/SCALETutorials/Apps/CommunityApps/TFTP-HPAApp.md
  content/SCALE/SCALETutorials/SystemSettings/Services/TFTPServiceSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/TFTPServiceScreen.md
  static/images/SCALE/23.10/InstallTFTPServerAddTFTPConfigEnvironVariables.png
  static/images/SCALE/23.10/InstallTFTPServerAppNetworkConfig.png
  static/images/SCALE/23.10/InstallTFTPServerAppScreen.png
  static/images/SCALE/23.10/InstallTFTPServerAppStorageHostPath.png
  static/images/SCALE/23.10/TFTPServerAppInfoScreen.png
  static/images/SCALE/23.10/TFTPServerAppInstalled.png
  static/images/SCALE/23.10/TFTPServerAppWidget.png
Labels: Version Specific, Technical Writer Review (DP)

#2019 Pd 411 update wg easy application article
  content/SCALE/SCALETutorials/Apps/CommunityApps/InstallWGEasyApp.md
  content/SCALE/SCALETutorials/SystemSettings/Services/OpenVPNSCALE.md
  content/SCALE/SCALEUIReference/Network/OpenVPN.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/OpenVPNScreens.md
  static/images/SCALE/23.10/WGEasyAppConfigSettings.png
  static/images/SCALE/23.10/WGEasyAppInfoScreen.png
  static/images/SCALE/23.10/WGEasyAppInstalScreen.png
  static/images/SCALE/23.10/WGEasyAppStorageEnableCustomHostPathSettings.png
  static/images/SCALE/23.10/WGEasyAppWidget.png
  static/images/SCALE/23.10/WGEasyInstallAddDNSOptions.png
  static/images/SCALE/23.10/WGEasyInstallAddResourceLimits.png
  static/images/SCALE/23.10/WGEasyInstallAppNetworking.png
  static/images/SCALE/23.10/WGEasyInstallAppStorageAddExtraHostPaths.png
  static/images/SCALE/23.10/WGEasyWebPortal.png
Labels: Version Specific, Technical Writer Review (DP)

#2029 Pd 408 review accounts users and groups content
  content/SCALE/GettingStarted/Configure/SetUpSharing.md
  content/SCALE/SCALETutorials/Credentials/ManageLocalGroups.md
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBHomeShare.md
  content/SCALE/SCALEUIReference/Credentials/LocalGroupsScreens.md
  content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
  static/images/SCALE/22.12/AddGroupGIDConfigSCALE.png
  static/images/SCALE/22.12/AddUser-UserIDAndGroupSettings.png
  static/images/SCALE/22.12/AddUserDirPermAuthSCALE.png
  static/images/SCALE/22.12/AddUserDirPermsAuthSettings.png
  static/images/SCALE/22.12/AddUserHomeDirAuthSCALE.png
  static/images/SCALE/22.12/AddUserHomeDirPermSCALE.png
  static/images/SCALE/22.12/AddUserIdentificationSettings.png
  static/images/SCALE/22.12/AllUsersScreenBuiltInSCALE.png
  static/images/SCALE/22.12/AllUsersScreenSCALE.png
  static/images/SCALE/22.12/EditUserIdentificationSCALE.png
  static/images/SCALE/22.12/GroupsListedExpandedSCALE.png
  static/images/SCALE/22.12/GroupsListedSCALE.png
  static/images/SCALE/22.12/GroupsManageMembersSCALE.png
  static/images/SCALE/22.12/UserScreenUserDetails.png
  static/images/SCALE/23.10/AddGroupGIDConfigSCALE.png
  static/images/SCALE/23.10/AddUser-UserIDAndGroupSettings.png
  static/images/SCALE/23.10/AddUserDirPermsAuthSettings.png
  static/images/SCALE/23.10/AddUserHomeDirAuthSCALE.png
  static/images/SCALE/23.10/AddUserHomeDirPermSCALE.png
  static/images/SCALE/23.10/AddUserIdentificationSettings.png
  static/images/SCALE/23.10/AllUsersScreenBuiltInSCALE.png
  static/images/SCALE/23.10/AllUsersScreenSCALE.png
  static/images/SCALE/23.10/EditGroup.png
  static/images/SCALE/23.10/EditUserIdentificationSCALE.png
  static/images/SCALE/23.10/GroupsListedExpandedSCALE.png
  static/images/SCALE/23.10/GroupsListedSCALE.png
  static/images/SCALE/23.10/GroupsManageMembersSCALE.png
  static/images/SCALE/23.10/UserScreenUserDetails.png
Labels: Version Specific, Technical Writer Review (MJ)

#2037 PD-555: Snippetized CORE and SCALE Cloud provider lists
  content/CORE/CORETutorials/Tasks/CreatingCloudSyncTasks.md
  content/CORE/UIReference/System/CloudCredentials.md
  content/CORE/UIReference/Tasks/CloudSyncTasks.md
  content/SCALE/SCALETutorials/Credentials/BackupCredentials/AddCloudCredentials.md
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddCloudSyncTasks.md
  content/SCALE/SCALEUIReference/Credentials/BackupCredentials/CloudCredentialScreens.md
  content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  content/_includes/CloudServiceProvidersCORE.md
  content/_includes/CloudServiceProvidersSCALE.md
  words-to-ignore.txt
Labels: Technical Writer Review (DP)

#2028 PD-371: 23.10 MinIO app article updates
  content/SCALE/SCALETutorials/Apps/CommunityApps/MinIOApp/MinIOClustering.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/MinIOApp/MinioManualUpdate.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/MinIOApp/_index.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/MinIOClustersSCALE/MinIOClustering.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/MinIOClustersSCALE/_index.md
  content/SCALE/SCALETutorials/Apps/EnterpriseApps/ConfigMinioEnterprise.md
  content/SCALE/SCALETutorials/SystemSettings/Services/S3ServiceSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/S3ServiceScreen.md
  content/_includes/AddMinioEnterpriseTrain.md
  content/_includes/MinIODNSAndResourceLimits.md
  content/_includes/MinIODatasetRequirements.md
  content/_includes/MinIOEnableDistributedModeInfo.md
  content/_includes/MinIOInstallAppNameWorkloadConfigSteps.md
  content/_includes/MinIOInstallArgAndEnvironVarSteps.md
  content/_includes/MinIOPortsAndLogSearch.md
  content/_includes/MinIOStorageDataVolume.md
  static/images/SCALE/23.10/AppsEditCatalogAddEnterpriseTrain.png
  static/images/SCALE/23.10/AppsMinIOS3widget.png
  static/images/SCALE/23.10/DiscoverScreenMinIOAppWidgets.png
  static/images/SCALE/23.10/InstallMinIOAddMultiModeSNMDorMNMD.png
  static/images/SCALE/23.10/InstallMinIOEnterprise.png
  static/images/SCALE/23.10/InstallMinIOLogging.png
  static/images/SCALE/23.10/InstallMinIOLoggingEnableLogSearch.png
  static/images/SCALE/23.10/InstallMinIONetworkConfig.png
  static/images/SCALE/23.10/InstallMinIOStorageConfig.png
  static/images/SCALE/23.10/InstallMinioAddConfiguration.png
  static/images/SCALE/23.10/InstallMinioAddConfigurationDistribMode.png
  static/images/SCALE/23.10/InstallMinioAddMinioExtraArguments.png
  static/images/SCALE/23.10/InstallMinioAddResourceLimits.png
  static/images/SCALE/23.10/InstallMinioAdvancedDNSSettings.png
  static/images/SCALE/23.10/InstallMinioConfigPortsAndLogSearch.png
  static/images/SCALE/23.10/InstallMinioS3Screen.png
  static/images/SCALE/23.10/InstallMinioStorageAddExtraHostPathVol.png
  static/images/SCALE/23.10/InstallMinioStorageAddExtraVols.png
  static/images/SCALE/23.10/InstallMinioStorageAddPostgresVolumes.png
  static/images/SCALE/23.10/InstallMinioWorkloadConfig.png
  static/images/SCALE/23.10/MinIOAppInstalled.png
  static/images/SCALE/23.10/MinIOEnterpriseInstalled.png
  static/images/SCALE/23.10/MinIOWebPortal.png
  static/images/SCALE/23.10/MiniIOS3AppInfoScreen.png
  static/images/SCALE/23.10/MinioApplicationInforWidgetWithRollBack.png
  static/images/SCALE/23.10/MinioEnterpriseAppWidget.png
  static/images/SCALE/23.10/MinioEnterpriseInfoScreen.png
  words-to-ignore.txt
Labels: Technical Writer Review (DP)

#2035 PD-604: 22.12.3.3 Release Notes
  content/SCALE/SCALE22.12.md
  words-to-ignore.txt
Labels: Version Specific

#2036 PD-605: CORE 13.0-U5.3 Release Notes
  content/CORE/COREReleaseNotes.md
Labels: Version Specific

#2039 PD-574 LLDP Service is listed in the docs, but doesn't seem to be available on TrueNAS SCALE
  content/SCALE/SCALEDeprecatedFeatures.md
  content/SCALE/SCALETutorials/SystemSettings/Services/LLDPServicesSCALE.md
  content/_includes/BluefinDeprecated.md
Labels: Technical Writer Review (MJ)

#2040 PD-416 Update Cloud Sync Task Articles
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddCloudSyncTasks.md
  content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  content/_includes/CreateCloudSyncTaskScale.md
  static/images/SCALE/22.02/AddCloudSyncTaskAddBackupCredentials.png
  static/images/SCALE/22.02/AddCloudSyncTaskAdvancedRemoteOptions.png
  static/images/SCALE/22.02/AddCloudSyncTaskBottom.png
  static/images/SCALE/22.02/AddCloudSyncTaskControlAdvancedOptions.png
  static/images/SCALE/22.02/AddCloudSyncTaskRemoteS3Settings.png
  static/images/SCALE/22.02/AddCloudSyncTaskTransferAndRemote.png
  static/images/SCALE/22.02/CloudCredentialsMSOneDriveAuthentication.png
  static/images/SCALE/22.02/CloudCredentialsOpenStacktv3EndpointAdvanced.png
  static/images/SCALE/22.02/CloudSyncAddGoogleDriveAuthentication.png
  static/images/SCALE/22.02/CloudSyncMalformedHeaderDialog.png
  static/images/SCALE/22.02/CloudSynchTasksWidgetNoTasks.png
  static/images/SCALE/23.10/AddCloudSyncTaskPushControlAdvancedEncrypt.png
  static/images/SCALE/23.10/AddCloudSyncTaskPushControlAdvancedOptions.png
  static/images/SCALE/23.10/AddCloudSyncTaskPushTransferRemote.png
  static/images/SCALE/23.10/CloudSyncTaskWidgeNoTasks.png
  words-to-ignore.txt
Labels: Version Specific

#2056 PD-503 Update FTP Service Articles - UI and Tutorial
  content/SCALE/SCALETutorials/SystemSettings/Services/FTPServiceSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/FTPServiceScreenSCALE.md
  words-to-ignore.txt
Labels: Technical Writer Review (MJ)

#2046 Certificates Screenshots update
  content/SCALE/SCALEUIReference/Credentials/Certificates/CertificatesScreensSCALE.md
  static/images/SCALE/22.02/AddCatalogScreen.png
  static/images/SCALE/22.02/AddCatalogWarningSCALE.png
  static/images/SCALE/22.02/AddCertificateCertifcateSubject.png
  static/images/SCALE/22.02/AddCertificateCertificateOptions.png
  static/images/SCALE/22.02/AddCertificateConfirmOptions.png
  static/images/SCALE/22.02/AddCertificateExtraConstraintsInternalCert.png
  static/images/SCALE/22.02/AddCertificateIdentifierAndTypeInternalCert.png
  static/images/SCALE/22.02/AddCertificateImportCertOptions.png
  static/images/SCALE/22.02/AddCertificateImportCertificateOptions.png
  static/images/SCALE/22.02/AddCertificateImportExtraConstraints.png
  static/images/SCALE/22.02/AddCertificateWizard.png
  static/images/SCALE/22.02/CertificatesWidget.png
  static/images/SCALE/23.10/AddCertificateCertifcateSubject.png
  static/images/SCALE/23.10/AddCertificateCertificateOptions.png
  static/images/SCALE/23.10/AddCertificateConfirmOptions.png
  static/images/SCALE/23.10/AddCertificateExtraConstraintsInternalCert.png
  static/images/SCALE/23.10/AddCertificateIdentifierAndTypeInternalCert.png
  static/images/SCALE/23.10/AddCertificateImport.png
  static/images/SCALE/23.10/AddCertificateImportCertificateOptions.png
  static/images/SCALE/23.10/CertificatesWidget.png
  static/images/SCALE/23.10/EditCertificateScreen.png
Labels: Technical Writer Review (MJ)

#2050 PD-579 Review ACME DNS Authenticator content
  content/SCALE/SCALETutorials/Credentials/Certificates/AddACMESCALE.md
  content/SCALE/SCALETutorials/Credentials/Certificates/SettingUpLetsEncryptCertificates.md
  content/SCALE/SCALEUIReference/Credentials/Certificates/ACMEDNSAuthScreensSCALE.md
  static/images/SCALE/22.12/LetsEncryptACMECertificate.png
  static/images/SCALE/22.12/LetsEncryptAcmeDNSAuthenticator.png
  static/images/SCALE/22.12/LetsEncryptCSR.png
Labels: Technical Writer Review (MJ)

#2051 PD-385 Cobia Updates to Replication
  content/SCALE/SCALETutorials/DataProtection/Replication/AdvancedReplication/ReplicationWithEncryptionSCALE.md
  content/SCALE/SCALETutorials/DataProtection/Replication/_index.md
Labels: Technical Writer Review (DP)

#2052 PD-549: SCALE CLI add interactive argument editor text UI content to main CLI index file.
  content/SCALE/SCALECLIReference/Account/CLIgroup.md
  content/SCALE/SCALECLIReference/Account/CLIuser.md
  content/SCALE/SCALECLIReference/_index.md
  content/_includes/CLI/HintInteractiveArgsEditor.md
  content/_includes/CLI/InteractiveArgsEditor.md
  static/images/SCALE/CLI/Account/GroupCreateInteractiveArgumentsEditor.png
  static/images/SCALE/CLI/Account/UserCreateInteractiveArgumentsEditor.png
  static/images/SCALE/CLI/CLIUserCreateInteractiveArgumentsEditor.png
Labels: Technical Writer Review (MJ)
