Repository truenas/documentation, pull requests merged in 2023-06, with the labels that each got.

#1949 Update NFS Authorized networks empty field behavior
  content/SCALE/SCALETutorials/Shares/AddingNFSShares.md
Labels: Version Specific, Technical Writer Review (MJ)

#1947 PD-487: Update TrueNAS Security Best Practices
  content/Solutions/Optimizations/Security.md
Labels: Technical Writer Review (MJ)

#1920 PD-490: Single sourced writeup of Bluefin deprecated services and add generic URL for external links
  content/SCALE/SCALE22.12.md
  content/SCALE/SCALEDeprecatedFeatures.md
  content/_includes/BluefinDeprecated.md
  words-to-ignore.txt
Labels: Version Specific, Technical Writer Review (MJ)

#1941 PD-380 Update Cluster Articles
  content/Solutions/Integrations/SMBClustering.md
  content/TrueCommand/Clusters.md
  content/_includes/ClusterIntro.md
  content/_includes/ClusterRequirements.md
  content/_includes/ClusterSetup.md
  content/_includes/ClusterWarnings.md
  words-to-ignore.txt
Labels: Version Specific, Review (TM)

#1940 PD-309 Update SMB Service and Multichannel content for new field
  content/SCALE/SCALETutorials/Shares/SMB/SMBMultichannel.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/SMBServicesScreen.md
  static/images/SCALE/22.12/SMBServiceAdvancedSCALE.png
Labels: Version Specific, Technical Writer Review (MJ)

#1909 PD-477 create WebDAV migration article
  content/SCALE/GettingStarted/Configure/UIConfigurationSCALE.md
  content/SCALE/SCALETutorials/Apps/MigrateWebDAV.md
  content/SCALE/SCALETutorials/Shares/ConfigureWebDAV.md
  content/SCALE/SCALETutorials/Shares/WebDAV/_index.md
  content/SCALE/SCALETutorials/SystemSettings/Services/WebDAVServiceSCALE.md
  content/SCALE/SCALEUIReference/Shares/WebDAV/_index.md
  content/SCALE/SCALEUIReference/Shares/WebDAVSharesScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/WebDAVServiceScreen.md
  content/_includes/SCALEServiceDeprecationNotice.md
  content/_includes/SCALEWebDAVDeprecation.md
  static/images/SCALE/22.12/WebDAVAppWidget.png
  static/images/SCALE/22.12/WebDAVConfigurationBasicAuth.png
  static/images/SCALE/22.12/WebDAVNetworkConfigForHTTPS.png
  static/images/SCALE/22.12/WebDAVStorageConfigAddShare.png
  words-to-ignore.txt
Labels: Version Specific

#1946 PD-504: 13.0-U5.1 Release Note
  content/CORE/COREReleaseNotes.md
Labels: Version Specific, Technical Writer Review (MJ)

#1950 PD-501: Update Security.md
  content/SCALE/SCALETutorials/Credentials/RootlessLogin.md
  content/Solutions/Optimizations/Security.md
Labels: Technical Writer Review (MJ)

#1911 PD-476 create migrate tftp service tutorial
  content/SCALE/SCALETutorials/Apps/TFTP-HPAApp.md
  content/SCALE/SCALETutorials/SystemSettings/Services/TFTPServiceSCALE.md
  static/images/SCALE/22.12/InstallTFTPdAppAddEnvironVariables.png
  static/images/SCALE/22.12/InstallTFTPdAppHostNetwork.png
  static/images/SCALE/22.12/InstallTFTPdAppHostPath.png
  static/images/SCALE/22.12/InstallTFTPdAppNameTimezone.png
  static/images/SCALE/22.12/tftpd-hpaAppWidget.png
Labels: Version Specific, Review (TM)

#1959 PD-488: mention that multiple interfaces on the subnet are not allowed
  content/CORE/CORETutorials/Network/Interfaces/SettingStaticIP.md
  content/SCALE/GettingStarted/Install/ConsoleSetupMenuScale.md
  content/SCALE/SCALETutorials/Network/ConfigureStaticRoutes.md
  content/SCALE/SCALETutorials/Network/Interfaces/ManagingInterfaces.md
  content/SCALE/SCALETutorials/Network/Interfaces/SettingUpStaticIPs.md
  content/_includes/AliasOrStaticIP.md
  content/_includes/MultipleInterfacesOnNetwork.md
  static/images/SCALE/22.12/EditGlobalConfiguration.png
  static/images/SCALE/22.12/EditInterfaceAddAlias.png
  static/images/SCALE/22.12/EditInterfaceClearDHCP.png
  words-to-ignore.txt
Labels: Version Specific, Review (TM)

#1961 PD-362: Security Notices updates
  content/CORE/CoreSecurityReports/SMB1Advisory.md
  content/CORE/CoreSecurityReports/_index.md
  content/SCALE/ScaleSecurityReports/_index.md
Labels: Version Specific, Technical Writer Review (DP)

#1960 Pd 493 create wg easy tutorial
  content/SCALE/SCALETutorials/Apps/InstallWGEasyApp.md
  content/SCALE/SCALETutorials/SystemSettings/Services/OpenVPNSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/OpenVPNScreens.md
  static/images/SCALE/22.12/WgeasyAddAdvancedDNS.png
  static/images/SCALE/22.12/WgeasyAppWidget.png
  static/images/SCALE/22.12/WgeasyApplicationName.png
  static/images/SCALE/22.12/WgeasyConfigAddAllowIPAndEnvironments.png
  static/images/SCALE/22.12/WgeasyConfigSettings.png
  static/images/SCALE/22.12/WgeasyEnableResourceLimits.png
  static/images/SCALE/22.12/WgeasyNetworking.png
  static/images/SCALE/22.12/WgeasyStorageAddExtraHostPathVolumes.png
  static/images/SCALE/22.12/WgeasyStorageEnableCustomHostPath.png
Labels: Version Specific, Technical Writer Review (DP)

#1953 PD-296: SCALE 22.12.3 release notes
  content/SCALE/SCALE22.12.md
  content/_includes/BluefinDeprecated.md
  words-to-ignore.txt
Labels: Version Specific

#1958 Pd 494 create rsyncd app tutorial
  content/SCALE/SCALETutorials/Apps/InstallRsyncdApp.md
  content/SCALE/SCALETutorials/SystemSettings/Services/ConfigRsyncServiceSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/RsyncServicesScreenSCALE.md
  static/images/SCALE/22.12/RsyncdAddModuleAccessMode.png
  static/images/SCALE/22.12/RsyncdAddModuleAllowDenyHosts.png
  static/images/SCALE/22.12/RsyncdAddModuleNameAndPath.png
  static/images/SCALE/22.12/RsyncdAppWidget.png
  static/images/SCALE/22.12/RsyncdApplicationName.png
  static/images/SCALE/22.12/RsyncdResourceConfig.png
  static/images/SCALE/22.12/RsyncdRsyncConfigAddAuxParameters.png
Labels: Version Specific

#1983 PD-252 Create Storage CLI Namespace Articles
  content/SCALE/SCALECLIReference/Storage/CLIDataset.md
  content/SCALE/SCALECLIReference/Storage/CLIDisk.md
  content/SCALE/SCALECLIReference/Storage/CLIEnclosure.md
  content/SCALE/SCALECLIReference/Storage/CLIFilesystem-Storage.md
  content/SCALE/SCALECLIReference/Storage/CLIPool.md
  content/SCALE/SCALECLIReference/Storage/CLIResilver.md
  content/SCALE/SCALECLIReference/Storage/CLIScrub.md
  content/SCALE/SCALECLIReference/Storage/CLISnapshot.md
  content/SCALE/SCALECLIReference/Storage/CLIVmware.md
  content/SCALE/SCALECLIReference/Storage/_index.md
  content/SCALE/SCALEUIReference/SystemSettings/EnclosureScreensSCALE.md
  content/_includes/SCALECLIIntroduction.md
Labels: Technical Writer Review (DP)

#1984 Pd 251 create cli sharing namespace articles
  content/SCALE/SCALECLIReference/Sharing/CLINFS.md
  content/SCALE/SCALECLIReference/Sharing/CLISMB.md
  content/SCALE/SCALECLIReference/Sharing/CLIWebdav.md
  content/SCALE/SCALECLIReference/Sharing/CLIiSCSI.md
  content/SCALE/SCALECLIReference/Sharing/_index.md
Labels: Technical Writer Review (DP)

#1974 PD-498 Update HA Console Setup Instructions
  content/SCALE/GettingStarted/Install/ConsoleSetupMenuScale.md
  content/SCALE/GettingStarted/Install/InstallEnterpriseHASCALE.md
  static/images/SCALE/22.12/CSMNetworkConfigurationHA.png
  static/images/SCALE/22.12/CSMNetworkConfigurationHANoValues.png
  static/images/SCALE/22.12/CSMNetworkInterfacesHA.png
  static/images/SCALE/22.12/CSMNetworkInterfacesNoAliasIP.png
  static/images/SCALE/22.12/CSMUpdateNetworkInterfacesHA.png
  static/images/SCALE/22.12/CSMUpdateNetworkInterfacesHANoValues.png
  static/images/SCALE/22.12/EditInterfaceFailoveSettingsHA.png
Labels: Technical Writer Review (DP)

#1952 TrueCommand 2.3.3 Documentation
  content/Solutions/Integrations/SMBClustering.md
  content/TrueCommand/Administration/Admin/SAML/ConfigIDPSAMLSSO.md
  content/TrueCommand/Administration/Admin/SAML/SAMLAD.md
  content/TrueCommand/Administration/Admin/SAML/SAMLGA.md
  content/TrueCommand/Administration/Admin/SAML/_index.md
  content/TrueCommand/Clusters.md
  content/TrueCommand/TCReleaseNotes.md
  content/_includes/ClusterIntro.md
  content/_includes/ClusterRequirements.md
  content/_includes/ClusterSetup.md
  content/_includes/ClusterWarnings.md
  static/images/SAML/GAAddCustomSAMLAppAddServiceProviderDetailsCropped.png
  static/images/SAML/GAAddCustomSAMLAppAttributeMappingCropped.png
  static/images/SAML/GAAddCustomSAMLAppDetailsAddedCropped.png
  static/images/SAML/GAAddCustomSAMLAppDetailsCropped.png
  static/images/SAML/GAAddCustomSAMLAppDownloadMetaDataWindowCropped.png
  static/images/SAML/GAAddCustomSAMLAppTrueCommandSAMLTestCropped.png
  static/images/SAML/GAAddServiceProviderDetailsCropped.png
  static/images/SAML/GAClickAddApp.png
  static/images/SAML/GASAMLAppClickViewDetailsCropped.png
  static/images/SAML/GASAMLAppSetServiceStatusOnForEveryoneCropped.png
  static/images/SAML/GASelectWebandMobileApps.png
  words-to-ignore.txt
Labels: Version Specific

#1985 PD-544: 22.12.3.1 Release Notes
  content/SCALE/SCALE22.12.md
Labels: Version Specific

#1992 Update CloudSyncTasksScreensSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
Labels: Technical Writer Review (MJ)

#1989 Pd 253 create cli system namespace articles
  content/SCALE/SCALECLIReference/System/CLIACME.md
  content/SCALE/SCALECLIReference/System/CLIAdvanced.md
  content/SCALE/SCALECLIReference/System/CLIAlert.md
  content/SCALE/SCALECLIReference/System/CLIBoot.md
  content/SCALE/SCALECLIReference/System/CLIBootenv.md
  content/SCALE/SCALECLIReference/System/CLICertificate.md
  content/SCALE/SCALECLIReference/System/CLIConfig.md
  content/SCALE/SCALECLIReference/System/CLICore.md
  content/SCALE/SCALECLIReference/System/CLIDevice.md
  content/SCALE/SCALECLIReference/System/CLIFailover.md
  content/SCALE/SCALECLIReference/System/CLIGeneral.md
  content/SCALE/SCALECLIReference/System/CLIInitShutdownScript.md
  content/SCALE/SCALECLIReference/System/CLIKMIP.md
  content/SCALE/SCALECLIReference/System/CLIKeychainCredential.md
  content/SCALE/SCALECLIReference/System/CLIMail.md
  content/SCALE/SCALECLIReference/System/CLINTPServer.md
  content/SCALE/SCALECLIReference/System/CLIReporting.md
  content/SCALE/SCALECLIReference/System/CLISupport.md
  content/SCALE/SCALECLIReference/System/CLISystemDataset.md
  content/SCALE/SCALECLIReference/System/CLITrueCommand.md
  content/SCALE/SCALECLIReference/System/CLITruenas.md
  content/SCALE/SCALECLIReference/System/CLITunable.md
  content/SCALE/SCALECLIReference/System/CLIUpdate.md
  content/SCALE/SCALECLIReference/System/_index.md
  content/SCALE/SCALETutorials/Credentials/ConfiguringKMIPSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/General/GeneralSettings.md
  content/SCALE/SCALEUIReference/SystemSettings/FailoverScreen.md
  content/SCALE/SCALEUIReference/SystemSettings/SystemBootScreensSCALE.md
Labels: Technical Writer Review (DP)

#1990 PD-441 CLI Enclosure Namespace
  content/SCALE/SCALECLIReference/Storage/CLIEnclosure.md
  static/images/SCALE/CLI/CLIStorageEnclosureGetInstanceMultiple.png
  static/images/SCALE/CLI/CLIStorageEnclosureGetInstanceSingle.png
  static/images/SCALE/CLI/CLIStorageEnclosureQuery.png
  static/images/SCALE/CLI/CLIStorageEnclosureQueryMultiple.png
  static/images/SCALE/CLI/CLIStorageEnclosureSetSlotStatusIDENTIFY.png
  static/images/SCALE/CLI/CLIStorageEnclosureUpdateLabel.png
Labels: Technical Writer Review (MJ)

#1997 PD-250 CLI Guide: Document Service namespaces
  content/SCALE/SCALECLIReference/Service/CLICTDB/_index.md
  content/SCALE/SCALECLIReference/Service/CLICluster/_index.md
  content/SCALE/SCALECLIReference/Service/CLIDynDNS/_index.md
  content/SCALE/SCALECLIReference/Service/CLIFTP/_index.md
  content/SCALE/SCALECLIReference/Service/CLIGluster/_index.md
  content/SCALE/SCALECLIReference/Service/CLIIPMI/_index.md
  content/SCALE/SCALECLIReference/Service/CLINFS/_index.md
  content/SCALE/SCALECLIReference/Service/CLIOpenVPN/_index.md
  content/SCALE/SCALECLIReference/Service/CLIRsync/_index.md
  content/SCALE/SCALECLIReference/Service/CLIRsyncMod/_index.md
  content/SCALE/SCALECLIReference/Service/CLIS3/_index.md
  content/SCALE/SCALECLIReference/Service/CLISMART/_index.md
  content/SCALE/SCALECLIReference/Service/CLISMB/_index.md
  content/SCALE/SCALECLIReference/Service/CLISNMP/_index.md
  content/SCALE/SCALECLIReference/Service/CLISSH/_index.md
  content/SCALE/SCALECLIReference/Service/CLITFTP/_index.md
  content/SCALE/SCALECLIReference/Service/CLIUPS/_index.md
  content/SCALE/SCALECLIReference/Service/CLIVM/_index.md
  content/SCALE/SCALECLIReference/Service/CLIWebDav/_index.md
  content/SCALE/SCALECLIReference/Service/_index.md
Labels: Technical Writer Review (MJ)

#1982 PD-249 create filesystem cli articles
  content/SCALE/SCALECLIReference/Filesystem/CLIAcltemplate.md
  content/SCALE/SCALECLIReference/Filesystem/_index.md
Labels: Technical Writer Review (DP)

#2001 PD-392: Remove drive count limitation notice for Cobia
  content/SCALE/SCALE22.12.md
  content/_includes/TNHardwareGuide.md
Labels: Version Specific

#2002 PD-497: Disk Import removal
  content/SCALE/SCALETutorials/Storage/Datasets/ImportingData.md
  content/SCALE/SCALETutorials/Storage/Datasets/_index.md
  content/SCALE/SCALETutorials/Storage/Pools/Disks/_index.md
  content/SCALE/SCALETutorials/Storage/Pools/ImportPoolScale.md
  content/SCALE/SCALEUIReference/Storage/Datasets/DatasetsScreensScale.md
  content/SCALE/SCALEUIReference/Storage/Datasets/ImportDataScreenSCALE.md
  content/SCALE/SCALEUIReference/Storage/Datasets/_index.md
Labels: Version Specific

#2009 PD-352: Remove OneDrive cloud sync task/credentials text
  content/SCALE/SCALETutorials/Credentials/BackupCredentials/AddCloudCredentials.md
  content/SCALE/SCALEUIReference/Credentials/BackupCredentials/CloudCredentialScreens.md
Labels: Version Specific

#2003 Reset SCALE Release Notes for Cobia branch and docs
  content/SCALE/SCALE22.12.md
  content/SCALE/SCALEReleaseNotes.md
Labels: Version Specific

#2010 PD-381: Dynamic DNS content rework (part 1)
  content/SCALE/SCALEReleaseNotes.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/ddns-updater.md
  content/SCALE/SCALETutorials/SystemSettings/Services/DDNSServiceMigrate.md
  content/SCALE/SCALETutorials/SystemSettings/Services/DDNSServiceSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/DDNSServiceScreenSCALE.md
  words-to-ignore.txt
Labels: Version Specific, Technical Writer Review (DP)

#1965 PD-354 Procedure for updating NVDIMM - public facing
  content/Hardware/MSeries/NVDIMMUpdates.md
  static/images/Hardware/NVDIMMFirmwareUpdates/FirmwareVersion.png
  static/images/Hardware/NVDIMMFirmwareUpdates/Selected1Running1.png
  static/images/Hardware/NVDIMMFirmwareUpdates/SuccesfulNVDIMMUpdate.png
  static/images/Hardware/NVDIMMFirmwareUpdates/SuccesfulNVDIMMUpdate1.png
  static/images/Hardware/NVDIMMFirmwareUpdates/SuccesfulNVDIMMUpdate2.png
Labels: Technical Writer Review (MJ)

#2015 PD-381: rework ddns-updater app tutorial (Part 2)
  content/SCALE/SCALEReleaseNotes.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/ddns-updater.md
  static/images/SCALE/22.12/ddns-updaterConfigIPSettings.png
  static/images/SCALE/22.12/ddns-updaterConfigPeriodSettings.png
  static/images/SCALE/22.12/ddns-updaterDNSProviderConfigAdd.png
  static/images/SCALE/22.12/ddnsUpdaterAppWidget.png
  static/images/SCALE/23.10/DdnsAppDetails.png
  static/images/SCALE/23.10/DdnsUpdaterNetworkConfig.png
  static/images/SCALE/23.10/DdnsUpdaterResourceConfig.png
  static/images/SCALE/23.10/DdnsUpdaterStorageConfig.png
  static/images/SCALE/23.10/DdnsUpdaterUserGroupConfig.png
  static/images/SCALE/23.10/FindDdnsUpdaterApp.png
  static/images/SCALE/23.10/Installddns-updaterScreen.png
  static/images/SCALE/23.10/ddns-updaterDNSProviderConfigAdd.png
  words-to-ignore.txt
Labels: Version Specific
