Repository truenas/documentation, pull requests merged in 2023-03, with the labels that each got.

#1768 Remove additional callout for SMB aux param adjust.
  content/CORE/COREReleaseNotes.md
Labels: Technical Writer Review (CD), Ready to merge

#1767 PD-188 Update SSH Service Articles
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/SSHServiceSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/SSHServiceScreenSCALE.md
  static/images/SCALE/22.12/SSHServicesAdvancedSettings.png
Labels: Technical Writer Review (CD), Ready to merge

#1771 13.0-U4 - Add known issue for Mini XL+ hardware detection
  content/CORE/COREReleaseNotes.md
Labels: Ready to merge

#1773 SCALE Tutorials/Storage index cleanup
  content/SCALE/SCALETutorials/Storage/Datasets/_index.md
  content/SCALE/SCALETutorials/Storage/Pools/_index.md
  content/SCALE/SCALETutorials/Storage/_index.md
Labels: Ready to merge

#1770 PD-35 SCALE 22.12 update dashboard help widget screenshots and content
  content/SCALE/GettingStarted/FirstTimeLogin.md
  content/SCALE/SCALEUIReference/SCALEDashboard.md
  content/_includes/StatusOfTrueCommand.md
  static/images/SCALE/22.12/AlertServicesSCALE.png
  static/images/SCALE/22.12/AlertSettingsSCALE.png
  static/images/SCALE/22.12/AlertsNotifications.png
  static/images/SCALE/22.12/AlertsSetupSystemEmailSCALE.png
  static/images/SCALE/22.12/DashboardCPUWidgetSCALE.png
  static/images/SCALE/22.12/DashboardConfigureScreenSCALE.png
  static/images/SCALE/22.12/DashboardHelpWidgetSCALE.png
  static/images/SCALE/22.12/DashboardInterfaceAddressesWidgetSCALE.png
  static/images/SCALE/22.12/DashboardInterfaceWidgetSCALE.png
  static/images/SCALE/22.12/DashboardMainScreenSCALE.png
  static/images/SCALE/22.12/DashboardMemoryWidgetSCALE.png
  static/images/SCALE/22.12/DashboardNetworkWidgetSCALE.png
  static/images/SCALE/22.12/DashboardStorageWidgetSCALE.png
  static/images/SCALE/22.12/DashboardSystemInfoWidgetSCALE.png
  static/images/SCALE/22.12/TopToolbar.png
  static/images/SCALE/22.12/TrueCommandCloudConnectSCALE.png
  static/images/SCALE/22.12/TrueCommandCloudLoginSCALE.png
  static/images/SCALE/22.12/TrueCommandCloudStatusDialogSCALE.png
  static/images/SCALE/22.12/TrueCommandIcon.png
  static/images/SCALE/22.12/TrueNASAboutScreenSCALE.png
Labels: Ready to merge

#1774 PD-101 fix grammar and style issues in pools UI ref article
  content/SCALE/SCALEUIReference/Storage/Pools/PoolManagerScreens.md
  static/images/SCALE/22.12/PoolManagerWithDiskWarningSCALE1.png
  static/images/SCALE/22.12/StorageCreatePoolManagerSCALE.png
Labels: Ready to merge

#1759 PD-121 update directory services articles
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigADSCALE.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigIDmapSCALE.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigKerberosSCALE.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigLDAPSCALE.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/_index.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/ActiveDirectory.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/Idmap.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/KerberosKeytab.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/KerberosRealms.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/KerberosSettings.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/LDAP.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/_index.md
  content/_includes/KerberosIntroWarnings.md
  content/_includes/KerberosWarning.md
  static/images/SCALE/22.12/ActiveDirectoryBasicOptions.png
  static/images/SCALE/22.12/ActiveDirectoryWidget.png
  static/images/SCALE/22.12/AddIdmapBackendAD.png
  static/images/SCALE/22.12/AddIdmapBackendAUTORIDSettings.png
  static/images/SCALE/22.12/AddIdmapBackendLDAPOptionsSettings.png
  static/images/SCALE/22.12/AddIdmapBackendLDAPSettings.png
  static/images/SCALE/22.12/AddIdmapBackendNSSSettings.png
  static/images/SCALE/22.12/AddIdmapBackendRFC2307Options.png
  static/images/SCALE/22.12/AddIdmapBackendTDBSettings.png
  static/images/SCALE/22.12/AddIdmapDefalutScreen.png
  static/images/SCALE/22.12/AddIdmapSMBPrimaryDomainScreen.png
  static/images/SCALE/22.12/AddKerberosKeytabScreen.png
  static/images/SCALE/22.12/AddKerberosRealmScreen.png
  static/images/SCALE/22.12/DigCommandOutput.png
  static/images/SCALE/22.12/DirServicesAdvancedSettingsScreen.png
  static/images/SCALE/22.12/DirectoryServicesADandLDAPWidgets.png
  static/images/SCALE/22.12/DirectoryServicesScreen.png
  static/images/SCALE/22.12/IdmapScreen.png
  static/images/SCALE/22.12/IdmapWidget.png
  static/images/SCALE/22.12/KerberosKeytabWidget.png
  static/images/SCALE/22.12/KerberosKeytabsScreen.png
  static/images/SCALE/22.12/KerberosRealmsScreen.png
  static/images/SCALE/22.12/KerberosRealmsWidget.png
  static/images/SCALE/22.12/KerberosSettingsScreen.png
  static/images/SCALE/22.12/KerberosSettingsWidget.png
  static/images/SCALE/22.12/LDAPAdvancedOptionsSettings.png
  static/images/SCALE/22.12/LDAPBasicOptionsSettings.png
  static/images/SCALE/22.12/LDAPwidget.png
Labels: Technical Writer Review (CD), Ready to merge

#1772 PD-108 Update Alerts and SMTP Content
  content/TrueCommand/Alerts/AlertManage.md
  content/TrueCommand/Alerts/Colors.md
  content/TrueCommand/Alerts/_index.md
Labels: Technical Writer Review (CD), Ready to merge

#1765 Pd-142 update storage articles add promote function scale
  content/SCALE/SCALETutorials/Storage/Datasets/CreatingSnapshots.md
  content/SCALE/SCALETutorials/Storage/Datasets/ManageSnapshotsSCALE.md
  content/SCALE/SCALEUIReference/Storage/Datasets/DatasetsScreensScale.md
  content/SCALE/SCALEUIReference/Storage/Datasets/SnapshotsScreens.md
  content/_includes/CloneAndPromoteSnapshotDataset.md
  static/images/SCALE/22.12/AddSnapshotSCALE1.png
  static/images/SCALE/22.12/AddSnapshotScreenSCALE.png
  static/images/SCALE/22.12/DataProtectSnapshotTasksSCALE.png
  static/images/SCALE/22.12/DatasetDataProtectManageSnapshotsSCALE.png
  static/images/SCALE/22.12/DatasetDetailsParentDataNotPromotedSCALE.png
  static/images/SCALE/22.12/DatasetRollbackSnapshotWarnSCALE.png
  static/images/SCALE/22.12/SnapshotDeleteBatchConfirmSCALE.png
  static/images/SCALE/22.12/SnapshotDeleteBatchSCALE.png
  static/images/SCALE/22.12/SnapshotDeleteNonPromotedSCALE.png
  static/images/SCALE/22.12/SnapshotsListingExpandedSCALE1.png
  static/images/SCALE/22.12/SnapshotsListingSCALE1.png
  static/images/SCALE/22.12/SnapshotsShowColumnsCaution.png
  static/images/SCALE/22.12/StorageSnapshotCloneNewDatasetAfterPromoteSCALE.png
  static/images/SCALE/22.12/StorageSnapshotCloneNewDatasetCreatedSCALE.png
  static/images/SCALE/22.12/StorageSnapshotCloneNewDatasetListedContentSCALE.png
  static/images/SCALE/22.12/StorageSnapshotCloneNewDatasetPromoteSCALE.png
  static/images/SCALE/22.12/StorageSnapshotCloneNewDatasetSCALE.png
  static/images/SCALE/22.12/StorageSnapshotsListedContentSCALE.png
Labels: Technical Writer Review (MJ)

#1777 PD-179 There should be a warning about T10-DIF drives not being supported
  content/SCALE/SCALE22.12.md
  content/_includes/TNHardwareGuide.md
Labels: Technical Writer Review (MJ)

#1781 typo fix
  content/SCALE/GettingStarted/Install/UIConfigurationSCALE.md
Labels: Technical Writer Review (CD)

#1789 PD-268 Update Set Up Storage Articles
  content/SCALE/GettingStarted/Configure/SetUpStorageScale.md
  content/SCALE/GettingStarted/SCALEHardwareGuide.md
  content/SCALE/SCALETutorials/Storage/Datasets/AddManageZvols.md
  content/SCALE/SCALETutorials/Storage/Datasets/DatasetsSCALE.md
  content/SCALE/SCALETutorials/Storage/Pools/CreatePoolScale.md
  content/SCALE/SCALETutorials/Storage/Pools/createPoolScale.md
  content/_includes/CreateDatasetSCALE.md
  content/_includes/CreatePool.md
Labels: Technical Writer Review (CD)

#1790 Pd 269 update set up sharing articles
  content/SCALE/GettingStarted/Configure/SetUpSharing.md
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShares.md
Labels: Technical Writer Review (TR)

#1798 Pd-208 scale remove netbiosname field from docs
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShares.md
  static/images/SCALE/22.12/SMBDatasetACLEdit.png
Labels: Technical Writer Review (TR)

#1802 PD-206 SCALE - Update Disk Scrub content to note where task progress is shown
  content/SCALE/SCALETutorials/DataProtection/ScrubTasksSCALE.md
Labels: Technical Writer Review (MJ)

#1800 PD-241 Update First Time Login Article
  content/SCALE/GettingStarted/Configure/FirstTimeLogin.md
  content/_includes/Jobs.md
Labels: Technical Writer Review (TR)

#1806 PD-271 SCALE 22.12 Validate System Services LLDP Service is no Longer Part of SCALE
  content/SCALE/SCALEUIReference/SystemSettings/Services/LLDPServicesScreenSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/_index.md
Labels: Technical Writer Review (MJ)

#1809 PD-17 Clarification on zpool upgrades and Scale
  content/SCALE/SCALETutorials/SystemSettings/UpdateSCALE.md
  static/images/SCALE/22.12/BootPoolUpgradeStatus.png
Labels: Technical Writer Review (MJ)

#1786 Pd 236 unified enterprise guide
  content/SCALE/GettingStarted/Configure/_index.md
  content/SCALE/GettingStarted/_index.md
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShares.md
  content/SCALE/_index.md
  content/_includes/SCALEDocsSections.md
  static/images/SCALE/22.12/SMBDatasetACLEdit.png
  static/includes/General/MenuNav.md.part
Labels: Technical Writer Review (TR)

#1794 Pd-94 scale update vm articles content
  content/SCALE/SCALETutorials/Virtualization/AddManageVMDevicesSCALE.md
  content/SCALE/SCALETutorials/Virtualization/CreatingManagingVMsSCALE.md
  content/SCALE/SCALEUIReference/Virtualization/VirtualizationScreens.md
  content/SCALE/SCALEUIReference/Virtualization/_index.md
  static/images/SCALE/22.12/CreateVMWCPUMemSCALE.png
  static/images/SCALE/22.12/CreateVMWConfirmSCALE.png
  static/images/SCALE/22.12/CreateVMWDisksSCALE.png
  static/images/SCALE/22.12/CreateVMWGPUsSCALE.png
  static/images/SCALE/22.12/CreateVMWInstallMediaSCALE.png
  static/images/SCALE/22.12/CreateVMWInstallMediaUploadSCALE.png
  static/images/SCALE/22.12/CreateVMWNetworkInterfaceSCALE.png
  static/images/SCALE/22.12/CreateVMWOpSysSCALE.png
  static/images/SCALE/22.12/DeleteDeviceVMDiskSCALE.png
  static/images/SCALE/22.12/EditDeviceVMDiskSCALE.png
  static/images/SCALE/22.12/EditVMCPUandMemory.png
  static/images/SCALE/22.12/VMAddDeviceCDROM.png
  static/images/SCALE/22.12/VMAddDeviceDisk.png
  static/images/SCALE/22.12/VMAddDeviceDisplay.png
  static/images/SCALE/22.12/VMAddDeviceNIC.png
  static/images/SCALE/22.12/VMAddDevicePCIpass.png
  static/images/SCALE/22.12/VMAddDeviceRawFile.png
  static/images/SCALE/22.12/VMAddDeviceUSBpass.png
  static/images/SCALE/22.12/VMDetailsDevicesSCALE.png
  static/images/SCALE/22.12/VMListedSCALE.png
  static/images/SCALE/22.12/VMRunningOptionsSCALE.png
Labels: Technical Writer Review (MJ)

#1807 PD-82 SCALE 22.12.0 Update Clustering Preparation Article Content
  content/SCALE/SCALETutorials/Shares/SMB/ManageSMBShares.md
  content/TrueCommand/Clusters.md
  content/_includes/ClusterSetup.md
  static/images/SCALE/22.12/ClusteredSMBShare.png
  static/images/TrueCommand/2.3.1/ConfigureClusterActiveDirectory.png
  static/images/TrueCommand/2.3.1/ConfigureClusterAssociateVIPs.png
  static/images/TrueCommand/2.3.1/ConfigureClusterReview.png
  static/images/TrueCommand/2.3.1/ConfigureClusterSMBNetwork.png
Labels: Technical Writer Review (MJ)

#1793 PD-270 Update Backing Up Articles
  content/SCALE/GettingStarted/Configure/SetUpBackupScale.md
  content/SCALE/SCALETutorials/Credentials/BackupCredentials/AddCloudCredentials.md
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddCloudSyncTasks.md
  content/SCALE/SCALETutorials/DataProtection/Replication/AddReplicationSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/General/ManageSysConfigSCALE.md
  content/_includes/CreateCloudSyncTaskScale.md
  content/_includes/DownloadSystemConfigFileSCALE.md
  content/_includes/OAuthCloudCredentialSetupSCALE.md
Labels: Technical Writer Review (CD)

#1811 PD-159 updated SMARTServicesSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/SMARTServicesSCALE.md
Labels: Technical Writer Review (TR)

#1810 PD-235 Update Install HA Article
  content/SCALE/GettingStarted/Install/InstallEnterpriseHASCALE.md
  content/_includes/HAControllerInstallBestPracticeSCALE.md
Labels: Technical Writer Review (CD)

#1783 PD-152 updated AddingNFSShares.md
  content/SCALE/SCALETutorials/Shares/NFS/AddingNFSShares.md
Labels: Review (TM)

#1813 Pd 94 scale update vm articles content
  content/SCALE/SCALETutorials/Virtualization/AddManageVMDevicesSCALE.md
  content/SCALE/SCALETutorials/Virtualization/CreatingManagingVMsSCALE.md
  content/SCALE/SCALEUIReference/Virtualization/VirtualizationScreens.md
  content/SCALE/SCALEUIReference/Virtualization/_index.md
  static/images/SCALE/22.12/CreateVMWCPUMemSCALE.png
  static/images/SCALE/22.12/CreateVMWConfirmSCALE.png
  static/images/SCALE/22.12/CreateVMWDisksSCALE.png
  static/images/SCALE/22.12/CreateVMWGPUsSCALE.png
  static/images/SCALE/22.12/CreateVMWInstallMediaSCALE.png
  static/images/SCALE/22.12/CreateVMWInstallMediaUploadSCALE.png
  static/images/SCALE/22.12/CreateVMWNetworkInterfaceSCALE.png
  static/images/SCALE/22.12/CreateVMWOpSysSCALE.png
  static/images/SCALE/22.12/DeleteDeviceVMDiskSCALE.png
  static/images/SCALE/22.12/EditDeviceVMDiskSCALE.png
  static/images/SCALE/22.12/EditVMCPUandMemory.png
  static/images/SCALE/22.12/VMAddDeviceCDROM.png
  static/images/SCALE/22.12/VMAddDeviceDisk.png
  static/images/SCALE/22.12/VMAddDeviceDisplay.png
  static/images/SCALE/22.12/VMAddDeviceNIC.png
  static/images/SCALE/22.12/VMAddDevicePCIpass.png
  static/images/SCALE/22.12/VMAddDeviceRawFile.png
  static/images/SCALE/22.12/VMAddDeviceUSBpass.png
  static/images/SCALE/22.12/VMDetailsDevicesSCALE.png
  static/images/SCALE/22.12/VMListedSCALE.png
  static/images/SCALE/22.12/VMRunningOptionsSCALE.png
Labels: Technical Writer Review (TR)

#1814 PD-56 Rewrite TrueCommand + TrueNAS SCALE SMB Clustering docs
  content/SCALE/GettingStarted/Configure/ClusterPreparation.md
  content/SCALE/SCALETutorials/Apps/MinIOClustersSCALE/MinIOClustering.md
  content/Solutions/Integrations/SMBClustering.md
  content/TrueCommand/Clusters.md
  content/_includes/ClusterIntro.md
  content/_includes/ClusterRequirements.md
  content/_includes/ClusterSetup.md
  content/_includes/ClusterTypes.md
  content/_includes/ClusterWarnings.md
Labels: Technical Writer Review (MJ)

#1819 PD-135 NFS documentation doesn't cover different security options
  content/SCALE/SCALETutorials/Shares/NFS/AddingNFSShares.md
  content/SCALE/SCALEUIReference/Shares/NFS/NFSSharesScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md
Labels: Technical Writer Review (CD)

#1820 PD-209 Update Dataset Articles Share Type
  content/SCALE/SCALEUIReference/Storage/Datasets/DatasetsScreensScale.md
  content/_includes/CreateDatasetSCALE.md
Labels: Version Specific, Technical Writer Review (TR)

#1829 PD-38: update ssh content related to sudo
  content/SCALE/SCALETutorials/Credentials/RootlessLogin.md
Labels: Version Specific, Review (TM)

#1822 PD-275 Update Adding SMB Share Article
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShares.md
  content/SCALE/SCALEUIReference/Shares/SMB/SMBSharesScreens.md
  static/images/SCALE/22.12/EditACLBuiltin_UserGroupForSMBShare.png
Labels: Review (TM)

#1828 Pd-55 document new app netdata scale
  content/SCALE/SCALETutorials/Apps/InstallNetdataApp.md
  static/images/SCALE/22.12/InstallNetDAppAdvancedDNSSettingsSCALE.png
  static/images/SCALE/22.12/InstallNetDAppAvailAppSCALE.png
  static/images/SCALE/22.12/InstallNetDAppCloudSignUpSCALE.png
  static/images/SCALE/22.12/InstallNetDAppDatasetsSCALE.png
  static/images/SCALE/22.12/InstallNetDAppDeployingSCALE.png
  static/images/SCALE/22.12/InstallNetDAppNameSCALE.png
  static/images/SCALE/22.12/InstallNetDAppNetDAgentCropSCALE.png
  static/images/SCALE/22.12/InstallNetDAppNetDAgentDashNoCloudSCALE.png
  static/images/SCALE/22.12/InstallNetDAppResourceSCALE.png
  static/images/SCALE/22.12/InstallNetDAppRunningOptionsSCALE.png
  static/images/SCALE/22.12/InstallNetDAppRunningSCALE.png
  static/images/SCALE/22.12/InstallNetDAppServiceConfHostPSCALE.png
  static/images/SCALE/22.12/InstallNetDAppServiceConfSCALE.png
Labels: Version Specific, Technical Writer Review (TR)

#1835 Pd52 vm redirects https scale
  content/SCALE/SCALETutorials/Apps/UsingApps.md
  content/SCALE/SCALETutorials/SystemSettings/General/GeneralSettings.md
  content/_includes/AppsVMsNoHTTPS.md
  static/images/SCALE/22.12/SystemSettingsGUISettingsSCALE.png
Labels: Version Specific, Technical Writer Review (TR)

#1821 PD-185 Create Failover UI Reference Article
  content/SCALE/SCALETutorials/Network/ManageNetworkSettingsHA.md
  content/SCALE/SCALEUIReference/SystemSettings/FailoverScreen.md
  content/_includes/EnterpriseHANetworkIPs.md
  static/images/SCALE/22.12/FailoverScreen.png
  static/images/SCALE/22.12/FailoverSyncToPeerDialog.png
Labels: Version Specific, Technical Writer Review (TR)

#1827 Pd 156 create basic time machine share tutorial
  content/SCALE/SCALETutorials/Shares/SMB/SetUpBasicTimeMachineSMBShare.md
Labels: Version Specific, Technical Writer Review (TR)

#1830 PD-201 Update BackBlaze B2 Cloud Sync Article Content
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddCloudSyncTasks.md
Labels: Review (TM)

#1837 Update 22.12.2 Release Schedule
  content/SCALE/SCALE22.12.md
  pnpm-lock.yaml
Labels: Technical Writer Review (TR)

#1832 Pd-32 scale 22.12 update nextcloud article
  content/SCALE/SCALETutorials/Apps/InstallNextCloudMedia.md
  static/images/SCALE/22.12/AddNextcloudAppNameSCALE.png
  static/images/SCALE/22.12/AddNextcloudAvailableAppsSCALE.png
  static/images/SCALE/22.12/AddNextcloudConfigurationSCALE.png
  static/images/SCALE/22.12/AddNextcloudEnvironmentSCALE.png
Labels: Version Specific, Technical Writer Review (TR)

#1838 Pd-46 scale 22.12 group article updates
  content/SCALE/SCALETutorials/Credentials/ManageLocalGroups.md
  content/SCALE/SCALEUIReference/Credentials/LocalGroupsScreens.md
  content/SCALE/SCALEUIReference/Storage/Datasets/QuotaScreens.md
  static/images/SCALE/22.12/AddGroupGIDConfigSCALE.png
  static/images/SCALE/22.12/AddGroupQuotasSetQuotaSCALE.png
  static/images/SCALE/22.12/AddUserQuotasSetQuotasSCALE.png
  static/images/SCALE/22.12/EditGroupQuotasSCALE.png
  static/images/SCALE/22.12/EditUserQuotasSCALE.png
  static/images/SCALE/22.12/GroupQuotasNoQuotaSCALE.png
  static/images/SCALE/22.12/GroupQuotasVideoQuotaSCALE.png
  static/images/SCALE/22.12/GroupsListedExpandedSCALE.png
  static/images/SCALE/22.12/GroupsListedSCALE.png
  static/images/SCALE/22.12/GroupsManageMembersSCALE.png
  static/images/SCALE/22.12/UserQuotasDataQuotaSCALE.png
  static/images/SCALE/22.12/UserQuotasNoQuotasSCALE.png
Labels: Version Specific, Technical Writer Review (TR)

#1840 PD-197 SCALE 22.12.2 Update Launch Docker Image UI ref and any tutorials
  content/SCALE/SCALETutorials/Apps/Docker.md
  content/SCALE/SCALEUIReference/Apps/LaunchDockerImageScreens.md
  static/images/SCALE/22.12/LaunchDockerImageAddDNS.png
Labels: Version Specific, Technical Writer Review (CD)

#1836 PD-141 Add instructions on how to deal with NAS times that are wildly off
  content/SCALE/SCALETutorials/Dashboard/SCALETimeSync.md
Labels: Technical Writer Review (MJ)

#1815 PD-273 Reorganize and Update Support Articles
  content/Contributing/IssueReporting/JiraIssueReporting.md
  content/Contributing/IssueReporting/_index.md
  content/Contributing/_index.md
  content/SCALE/GettingStarted/Configure/UIConfigurationSCALE.md
  content/SCALE/GettingStarted/Getting Support/FileIssueSCALE.md
  content/SCALE/GettingStarted/Getting Support/GetSupportSCALE.md
  content/SCALE/GettingStarted/Getting Support/_index.md
  content/SCALE/SCALETutorials/SystemSettings/General/AddLicenseProactiveSupport.md
  content/SCALE/SCALETutorials/SystemSettings/General/GetSupportSCALE.md
  content/_includes/CreateDebugSCALE.md
  content/_includes/FileIssueTicketSCALE.md
  content/_includes/UsingTrueNASCommunityAndSocialMedia.md
  static/includes/CORE/CreateDebug.md.part
  static/includes/General/CreateJiraSuggestion.md.part
Labels: Technical Writer Review (TR), Technical Writer Review (CD)

#1841 PD-212 update sign in splash screen installer scale
  content/SCALE/GettingStarted/Configure/FirstTimeLogin.md
  static/images/SCALE/22.12/FirstTimeLoginInstallOpt3SCALE.png
Labels: Version Specific

#1839 PD-84 Update Replication Tutorials
  content/SCALE/SCALETutorials/DataProtection/Replication/AddReplicationSCALE.md
  content/SCALE/SCALETutorials/DataProtection/Replication/LocalReplicationSCALE.md
  content/SCALE/SCALETutorials/DataProtection/Replication/RemoteReplicationSCALE.md
  content/SCALE/SCALETutorials/DataProtection/Replication/ReplicationWithEncryptionSCALE.md
  content/SCALE/SCALETutorials/DataProtection/Replication/UseAdvancedReplicationSCALE.md
  content/SCALE/SCALETutorials/DataProtection/Replication/_index.md
  content/SCALE/SCALETutorials/Storage/Datasets/AddManageZvols.md
  content/SCALE/SCALETutorials/Storage/Datasets/ZvolSpaceWarning.md
  content/_includes/BasicReplicationProcess.md
  content/_includes/ReplicationConfigNewSSHConnection.md
  content/_includes/ReplicationCreateDatasetAndAdminHomeDirSteps.md
  content/_includes/ReplicationIntroSCALE.md
  content/_includes/ReplicationSSHTransferSecurity.md
  content/_includes/ReplicationScheduleAndRetentionSteps.md
  static/images/SCALE/22.12/ChangeAdminUserHomeDirectorySetting.png
  static/images/SCALE/22.12/CreateLocalReplicationTask.png
  static/images/SCALE/22.12/CreateRemoteReplicationTask.png
  static/images/SCALE/22.12/CreateRemoteReplicationTaskSetSudo.png
  static/images/SCALE/22.12/CreateReplicationTaskSetSchedule.png
  static/images/SCALE/22.12/CreatelReplicationTaskSetSchedule.png
  static/images/SCALE/22.12/NewSSHConnectionAuthetication.png
  static/images/SCALE/22.12/NewSSHConnectionNameAndMethod.png
  static/images/SCALE/22.12/RemoteReplicateSnapshotAndNameSchema.png
  static/images/SCALE/22.12/ReplicationSnapshotConfirmationDialog.png
  static/images/SCALE/22.12/ReplicationSnapthotListInDestinationDataset.png
  static/images/SCALE/22.12/ReplicationTaskEncryptionOptions.png
  static/images/SCALE/22.12/ReplicationTaskWidgetWithPendingTask.png
  static/images/SCALE/22.12/UseSudoForZFSCommandsDialog.png
Labels: Technical Writer Review (TR)
