Repository truenas/documentation, pull requests merged in 2023-04, with the labels that each got.

#1843 PD-149 SCALE 22.12.2/23.10 App Article Improvements
  content/SCALE/SCALETutorials/Apps/Customizing Advanced (Kubernetes) Settings/Configuring Host Path Safety Checks.md
  content/SCALE/SCALETutorials/Apps/Customizing Advanced (Kubernetes) Settings/_index.md
  content/SCALE/SCALETutorials/Apps/UsingApps.md
  content/SCALE/SCALEUIReference/Apps/AppsScreensSCALE.md
  static/images/SCALE/22.12/AppsAdvancedSettingsKubernetesSettingsReInitialization.png
  static/images/SCALE/22.12/AppsChooseLogWindow.png
  static/images/SCALE/22.12/AppsChoosePodWindow.png
  static/images/SCALE/22.12/AppsPodShellWindow.png
  static/images/SCALE/22.12/AppsSummaryScreen.png
Labels: Version Specific, Technical Writer Review (MJ)

#1848 Update InterfacesScreen.md
  content/CORE/UIReference/Network/InterfacesScreen.md
Labels: Technical Writer Review (TR)

#1851 PD-318: HA warning for System Configuration reset
  content/SCALE/SCALETutorials/SystemSettings/General/ManageSysConfigSCALE.md
Labels: Version Specific

#1853 PD-239 Update Initial Config Article LDAP Content
  content/TrueCommand/Administration/Admin/LDAPServers.md
  content/TrueCommand/TCGettingStarted/InitialConfig.md
  content/_includes/TrueCommandLDAP.md
  static/images/TrueCommand/2.3.2/AddLDAPServerScreen.png
  static/images/TrueCommand/2.3.2/AddRecipientScreen.png
  static/images/TrueCommand/2.3.2/AdministrationAlertRecipientsWidget.png
  static/images/TrueCommand/2.3.2/AdministrationCertificateAuthoritiesWidget.png
  static/images/TrueCommand/2.3.2/AdministrationCertificatesWidget.png
  static/images/TrueCommand/2.3.2/AdministrationConfigurationWidget.png
  static/images/TrueCommand/2.3.2/AdministrationLDAPServersWidget.png
  static/images/TrueCommand/2.3.2/ConfigurationScreenGeneralSSLAlertOptions.png
  static/images/TrueCommand/2.3.2/ConfigurationScreenSSLOptions.png
  static/images/TrueCommand/2.3.2/MailingListConfigureScreen.png
  static/includes/TrueCommand/2.0/TrueCommandSSL.md.part
  words-to-ignore.txt
Labels: Version Specific, Technical Writer Review (TR)

#1854 PD-220 Update TC Snapshots Article Content
  content/TrueCommand/SystemManagement/SingleSystem/TrueCommandSnapshots.md
  static/images/TrueCommand/2.3.2/CreateSnapshotButtons.png
  static/images/TrueCommand/2.3.2/CreateSnapshotDialog.png
  static/images/TrueCommand/2.3.2/CreateSnapshotTaskDataset.png
  static/images/TrueCommand/2.3.2/CreateSnapshotTaskScheduleAndLifetime.png
  static/images/TrueCommand/2.3.2/CreateSnapshotsOptions.png
  static/images/TrueCommand/2.3.2/ExploreSystemDatasetSnapshotList.png
  static/images/TrueCommand/2.3.2/ExploreSystemSelectPool.png
Labels: Version Specific, Technical Writer Review (TR)

#1855 PD-221 Update Systems Article Information on Updates
  content/TrueCommand/Administration/SystemLog.md
  content/TrueCommand/Administration/Systems.md
  content/TrueCommand/Administration/Users.md
  content/TrueCommand/Administration/_index.md
  static/images/TrueCommand/2.3.2/SystenUpdateAvailable.png
Labels: Version Specific, Technical Writer Review (TR)

#1782 PD-213: SCALE 22.12.2 release notes
  content/SCALE/SCALE22.12.md
  words-to-ignore.txt
Labels: Version Specific

#1862 PD-283 Update ZFS Primer Article
  content/References/ZFSPrimer.md
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#1863 PD-182 Add Restoring a Hot Spare to Replacing Disk Articles
  content/CORE/CORETutorials/Storage/Disks/DiskReplace.md
  content/SCALE/SCALETutorials/Storage/Pools/Disks/ReplacingDisks.md
  content/_includes/RestoreHotSpare.md
Labels: Technical Writer Review (TR)

#1866 PD-232 Rework Network Port ID Articles: R-Series
  content/Hardware/RSeries/RSeriesNetworkPortIDs.md
Labels: Technical Writer Review (MJ)

#1868 PD-328 correct 22.12.2 release notes
  content/SCALE/SCALE22.12.md
  content/_includes/SMBShareMSDOSalert.md
Labels: Review (TM)

#1850 PD-191: TC 2.3.2 release notes
  content/TrueCommand/TCReleaseNotes.md
  words-to-ignore.txt
Labels: Version Specific

#1871 PD-285 Write tutorial for Google Photos credentials created with Google API
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddGooglePhotosCloudSyncTask.md
  static/images/SCALE/22.12/GooglePhotosAPIAddCloudCredentials.png
  static/images/SCALE/22.12/GooglePhotosAPIAddCredentials.png
  static/images/SCALE/22.12/GooglePhotosAPIAddTestingUser.png
  static/images/SCALE/22.12/GooglePhotosAPIAppInformation.png
  static/images/SCALE/22.12/GooglePhotosAPIClickEnable.png
  static/images/SCALE/22.12/GooglePhotosAPICopyIDandSecret.png
  static/images/SCALE/22.12/GooglePhotosAPICreateExternal.png
  static/images/SCALE/22.12/GooglePhotosAPICreateOAuthClientID.png
  static/images/SCALE/22.12/GooglePhotosAPIDeveloperContactInformation.png
  static/images/SCALE/22.12/GooglePhotosAPIEnableAPIsandServices.png
  static/images/SCALE/22.12/GooglePhotosAPINewProject.png
  static/images/SCALE/22.12/GooglePhotosAPIPhotosLibraryAPISearch.png
  static/images/SCALE/22.12/GooglePhotosAPIPublish.png
  static/images/SCALE/22.12/GooglePhotosAPIrcloneConfig.png
  static/images/SCALE/22.12/GooglePhotosAPIrcloneConfig2.png
  static/images/SCALE/22.12/GooglePhotosAPIrcloneConfig3.png
Labels: Technical Writer Review (MJ)

#1876 Pd 175 core u4 improve certificate articles
  content/CORE/CORETutorials/SystemConfiguration/CreatingCAsandCertificates/CreatingCertificateAuthorities.md
  content/CORE/CORETutorials/SystemConfiguration/CreatingCAsandCertificates/CreatingCertificates.md
  content/CORE/CORETutorials/SystemConfiguration/CreatingCAsandCertificates/_index.md
  content/CORE/UIReference/System/CAs.md
  static/images/CORE/13.0/AddCSRCertOptionsNoProfile.png
  static/images/CORE/13.0/AddCSRECCProfile.png
  static/images/CORE/13.0/AddCSRIdentTypeNoProfile.png
  static/images/CORE/13.0/AddCSRRSAProfile.png
  static/images/CORE/13.0/AddInternalCACertOptionsNoProfile.png
  static/images/CORE/13.0/AddInternalCAIdentTypeNoProfile.png
  static/images/CORE/13.0/AddInternalCAOpenVPNRootProfile.png
  static/images/CORE/13.0/AddInternalCAProfile.png
  static/images/CORE/13.0/AddInternalCertCertOptionsNoProfile.png
  static/images/CORE/13.0/AddInternalCertECCProfile.png
  static/images/CORE/13.0/AddInternalCertExtensions.png
  static/images/CORE/13.0/AddInternalCertIdentTypeNoProfile.png
  static/images/CORE/13.0/AddInternalCertRSAProfile.png
  static/images/CORE/13.0/AddInternalCertSubject.png
  static/images/CORE/13.0/ImportCA.png
  static/images/CORE/13.0/ImportCSR.png
  static/images/CORE/13.0/ImportCertificate.png
  static/includes/Reference/CertificateAuthorityIdentifierType.md.part
  static/includes/Reference/CertificateAuthorityImport.md.part
Labels: Technical Writer Review (TR)

#1879 PD-293: Site sizing and style adjustments
  layouts/partials/site-footer.html
  layouts/partials/site-header.html
  static/custom.css
Labels: Technical Writer Review (MJ)
