Repository truenas/documentation, pull requests merged in 2023-01, with the labels that each got.

#1684 incidental typo fix
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShares.md
Labels: Technical Writer Review (CD)

#1682 Docs-4319 Update WebDAV Tutorial Content
  content/SCALE/SCALETutorials/Shares/WebDAV/ConfigureWebDAV.md
Labels: Technical Writer Review (CD)

#1689 PD-90 Fix Issues with Import Data and Pool Articles
  content/SCALE/SCALETutorials/Storage/Datasets/CreatingSnapshots.md
  content/SCALE/SCALETutorials/Storage/Datasets/ImportingData.md
  content/SCALE/SCALETutorials/Storage/Pools/ImportPoolScale.md
  content/SCALE/SCALEUIReference/Storage/Datasets/ImportDataScreenSCALE.md
Labels: Technical Writer Review (CD)

#1683 Docs-4389 Create SMB Article on MacOS Client Limitations
  content/SCALE/SCALETutorials/Shares/SMB/SMBUsingDecomposedUnicode.md
Labels: Technical Writer Review (CD)

#1681 Docs-4410 Update Nextcloud and Admin User Articles
  content/SCALE/SCALETutorials/Apps/InstallNextCloudMedia.md
  content/SCALE/SCALETutorials/Apps/NextcloudSCALE.md
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALE/SCALETutorials/Credentials/RootlessLogin.md
  static/images/SCALE/22.12/AddNextcloudDataAndOptPaths.png
  static/images/SCALE/22.12/AddNextcloudDbAndDbBackup.png
  static/images/SCALE/22.12/AddNextcloudEnableCronJobs.png
  static/images/SCALE/22.12/AddNextcloudEnterApplicationName.png
  static/images/SCALE/22.12/AddNextcloudUsernameAndPassword.png
  static/images/SCALE/22.12/AppsAddNextcloudDatasets.png
  static/images/SCALE/22.12/AppsAddNextcloudHostPath.png
  static/images/VMWareESXi/AddNextcloudEnterApplicationName.png
  static/images/VMWareESXi/AppsAddNextcloudDatasets.png
Labels: File Moved

#1691 Pd 31 update docker image and apps articles content
  content/SCALE/SCALETutorials/Apps/Docker.md
  content/SCALE/SCALETutorials/Apps/InstallPiHOleWithDocker.md
  content/SCALE/SCALETutorials/Apps/InstallPiHoleApp.md
  content/SCALE/SCALETutorials/Apps/UsingApps.md
  content/SCALE/SCALEUIReference/Apps/AppsScreensSCALE.md
  content/SCALE/SCALEUIReference/Apps/LaunchDockerImageScreens.md
  static/images/SCALE/22.12/AppAddPlexApplicationName.png
  static/images/SCALE/22.12/AppPiHoleApplicationNameAndVersion.png
  static/images/SCALE/22.12/AppPiHoleConfigurationSettings.png
  static/images/SCALE/22.12/AppPiHoleDNSAndResourceLimitsSettings.png
  static/images/SCALE/22.12/AppPiHoleNetworkingSettings.png
  static/images/SCALE/22.12/AppPiHoleStorageSettings.png
  static/images/SCALE/22.12/AppsDeleteAppImagesNotToBeDeleted.png
  static/images/SCALE/22.12/AppsInstalledPlexWidgetActive.png
  static/images/SCALE/22.12/AppsManageDockerImageDelete.png
  static/images/SCALE/22.12/DeleteStoppedApp.png
  static/images/SCALE/22.12/DeleteStoppedAppDialog.png
  static/images/SCALE/22.12/LaunchDockerImageAddContainerEntrypoints.png
  static/images/SCALE/22.12/LaunchDockerImageAddContainerEnvironmentVariables.png
  static/images/SCALE/22.12/LaunchDockerImageAddDNS.png
  static/images/SCALE/22.12/LaunchDockerImageAddNetworking.png
  static/images/SCALE/22.12/LaunchDockerImageAddPortForwarding.png
  static/images/SCALE/22.12/LaunchDockerImageAddStorage.png
  static/images/SCALE/22.12/LaunchDockerImageAddWorkloadDetails.png
  static/images/SCALE/22.12/LaunchDockerImageAppNameVerContainerImage.png
  static/images/SCALE/22.12/LaunchDockerImageApplicationVersion.png
  static/images/SCALE/22.12/LaunchDockerImageContainerImage.png
  static/images/SCALE/22.12/LaunchDockerImageResourcesAdd.png
  static/images/SCALE/22.12/LaunchDockerImageScalingUpgrade.png
  static/images/SCALE/22.12/LaunchDockerImageStorageAddVolumes.png
Labels: Technical Writer Review (CD)

#1693 Add 13.0-U4 tentative release date
  content/CORE/COREReleaseNotes.md
Labels: Technical Writer Review (CD)

#1695 Internal suggestion to improve Generic VM install text
  content/SCALE/GettingStarted/Install/InstallingSCALE.md
Labels: Technical Writer Review (CD)

#1694 PD-40 Update Clustering Articles
  content/SCALE/GettingStarted/ClusterPreparation.md
  content/SCALE/SCALETutorials/Apps/MinIOClustersSCALE/MinIOClustering.md
  content/SCALE/SCALETutorials/Apps/MinIOClustersSCALE/MinioManualUpdate.md
  content/SCALE/SCALETutorials/Apps/MinIOClustersSCALE/_index.md
  content/_includes/ClusterSetup.md
  content/_includes/ClusterTypes.md
  content/_includes/ClusterWarnings.md
  static/images/SCALE/22.12/AppsMinIOAppNameAndScaling.png
  static/images/SCALE/22.12/AppsMinIOConfigurationArgs.png
  static/images/SCALE/22.12/AppsMinIOEnvironmentVariables.png
  static/images/SCALE/22.12/AppsMinIOStorage.png
Labels: Technical Writer Review (CD)

#1699 PD-87 Update Email Articles
  content/SCALE/SCALETutorials/TopToolbar/SettingUpSystemEmail.md
  content/SCALE/SCALEUIReference/TopToolbar/Alerts/EmailScreens.md
  static/images/SCALE/22.12/AddAlertServiceEmailScreen.png
  static/images/SCALE/22.12/EmailGmailAllow.png
  static/images/SCALE/22.12/EmailGmailAuthorization.png
  static/images/SCALE/22.12/EmailGmailChooseAccount.png
  static/images/SCALE/22.12/EmailGmailOAuthConfigurationScreen1.png
  static/images/SCALE/22.12/EmailGmailOAuthConfigurationScreen2.png
  static/images/SCALE/22.12/EmailGmailSignIn.png
  static/images/SCALE/22.12/EmailSMTPConfigurationScreen.png
Labels: Technical Writer Review (CD)

#1700 PD-96 Update Periodic Snapshot Tasks Articles
  content/SCALE/SCALETutorials/DataProtection/PeriodicSnapshotTasksSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/PeriodicSnapshotTasksScreensSCALE.md
  static/images/SCALE/22.12/PeriodicSnapshotTaskWidgetNoTasks.png
  static/images/SCALE/22.12/PeriodicSnapshotTasksWidget.png
Labels: Technical Writer Review (CD)

#1704 PD-36 Update SMB Share Articles with Naming Convention Information
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBHomeShare.md
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShadowCopies.md
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShares.md
  content/SCALE/SCALETutorials/Shares/SMB/ManageSMBShares.md
  content/SCALE/SCALEUIReference/Shares/SMB/SMBSharesScreens.md
  static/images/SCALE/22.12/DeleteSMBShareDialog.png
Labels: Technical Writer Review (CD)

#1706 PD-11 Create Time Sync Article
  content/SCALE/SCALETutorials/Dashboard/SCALETimeSync.md
  content/SCALE/SCALETutorials/Dashboard/_index.md
  content/SCALE/SCALEUIReference/SCALEDashboard.md
  static/images/SCALE/22.12/DashboardSytemInfoWidgetTimeSync.png
Labels: Technical Writer Review (TR)

#1705 PD-85 SCALE 22.12 Update Alert Settings Screenshots and Article Content
  content/SCALE/SCALEUIReference/TopToolbar/Alerts/AlertSettingsScreen.md
  static/images/SCALE/22.12/AlertSettingsCertificates.png
  static/images/SCALE/22.12/AlertSettingsClustering.png
  static/images/SCALE/22.12/AlertSettingsDirectoryServices.png
  static/images/SCALE/22.12/AlertSettingsHardware.png
  static/images/SCALE/22.12/AlertSettingsKMIP.png
  static/images/SCALE/22.12/AlertSettingsNetwork.png
  static/images/SCALE/22.12/AlertSettingsPlugins.png
  static/images/SCALE/22.12/AlertSettingsReporting.png
  static/images/SCALE/22.12/AlertSettingsScreen.png
  static/images/SCALE/22.12/AlertSettingsSharing.png
  static/images/SCALE/22.12/AlertSettingsStorage.png
  static/images/SCALE/22.12/AlertSettingsSystem.png
  static/images/SCALE/22.12/AlertSettingsTasks.png
  static/images/SCALE/22.12/AlertSettingsUPS.png
Labels: Technical Writer Review (MJ)

#1707 PD-86 SCALE 22.12.0 Update Alert Services Articles
  content/SCALE/SCALEUIReference/TopToolbar/Alerts/AlertServicesScreen.md
  static/images/SCALE/22.12/AddAlertServiceInfluxDBScreen.png
  static/images/SCALE/22.12/AddAlertServiceMattermostScreen.png
  static/images/SCALE/22.12/AddAlertServiceOpsGenieScreen.png
  static/images/SCALE/22.12/AddAlertServicePagerDutyScreen.png
  static/images/SCALE/22.12/AddAlertServiceSNMPTrapScreen.png
  static/images/SCALE/22.12/AddAlertServiceScreen.png
  static/images/SCALE/22.12/AddAlertServiceSlackScreen.png
  static/images/SCALE/22.12/AddAlertServiceTelegramScreen.png
  static/images/SCALE/22.12/AddAlertServiceVictorOpsScreen.png
  static/images/SCALE/22.12/AlertServicesScreen.png
Labels: Technical Writer Review (MJ)

#1709 PD-45 SCALE 22.12 Update System General and Advanced Settings
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  content/SCALE/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  static/images/SCALE/22.12/AdvancedSystemSettingsConsoleWidget.png
  static/images/SCALE/22.12/ConsoleConfigScreen.png
  static/images/SCALE/22.12/GeneralSettingsSCALEJiraTicketCreate.png
  static/images/SCALE/22.12/GeneralSettingsSCALEProactiveSupportForm.png
  static/images/SCALE/22.12/SyslogConfigScreen.png
  static/images/SCALE/22.12/SystemAdvancedScreen.png
  static/images/SCALE/22.12/SystemGeneralGuiSettings.png
  static/images/SCALE/22.12/SystemGeneralResetConfiguration.png
  static/images/SCALE/22.12/SystemGeneralScreen.png
  static/images/SCALE/22.12/SystemGeneralSupportWidget.png
  static/images/SCALE/22.12/SystemGeneralUploadConfig.png
  static/images/SCALE/GeneralSettingsSCALESupportLicenseComplete.png
Labels: Technical Writer Review (CD)

#1710 PD-88 Update Cloud Credentials and Sync Task Articles
  content/SCALE/SCALETutorials/Credentials/BackupCredentials/AddCloudCredentials.md
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddCloudSyncTasks.md
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddStorjCloudSyncTask.md
  content/SCALE/SCALEUIReference/Credentials/BackupCredentials/CloudCredentialScreens.md
  static/images/SCALE/22.12/CloudCredentialsAdd.png
  static/images/SCALE/22.12/CloudCredentialsAmzon3AdvancedAuthSettings.png
  static/images/SCALE/22.12/CloudCredentialsAmzon3AuthenticationSetting.png
  static/images/SCALE/22.12/CloudCredentialsOpenStackAuthAdvancedV3.png
Labels: Technical Writer Review (CD)

#1711 Clarification for SMTP Authentication description
  content/SCALE/SCALETutorials/TopToolbar/SettingUpSystemEmail.md
Labels: Technical Writer Review (CD)

#1670 Docs 4298 document storj app deployment
  content/SCALE/SCALETutorials/Apps/AddStorjNode.md
  static/images/SCALE/22.12/AddDatasetStorjSCALE.png
  static/images/SCALE/22.12/DatasetsDashboardSCALE.png
  static/images/SCALE/22.12/DatasetsDashboardStorjNode.png
  static/images/SCALE/22.12/DatasetsDashboardStorjNodeNested.png
  static/images/SCALE/22.12/InstallApplicationsStorjSCALE.png
  static/images/SCALE/22.12/InstallStorjAppAdvDNSSCALE.png
  static/images/SCALE/22.12/InstallStorjAppConfigExtraEnvVariablesSCALE.png
  static/images/SCALE/22.12/InstallStorjAppConfigSCALE.png
  static/images/SCALE/22.12/InstallStorjAppNameSCALE.png
  static/images/SCALE/22.12/InstallStorjAppNetworkingSCALE.png
  static/images/SCALE/22.12/InstallStorjAppResourceLimitsSCALE.png
  static/images/SCALE/22.12/InstallStorjAppResourceLimitsSelectedSCALE.png
  static/images/SCALE/22.12/InstallStorjAppStorageExtraHostPathSCALE.png
  static/images/SCALE/22.12/InstallStorjAppStorageSCALE.png
  static/images/SCALE/22.12/StorjHostaNode.png
Labels: Technical Writer Review (TR)

#1708 Docs 4409 revisions to accessing a nas from a vm additional options
  content/SCALE/SCALETutorials/Network/Interfaces/SettingUpBridge.md
  content/SCALE/SCALETutorials/Virtualization/AccessingNASFromVM.md
  content/_includes/NetworkBridgeSCALE.md
  static/images/SCALE/22.12/AddInterfaceNicDeviceOtherSettingsSCALE.png
  static/images/SCALE/22.12/AddInterfaceNicDeviceSCALE.png
  static/images/SCALE/22.12/EditInterfaceNicDeviceSCALE.png
  static/images/SCALE/22.12/NetworkInterfacesBridgeSCALE.png
  static/images/SCALE/22.12/NetworkInterfacesNoIPSCALE.png
  static/images/SCALE/22.12/NetworkInterfacesSCALE.png
  static/images/SCALE/22.12/VMEditDeviceNIC.png
  static/images/SCALE/22.12/VMSaveNetworkChanges.png
  static/images/SCALE/22.12/VMTestNetworkChanges.png
  static/images/SCALE/22.12/VMTestNetworkChangesConfirm.png
  static/images/SCALE/22.12/VirtualMachinesScreenwithVM.png
Labels: Technical Writer Review (TR)
