Repository truenas/documentation, pull requests merged in 2023-11, with the labels that each got.

#2274 Pd 839 create jellyfin tutorial
  content/SCALE/SCALETutorials/Apps/CommunityApps/Immich.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/jellyfin.md
  static/images/SCALE/Apps/InstallJellyfinAdditionalStorage.png
  static/images/SCALE/Apps/InstallJellyfinConfigSettings.png
  static/images/SCALE/Apps/InstallJellyfinNetworkConfig.png
  static/images/SCALE/Apps/InstallJellyfinResourceConfig.png
  static/images/SCALE/Apps/InstallJellyfinScreen.png
  static/images/SCALE/Apps/InstallJellyfinStorageConfigHostPath.png
  static/images/SCALE/Apps/InstallJellyfinStorageConfigixVolume.png
  static/images/SCALE/Apps/InstallJellyfinUserGroupSettings.png
  static/images/SCALE/Apps/JellyfinAppDetailsScreen.png
  static/images/SCALE/Apps/JellyfinInstalled.png
  static/images/SCALE/Apps/JellyfinWebPortal.png
  static/images/SCALE/Apps/JellyfinWidget.png
Labels: Technical Writer Review (MJ)

#2281 Pd 541 fleet dashboard article
  content/TrueCommand/UserGuide/Dashboard.md
  content/TrueCommand/UserGuide/FleetDashboard.md
  content/_includes/TCSystemOptionsMenu.md
  static/images/TrueCommand/Dashboard/DashboardSingleSystemView.png
  static/images/TrueCommand/Dashboard/DashboardSingleSystemViewExapnded.png
  static/images/TrueCommand/Dashboard/DashboardSystemOptions.png
  static/images/TrueCommand/Dashboard/DashboardSystemOptions202.png
  static/images/TrueCommand/Dashboard/FleetDashboard.png
  static/images/TrueCommand/Dashboard/FleetDashboardAlertsWidget.png
  static/images/TrueCommand/Dashboard/FleetDashboardDataProtectionWidget.png
  static/images/TrueCommand/Dashboard/FleetDashboardPoolsWidget.png
  static/images/TrueCommand/Dashboard/FleetDashboardSMARTResultWidget.png
  static/images/TrueCommand/Dashboard/FleetDashboardSharesWidget.png
  static/images/TrueCommand/Dashboard/FleetDashboardSystemsCard.png
  static/images/TrueCommand/Dashboard/FleetDashboardSystemsWidget.png
  static/images/TrueCommand/Dashboard/SystemSettingUpdate.png
  static/images/TrueCommand/Dashboard/TCDashBoard.png
  static/images/TrueCommand/Dashboard/UpdateNASWindow.png
Labels: Technical Writer Review (DP)

#2278 Pd 847 tc getting started article updates
  content/TrueCommand/TCGettingStarted/ConnectingTrueNAS.md
  content/TrueCommand/TCGettingStarted/InitialConfig.md
  content/TrueCommand/TCGettingStarted/InterfaceOverview.md
  content/TrueCommand/TCGettingStarted/TCFirstTimeLogin.md
  content/TrueCommand/TCGettingStarted/TCReleaseNotes.md
  content/TrueCommand/TCGettingStarted/UserAccounts.md
  content/TrueCommand/TCGettingStarted/_index.md
  content/TrueCommand/UserGuide/Alerts/Colors.md
  content/_includes/TCCloudConnectSystems.md
  content/_includes/TCPermissionsHierarchy.md
  content/_includes/TCResettingUserPassword.md
  content/_includes/TCThemeOptions.md
  content/_includes/TrueCommandLDAP.md
  static/images/TrueCommand/Administration/AddLDAPServer.png
  static/images/TrueCommand/Administration/AdministrationAboutWidget.png
  static/images/TrueCommand/Administration/AdministrationConfigLDAP.png
  static/images/TrueCommand/Administration/AdministrationConfigTelemetry.png
  static/images/TrueCommand/Administration/AdministrationScreen.png
  static/images/TrueCommand/Administration/OpenSourceLicensesWindow.png
  static/images/TrueCommand/Administration/TrueCommand231AdminSystemInfo.png
  static/images/TrueCommand/Dashboard/AddNewSystem.png
  static/images/TrueCommand/Dashboard/FleetDashboardNoSystems.png
  static/images/TrueCommand/Dashboard/MainDashboardNoSystems.png
  static/images/TrueCommand/Dashboard/TopBar.png
  static/images/TrueCommand/Dashboard/TrueCommand231DashboardNoListings.png
  static/images/TrueCommand/Dashboard/TrueCommandIcon.png
  static/images/TrueCommand/SystemInventory/SystemInventoryScreen.png
  static/images/TrueCommand/Systems/SystemsGroupsNewGroup.png
  static/images/TrueCommand/Systems/SystemsPage.png
Labels: Technical Writer Review (DP)

#2294 PD-818: Obsolete AWS AMI content
  content/Solutions/Integrations/AWSDeploy.md
Labels: Technical Writer Review (DP)

#2291 Pd 758 core s 3 to minio plugin tutorial
  content/CORETutorials/JailsPluginsVMs/Plugins/CreatingCustomPlugin.md
  content/CORETutorials/JailsPluginsVMs/Plugins/MinIOPlugin.md
  content/CORETutorials/Services/ConfiguringS3.md
  content/CORETutorials/Services/S3forMinIO.md
  content/GettingStarted/COREReleaseNotes.md
  content/GettingStarted/Deprecations.md
  content/UIReference/Services/S3Screen.md
  content/_includes/S3Deprecation.md
  static/images/CORE/13.0/MinioClientInstall.png
  static/images/CORE/13.0/MinioClientMirror.png
  static/images/CORE/13.0/MinioClientSetAlias.png
  static/images/CORE/13.0/MinioPluginConsole.png
  static/images/CORE/13.0/MinioPluginDetails.png
  static/images/CORE/13.0/MinioPluginInstall.png
  static/images/CORE/13.0/MinioPluginInstalled.png
  static/images/CORE/13.0/MinioPluginJail.png
  static/images/CORE/13.0/MinioPluginPortForwarding.png
  static/images/CORE/13.0/MinioPluginVerifyBuckets.png
  words-to-ignore.txt
Labels: Technical Writer Review (MJ)

#2299 PD-851 Update Netdata Tutorial to Cobia
  content/SCALE/SCALETutorials/Apps/CommunityApps/InstallNetdataApp.md
  static/images/SCALE/Apps/InstallNetDAppAdvancedDNSSettingsSCALE.png
  static/images/SCALE/Apps/InstallNetDAppAvailAppSCALE.png
  static/images/SCALE/Apps/InstallNetDAppDeployingSCALE.png
  static/images/SCALE/Apps/InstallNetDAppNameSCALE.png
  static/images/SCALE/Apps/InstallNetDAppResourceSCALE.png
  static/images/SCALE/Apps/InstallNetDAppRunningOptionsSCALE.png
  static/images/SCALE/Apps/InstallNetDAppRunningSCALE.png
  static/images/SCALE/Apps/InstallNetDAppServiceConfHostPSCALE.png
  static/images/SCALE/Apps/InstallNetDAppServiceConfSCALE.png
  static/images/SCALE/Apps/InstallNetdataAdvancedDNSOptions.png
  static/images/SCALE/Apps/InstallNetdataConfigAddEnvironmentVariable.png
  static/images/SCALE/Apps/InstallNetdataConfigurationSettings.png
  static/images/SCALE/Apps/InstallNetdataResourceLimitsEnablePod.png
  static/images/SCALE/Apps/InstallNetdataScreen.png
  static/images/SCALE/Apps/InstallNetdataStorage.png
  static/images/SCALE/Apps/InstallNetdataStorageEnableHostPath.png
  static/images/SCALE/Apps/InstallNetdataStorageExtraHostPath.png
  static/images/SCALE/Apps/NetdataAppDetailsScreen.png
  static/images/SCALE/Apps/NetdataInstalled.png
  static/images/SCALE/Apps/NetdataNodesDashboard.png
  static/images/SCALE/Apps/NetdataSignInScreen.png
  static/images/SCALE/Apps/NetdataWebPortalLocalDashboard.png
  static/images/SCALE/Apps/NetdataWidget.png
Labels: Technical Writer Review (DP)

#2302 Pd 858 master branch note of u 6 min io migration
  content/CORE/CORETutorials/JailsPluginsVMs/Plugins/CreatingCustomPlugin.md
  content/CORE/CORETutorials/JailsPluginsVMs/Plugins/MinIOPlugin.md
  content/CORE/CORETutorials/JailsPluginsVMs/_index.md
  content/CORE/CORETutorials/Services/ConfiguringS3.md
  content/CORE/CORETutorials/Services/S3forMinIO.md
  content/CORE/GettingStarted/COREReleaseNotes.md
  content/CORE/GettingStarted/Deprecations.md
  content/CORE/UIReference/Services/S3Screen.md
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
  content/TrueCommand/TCGettingStarted/TCReleaseNotes.md
  content/TrueNASUpgrades/_index.md
  content/_includes/NightlyTestWarning.md
  content/_includes/S3Deprecation.md
  data/properties/core-releases.yaml
  data/properties/scale-releases.yaml
  data/properties/tc-releases.yaml
  layouts/shortcodes/releaselist.html
  static/images/CORE/Plugins/MinioPluginConsole.png
  static/images/CORE/Plugins/MinioPluginDetails.png
  static/images/CORE/Plugins/MinioPluginInstall.png
  static/images/CORE/Plugins/MinioPluginInstalled.png
Labels: Technical Writer Review (MJ)

#2320 PD-862 Fix missing Network Port IDs and MSeries NVDIMM upgrade content
  content/Hardware/MSeries.md
  content/Hardware/MiniFamily.md
  content/Hardware/RSeries.md
  content/Hardware/XSeries.md
  words-to-ignore.txt
Labels: Technical Writer Review (MJ)

#2322 PD-846 Add Setting Up External SMB Shares
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShares.md
  static/images/SCALE/Shares/SetUpExternalSMBShare.png
Labels: Technical Writer Review (DP)

#2327 Update 23.10Upgrades.md - port release notes caution when upgrading from Bluefin
  content/GettingStarted/23.10Upgrades.md
Labels: Version Specific

#2333 PD-889 Update MinIO and Pool Updates
  content/SCALE/SCALETutorials/Apps/CommunityApps/MinIOApp/MinIOClustering.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/MinIOApp/_index.md
  content/SCALE/SCALETutorials/Storage/Pools/ManagePoolsScale.md
  content/_includes/MinIOEnableDistributedModeInfo.md
  content/_includes/MinIOInstallArgAndEnvironVarSteps.md
  static/images/SCALE/Apps/InstallMinioAddConfiguration.png
  static/images/SCALE/Apps/InstallMinioEnableDistributedMode.png
  static/images/SCALE/Apps/MinIORootUser.png
  static/images/SCALE/Storage/StorageDashboardUpgradPoolConfirmationDialog.png
  words-to-ignore.txt
Labels: Review (TM)

#2331 Pd 892 investigate reporting changes including graphite
  content/SCALETutorials/ConfigReportsScale.md
  content/SCALEUIReference/ReportingScreensSCALE.md
  static/images/SCALE/23.10/AddReportingExporter.png
  static/images/SCALE/23.10/AddReportingExporterGraphite.png
  static/images/SCALE/23.10/CPUReportingUsageTemp.png
  static/images/SCALE/23.10/DiskReportingIO.png
  static/images/SCALE/23.10/MemoryReportingPhysSwap.png
  static/images/SCALE/23.10/NetworkReportingIntTraffic.png
  static/images/SCALE/23.10/ReportingExportersScreen.png
  static/images/SCALE/23.10/SystemReportingProcessUptime.png
  static/images/SCALE/23.10/TimeoutDialog.png
  static/images/SCALE/23.10/ZFSReportingActualHitsHitsRate.png
  words-to-ignore.txt
Labels: Technical Writer Review (MJ), Review (TM)

#2334 Pd 894 address iso install upgrade cache changes
  content/GettingStarted/23.10Upgrades.md
  content/GettingStarted/Install/InstallEnterpriseHASCALE.md
  content/GettingStarted/Install/InstallingSCALE.md
  content/GettingStarted/SCALEReleaseNotes.md
  content/SCALETutorials/SystemSettings/UpdateSCALE.md
  content/_includes/ISOUpgrades.md
  content/_includes/SCALEInstallerProcedure.md
  content/_includes/UpgradeClearCache.md
  static/images/SCALE/22.12/SCALEInstallDriveScreen.png
  static/images/SCALE/22.12/SCALEInstallMainScreen.png
  static/images/SCALE/22.12/SCALEInstallPartitionScreen.png
  static/images/SCALE/22.12/SCALEInstallUpdateMethodSelection.png
  static/images/SCALE/22.12/SCALEInstallUpgradeFresh.png
  static/images/SCALE/22.12/SCALEInstallWarningScreen.png
  static/images/SCALE/22.12/SCALEInstallerConsoleSetupAdminAccount.png
  static/images/SCALE/22.12/SCALEInstallerConsoleSetupAdminPassword.png
  static/images/SCALE/23.10/SCALEInstallDriveScreen.png
  static/images/SCALE/23.10/SCALEInstallMainScreen.png
  static/images/SCALE/23.10/SCALEInstallPartitionScreen.png
  static/images/SCALE/23.10/SCALEInstallWarningScreen.png
  static/images/SCALE/23.10/SCALEInstallerConsoleSetupAdminAccount.png
  static/images/SCALE/23.10/SCALEInstallerConsoleSetupAdminPassword.png
  words-to-ignore.txt
Labels: Technical Writer Review (MJ), Review (TM)
