Repository truenas/documentation, pull requests merged in 2023-10, with the labels that each got.

#2226 Pd 456 update cli keychain credential.md article
  content/SCALE/SCALECLIReference/System/CLIKeychainCredential.md
Labels: Technical Writer Review (TR)

#2231 PD-806: 22.12.4.1 hotpatch release notes
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific

#2235 PD-809: 22.12.4.2 relnotes updates
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific

#2239 PD-811: typo fix backport for 13.0 branch
  content/UIReference/Storage/Pools/PoolsScreens.md
Labels: Version Specific

#2245 PD-812: typo fix (23.10 cherry-pick)
  content/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md
Labels: Version Specific

#2254 PD-820: Known Issue for TrueNAS Enterprise system NIC name change on upgrade
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific

#2246 Pd 807 nf sv 4 smb mixed mode shares
  content/SCALE/SCALETutorials/Shares/AddingNFSShares.md
  content/SCALE/SCALETutorials/Shares/MixedModeShares.md
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShares.md
  content/SCALE/SCALETutorials/Storage/Datasets/PermissionsSCALE.md
  content/_includes/CreateDatasetSCALE.md
  content/_includes/ShareDatasetsNotPools.md
  static/images/SCALE/SystemSettings/ServicesNFSAddKerberosSPNEntry.png
  words-to-ignore.txt
Labels: Technical Writer Review (MJ)

#2259 Update release schedule and add upgrade warning (23.10)
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific

#2263 23.10 (Cobia): Clarify upgrade options
  content/GettingStarted/23.10Upgrades.md
  content/GettingStarted/Migrate/MigratingFromCORE.md
  content/GettingStarted/SCALEReleaseNotes.md
  content/_includes/23.10UpgradeMethods.md
  words-to-ignore.txt
Labels: Version Specific

#2268 PD-837: 23.10.0.1 Docs
  content/GettingStarted/SCALEReleaseNotes.md
  words-to-ignore.txt
Labels: Version Specific
