Repository truenas/documentation, pull requests merged in 2023-05, with the labels that each got.

#1882 PD-316 Rework Network Port ID Articles: M and X Series
  content/Hardware/MSeries/MSeriesNetworkPortIDs.md
  static/images/Hardware/Networking/M30NetworkPorts.png
  static/images/Hardware/Networking/M40NetworkPorts(128G).png
  static/images/Hardware/Networking/M40NetworkPorts(192G).png
  static/images/Hardware/Networking/M50NetworkPorts.png
  static/images/Hardware/Networking/M60NetworkPorts(x12ES).png
  static/images/Hardware/Networking/M60NetworkPorts(x8ES).png
  static/images/Hardware/Networking/Thumbs.db
Labels: Review (TM)

#1881 PD-243 update cli introductory article content
  content/SCALE/SCALECLIReference/_index.md
  content/_includes/SCALECLIGetHelp.md
  content/_includes/SCALECLIIntroduction.md
  static/images/SCALE/CLI/CLIAutofillList.png
  static/images/SCALE/CLI/CLIBasicCommands.png
  static/images/SCALE/CLI/CLIListForCommandWithOptions.png
  static/images/SCALE/CLI/CSMCLIlaunch.png
  static/images/SCALE/CLI/EnterCLIinShell.png
  static/images/SCALE/CLI/EnterFullCommandAtCLIPrompt.png
  static/images/SCALE/CLI/EnterFullCommandAtNamespacePrompt.png
  words-to-ignore.txt
Labels: Review (TM)

#1885 PD-293: adjust top menu so Resources and Get TrueNAS dropdowns don't …
  static/custom.css
Labels: Technical Writer Review (TR)

#1883 PD-247: create auth namespace article content
  content/SCALE/SCALECLIReference/Auth/CLIApiKey.md
  content/SCALE/SCALECLIReference/Auth/CLIPrivilege.md
  content/SCALE/SCALECLIReference/Auth/CLISessions.md
  content/SCALE/SCALECLIReference/Auth/CLITwoFactor.md
  content/SCALE/SCALECLIReference/Auth/_index.md
  content/SCALE/SCALECLIReference/_index.md
  content/_includes/CLIGuideWIP.md
Labels: Review (TM)

#1887 Pd 244 update network namespace articles
  content/SCALE/SCALECLIReference/Network/CLIConfiguration.md
  content/SCALE/SCALECLIReference/Network/CLIDNS.md
  content/SCALE/SCALECLIReference/Network/CLIGeneral.md
  content/SCALE/SCALECLIReference/Network/CLIIPMI.md
  content/SCALE/SCALECLIReference/Network/CLIInterface.md
  content/SCALE/SCALECLIReference/Network/CLIRoute.md
  content/SCALE/SCALECLIReference/Network/CLIStaticRoute.md
  content/SCALE/SCALECLIReference/Network/_index.md
Labels: Technical Writer Review (TR)

#1903 PD-383 Clarify Share Type=Apps Setting
  content/SCALE/SCALEUIReference/Storage/Datasets/DatasetsScreensScale.md
  content/_includes/CreateDatasetSCALE.md
Labels: Technical Writer Review (DP)

#1904 PD-382 add deprecation notice to service articles
  content/SCALE/SCALETutorials/SystemSettings/Services/DDNSServiceSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/S3ServiceSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/TFTPServiceSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/WebDAVServiceSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/DDNSServiceScreenSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/S3ServiceScreen.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/TFTPServiceScreen.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/WebDAVServiceScreen.md
  content/_includes/SCALEServiceDeprecationNotice.md
Labels: Version Specific, Technical Writer Review (DP)

#1908 Pd 479 create ddns migration article
  content/SCALE/SCALETutorials/SystemSettings/Services/DDNSServiceMigrate.md
  content/SCALE/SCALETutorials/SystemSettings/Services/DDNSServiceSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/DDNSServiceScreenSCALE.md
  content/_includes/SCALEServiceDeprecationNotice.md
  static/images/SCALE/22.12/ddns-updaterConfigIPSettings.png
  static/images/SCALE/22.12/ddns-updaterConfigPeriodSettings.png
  static/images/SCALE/22.12/ddns-updaterDNSProviderConfigAdd.png
  static/images/SCALE/22.12/ddnsUpdaterAppWidget.png
Labels: Technical Writer Review (DP)

#1912 PD-370 Update StorJ Node App Tutorial
  content/SCALE/SCALETutorials/Apps/AddStorjNode.md
  static/images/SCALE/22.12/StorjHostaNode.png
Labels: Technical Writer Review (DP)

#1923 Address user feedback: broken link, suggestion path change, and feedb…
  config.toml
  content/SCALE/GettingStarted/Migrate/MigratingFromCORE.md
  layouts/partials/menu-nextprev.html
Labels: Technical Writer Review (MJ)

#1910 PD-356 CORE 13 U5 Improve View Enclosure Article Content
  content/CORE/UIReference/System/ViewEnclosure.md
  content/SCALE/SCALEUIReference/SystemSettings/EnclosureScreensSCALE.md
  static/images/CORE/13.0/ViewEnclosureEditLabel.png
  static/images/CORE/13.0/ViewEnclosureElements.png
  static/images/CORE/13.0/ViewEnclosureExpansionShelf.png
  static/images/CORE/13.0/ViewEnclosureM40WithShelf.png
  static/images/CORE/13.0/ViewEnclosureMiniDisks.png
  static/images/CORE/13.0/ViewEnclosureMiniExample.png
  static/images/CORE/13.0/ViewEnclosureR20Disks.png
  static/images/CORE/13.0/ViewEnclosureR20Front.png
  static/images/CORE/13.0/ViewEnclosureR20Rear.png
  static/images/CORE/13.0/ViewEnclosureWidget.png
Labels: Version Specific, Technical Writer Review (MJ), Technical Writer Review (DP)

#1919 PD-384 core dataset encryption updates
  content/CORE/CORETutorials/Storage/Pools/Datasets.md
  content/CORE/CORETutorials/Storage/Pools/PoolCreate.md
  content/CORE/CORETutorials/Storage/Pools/StorageEncryption.md
  content/CORE/UIReference/Storage/Pools/DatasetsScreen.md
  content/CORE/UIReference/Storage/Pools/PoolsScreens.md
Labels: Version Specific, Technical Writer Review (DP)

#1921 Pd 386 update managing plugins article with s3 key information
  content/CORE/CORETutorials/JailsPluginsVMs/Plugins/ManagingPlugins.md
Labels: Version Specific

#1926 PD-360 Update SCALE NFS Share Articles
  content/SCALE/SCALETutorials/Shares/AddingNFSShares.md
  content/SCALE/SCALEUIReference/Shares/NFSSharesScreens.md
Labels: Technical Writer Review (DP)

#1927 PD-323 Create Loading UI in a Frame Tutorial
  content/SCALE/SCALECLIReference/System/CLIGeneral.md
  content/SCALE/SCALECLIReference/System/CLIUpdate.md
  content/SCALE/SCALECLIReference/System/_index.md
Labels: Technical Writer Review (DP)

#1924 Pd 365 add scale kmip article
  content/SCALE/SCALETutorials/Credentials/ConfiguringKMIPSCALE.md
  content/SCALE/SCALEUIReference/Credentials/KMIPSCALE.md
  static/images/SCALE/22.12/KMIPScreen.png
Labels: Technical Writer Review (DP)

#1932 Pd 382 add deprecation notice to service articles
  content/SCALE/SCALETutorials/SystemSettings/Services/ConfigRsyncServiceSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/OpenVPNSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/OpenVPNScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/RsyncServicesScreenSCALE.md
  static/images/SCALE/OpenVPNClient.png
  static/images/SCALE/OpenVPNServer.png
Labels: Version Specific

#1934 PD-388 UPS configuration with HA systems
  content/CORE/CORETutorials/Services/ConfigureUPS.md
  content/CORE/UIReference/Services/UPSScreen.md
  content/SCALE/SCALETutorials/SystemSettings/Services/UPSServicesSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/UPSServicesScreenSCALE.md
  content/_includes/HAUninterruptiblePowerSupplyNotice.md
Labels: Technical Writer Review (MJ)

#1901 PD-289 CORE 13.0-U5 Release Notes
  content/CORE/COREReleaseNotes.md
  content/CORE/CORETutorials/JailsPluginsVMs/Plugins/ManagingPlugins.md
  content/CORE/CORETutorials/Storage/Pools/Datasets.md
  content/CORE/CORETutorials/Storage/Pools/PoolCreate.md
  content/CORE/CORETutorials/Storage/Pools/StorageEncryption.md
  content/CORE/UIReference/Storage/Pools/DatasetsScreen.md
  content/CORE/UIReference/Storage/Pools/PoolsScreens.md
  content/CORE/UIReference/System/ViewEnclosure.md
  content/SCALE/SCALEUIReference/SystemSettings/EnclosureScreensSCALE.md
  static/images/CORE/13.0/ViewEnclosureEditLabel.png
  static/images/CORE/13.0/ViewEnclosureElements.png
  static/images/CORE/13.0/ViewEnclosureExpansionShelf.png
  static/images/CORE/13.0/ViewEnclosureM40WithShelf.png
  static/images/CORE/13.0/ViewEnclosureMiniDisks.png
  static/images/CORE/13.0/ViewEnclosureMiniExample.png
  static/images/CORE/13.0/ViewEnclosureR20Disks.png
  static/images/CORE/13.0/ViewEnclosureR20Front.png
  static/images/CORE/13.0/ViewEnclosureR20Rear.png
  static/images/CORE/13.0/ViewEnclosureWidget.png
  words-to-ignore.txt
Labels: Version Specific
