Repository truenas/documentation, pull requests merged in 2024-01, with the labels that each got.

#2389 (23.10.1) Add known issue for non-physical network interfaces
  content/GettingStarted/SCALEReleaseNotes.md
  words-to-ignore.txt
Labels: Version Specific, Technical Writer Review (DP)

#2401 Port v3.0.0 fix to 3.0 branch
  content/Recommendations/TCCloudSecurity.md
  content/TCGettingStarted/InitialConfig.md
  content/TCGettingStarted/Install/InstallTCDocker.md
  content/TCGettingStarted/InterfaceOverview.md
  content/UserGuide/Dashboard.md
  content/UserGuide/ReplicationManagement.md
  content/UserGuide/SystemInventory.md
  words-to-ignore.txt
Labels: Version Specific

#2404 Whereami note ported to 13.0
  layouts/partials/page-header.html
  static/custom.css
Labels: Version Specific

#2405 Whereami notice for 23.10 branch
  layouts/partials/page-header.html
Labels: Version Specific, Technical Writer Review (MJ)

#2406 whereami notice port to 22.12 branch
  layouts/partials/page-header.html
Labels: Version Specific, Technical Writer Review (MJ)

#2408 whereami notice port to tc 2.3 branch
  layouts/partials/page-header.html
Labels: Version Specific

#2407 whereami notice port to TC 3.0 branch
  layouts/partials/page-header.html
Labels: Version Specific, Technical Writer Review (MJ)

#2403 Polish "where am I" notice at top of nightly version content pages
  layouts/partials/page-header.html
  static/custom.css
Labels: Technical Writer Review (MJ)

#2412 Pd 909 refine the single sourced release schedules presentation
  content/CORE/GettingStarted/COREReleaseNotes.md
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
  content/TrueCommand/TCGettingStarted/TCReleaseNotes.md
  content/TrueNASUpgrades/_index.md
  data/properties/core-releases.yaml
  data/properties/scale-releases.yaml
  data/properties/tc-releases.yaml
  layouts/shortcodes/releaselist.html
  layouts/shortcodes/section-cards.html
  layouts/shortcodes/timeline.html
  words-to-ignore.txt
Labels: Technical Writer Review (MJ)

#2409 PD-968: Syncthing Enterprise article (and snippets) review (23.10)
  content/SCALETutorials/Apps/EnterpriseApps/Syncthing.md
  content/_includes/SyncthingFirstSteps.md
  content/_includes/SyncthingOverview.md
  content/_includes/SyncthingWebPortalInfo.md
  words-to-ignore.txt
Labels: Version Specific, Technical Writer Review (MJ)

#2414 Make whereami note consistent with gdoc hint styling (13.0)
  layouts/partials/page-header.html
Labels: Version Specific

#2415 Make whereami note styling consistent (23.10)
  layouts/partials/page-header.html
Labels: Version Specific

#2416 Make whereami note style consistent (22.12)
  layouts/partials/page-header.html
Labels: Version Specific

#2417 Make whereami note style consistent (3.0)
  layouts/partials/page-header.html
Labels: Version Specific, Technical Writer Review (MJ)

#2418 Make whereami note styling consistent (2.3)
  layouts/partials/page-header.html
Labels: Version Specific, Technical Writer Review (MJ)

#2413 Some post-merges cleanups
  layouts/_default/baseof.html
  layouts/partials/page-header.html
  layouts/shortcodes/imagecard.html
Labels: Technical Writer Review (DP)

#2419 PD-974: Update sessions token lifetime max value (23.10)
  content/_includes/SessionsSettingsWidget.md
Labels: Version Specific

#2393 Pd 960 scale 23.10.1.1 hotpatch docs
  content/GettingStarted/Migrate/ComponentNaming.md
  content/GettingStarted/SCALEReleaseNotes.md
  content/_includes/NetworkPortIdentifications.md
  static/images/CORE/NetworkInterfacesScreen.png
  words-to-ignore.txt
Labels: Version Specific, Review (TM)

#2422 Pd 953 update system settings advanced article content
  content/SCALE/SCALETutorials/SystemSettings/Advanced/ManageGlobal2FASCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Advanced/_index.md
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  content/_includes/AccessSettingsWidget.md
  static/images/SCALE/SystemSettings/AddCronJobScreen.png
  static/images/SCALE/SystemSettings/AddInitShutdownScriptConfigScreen.png
  static/images/SCALE/SystemSettings/AdvancedSystemAllowedIPAddressesWidget.png
  static/images/SCALE/SystemSettings/AdvancedSystemSelfEncryptingDriveConfigScreen.png
  static/images/SCALE/SystemSettings/AdvancedSystemSettingsAccessWidget.png
  static/images/SCALE/SystemSettings/AdvancedSystemSettingsSyslogWidget.png
  static/images/SCALE/SystemSettings/AdvancedSystemStorageWidget.png
  static/images/SCALE/SystemSettings/Console.png
  static/images/SCALE/SystemSettings/Enable2FAGlobally.png
  static/images/SCALE/SystemSettings/GlobalTwoFactorAuthenticationSettingsScreen.png
  static/images/SCALE/SystemSettings/GlobalTwoFactorAuthenticationWidget.png
  static/images/SCALE/SystemSettings/SyslogConfigScreen.png
  static/images/SCALE/SystemSettings/SystemAdvancedAuditScreen.png
  static/images/SCALE/SystemSettings/SystemAdvancedAuditWidget.png
  static/images/SCALE/SystemSettings/SystemAdvancedScreen.png
  static/images/SCALE/SystemSettings/SystemAdvancedScreen2.png
  static/images/SCALE/SystemSettings/SystemStorageConfigScreen.png
  words-to-ignore.txt
Labels: Technical Writer Review (DP)

#2427 PD-946-revise-jellyfin-app-tutorial
  content/SCALE/SCALETutorials/Apps/CommunityApps/jellyfin.md
Labels: Review (TM)

#2426 Pd 413 review v mware snapshots and storage state behavior docs
  content/SCALE/SCALETutorials/DataProtection/CreatingVMwareSnapshots.md
  content/SCALE/SCALETutorials/Datasets/AddManageZvols.md
  content/SCALE/SCALEUIReference/DataProtection/VMwareSnapshotsScreen.md
  static/images/SCALE/DataProtection/VMWareSnapshotsScreenConfigured.png
  static/images/SCALE/DataProtection/emptyvmwaresnapshotadd.png
  static/images/SCALE/DataProtection/vmwareaddsnapshottask.png
  static/images/SCALE/DataProtection/vmwaresnapshottask.png
  static/images/SCALE/Datasets/DatasetsScreenClonedZvol.png
  static/images/SCALE/Shares/iSCSIvmwareCloneAssociatedTargets.png
  static/images/SCALE/Shares/iSCSIvmwareCloneExtents.png
  static/images/VMWareESXi/ConfigureiSCSI.png
  static/images/VMWareESXi/StorageAdapters.png
  static/images/VMWareESXi/StorageDatastoresClone.png
  static/images/VMWareESXi/StorageDevices.png
  static/images/VMWareESXi/StorageDevicesClone.png
  static/images/VMWareESXi/VMWareTrueNASVMCreated.png
  static/images/VMWareESXi/VMWizardSelectExisting.png
Labels: Technical Writer Review (MJ)

#2436 PD-989: 23.10.1.3 Hotpatch
  content/GettingStarted/Install/InstallPrepEnterprise.md
  content/GettingStarted/SCALEReleaseNotes.md
  content/_includes/SCALEHADisableSTP.md
  words-to-ignore.txt
Labels: Version Specific

#2434 PD-971: backport typo fix (23.10)
  content/SCALEUIReference/Apps/InstallCustomAppScreens.md
Labels: Version Specific

#2429 Pd 710 create audit articles
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShares.md
  content/SCALE/SCALETutorials/SystemSettings/AuditingSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  content/_includes/ConfigureSMBShareAuditingSCALE.md
  content/_includes/ConfigureSystemAuditSCALE.md
  static/images/SCALE/Shares/SMBShareAdvancedAuditLogging.png
  static/images/SCALE/SystemSettings/SystemSettingsAuditScreen.png
  words-to-ignore.txt
Labels: Review (TM)

#2439 Pd 973 Syncthing ingest tutorial
  content/SCALE/GettingStarted/DataMigrationSyncthing.md
  content/_includes/AddEnterpriseTrain.md
  static/custom.css
  static/images/SCALE/Apps/SyncthingAddDeviceAdvanced.png
  static/images/SCALE/Apps/SyncthingAdditionalStorage.png
  static/images/SCALE/Apps/SyncthingEditFolder.png
  static/images/SCALE/Apps/SyncthingEnterpriseAppWidget.png
  static/images/SCALE/Apps/SyncthingMigrateInstalled.png
  static/images/SCALE/Apps/SyncthingSMBMigrationMode.png
  static/images/SCALE/Apps/SyncthingUIAddFolder.png
  static/images/SCALE/Apps/SyncthingUISettingsDeviceName.png
  static/images/SCALE/Apps/SyncthingUISettingsDeviceNameMigrate.png
  words-to-ignore.txt
Labels: Review (TM)

#2438 Pd 918 update smb and nfs share and service UI ref articles
  content/SCALE/GettingStarted/Configure/SetUpSharing.md
  content/SCALE/SCALETutorials/Shares/AddingNFSShares.md
  content/SCALE/SCALETutorials/Shares/MixedModeShares.md
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShares.md
  content/SCALE/SCALETutorials/Shares/SMB/ManageSMBShares.md
  content/SCALE/SCALETutorials/Shares/SMB/_index.md
  content/SCALE/SCALEUIReference/Credentials/LocalGroupsScreens.md
  content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
  content/SCALE/SCALEUIReference/Shares/NFSSharesScreens.md
  content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md
  content/SCALE/SCALEUIReference/Shares/_index.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/SMBServicesScreen.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/_index.md
  content/Solutions/Optimizations/Security.md
  content/_includes/CreateDatasetSCALE.md
  static/images/SCALE/Apps/SMBServiceAdvanced1.png
  static/images/SCALE/Shares/AddNFSAdvancedOptionsAccessSettings.png
  static/images/SCALE/Shares/AddNFSPath.png
  static/images/SCALE/Shares/AddNFSScreen.png
  static/images/SCALE/Shares/AddNFSSharePath.png
  static/images/SCALE/Shares/AddSMBAdvancedAuditLoggingSettings.png
  static/images/SCALE/Shares/AddSMBPath.png
  static/images/SCALE/Shares/AddShareBasicOptions.png
  static/images/SCALE/Shares/NFSSessionsScreen.png
  static/images/SCALE/Shares/NFSShareWidgetNoShare.png
  static/images/SCALE/Shares/NFSWidgetOptions.png
  static/images/SCALE/Shares/SMBACLEditor.png
  static/images/SCALE/Shares/SMBShareACLScreen.png
  static/images/SCALE/Shares/SMBShareScreenNoShare.png
  static/images/SCALE/Shares/SMBStatusScreenSessionsTab.png
  static/images/SCALE/Shares/SetUpExternalSMBShare.png
  static/images/SCALE/Shares/SharingDashboardNoShares.png
  static/images/SCALE/Shares/SharingNFSAddSCALE.png
  static/images/SCALE/Shares/SharingNFSEnableServiceDialog.png
  static/images/SCALE/Shares/SharingSMBScreen.png
  static/images/SCALE/Shares/SharingSMBServicesActionOptions.png
  static/images/SCALE/Shares/WindowsSMBShareWidget.png
  static/images/SCALE/Shares/WindowsSMBShareWidgetNoShares.png
  static/images/SCALE/SystemSettings/SMBServiceAdvanced1.png
  static/images/SCALE/SystemSettings/ServicesSCALE.png
  words-to-ignore.txt
Labels: Technical Writer Review (DP)

#2443 PD-978 Rework TrueNASUpgrades as Software Releases
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
  content/SCALE/GettingStarted/Upgrades.md
  content/TrueNASUpgrades/_index.md
  data/properties/core-downloads.yaml
  data/properties/scale-downloads.yaml
  layouts/_default/baseof.html
  layouts/shortcodes/releaselist.html
  layouts/shortcodes/tabbox.html
  layouts/shortcodes/timeline.html
  static/custom.css
  words-to-ignore.txt
Labels: Technical Writer Review (MJ)

#2441 Pd 849 Syncthing Migration Followup
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
  content/SCALE/SCALETutorials/Apps/EnterpriseApps/Syncthing.md
  content/Solutions/MigratingToTrueNAS.md
  content/_includes/23.10FeatureList.md
  content/_includes/24.04FeatureList.md
  content/_includes/ReleaseScheduleWarning.md
Labels: Technical Writer Review (MJ)

#2445 PD-995: Sandbox (SCALE Jails) article
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
  content/SCALE/SCALETutorials/Apps/Sandboxes.md
  static/images/SCALE/Datasets/SandboxDatasetCreate.png
  static/images/SCALE/SystemSettings/JailmakerInitScriptCreate.png
Labels: Technical Writer Review (DP)

#2442 Pd 994 update other smb share tutorials
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBHomeShare.md
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShadowCopies.md
  content/SCALE/SCALETutorials/Shares/SMB/SetUpBasicTimeMachineSMBShare.md
Labels: Technical Writer Review (DP)

#2450 DOCS add secure application access draft
  content/SCALE/SCALETutorials/Apps/AppSecurity/_index.md
  static/images/SCALE/Apps/CloudflareAddApplication.png
  static/images/SCALE/Apps/CloudflareAddPolicy.png
  static/images/SCALE/Apps/CloudflareCreateAdditionalRules.png
  static/images/SCALE/Apps/CloudflareTunnelHostname.png
  static/images/SCALE/Apps/CloudflareTunnelOverview.jpg
  static/images/SCALE/Apps/CloudflareTunnelStateHealthy.png
  static/images/SCALE/Apps/CloudflareTunnelTLSSetting.png
  static/images/SCALE/Apps/NextcloudEnviromentVariables.png
Labels: Technical Writer Review (DP)
