Repository truenas/documentation, pull requests merged in 2024-11, with the labels that each got.

#3180 Update SCALEReleaseNotes.md
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Review (TM)

#3176 PD-1351 / 24.10 / PD-1351 Research and Expand Snapshot and Replication Documentation
  content/SCALETutorials/DataProtection/PeriodicSnapshotTasksSCALE.md
Labels: Technical Writer Review (MJ), Re-Review

#3179 PD-1515 / 24.10 / PD-1515 Add more depth/note requirements when making new certificates in TrueNAS
  content/SCALETutorials/Credentials/Certificates/CertificatesSCALE.md
Labels: Technical Writer Review (MJ), backport-25.04

#3184 PD-1467 / 24.10 / Pd 1467 clarify storj bucket nuances
  content/GettingStarted/Configure/SetUpBackupScale.md
  content/SCALETutorials/Credentials/BackupCredentials/AddCloudCredentials.md
  content/SCALETutorials/DataProtection/TrueCloudTasks.md
  content/SCALEUIReference/Credentials/BackupCredentials/CloudCredentialScreens.md
  content/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  content/SCALEUIReference/DataProtection/TrueCloudBackupTasksScreen.md
  static/images/SCALE/DataProtection/AddCloudSyncTaskNewBucket.png
  static/images/SCALE/DataProtection/AddTrueCloudTaskNewBucket.png
  static/includes/AddStorjCloudCredential.md
  static/includes/CreateStorjiXAccount.md
  static/includes/SetUpStorjiXAccountS3Access.md
  static/includes/StorjBucket.md
Labels: backport-25.04

#3185 PD-1515 / 25.04 / PD-1515 Add more depth/note requirements when making new certificates in TrueNAS (by linzi-ix)
  content/SCALE/SCALETutorials/Credentials/Certificates/CertificatesSCALE.md
Labels: Technical Writer Review (MJ)

#3151 PD-1511 / 25.04 / Pd 1511 update storage devices screens
  content/SCALE/SCALETutorials/Storage/ManagePoolsScale.md
  content/SCALE/SCALEUIReference/Storage/DevicesScreensSCALE.md
  static/images/SCALE/Storage/DeviceDiskInfoWidget.png
  static/images/SCALE/Storage/DeviceDiskSMARTInfoWidget.png
  static/images/SCALE/Storage/DevicesDiskWidgets.png
  static/images/SCALE/Storage/DevicesExtend.png
  static/images/SCALE/Storage/DevicesMirrorVDEVSelected.png
  static/images/SCALE/Storage/DevicesScreenDataVdevsUnexpanded.png
Labels: Technical Writer Review (LM), Re-Review, backport-24.10

#3150 PD-1518 / 25.04 / PD-1518 Update Getting Started Storage and Share Articles
  content/SCALE/GettingStarted/Configure/SetUpSharing.md
  content/SCALE/GettingStarted/Configure/SetUpStorageScale.md
Labels: Technical Writer Review (LM), Re-Review, backport-24.10, backport-24.04

#3188 PD-1511 / 24.10 / Pd 1511 update storage devices screens (by micjohnson777)
  content/SCALETutorials/Storage/ManagePoolsScale.md
  content/SCALEUIReference/Storage/DevicesScreensSCALE.md
  static/images/SCALE/Storage/DeviceDiskInfoWidget.png
  static/images/SCALE/Storage/DeviceDiskSMARTInfoWidget.png
  static/images/SCALE/Storage/DevicesDiskWidgets.png
  static/images/SCALE/Storage/DevicesExtend.png
  static/images/SCALE/Storage/DevicesMirrorVDEVSelected.png
  static/images/SCALE/Storage/DevicesScreenDataVdevsUnexpanded.png
Labels: Technical Writer Review (LM)

#3186 PD-1467 / 25.04 / Pd 1467 clarify storj bucket nuances (by DjP-iX)
  content/SCALE/GettingStarted/Configure/SetUpBackupScale.md
  content/SCALE/SCALETutorials/Credentials/BackupCredentials/AddCloudCredentials.md
  content/SCALE/SCALETutorials/DataProtection/TrueCloudTasks.md
  content/SCALE/SCALEUIReference/Credentials/BackupCredentials/CloudCredentialScreens.md
  content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/TrueCloudBackupTasksScreen.md
  static/images/SCALE/DataProtection/AddCloudSyncTaskNewBucket.png
  static/images/SCALE/DataProtection/AddTrueCloudTaskNewBucket.png
  static/includes/AddStorjCloudCredential.md
  static/includes/CreateStorjiXAccount.md
  static/includes/SetUpStorjiXAccountS3Access.md
  static/includes/StorjBucket.md
Labels: Technical Writer Review (LM)

#3191 PD-1579 / 24.10 / Pd 1579 24 10 0 1 release notes docs
  content/GettingStarted/SCALEReleaseNotes.md
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  static/includes/SCALEUpgradePaths.md
Labels: Version Specific, Technical Writer Review (MJ), Review (TM)

#3192 PD-1584 / 24.04 / Pd 1584 24 04 2 4 release notes
  content/GettingStarted/SCALEReleaseNotes.md
  content/SCALETutorials/Apps/_index.md
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  static/images/SCALE/Apps/HostPathACL.png
  static/includes/SCALEUpgradePaths.md
Labels: Version Specific, Technical Writer Review (MJ), Review (TM)

#3193 PD-1579 / 25.04 / Pd 1579 follow up 24 10 0 1 release notes docs
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  static/includes/SCALEUpgradePaths.md
Labels: Version Specific, Technical Writer Review (MJ)

#3183 PD-1477 / 25.04 / Pd 1477 update nextcloud tutorial
  content/TruenasApps/StableApps/InstallNextCloudMedia.md
  static/images/SCALE/Apps/AddNextcloudDatasetNetdataUserACL.png
  static/images/SCALE/Apps/AddNextcloudParentDatasetNetdataUserACL.png
  static/images/SCALE/Apps/AddPostgres_DataACLPermissions.png
  static/images/SCALE/Apps/AppsAddNextcloudDatasets.png
  static/images/SCALE/Apps/InstallAppStorageConfigurationACLandACESettings.png
  static/images/SCALE/Apps/InstallNextcloudConfig1.png
  static/images/SCALE/Apps/InstallNextcloudConfig2.png
  static/images/SCALE/Apps/InstallNextcloudConfigAPTPackageOptions.png
  static/images/SCALE/Apps/InstallNextcloudConfigCronSettings.png
  static/images/SCALE/Apps/InstallNextcloudEnableHostPath.png
  static/images/SCALE/Apps/InstallNextcloudResourcesConfig.png
  static/images/SCALE/Apps/InstallNextcloudScreen.png
  static/images/SCALE/Apps/InstallNextcloudStorageAppDataACLandACESettings.png
  static/images/SCALE/Apps/InstallNextcloudStorageConfigPostgressHostPaths.png
  static/images/SCALE/Apps/InstallNextcloudStorageDataACLandACESettings.png
  static/images/SCALE/Apps/NextcloudAppDetailsScreen.png
  static/images/SCALE/Apps/SetPostgres_dataACLtoPOSIX.png
  static/includes/apps/AddMultipleAppInstancesAndNaming.md
  static/includes/apps/AppBeforeYouBeginNewUser.md
  static/includes/apps/AppInstallWizardACLConfiguration.md
  static/includes/apps/AppInstallWizardCertificateSettings.md
  static/includes/apps/AppInstallWizardEnvironVariablesSettings.md
  static/includes/apps/AppInstallWizardNetworkConfig.md
  static/includes/apps/AppWizardStorageSMBOption.md
  static/includes/apps/AppsBeforeYouBeginCertificate.md
  static/includes/apps/AppsInstallWizardDefaultPorts.md
  static/includes/apps/AppsInstallWizardGPUPassthrough.md
  static/includes/apps/AppsStableBeforeYouBegin.md
  static/includes/apps/InstallAppsStorageConfig.md
  static/includes/apps/InstallAppsStorageConfig2.md
  static/includes/apps/LocateAndOpenInstallWizard.md
  static/includes/apps/MinIODatasetRequirements.md
Labels: Technical Writer Review (DP), Re-Review

#3187 PD-1296 / 24.10 / PD-1296-review-ui-images-for-electric-eel
  static/images/SCALE/Dashboard/AlertsNotifications.png
  static/images/SCALE/DataProtection/DataProtectionSMARTTestWidgetSCALE.png
  static/images/SCALE/DataProtection/scrubtaskpriority.png
  static/images/SCALE/DataProtection/vmwareaddsnapshottask.png
  static/images/SCALE/Shares/MigratedAFPShareSCALE.png
  static/images/SCALE/Shares/iSCSISystemServicesSCALE.png
  static/images/SCALE/Storage/DevicesExtend.png
  static/images/SCALE/SystemSettings/SMARTSystemServicesSCALE.png
Labels: Technical Writer Review (MJ), Re-Review

#3194 PD-1482 / 25.04 / Pd 1482 update remote replication tutorial
  content/SCALE/SCALETutorials/DataProtection/Replication/RemoteReplicationSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/ReplicationScreensSCALE.md
  static/images/SCALE/DataProtection/AddReplicationTaskEncyptionHexOption.png
  static/images/SCALE/DataProtection/AdvancedAddReplicationTaskGeneralTransportSSH+NETCAT.png
  static/images/SCALE/DataProtection/ReplicationTaskDetails.png
  static/images/SCALE/DataProtection/ReplicationTaskWizardWhatAndWhereAllSettings.png
  static/images/SCALE/DataProtection/ReplicationTasksListScreen.png
  static/images/SCALE/DataProtection/ReplicationTasksWidget.png
  static/images/SCALE/DataProtection/ReplicationTasksWidgetNoTasks.png
  static/includes/BasicReplicationProcess.md
  static/includes/ReplicationCreateDatasetAndAdminHomeDirSteps.md
  static/includes/ReplicationScheduleAndRetentionSteps.md
Labels: Technical Writer Review (LM), Re-Review, backport-24.10

#3166 PD-1469 / 25.04 / Pd 1469 update static route and aliases content
  content/SCALE/GettingStarted/Configure/UIConfigurationSCALE.md
  content/SCALE/SCALETutorials/Network/ConfigureStaticRoutes.md
  content/SCALE/SCALETutorials/Network/Interfaces/SettingUpStaticIPs.md
  content/SCALE/SCALETutorials/Network/Interfaces/_index.md
  content/Solutions/Optimizations/Networking.md
  static/images/SCALE/Network/InterfaceSavetStaticIPChange.png
  static/images/SCALE/Network/InterfaceStaticIPChangeIsPermanent.png
  static/includes/AliasOrStaticIP.md
  static/includes/BeforeYouBridge.md
  static/includes/MultipleInterfacesOnNetwork.md
  static/includes/NetworkInterfaceTypes.md
Labels: Technical Writer Review (DP), Re-Review

#3195 24.10.0.2 relnotes updates
  content/GettingStarted/SCALEReleaseNotes.md
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  static/includes/SCALEUpgradePaths.md
Labels: Version Specific

#3196 24.04.2.5 Release updates
  content/GettingStarted/SCALEReleaseNotes.md
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  static/includes/SCALEUpgradePaths.md
Labels: Version Specific

#3197 24.04.2.5 and 24.10.0.2 releases followup for master branch
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  static/includes/SCALEUpgradePaths.md
Labels: Version Specific

#3202 PD-1519 / 25.04 / PD-1519 Update File and Directory Mask Descriptions
  content/SCALE/SCALEUIReference/SystemSettings/Services/SMBServicesScreen.md
Labels: Technical Writer Review (LM), backport-24.10

#3203 PD-1519 / 13.0 / PD-1519 Update File and Directory Mask Descriptions
  content/UIReference/Services/SMBScreen.md
Labels: Technical Writer Review (LM), backport-13.3

#3206 PD-1519 / 24.10 / PD-1519 Update File and Directory Mask Descriptions (by micjohnson777)
  content/SCALEUIReference/SystemSettings/Services/SMBServicesScreen.md
Labels: Technical Writer Review (LM)

#3207 PD-1519 / 13.3 / PD-1519 Update File and Directory Mask Descriptions (by micjohnson777)
  content/UIReference/Services/SMBScreen.md
Labels: Technical Writer Review (LM)

#3205 PD-1571 / 13.0 / PD-1571-misleading-link-on-core-afs-page
  content/CORETutorials/Sharing/AFPShare.md
  content/UIReference/Services/AFPScreen.md
Labels: Technical Writer Review (MJ), backport-13.3

#3181 PD-1403: Remove CORE/TC options for nightly docs from product/version switcher
  layouts/partials/docs-nav.html
Labels: Backport Requested, Technical Writer Review (LM), backport-24.10, backport-24.04, backport-23.10, backport-13.3, backport-13.0, backport-3.0

#3223 PD-1403 / 13.3 / backport version switcher change (13.3)
  layouts/partials/docs-nav.html
Labels: Backport Requested, backport-24.10, backport-24.04, backport-23.10, backport-13.0, backport-3.0

#3225 PD-1403 / 23.10 / backport version switcher change (by Mrt134)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (MJ)

#3226 PD-1403 / 24.04 / backport version switcher change (by Mrt134)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (MJ)

#3228 PD-1403 / 3.0 / backport version switcher change (by Mrt134)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (MJ)

#3201 Update SCALEReleaseNotes.md - clarify encrypted dataset and app migrate
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific, Technical Writer Review (MJ)

#3222 Fix landing page nav menu
  layouts/partials/menu-filetree.html
Labels: Technical Writer Review (MJ)

#3200 PD-1499 / 25.04 / Pd 1499 create do not create root dataset share warning
  content/SCALE/GettingStarted/Configure/SetUpSharing.md
  content/SCALE/SCALETutorials/Shares/AFPMigration.md
  content/SCALE/SCALETutorials/Shares/AddingNFSShares.md
  content/SCALE/SCALETutorials/Shares/MixedModeShares.md
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBHomeShare.md
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShadowCopies.md
  content/SCALE/SCALETutorials/Shares/SMB/ManageSMBShares.md
  content/SCALE/SCALETutorials/Shares/SMB/SMBMultichannel.md
  content/SCALE/SCALETutorials/Shares/SMB/SetUpBasicTimeMachineSMBShare.md
  content/SCALE/SCALETutorials/Shares/SMB/_index.md
  content/SCALE/SCALETutorials/Shares/_index.md
  static/includes/RootLevelDatasetShareWarning.md
Labels: Technical Writer Review (DP), Re-Review, backport-24.10, backport-24.04

#3235 PD-1541 / 24.10 / Pd 1541 update product version switcher for apps backports
  layouts/partials/docs-nav.html
  words-to-ignore.txt
Labels: Technical Writer Review (MJ), backport-23.10, backport-13.3, backport-13.0, backport-3.0

#3211 PD-1574 / 25.04 / PD-1574 Add New Screenshots and Update Content
  content/SCALE/SCALETutorials/Credentials/AdminRoles.md
  static/images/SCALE/Dashboard/ChangeLoggedInUserPassword.png
  static/images/SCALE/Dashboard/ChangeLoggedInUserPasswordShare&ReadonlyAdmin.png
  static/includes/ChangeLoggedInUserPassword.md
Labels: Technical Writer Review (DP), Re-Review, backport-24.10

#3213 PD-1568 / 25.04 / Pd 1568 consolidate global network setting articles
  content/SCALE/SCALETutorials/Network/AddingGlobalConf.md
  content/SCALE/SCALETutorials/Network/ManagingGlobalConfig.md
  content/SCALE/SCALEUIReference/Network/GlobalConfigurationScreens.md
  static/includes/ConfigureController1Networking.md
Labels: Technical Writer Review (DP), Re-Review, backport-24.10

#3241 PD-1541 / 23.10 / Pd 1541 update product version switcher for apps backports (by DjP-iX)
  layouts/partials/docs-nav.html
  words-to-ignore.txt
Labels: Technical Writer Review (MJ)

#3208 PD-1564 / 25.04 / Pd 1564 update ad article content
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigADSCALE.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/ActiveDirectory.md
Labels: Technical Writer Review (DP), Re-Review, backport-24.10, backport-24.04

#3210 PD-1581 / 24.10 / PD-1581-link-install-nvidia-drivers-instructions-from-virtual-devices-tutorial
  content/SCALETutorials/Virtualization/_index.md
Labels: Technical Writer Review (DP), Re-Review, backport-25.04

#3245 PD-1580 / 24.10 / PD-1580-update-manage-pools-scale
  content/SCALETutorials/Storage/ManagePoolsScale.md
Labels: Technical Writer Review (MJ), backport-25.04

#3247 PD-1541 / 25.04 / PD-1541-Update-Product/Version-Switcher-for-apps
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (LM), backport-24.10, backport-23.10, backport-13.3, backport-13.0, backport-3.0

#3252 PD-1592 / 25.04 / PD-1592 SCALE has "plugin" alerts
  static/includes/AlertsCategories.md
Labels: Technical Writer Review (LM)

#3251 PD-1580 / 25.04 / PD-1580-update-manage-pools-scale (by linzi-ix)
  content/SCALE/SCALETutorials/Storage/ManagePoolsScale.md
Labels: Technical Writer Review (MJ)

#3250 PD-1581 / 25.04 / PD-1581-link-install-nvidia-drivers-instructions-from-virtual-devices-tutorial (by linzi-ix)
  content/SCALE/SCALETutorials/Virtualization/_index.md
Labels: Technical Writer Review (MJ), Re-Review

#3263 PD-1543 / 25.04 / Pd 1543 docs hub 404 page is returning a 200 code
  content/404Error.md
  layouts/partials/head/custom.html
Labels: backport-24.10, backport-24.04, backport-23.10, backport-13.3, backport-13.0, backport-3.0

#3264 Add max file size for SMB write to SMB Reference article
  content/References/SMB.md
  words-to-ignore.txt
Labels: Technical Writer Review (MJ)

#3260 PD-1628 / None / update cautions for virtualization features in 13.3
  content/CORETutorials/JailsPluginsVMs/Jails/AccessingJailsUsingSSH.md
  content/CORETutorials/JailsPluginsVMs/Jails/InstallingJailSoftware.md
  content/CORETutorials/JailsPluginsVMs/Jails/ManagingJails.md
  content/CORETutorials/JailsPluginsVMs/Jails/SettingUpJailStorage.md
  content/CORETutorials/JailsPluginsVMs/Jails/_index.md
  content/CORETutorials/JailsPluginsVMs/Plugins/CreatingCustomPlugin.md
  content/CORETutorials/JailsPluginsVMs/Plugins/MinIOPlugin.md
  content/CORETutorials/JailsPluginsVMs/Plugins/PlexPlugin.md
  content/CORETutorials/JailsPluginsVMs/Plugins/_index.md
  content/CORETutorials/JailsPluginsVMs/UpdateJailsPlugins.md
  content/CORETutorials/JailsPluginsVMs/VirtualMachines/SettingUpNPIV.md
  content/CORETutorials/JailsPluginsVMs/VirtualMachines/_index.md
  content/CORETutorials/JailsPluginsVMs/_index.md
  content/GettingStarted/Applications.md
  content/GettingStarted/DataBackups.md
  content/GettingStarted/Deprecations.md
  content/UIReference/JailsPluginsVMs/JailsScreens.md
  content/UIReference/JailsPluginsVMs/PluginsScreens.md
  content/UIReference/JailsPluginsVMs/VirtualMachines.md
  content/UIReference/JailsPluginsVMs/_index.md
  static/includes/COREFeatureSupport.md
  words-to-ignore.txt
Labels: Version Specific

#3262 PD-1629 / None / (13.0-U6.2 and 13.3-U1 followups) Update security recommendations and fix two broken images
  content/Solutions/Optimizations/Security.md
  static/images/Hardware/Minis/MiniX+XL+OOBM.png
  static/images/Hardware/Minis/MiniXL+HardwareUpgradesGuide.png
  static/includes/COREFeatureSupport.md
Labels: Version Specific

#3261 PD-1503 / 25.04 / PD-1503 Create Plex App Tutorial
  content/TruenasApps/StableApps/PlexApp.md
  static/images/SCALE/Apps/AddPlexAppDatasets.png
  static/images/SCALE/Apps/InstallPlexAddStorageTemporaryDirectorySettings.png
  static/images/SCALE/Apps/InstallPlexAddStorageTmpfsDirectorySetting.png
  static/images/SCALE/Apps/InstallPlexConfig1.png
  static/images/SCALE/Apps/InstallPlexConfigAddDevice.png
  static/images/SCALE/Apps/InstallPlexResourcesConfiguration.png
  static/images/SCALE/Apps/InstallPlexScreen.png
  static/images/SCALE/Apps/InstallPlexStorageConfigDataACLandACE.png
  static/images/SCALE/Apps/InstallPlexStorageLogsTemporaryAndTranscodeTmpfsSettings.png
  static/images/SCALE/Apps/InstallPlexUserAndGroupConfig.png
  static/images/SCALE/Apps/PlexAppWebPortalSignInScreen.png
  static/images/SCALE/Apps/PlexDetailsScreen.png
  static/includes/apps/AppInstallWizardTemporaryAndTmpfsDirectories.md
  static/includes/apps/AppInstallWizardUserAndGroupConfig.md
  static/includes/apps/AppsStableBeforeYouBegin.md
  static/includes/apps/InstallAppsStorageConfig.md
Labels: Re-Review, backport-24.10

#3215 PD-1611 / 13.0 / 13.0-U6.3 relnotes
  content/CORETutorials/JailsPluginsVMs/Jails/AccessingJailsUsingSSH.md
  content/CORETutorials/JailsPluginsVMs/Jails/CreatingJails.md
  content/CORETutorials/JailsPluginsVMs/Jails/InstallingJailSoftware.md
  content/CORETutorials/JailsPluginsVMs/Jails/ManagingJails.md
  content/CORETutorials/JailsPluginsVMs/Jails/SettingUpJailStorage.md
  content/CORETutorials/JailsPluginsVMs/Jails/_index.md
  content/CORETutorials/JailsPluginsVMs/Plugins/CreatingCustomPlugin.md
  content/CORETutorials/JailsPluginsVMs/Plugins/ManagingPlugins.md
  content/CORETutorials/JailsPluginsVMs/Plugins/MinIOPlugin.md
  content/CORETutorials/JailsPluginsVMs/Plugins/_index.md
  content/CORETutorials/JailsPluginsVMs/UpdateJailsPlugins.md
  content/CORETutorials/JailsPluginsVMs/VirtualMachines/CreatingBasicVM.md
  content/CORETutorials/JailsPluginsVMs/VirtualMachines/SettingUpNPIV.md
  content/CORETutorials/JailsPluginsVMs/VirtualMachines/_index.md
  content/CORETutorials/JailsPluginsVMs/_index.md
  content/GettingStarted/Applications.md
  content/GettingStarted/COREReleaseNotes.md
  content/GettingStarted/DataBackups.md
  content/GettingStarted/Deprecations.md
  content/UIReference/JailsPluginsVMs/Jails/JailsScreens.md
  content/UIReference/JailsPluginsVMs/Jails/_index.md
  content/UIReference/JailsPluginsVMs/Plugins/PluginsScreens.md
  content/UIReference/JailsPluginsVMs/Plugins/_index.md
  content/UIReference/JailsPluginsVMs/VirtualMachines/VirtualMachines.md
  content/UIReference/JailsPluginsVMs/VirtualMachines/_index.md
  content/UIReference/JailsPluginsVMs/_index.md
  static/includes/COREFeatureSupport.md
  words-to-ignore.txt
Labels: Version Specific, Technical Writer Review (MJ)

#3220 PD-1611: 13.3-U1 Release notes
  content/CORETutorials/JailsPluginsVMs/Jails/AccessingJailsUsingSSH.md
  content/CORETutorials/JailsPluginsVMs/Jails/InstallingJailSoftware.md
  content/CORETutorials/JailsPluginsVMs/Jails/ManagingJails.md
  content/CORETutorials/JailsPluginsVMs/Jails/SettingUpJailStorage.md
  content/CORETutorials/JailsPluginsVMs/Jails/_index.md
  content/CORETutorials/JailsPluginsVMs/Plugins/CreatingCustomPlugin.md
  content/CORETutorials/JailsPluginsVMs/Plugins/MinIOPlugin.md
  content/CORETutorials/JailsPluginsVMs/Plugins/PlexPlugin.md
  content/CORETutorials/JailsPluginsVMs/Plugins/_index.md
  content/CORETutorials/JailsPluginsVMs/UpdateJailsPlugins.md
  content/CORETutorials/JailsPluginsVMs/VirtualMachines/SettingUpNPIV.md
  content/CORETutorials/JailsPluginsVMs/VirtualMachines/_index.md
  content/CORETutorials/JailsPluginsVMs/_index.md
  content/GettingStarted/Applications.md
  content/GettingStarted/COREReleaseNotes.md
  content/GettingStarted/DataBackups.md
  content/GettingStarted/Deprecations.md
  content/UIReference/JailsPluginsVMs/JailsScreens.md
  content/UIReference/JailsPluginsVMs/PluginsScreens.md
  content/UIReference/JailsPluginsVMs/VirtualMachines.md
  content/UIReference/JailsPluginsVMs/_index.md
  data/properties/core-downloads.yaml
  data/properties/core-releases.yaml
  static/includes/COREFeatureSupport.md
  static/includes/COREUpgradePaths.md
  words-to-ignore.txt
Labels: Version Specific, Technical Writer Review (MJ)

#3221 PD-1611 / 25.04 / master branch followups
  content/Solutions/Optimizations/Security.md
  data/properties/core-downloads.yaml
  data/properties/core-releases.yaml
  static/images/Hardware/Minis/MiniX+XL+OOBM.png
  static/images/Hardware/Minis/MiniXL+HardwareUpgradesGuide.png
  static/includes/COREFeatureSupport.md
  static/includes/COREUpgradePaths.md
Labels: Version Specific, Technical Writer Review (MJ)

#3274 PD-1512 / 25.04 / PD-1512-update-feedback-screen-for-non-enterprise-systems (by linzi-ix)
  static/images/SCALE/Dashboard/FeedbackWindow.png
  static/includes/FeedbackWindow.md
Labels: Technical Writer Review (MJ)

#3271 PD-1583 / 25.04 / Pd 1583 address ix apps and ix applications datasets
  content/SCALE/SCALEUIReference/Datasets/_index.md
  content/TruenasApps/EnterpriseApps/_index.md
  content/TruenasApps/_index.md
  static/includes/CreateDatasetSCALE.md
  static/includes/apps/AppsBestPractices.md
  static/includes/apps/AppsDatasets.md
  static/includes/apps/AppsFileSharing.md
  static/includes/apps/AppsInstallWizardSettings.md
  static/includes/apps/AppsPool.md
  static/includes/apps/AppsPoolOrDataset.md
  static/includes/apps/AppsSMBErrorWarning.md
Labels: Technical Writer Review (MJ), Re-Review, backport-24.10

#3278 Update 13.3 ReleaseNotes - quick resync with general announcement
  content/GettingStarted/COREReleaseNotes.md
Labels: Version Specific

#3277 Update 13.0-U6.3 ReleaseNotes.md - Quick resync with general announcement
  content/GettingStarted/COREReleaseNotes.md
Labels: Version Specific

#3279 Revert "PD-1503 / 24.10 / PD-1503 Create Plex App Tutorial (by micjoh…
  content/TruenasApps/StableApps/PlexApp.md
  static/images/SCALE/Apps/AddPlexAppDatasets.png
  static/images/SCALE/Apps/InstallPlexAddStorageTemporaryDirectorySettings.png
  static/images/SCALE/Apps/InstallPlexAddStorageTmpfsDirectorySetting.png
  static/images/SCALE/Apps/InstallPlexConfig1.png
  static/images/SCALE/Apps/InstallPlexConfigAddDevice.png
  static/images/SCALE/Apps/InstallPlexResourcesConfiguration.png
  static/images/SCALE/Apps/InstallPlexScreen.png
  static/images/SCALE/Apps/InstallPlexStorageConfigDataACLandACE.png
  static/images/SCALE/Apps/InstallPlexStorageLogsTemporaryAndTranscodeTmpfsSettings.png
  static/images/SCALE/Apps/InstallPlexUserAndGroupConfig.png
  static/images/SCALE/Apps/PlexAppWebPortalSignInScreen.png
  static/images/SCALE/Apps/PlexDetailsScreen.png
  static/includes/apps/AppInstallWizardTemporaryAndTmpfsDirectories.md
Labels: Version Specific

#3284 PD-1521 / 13.0 / Update Certificates.md
  content/UIReference/System/Certificates.md
Labels: Technical Writer Review (TR), backport-13.3

#3282 Update COREReleaseNotes.md
  content/GettingStarted/COREReleaseNotes.md
Labels: Technical Writer Review (TR)

#3281 Update PlexApp.md
  content/TruenasApps/StableApps/PlexApp.md
Labels: Technical Writer Review (TR)

#3291 SED known issue for 24.10
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Technical Writer Review (MJ)

#3253 PD-1572 / 25.04 / Pd 1572 review ipmi configuration tutorial
  content/SCALE/SCALETutorials/Network/SettingUpIPMI.md
  content/SCALE/SCALEUIReference/Network/IPMIScreens.md
  static/includes/IPMICompatibility.md
Labels: Technical Writer Review (MJ), Re-Review, backport-24.10

#3283 Update AppsDatasets.md
  static/includes/apps/AppsDatasets.md
Labels: Technical Writer Review (MJ), Re-Review

#3287 Update SMB mount on Apple expand with link to Apple tuning doc
  content/SCALE/SCALETutorials/Shares/SMB/_index.md
Labels: Technical Writer Review (MJ)

#3293 PD-1572 / 24.10 / Pd 1572 review ipmi configuration tutorial (by DjP-iX)
  content/SCALETutorials/Network/SettingUpIPMI.md
  content/SCALEUIReference/Network/IPMIScreens.md
  static/includes/IPMICompatibility.md
Labels: Technical Writer Review (MJ)

#3285 PD-1521 / 13.3 / Update Certificates.md (by linzi-ix)
  content/UIReference/System/Certificates.md
Labels: Technical Writer Review (MJ)

#3294 PD-1569 / 25.04 / Pd 1569 re investigate and refresh disk replace procedures scale
  content/SCALE/SCALETutorials/Storage/Disks/ReplacingDisks.md
  static/images/SCALE/Storage/DevicesDiskDegraded.png
  static/images/SCALE/Storage/DevicesDiskDegradedHotSpare.png
  static/images/SCALE/Storage/ReplacingDiskDialog.png
  static/includes/RestoreHotSpare.md
Labels: Technical Writer Review (TR), backport-24.10

#3286 PD-1569 / 13.3 / Pd 1569 re investigate and refresh disk replace procedures
  content/CORETutorials/Storage/Disks/DiskReplace.md
  content/CORETutorials/Storage/Pools/_index.md
  static/images/CORE/Storage/AddVdevsScreenHotSpare.png
  static/images/CORE/Storage/StoragePoolsStatusHotSpareActive.png
Labels: Technical Writer Review (MJ), Re-Review, backport-13.0

#3302 fixed/removed broken links
  content/Solutions/Integrations/Veeam.md
  content/TruenasApps/CommunityApps/dockge.md
Labels: Technical Writer Review (MJ)

#3301 PD-1455 / 24.10 / PD-1455-backport-typo-fix
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (MJ), backport-24.04, backport-23.10, backport-13.3, backport-13.0, backport-3.0

#3304 Clean up pagefind call and obsolete docsbot script (13.3)
  layouts/partials/menu.html
  layouts/partials/search-form.html
Labels: Version Specific, Technical Writer Review (MJ)

#3305 Pagefind docsbot code cleanup 24.10
  layouts/partials/menu-filetree.html
  layouts/partials/search-form.html
Labels: Version Specific, Technical Writer Review (MJ)

#3307 Clean up pagefind and docs bot code a bit (3.0)
  layouts/partials/menu.html
  layouts/partials/search-form.html
Labels: Version Specific, Technical Writer Review (MJ)

#3309 PD-1455 / 13.0 / PD-1455-backport-typo-fix (by DjP-iX)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (MJ)

#3311 PD-1455 / 23.10 / PD-1455-backport-typo-fix (by DjP-iX)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (MJ)

#3310 PD-1455 / 13.3 / PD-1455-backport-typo-fix (by DjP-iX)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (MJ)

#3312 PD-1455 / 24.04 / PD-1455-backport-typo-fix (by DjP-iX)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (MJ)

#3313 PD-1455 / 3.0 / PD-1455-backport-typo-fix (by DjP-iX)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (MJ)

#3314 Add missing titles to api html files
  static/api/core_rest_api.html
  static/api/scale_rest_api.html
  static/api/tc_rest_api.html
Labels: Technical Writer Review (TR)

#3315 Update scale_rest_api.html (23.10)
  static/api/scale_rest_api.html
Labels: Version Specific, Technical Writer Review (TR)

#3318 Update tc_rest_api.html
  static/api/tc_rest_api.html
Labels: Version Specific, Technical Writer Review (TR)

#3316 Add missing titles to api html files (13.0)
  static/api/core_rest_api.html
  static/api/scale_rest_api.html
  static/api/tc2api.html
Labels: Version Specific, Technical Writer Review (TR)

#3319 Update baseof.print.html (13.0)
  layouts/_default/baseof.print.html
Labels: Version Specific, Technical Writer Review (TR)

#3158 PD-1252 / 25.04 / Pd 1252 update/replace smb home shares content
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBHomeShare.md
  content/SCALE/SCALETutorials/Shares/SMB/_index.md
  content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md
  static/images/SCALE/Shares/AddPrivateSMBShare.png
  static/images/SCALE/Shares/AddPrivateSMBShareAdvancedOptions.png
  static/images/SCALE/Shares/AddSMBAdvancedOtherSettings.png
  static/images/SCALE/Shares/SetACLPresetForPrivateDataset.png
  static/images/SCALE/Shares/SetUserHomeDirectoryToPrivate.png
  static/includes/ChangeBuiltin-UserACL.md
  static/includes/SMBPurposePresets.md
Labels: Technical Writer Review (DP), Re-Review, backport-24.10, backport-24.04
