Repository truenas/documentation, pull requests merged in 2024-12, with the labels that each got.

#3308 PD-1555 / 25.04 / PD-1555 Add Version, Stopping Apps, and Encrypted Apps Pool Information
  content/TruenasApps/CommunityApps/_index.md
  content/TruenasApps/StableApps/_index.md
  content/TruenasApps/_index.md
  static/includes/apps/AppsBestPractices.md
  static/includes/apps/AppsDatasets.md
  static/includes/apps/AppsDirectoryService.md
  static/includes/apps/AppsDockerCompose.md
  static/includes/apps/AppsPool.md
Labels: Technical Writer Review (DP)

#3280 PD-1555 / 25.04 / PD-1555 Rename App Snippets and Updates
  content/TruenasApps/CommunityApps/Chia.md
  content/TruenasApps/CommunityApps/Immich.md
  content/TruenasApps/CommunityApps/_index.md
  content/TruenasApps/CommunityApps/ddns-updater.md
  content/TruenasApps/CommunityApps/jellyfin.md
  content/TruenasApps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md
  content/TruenasApps/EnterpriseApps/MinIO/ConfigMinioEnterpriseSNMD.md
  content/TruenasApps/EnterpriseApps/MinIO/_index.md
  content/TruenasApps/EnterpriseApps/Syncthing.md
  content/TruenasApps/EnterpriseApps/_index.md
  content/TruenasApps/StableApps/InstallNetdataApp.md
  content/TruenasApps/StableApps/InstallNextCloudMedia.md
  content/TruenasApps/StableApps/InstallWGEasyApp.md
  content/TruenasApps/StableApps/MinIOApp/MinIOClustering.md
  content/TruenasApps/StableApps/MinIOApp/_index.md
  content/TruenasApps/StableApps/PlexApp.md
  content/TruenasApps/StableApps/PrometheusApp.md
  content/TruenasApps/StableApps/SyncthingStable.md
  content/TruenasApps/StableApps/_index.md
  content/TruenasApps/_index.md
  static/includes/apps/AddingAppCertificate.md
  static/includes/apps/AppUserAndGroupConfig.md
  static/includes/apps/BeforeYouBeginAddAppCertificate.md
  static/includes/apps/BeforeYouBeginAddNewAppUser.md
  static/includes/apps/BeforeYouBeginEnterpriseApps.md
  static/includes/apps/BeforeYouBeginStableApps.md
  static/includes/apps/InstallWizardAdvancedDNSSettings.md
  static/includes/apps/InstallWizardAppNameAndVersion.md
  static/includes/apps/InstallWizardCertificateSettings.md
  static/includes/apps/InstallWizardDefaultPorts.md
  static/includes/apps/InstallWizardEnvironVariablesSettings.md
  static/includes/apps/InstallWizardGPUPassthrough.md
  static/includes/apps/InstallWizardHostNetworkSettings.md
  static/includes/apps/InstallWizardResourceConfig.md
  static/includes/apps/InstallWizardSettingsOverview.md
  static/includes/apps/InstallWizardStorageACLConfig.md
  static/includes/apps/InstallWizardStorageSMBOption.md
  static/includes/apps/InstallWizardStorageTemporaryAndTmpfs.md
  static/includes/apps/InstallWizardTimezoneSetting.md
  static/includes/apps/InstallWizardUserAndGroupConfig.md
  static/includes/apps/MultipleAppInstancesAndNaming.md
Labels: Technical Writer Review (TR), Re-Review

#3328 PD-1643 / 25.04 / PD-1643 SSH documentation has errors.
  content/SCALE/SCALETutorials/Credentials/AdminRoles.md
Labels: Technical Writer Review (MJ), backport-24.10

#3331 Add initial draft of a Remote Access solutions guide for TrueNAS 24.10
  content/Solutions/RemoteAccess.md
  words-to-ignore.txt
Labels: Technical Writer Review (MJ)

#3339 Brighten dark mode text a little to improve readability (master branch; backports needed)
  static/custom.css
Labels: Technical Writer Review (MJ)

#3349 PD-1656 / 24.04 / update dark mode text color (by Mrt134)
  static/custom.css
Labels: Technical Writer Review (MJ)

#3350 PD-1656 / 3.0 / update dark mode text color (by Mrt134)
  static/custom.css
Labels: Technical Writer Review (MJ)

#3326 PD-1626 / 25.04 / Pd 1626 nextcloud app tutorial improvements
  content/TruenasApps/StableApps/InstallNextCloudMedia.md
  content/TruenasApps/StableApps/PlexApp.md
  static/images/SCALE/Apps/NextcloudDetailsScreen.png
  static/includes/apps/BeforeYouBeginAddAppDatasets.md
  static/includes/apps/BeforeYouBeginAddNewAppUser.md
  static/includes/apps/BeforeYouBeginRunAsUser.md
  static/includes/apps/BeforeYouBeginStableApps.md
  static/includes/apps/InstallAppsStorageConfig.md
  static/includes/apps/InstallWizardStorageACLConfig.md
  static/includes/apps/LocateAndOpenInstallWizard.md
Labels: Technical Writer Review (TR)

#3351 Follow up to community suggestion (pr 3323)
  content/SCALE/SCALEUIReference/Credentials/Certificates/CAScreensSCALE.md
  content/SCALE/SCALEUIReference/Network/_index.md
Labels: Technical Writer Review (MJ)

#3356 Update Getting Support article with Community feature voting (13.0)
  content/CORETutorials/Getting Support.md
  static/images/Contribute/FeatureRequest.png
  static/images/Contribute/FeatureRequestVote.png
  static/images/Contribute/JiraSuggestionCreate.png
  static/images/Contribute/JiraSuggestionVote.jpg
  static/includes/CreateJiraSuggestion.md
Labels: Version Specific, Technical Writer Review (MJ)

#3358 Simple image fix (22.12 archive)
  content/SCALETutorials/Network/ManageNetworkSettingsHA.md
  static/images/SCALE/22.12/EditInterfaceFailoverSettingsHA.png
Labels: Version Specific, Technical Writer Review (LM)

#3337 PD-1478 / 25.04 / Pd 1478 update netdata tutorial
  content/TruenasApps/StableApps/InstallNetdataApp.md
  static/images/SCALE/Apps/InstallNetdataScreen.png
  static/images/SCALE/Apps/InstallNetdataStorageConfigACLandACE.png
  static/images/SCALE/Apps/InstallNetdataStorageEnableHostPath.png
  static/images/SCALE/Apps/NetdataAppDetailsScreen.png
  static/images/SCALE/Apps/NetdataSignInScreen.png
  static/includes/apps/BeforeYouBeginAddAppDatasets.md
  static/includes/apps/BeforeYouBeginAddAppDatasetsProcedure.md
  static/includes/apps/BeforeYouBeginRunAsUser.md
  static/includes/apps/BeforeYouBeginStableApps.md
Labels: Technical Writer Review (LM)

#3354 PD-1586 / 25.04 / Pd 1586 25 04 primary features upgrade notes writeup
  content/SCALE/GettingStarted/Migrate/MigrateCOREHAtoSCALEHA.md
  content/SCALE/GettingStarted/Migrate/MigratingFromCORE.md
  content/SCALE/GettingStarted/Migrate/_index.md
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
  content/TrueNASUpgrades/_index.md
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  static/includes/25.04FeatureList.md
  static/includes/MigrateCOREtoSCALE24_04.md
  static/includes/RESTAPIDeprecationNotice.md
  static/includes/SCALEUpgradePaths.md
Labels: Technical Writer Review (MJ), Re-Review

#3362 PD-1560 / 25.04 / Update SMARTTestsSCALE.md
  content/SCALE/SCALETutorials/DataProtection/SMARTTestsSCALE.md
Labels: Technical Writer Review (MJ), Re-Review

#3365 PD-1655 / 25.04 / Pd 1655 polish pass on apps index article
  content/TruenasApps/_index.md
  static/images/SCALE/Apps/CollaboraInfoScreen.png
  static/includes/apps/AppsDatasets.md
  static/includes/apps/AppsPool.md
  static/includes/apps/AppsVMsNoHTTPS.md
Labels: Technical Writer Review (MJ)

#3367 13.0-U6.4 relnotes
  content/GettingStarted/COREReleaseNotes.md
Labels: Version Specific

#3368 13.0-U6.4 release notes followup (master)
  data/properties/core-downloads.yaml
  data/properties/core-releases.yaml
  static/includes/COREUpgradePaths.md
  static/includes/SCALEUpgradePaths.md
Labels: Version Specific

#3335 PD-1634 / 25.04 / Pd 1634 24 10 1 docs follow up
  content/SCALE/SCALETutorials/SystemSettings/Advanced/ManageGPUSCALE.md
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  static/includes/25.04FeatureList.md
  static/includes/SCALEUpgradePaths.md
Labels: Version Specific

#3344 PD-1654 / 24.04 / Pd 1654 document cloud sync filename encryption known issue 24.04
  .github/CODEOWNERS
  content/GettingStarted/SCALEReleaseNotes.md
  content/SCALETutorials/DataProtection/CloudSyncTasks/_index.md
  content/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  static/includes/FilenameEncryption.md
Labels: Technical Writer Review (LM), Re-Review

#3345 PD-1654 / 24.10 / Pd 1654 document cloud sync filename encryption known issue 24.10
  content/SCALETutorials/DataProtection/CloudSyncTasks/_index.md
  content/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  static/includes/FilenameEncryption.md
Labels: Technical Writer Review (LM), Re-Review

#3330 PD-1643 / 24.10 / PD-1643 SSH documentation has errors. (by tonyriv3)
  content/SCALETutorials/Credentials/AdminRoles.md
Labels: Technical Writer Review (MJ)

#3374 Add additional 24.10.1 note about change to CPU widgets
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific, Technical Writer Review (TR)

#3366 Reorganize ReplacingDisks.md to avoid confusion
  content/SCALETutorials/Storage/Disks/ReplacingDisks.md
Labels: Technical Writer Review (LM)

#3369 Update ReplacingDisks.md
  content/SCALE/SCALETutorials/Storage/Disks/ReplacingDisks.md
Labels: Review (TM)

#3343 PD-1654 / 25.04 / Pd 1654 document cloud sync filename encryption known issue
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/_index.md
  content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  static/includes/FilenameEncryption.md
Labels: Review (TM), Re-Review

#3380 Elevate two changelog items to 24.10.1 release notes
  content/GettingStarted/SCALEReleaseNotes.md
  words-to-ignore.txt
Labels: Version Specific, Re-Review

#3373 PD-1624 / 13.0 / changes made
  content/CORETutorials/SystemConfiguration/SettingtheSystemDataset.md
Labels: Technical Writer Review (TR)

#3382 PD-1624 / 25.04 / Pd 1624 change system dataset needs additional info
  content/CORETutorials/SystemConfiguration/SettingtheSystemDataset.md
Labels: Technical Writer Review (LM)

#3384 PD-1620 / 25.04 / Pd 1620 elastic search
  content/TruenasApps/StableApps/ElasticSearch.md
  static/images/SCALE/Apps/ElasticSearchDetailsScreen.png
  static/images/SCALE/Apps/ElasticSearchWebPortal.png
  static/images/SCALE/Apps/InstallAppLabels.png
  static/images/SCALE/Apps/InstallElasticSearchResourcesConfig.png
  static/images/SCALE/Apps/InstallElasticSearchScreen.png
  static/images/SCALE/Apps/InstallElasticSearchStorageDataACLandACE.png
  static/includes/apps/InstallWizardEnvironVariablesSettings.md
  static/includes/apps/InstallWizardHostNetworkSettings.md
  static/includes/apps/InstallWizardLabelsConfiguration.md
  static/includes/apps/InstallWizardResourceConfig.md
  static/includes/apps/InstallWizardStorageACLConfig.md
Labels: Technical Writer Review (MJ), Re-Review

#3363 PD-1619 / 25.04 / Pd 1619 Update Diskover Data Tutorial with Label Configuration Snippet
  content/TruenasApps/StableApps/DiskoverDataApp.md
  static/images/SCALE/Apps/DiskoverAppDetailsScreen.png
  static/images/SCALE/Apps/DiskoverAppRunning.png
  static/images/SCALE/Apps/DiskoverSignInScreen.png
  static/images/SCALE/Apps/InstallDiskOverResourcesConfig.png
  static/images/SCALE/Apps/InstallDiskoverLabelConfig.png
  static/images/SCALE/Apps/InstallDiskoverScreen.png
  static/images/SCALE/Apps/InstallDiskoverStorageConfigACLandACESettings.png
  static/includes/apps/InstallWizardLabelsConfiguration.md
Labels: Technical Writer Review (LM), Re-Review

#3355 PD-1621 / 25.04 / PD-1621 New Emby Tutorial and Screenshots
  content/TruenasApps/StableApps/EmbyApp.md
  static/images/SCALE/Apps/EmbyAppRunning.png
  static/images/SCALE/Apps/EmbyCreateNewUserAcctScreen.png
  static/images/SCALE/Apps/EmbyDetailsScreen.png
  static/images/SCALE/Apps/EmbySetupMediaLibrariesScreen.png
  static/images/SCALE/Apps/EmbySignInScreen.png
  static/images/SCALE/Apps/InstallEmbyLabelsConfig.png
  static/images/SCALE/Apps/InstallEmbyResourcesConfig.png
  static/images/SCALE/Apps/InstallEmbyScreen.png
  static/images/SCALE/Apps/InstallEmbyStorageConfigHostPathACLandACESettings.png
  static/includes/apps/InstallWizardLabelsConfiguration.md
Labels: Technical Writer Review (LM), Re-Review

#3124 PD-1333 / 25.04 / Pd 1333 stig response for security site
  content/Solutions/Optimizations/STIGCompliance.md
Labels: Technical Writer Review (TR)

#3393 API docfix 24.04
  static/api/core_rest_api.html
  static/api/core_websocket_api.html
  static/api/scale_rest_api.html
Labels: Version Specific, Technical Writer Review (TR)

#3395 Fix up aliases on 23.10 apps index
  content/SCALETutorials/Apps/_index.md
Labels: Version Specific, Technical Writer Review (TR)

#3394 (master) Additional site audit cleanups
  content/SCALE/GettingStarted/Migrate/MigrateCOREHAtoSCALEHA.md
  content/TruenasApps/Sandboxes.md
  content/TruenasApps/StableApps/InstallNetdataApp.md
Labels: Technical Writer Review (TR)
