Repository truenas/documentation, pull requests merged in 2024-08, with the labels that each got.

#2948 Pd 1287 link to true nas core 13 0 release train release notes from https www truenas com docs core gettingstarted corereleasenotes
  content/CORE/GettingStarted/COREReleaseNotes.md
Labels: Technical Writer Review (MJ)

#2945 Pd 1294 (backport 24.04) scrub all mentions of suggestion tickets from the docs hub
  content/GettingStarted/Getting Support/FileIssueSCALE.md
  content/SCALEUIReference/TopToolbar/_index.md
  static/images/SCALE/Dashboard/FeedbackWindow.png
  static/images/SCALE/Dashboard/FeedbackWindowEnterpriseBugReport.png
  static/includes/CreateFeatureRequest.md
  static/includes/FeedbackWindow.md
  static/includes/FileIssueTicketSCALE.md
  static/includes/TopToolbar.md
Labels: Technical Writer Review (MJ)

#2954 PD-1360: update NUT known issue (24.04)
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific

#2941 Pd 1348 23.10 app url reduction and redirects
  content/GettingStarted/Configure/ClusterPreparation.md
  content/GettingStarted/SCALEReleaseNotes.md
  content/SCALETutorials/Apps/AppsAdvancedSettings.md
  content/SCALETutorials/Apps/CommunityApps/AddStorjNode.md
  content/SCALETutorials/Apps/CommunityApps/Chia.md
  content/SCALETutorials/Apps/CommunityApps/Collabora.md
  content/SCALETutorials/Apps/CommunityApps/InstallNetdataApp.md
  content/SCALETutorials/Apps/CommunityApps/InstallNextCloudMedia.md
  content/SCALETutorials/Apps/CommunityApps/InstallPiHoleApp.md
  content/SCALETutorials/Apps/CommunityApps/InstallWGEasyApp.md
  content/SCALETutorials/Apps/CommunityApps/MinIOApp/MinIOClustering.md
  content/SCALETutorials/Apps/CommunityApps/MinIOApp/MinioManualUpdate.md
  content/SCALETutorials/Apps/CommunityApps/MinIOApp/_index.md
  content/SCALETutorials/Apps/CommunityApps/PrometheusApp.md
  content/SCALETutorials/Apps/CommunityApps/Rsyncd.md
  content/SCALETutorials/Apps/CommunityApps/SyncthingCharts.md
  content/SCALETutorials/Apps/CommunityApps/TFTP-HPAApp.md
  content/SCALETutorials/Apps/CommunityApps/WebDAV.md
  content/SCALETutorials/Apps/CommunityApps/_index.md
  content/SCALETutorials/Apps/CommunityApps/ddns-updater.md
  content/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md
  content/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseSNMD.md
  content/SCALETutorials/Apps/EnterpriseApps/MinIO/_index.md
  content/SCALETutorials/Apps/EnterpriseApps/Syncthing.md
  content/SCALETutorials/Apps/EnterpriseApps/_index.md
  content/SCALETutorials/Apps/UsingCatalogs.md
  content/SCALETutorials/Apps/UsingCustomApp.md
  content/SCALETutorials/Apps/_index.md
  content/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALETutorials/DataProtection/RsyncTasksSCALE.md
  content/SCALEUIReference/Apps/InstallCustomAppScreens.md
  content/SCALEUIReference/Apps/_index.md
  layouts/404_apps.html
  static/includes/AddAppCertificate.md
  static/includes/AddEnterpriseTrain.md
  static/includes/AddMinIOCertificate.md
  static/includes/AddMinioEnterpriseTrain.md
  static/includes/AppsUnversioned.md
  static/includes/CommunityAppsLegacy.md
  static/includes/MinIODNSAndResourceLimits.md
  static/includes/MinIODatasetRequirements.md
  static/includes/MinIOEnableDistributedModeInfo.md
  static/includes/MinIOEnterpriseFirstSteps.md
  static/includes/MinIOEnterpriseStorageConfig.md
  static/includes/MinIOInstallAppNameWorkloadConfigSteps.md
  static/includes/MinIOInstallArgAndEnvironVarSteps.md
  static/includes/MinIOPortsAndLogSearch.md
  static/includes/MinIOStorageDataVolume.md
  static/includes/MinIoEnterpriseConfig1.md
  static/includes/MinIoEnterpriseConfig2.md
  static/includes/SCALEEnterpriseApps.md
  static/includes/SyncthingArticleIntro.md
  static/includes/SyncthingFirstSteps.md
  static/includes/SyncthingOverview.md
  static/includes/SyncthingWebPortalInfo.md
Labels: Version Specific

#2961 PD-1329-archive-tc-2-3-docs-23.10
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (MJ)

#2962 Pd 1329 archive tc 2 3 docs 24.04
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (MJ)

#2963 Pd-1329-archive-tc-2-3-docs-3.0
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (MJ)

#2964 Pd 1329 archive tc 2 3 docs 13.3
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (MJ)

#2965 Pd-1329-archive-tc-2-3-docs-13.0
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (MJ)

#2959 PD-1263-clarify-smb-share-purpose-descriptions-in-both-ui-ref-and-tutorial-and-review-the-settings-preset-to-each-purpose
  content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md
Labels: Technical Writer Review (MJ)

#2967 Correct frontmatter for extensioncalculator
  content/References/ExtensionCalculator.md
Labels: Technical Writer Review (MJ)

#2957 PD-1357: 13.3-RELEASE docs updates and changelog (13.3 branch)
  content/CORETutorials/Getting Support.md
  content/CORETutorials/Network/Interfaces/SettingStaticIP.md
  content/CORETutorials/Sharing/iSCSI/SettingUpFibreChannel.md
  content/CORETutorials/Storage/Pools/StorageEncryption.md
  content/CORETutorials/SystemConfiguration/ConfiguringFailover.md
  content/CORETutorials/SystemConfiguration/ConfiguringKMIP.md
  content/CORETutorials/UpdatingTrueNAS/UpdatingENTERPRISE.md
  content/CORETutorials/UpdatingTrueNAS/_index.md
  content/GettingStarted/COREReleaseNotes.md
  content/UIReference/Sharing/iSCSI/FibreChannel.md
  content/UIReference/System/Failover.md
  content/UIReference/System/KMIP.md
  content/UIReference/System/Support.md
  content/UIReference/System/ViewEnclosure.md
  data/properties/core-releases.yaml
  layouts/partials/page-header.html
  static/includes/13.3Overview.md
  static/includes/COREUpgradePaths.md
  static/includes/S3Deprecation.md
  static/includes/iSCSIRef.md
  words-to-ignore.txt
Labels: Version Specific, Technical Writer Review (MJ)

#2942 Pd 1289 tc 3 0 2 docs
  content/AdminGuide/Users.md
  content/TCGettingStarted/InterfaceOverview.md
  content/TCGettingStarted/TCReleaseNotes.md
  content/UserGuide/Alerts/AlertManage.md
  content/UserGuide/Clusters.md
  content/UserGuide/SystemManagement/MultiSystems.md
  content/UserGuide/_index.md
  data/properties/tc-releases.yaml
  static/images/TrueCommand/Alerts/AlertServiceSMTPEmailScreen.png
  static/includes/TCPermissionsHierarchy.md
  words-to-ignore.txt
Labels: Version Specific

#2943 Pd 1289 follow up (to be merged after TC 3.0.2 release)
  content/Solutions/Integrations/SMBClustering.md
  content/Solutions/Integrations/_index.md
  content/TrueCommand/TCGettingStarted/InterfaceOverview.md
  content/TrueCommand/UserGuide/Clusters.md
  content/TrueCommand/UserGuide/_index.md
  data/properties/core-releases.yaml
  data/properties/tc-releases.yaml
  static/includes/NUTsupport.md
  words-to-ignore.txt
Labels: Version Specific

#2978 Fix instructions for rsyncd authentication
  content/SCALE/SCALETutorials/Apps/CommunityApps/Rsyncd.md
Labels: Community, Review (TM)

#2971 PD-1251-clarify-shares-and-app-dataset-separation
  content/SCALE/SCALETutorials/Apps/_index.md
  content/SCALE/SCALETutorials/Shares/SMB/_index.md
  static/includes/AppsSMBErrorWarning.md
Labels: Review (TM)

#2975 Pd 1127 24.04 expand tutorials for deploying custom apps directly from docker hub or other primary pull points
  content/SCALETutorials/Apps/UsingCustomApp.md
  content/SCALEUIReference/Apps/InstallCustomAppScreens.md
Labels: Version Specific, Review (TM)

#2947 Pd 1349 24.04 app url reduction and redirects
  content/SCALETutorials/Apps/AppSecurity/CloudflareTunnel.md
  content/SCALETutorials/Apps/AppSecurity/_index.md
  content/SCALETutorials/Apps/CommunityApps/AddStorjNode.md
  content/SCALETutorials/Apps/CommunityApps/Chia.md
  content/SCALETutorials/Apps/CommunityApps/Collabora.md
  content/SCALETutorials/Apps/CommunityApps/Immich.md
  content/SCALETutorials/Apps/CommunityApps/InstallNetdataApp.md
  content/SCALETutorials/Apps/CommunityApps/InstallNextCloudMedia.md
  content/SCALETutorials/Apps/CommunityApps/InstallPiHoleApp.md
  content/SCALETutorials/Apps/CommunityApps/InstallWGEasyApp.md
  content/SCALETutorials/Apps/CommunityApps/MinIOApp/MinIOClustering.md
  content/SCALETutorials/Apps/CommunityApps/MinIOApp/MinioManualUpdate.md
  content/SCALETutorials/Apps/CommunityApps/MinIOApp/_index.md
  content/SCALETutorials/Apps/CommunityApps/PrometheusApp.md
  content/SCALETutorials/Apps/CommunityApps/Rsyncd.md
  content/SCALETutorials/Apps/CommunityApps/SyncthingCharts.md
  content/SCALETutorials/Apps/CommunityApps/TFTP-HPAApp.md
  content/SCALETutorials/Apps/CommunityApps/WebDAV.md
  content/SCALETutorials/Apps/CommunityApps/_index.md
  content/SCALETutorials/Apps/CommunityApps/ddns-updater.md
  content/SCALETutorials/Apps/CommunityApps/jellyfin.md
  content/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md
  content/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseSNMD.md
  content/SCALETutorials/Apps/EnterpriseApps/MinIO/_index.md
  content/SCALETutorials/Apps/EnterpriseApps/Syncthing.md
  content/SCALETutorials/Apps/EnterpriseApps/_index.md
  content/SCALETutorials/Apps/UsingCatalogs.md
  content/SCALETutorials/Apps/UsingCustomApp.md
  content/SCALETutorials/Apps/_index.md
  content/SCALEUIReference/Apps/InstallCustomAppScreens.md
  content/SCALEUIReference/Apps/_index.md
  static/includes/AppsUnversioned.md
  static/includes/CommunityAppsLegacy.md
Labels: Review (TM)

#2974 Update UpdateSCALE.md (24.04)
  content/SCALETutorials/SystemSettings/UpdateSCALE.md
Labels: Version Specific

#2966 Pd 1290 update admin user content for 24.10
  content/SCALE/GettingStarted/Configure/FirstTimeLogin.md
  content/SCALE/GettingStarted/Install/ConsoleSetupMenuScale.md
  content/SCALE/GettingStarted/Migrate/MigratingFromCORE.md
  content/SCALE/SCALETutorials/Credentials/AdminRoles.md
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
  static/images/SCALE/Credentials/AddAuxiliaryGroupAdminUserSettings.png
  static/images/SCALE/Credentials/AddUserHomeDirAuthSCALE.png
  static/images/SCALE/Install/SCALEInstallPartitionScreen.png
  static/images/SCALE/Install/SCALEInstallerAuthenticationMethod.png
  static/images/SCALE/Install/SCALEInstallerConsoleSetupAdminAccount.png
  static/includes/AddAdminUserAccount.md
  static/includes/RootLoginWarnSCALE.md
  static/includes/RootToAdminUserAccount.md
  static/includes/SCALEInstallerProcedure.md
Labels: Review (TM)

#2968 13.3 release followup (master branch, don't merge until 13.3-RELEASE is complete)
  content/_index.md
  data/properties/core-downloads.yaml
  data/properties/core-releases.yaml
  layouts/shortcodes/section-cards.html
  static/includes/COREUpgradePaths.md
Labels: Technical Writer Review (MJ)

#2980 (24.04) upgrade path update
  static/includes/SCALEUpgradePaths.md
Labels: Version Specific

#2989 Clean up some cli refs from Engineering feedback (24.04)
  content/SCALETutorials/DataProtection/CloudSyncTasks/_index.md
  content/SCALETutorials/Storage/Disks/SLOGOverprovisionSCALE.md
Labels: Version Specific

#2977 PD-914 Create FreeIPA Article
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigFreeIPA.md
Labels: Technical Writer Review (DP)

#2973 Update MigratingFromCORE.md
  content/SCALE/GettingStarted/Migrate/MigratingFromCORE.md
Labels: Technical Writer Review (MJ)

#2981 Pd 1052 true cloud content for expanded true nas storj integration and snapshot management
  content/SCALE/GettingStarted/Configure/SetUpBackupScale.md
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
  content/SCALE/SCALETutorials/Credentials/BackupCredentials/AddCloudCredentials.md
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddStorjCloudSyncTask.md
  content/SCALE/SCALETutorials/DataProtection/TrueCloudTasks.md
  content/SCALE/SCALETutorials/DataProtection/_index.md
  content/SCALE/SCALEUIReference/Credentials/BackupCredentials/CloudCredentialScreens.md
  content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/TrueCloudBackupTasksScreen.md
  content/SCALE/SCALEUIReference/DataProtection/_index.md
  static/images/SCALE/DataProtection/AddTrueCloudTask.png
  static/images/SCALE/DataProtection/AddTrueCloudTaskAdvancedOptions.png
  static/images/SCALE/DataProtection/AddTrueCloudTaskBasicOptions.png
  static/images/SCALE/DataProtection/StorjCreateAccessDownloadedEncryptionPassphrase.png
  static/images/SCALE/DataProtection/StorjCreateAccessEncryptionDialog.png
  static/images/SCALE/DataProtection/StorjCreateAccessSelectBuckets.png
  static/images/SCALE/DataProtection/StorjCreateAccessSelectConfig.png
  static/images/SCALE/DataProtection/StorjCreateAccessSelectDuration.png
  static/images/SCALE/DataProtection/StorjCreateAccessSelectPermissions.png
  static/images/SCALE/DataProtection/StorjCreateAccessWindow.png
  static/images/SCALE/DataProtection/StorjS3ConfirmDetails.png
  static/images/SCALE/DataProtection/StorjS3CredentialsGenerated.png
  static/images/SCALE/DataProtection/TrueCloudBackupTasksScreenComplete.png
  static/images/SCALE/DataProtection/TrueCloudDeleteSnapshot.png
  static/images/SCALE/DataProtection/TrueCloudLogs.png
  static/images/SCALE/DataProtection/TrueCloudRestore.png
  static/images/SCALE/DataProtection/TrueCloudSnapshots.png
  static/images/SCALE/DataProtection/TrueCloudTaskSuccess.png
  static/includes/24.10FeatureList.md
  static/includes/CloudServiceProvidersSCALE.md
Labels: Technical Writer Review (MJ)

#2992 Pd 1373 update apps content w 24.10 recent changes
  content/SCALE/SCALETutorials/Apps/ChartApps/_index.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/_index.md
  content/SCALE/SCALETutorials/Apps/EnterpriseApps/_index.md
  content/SCALE/SCALETutorials/Apps/StableApps/AddStorjNode.md
  content/SCALE/SCALETutorials/Apps/StableApps/Collabora.md
  content/SCALE/SCALETutorials/Apps/StableApps/InstallNetdataApp.md
  content/SCALE/SCALETutorials/Apps/StableApps/InstallNextCloudMedia.md
  content/SCALE/SCALETutorials/Apps/StableApps/InstallPiHoleApp.md
  content/SCALE/SCALETutorials/Apps/StableApps/InstallWGEasyApp.md
  content/SCALE/SCALETutorials/Apps/StableApps/MinIOApp/MinIOClustering.md
  content/SCALE/SCALETutorials/Apps/StableApps/MinIOApp/MinioManualUpdate.md
  content/SCALE/SCALETutorials/Apps/StableApps/MinIOApp/_index.md
  content/SCALE/SCALETutorials/Apps/StableApps/PrometheusApp.md
  content/SCALE/SCALETutorials/Apps/StableApps/SyncthingCharts.md
  content/SCALE/SCALETutorials/Apps/StableApps/_index.md
  content/SCALE/SCALETutorials/Apps/UsingTrains.md
  content/SCALE/SCALETutorials/Apps/_index.md
  content/SCALE/SCALEUIReference/Apps/_index.md
  static/images/SCALE/Apps/ApplicationsEditCatalog.png
  static/images/SCALE/Apps/ApplicationsManageCatalogsScreen.png
  static/images/SCALE/Apps/AppsAddCatalogScreen.png
  static/images/SCALE/Apps/AppsCatalogExpandedViewWithOptions.png
  static/images/SCALE/Apps/AppsCatalogScreen.png
  static/images/SCALE/Apps/AppsEditCatalogAddEnterpriseTrain.png
  static/images/SCALE/Apps/AppsInstalledApplicationsViewCatalog.png
  static/images/SCALE/Apps/AppsManageContainerImages.png
  static/images/SCALE/Apps/AppsNotesWidget.png
  static/images/SCALE/Apps/AppsTrainSettingsScreen.png
  static/images/SCALE/Apps/AppsTruenasCatalogSummaryWindow.png
  static/images/SCALE/Apps/ChooseShellDetailsDialog.png
  static/images/SCALE/Apps/InstalledAppsBulkActions.png
  static/images/SCALE/Apps/InstalledAppsScreenContainersWidget.png
  static/images/SCALE/Apps/InstalledAppsWorkloadsWidget.png
  static/images/SCALE/Apps/KubernetesSettingsScreenBottom.png
  static/images/SCALE/Apps/KubernetesSettingsScreenTop.png
  static/images/SCALE/Apps/ManageCatalogsAddCatalogScreen.png
  static/images/SCALE/Apps/MinIOVolumeMountsDialog.png
  static/includes/AddEnterpriseTrain.md
  static/includes/AppsCustomApp.md
  static/includes/AppsDockerCompose.md
  static/includes/AppsFileSharing.md
  static/includes/AppsPoolOrDataset.md
  static/includes/AppsSMBErrorWarning.md
  static/includes/AppsVMsNoHTTPS.md
Labels: Technical Writer Review (TR)

#2993 PD-1363 Update Network Content
  content/SCALE/GettingStarted/Configure/UIConfigurationSCALE.md
  content/SCALE/SCALETutorials/Network/AddingGlobalConf.md
  content/SCALE/SCALETutorials/Network/Interfaces/ManagingInterfaces.md
  content/SCALE/SCALETutorials/Network/Interfaces/SettingUpBridge.md
  content/SCALE/SCALETutorials/Network/Interfaces/SettingUpLAGG.md
  content/SCALE/SCALETutorials/Network/Interfaces/SettingUpVLAN.md
  content/SCALE/SCALETutorials/Network/Interfaces/_index.md
  content/SCALE/SCALETutorials/Virtualization/AccessingNASFromVM.md
  content/SCALE/SCALEUIReference/Network/NetworkInterfaceScreens.md
  content/Solutions/Optimizations/Networking.md
  static/images/SCALE/Network/TestNetworkChanges.png
  static/includes/AddColumnOrganizer.md
  static/includes/BeforeYouBridge.md
  static/includes/NetworkBridgeSCALE.md
  static/includes/UsingConsoleSetupMenuSCALE.md
Labels: Technical Writer Review (TR)

#2999 Pd 1213 review audit logging content
  content/SCALE/SCALETutorials/Shares/MixedModeShares.md
  content/SCALE/SCALETutorials/Shares/SMB/_index.md
  content/SCALE/SCALETutorials/SystemSettings/AuditingSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/_index.md
  content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md
  static/images/SCALE/Shares/SMBServiceStatusAfterFirstShareAdded.png
  static/images/SCALE/Shares/SMBShareACLScreen.png
  static/images/SCALE/Shares/SMBShareOptions.png
  static/images/SCALE/Shares/SharingSMBOptions.png
  static/images/SCALE/Shares/SharingSMBScreen.png
  static/images/SCALE/Shares/SharingSMBServiceStatusScreen.png
  static/images/SCALE/Shares/SharingSMBServicesActionOptions.png
  static/images/SCALE/Shares/WindowsSMBShareWidget.png
  static/images/SCALE/Shares/WindowsSMBShareWidgetNoShares.png
  static/images/SCALE/SystemSettings/SystemSettingsAuditScreen.png
  static/includes/ConfigureSMBShareAuditingSCALE.md
Labels: Technical Writer Review (MJ)

#3004 Some beginning adjustments to TrueNAS naming
  content/Archive.md
  content/CORE/API/_index.md
  content/CORE/CORETutorials/DirectoryServices/LDAP.md
  content/CORE/CORETutorials/Sharing/SMB/_index.md
  content/CORE/CoreSecurityReports/SMB1Advisory.md
  content/CORE/UIReference/DirectoryServices/LDAPScreen.md
  content/Contributing/Documentation/ContentUpdate.md
  content/Contributing/IssueReporting/JiraIssueReporting.md
  content/Contributing/IssueReporting/_index.md
  content/Hardware/MSeries.md
  content/Hardware/Notices/WDSMR.md
  content/References/dRAIDprimer.md
  content/SCALE/GettingStarted/DataMigrationSyncthing.md
  content/SCALE/GettingStarted/Install/InstallingSCALE.md
  content/SCALE/GettingStarted/Migrate/SCALEZFSFlagRemoval.md
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
  content/SCALE/SCALETutorials/Apps/StableApps/MinIOApp/MinIOClustering.md
  content/SCALE/SCALETutorials/DataProtection/CreatingVMwareSnapshots.md
  content/SCALE/SCALETutorials/Shares/SMB/_index.md
  content/SCALE/SCALETutorials/TopToolbar/GlobalSearch.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/Idmap.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/LDAP.md
  content/Solutions/MigratingToTrueNAS.md
  content/Solutions/MinioCOREtoSCALE.md
  content/Solutions/Optimizations/Security.md
  content/TrueCommand/TCGettingStarted/_index.md
  content/TrueCommand/UserGuide/SystemInventory.md
  content/_archive/COREReleaseNotes/12.0/12.0Beta2.md
  content/_archive/COREReleaseNotes/12.0/12.0RC1.md
  content/_archive/COREReleaseNotes/12.0/12.0U2.md
  content/_archive/COREReleaseNotes/12.0/12.0U3.md
  content/_archive/TCReleaseNotes/2.0.md
  static/includes/13.3Overview.md
  static/includes/24.04FeatureList.md
  static/includes/COREDocsSections.md
  static/includes/COREFeatureSupport.md
  static/includes/COREMigratesList.md
  static/includes/CORETopMenu.md
  static/includes/CloudServiceProvidersCORE.md
  static/includes/ClusterDeprecated.md
  static/includes/CreateDebugCORE.md
  static/includes/MigratingDescriptions.md
  static/includes/NetworkPortIdentifications.md
  static/includes/ReplicationConfigNewSSHConnection.md
  static/includes/ReplicationCreateDatasetAndAdminHomeDirSteps.md
  static/includes/S3Deprecation.md
  static/includes/TNDataCollection.md
  static/includes/TNHardwareGuide.md
  static/includes/TNLifecycle.md
  static/includes/iSCSIRef.md
Labels: Technical Writer Review (MJ)

#3003 Pd 1051 update enclosure management content
  content/SCALE/SCALEUIReference/SystemSettings/EnclosureScreensSCALE.md
  static/images/SCALE/Dashboard/DashboardSystemInfoWidget.png
  static/images/SCALE/SystemSettings/ViewEnclosureDiskDetailsMini.png
  static/images/SCALE/SystemSettings/ViewEnclosureDiskInfo.png
  static/images/SCALE/SystemSettings/ViewEnclosureExpansionShelf.png
  static/images/SCALE/SystemSettings/ViewEnclosureExpansionShelfDiskInfo.png
  static/images/SCALE/SystemSettings/ViewEnclosureFront.png
  static/images/SCALE/SystemSettings/ViewEnclosureFrontViewR20.png
  static/images/SCALE/SystemSettings/ViewEnclosureM40HeadUnit.png
  static/images/SCALE/SystemSettings/ViewEnclosureR20SelectDisk.png
  static/images/SCALE/SystemSettings/ViewEnclosureRear.png
  static/images/SCALE/SystemSettings/ViewEnclosureRearViewR20.png
  static/images/SCALE/SystemSettings/ViewEnclosureScreenMini.png
Labels: Technical Writer Review (MJ)

#3002 Add 24.04.2 known issue with CORE migration
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific, Technical Writer Review (MJ)

#3005 Adjust Docs Hub home page to focus attention on TrueNAS docs
  layouts/shortcodes/section-cards.html
Labels: Technical Writer Review (MJ)

#3015 (24.04 branch) Replace SCALE Nightly version text to 24.10 (temporary)
  layouts/partials/docs-nav.html
Labels: Version Specific, Technical Writer Review (TR)

#3014 (13.3 branch) Replace SCALE Nightly version text to 24.10 (temporary)
  layouts/partials/docs-nav.html
Labels: Version Specific, Technical Writer Review (TR)

#3013 (13.0 branch) Replace SCALE Nightly version text to 24.10 (temporary)
  layouts/partials/docs-nav.html
Labels: Version Specific, Technical Writer Review (TR)

#3012 (23.10 branch) Replace SCALE Nightly version text to 24.10 (temporary)
  layouts/partials/docs-nav.html
Labels: Version Specific, Technical Writer Review (TR)

#3011 (3.0 branch) Replace SCALE Nightly version text to 24.10 (temporary)
  layouts/partials/docs-nav.html
Labels: Version Specific, Technical Writer Review (TR)

#3006 PD-1258-update-replication-ui-ref-content-about-dataset-properties
  content/SCALE/SCALEUIReference/DataProtection/ReplicationScreensSCALE.md
Labels: Technical Writer Review (MJ)

#3017 Relocate line from article to snippet (where it should've been)
  content/SCALE/SCALETutorials/DataProtection/TrueCloudTasks.md
  static/includes/CloudServiceProvidersSCALE.md
Labels: Technical Writer Review (TR)
