Repository truenas/documentation, pull requests merged in 2024-10, with the labels that each got.

#3090 PD-1475 / 25.04 / Pd 1475 additional css styling for the docs bot
  layouts/partials/menu-filetree.html
  layouts/partials/menu.html
  layouts/partials/search-form.html
  layouts/partials/site-header.html
Labels: Review (TM), backport-24.10, backport-24.04, backport-23.10, backport-13.3, backport-13.0, backport-3.0

#3088 PD-1457 / 25.04 / Pd 1457 update nfs service content
  content/SCALE/SCALETutorials/Shares/AddingNFSShares.md
  content/SCALE/SCALETutorials/SystemSettings/Services/NFSServiceSCALE.md
  content/SCALE/SCALEUIReference/Shares/NFSSharesScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md
  static/images/SCALE/SystemSettings/ServicesNFSSettingsScreen.png
Labels: Technical Writer Review (LM)

#3089 PD-1457 / 24.10 / PD-1457 Update NFS share and service content backport to 24.10
  content/SCALETutorials/Shares/AddingNFSShares.md
  content/SCALETutorials/SystemSettings/Services/NFSServiceSCALE.md
  content/SCALEUIReference/Shares/NFSSharesScreens.md
  content/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md
  static/images/SCALE/SystemSettings/ServicesNFSSettingsScreen.png
Labels: backport-24.10

#3091 PD-1470 / 25.04 / PD-1470-document-installing-nvidia-drivers
  content/SCALE/SCALETutorials/Virtualization/_index.md
  content/TruenasApps/_index.md
  static/images/SCALE/Apps/AppsInstallNvidiaDrivers.png
  words-to-ignore.txt
Labels: Technical Writer Review (MJ), Re-Review

#3101 PD-1475 / 25.04 / Pd 1475 additional css styling for the docs bot
  layouts/partials/menu-filetree.html
  layouts/partials/menu.html
Labels: Technical Writer Review (MJ)

#3096 PD-1475 / 24.10 / Pd 1475 additional css styling for the docs bot (by DjP-iX)
  layouts/partials/menu-filetree.html
  layouts/partials/menu.html
  layouts/partials/search-form.html
  layouts/partials/site-header.html
Labels: Technical Writer Review (MJ)

#3095 PD-1475 / 24.04 / Pd 1475 additional css styling for the docs bot (by DjP-iX)
  i18n/en.yaml
  layouts/partials/menu.html
  layouts/partials/search-form.html
  layouts/partials/site-header.html
Labels: Technical Writer Review (MJ)

#3094 PD-1475 / 23.10 / Pd 1475 additional css styling for the docs bot (by DjP-iX)
  i18n/en.yaml
  layouts/partials/menu.html
  layouts/partials/site-header.html
Labels: Technical Writer Review (MJ)

#3092 PD-1475 / 13.0 / Pd 1475 additional css styling for the docs bot (by DjP-iX)
  i18n/en.yaml
  layouts/partials/menu.html
  layouts/partials/search-form.html
  layouts/partials/site-header.html
Labels: Technical Writer Review (MJ)

#3105 Update scale-releases.yaml
  data/properties/scale-releases.yaml
Labels: Technical Writer Review (LM)

#3104 Update Release notes RC.1
  content/GettingStarted/SCALEReleaseNotes.md
  data/properties/scale-releases.yaml
Labels: Technical Writer Review (LM)

#3087 PD-1461 / 24.10 / PD-1461 Backport User Home Directory Changes to 24.10
  content/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  static/images/SCALE/Credentials/AddUserHomeDirAuth.png
  static/images/SCALE/Credentials/AddUserHomeDirAuthSCALE.png
  static/images/SCALE/Credentials/AddUserHomeDirPerm.png
  static/images/SCALE/Credentials/AddUserHomeDirPermSCALE.png
Labels: Technical Writer Review (LM)

#3107 PD-1506 / 24.10 / Pd 1506 24 10 rc 2 release notes
  content/GettingStarted/SCALEReleaseNotes.md
  data/properties/scale-releases.yaml
  words-to-ignore.txt
Labels: Version Specific

#3108 PD-1506 / 25.04 / Pd 1506 follow up
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
Labels: Version Specific

#3116 H-Series test image for DocsBot ingest test
  content/Hardware/HSeries.md
  static/images/Hardware/HSeries/H-Series_Overview.png
Labels: Technical Writer Review (LM)

#3121 Update SCALEReleaseNotes.md (date typo)
  content/GettingStarted/SCALEReleaseNotes.md
  data/properties/scale-releases.yaml
Labels: Version Specific

#3115 PD-1508 / 25.04 / Pd 1508 24 04 2 3 follow up
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
Labels: Version Specific, Technical Writer Review (MJ)

#3120 Update SCALEZFSFlagRemoval.md (master)
  content/SCALE/GettingStarted/Migrate/SCALEZFSFlagRemoval.md
Labels: Technical Writer Review (LM)

#3118 Update SCALEZFSFlagRemoval.md (24.04)
  content/GettingStarted/Migrate/SCALEZFSFlagRemoval.md
Labels: Technical Writer Review (LM)

#3119 Update SCALEZFSFlagRemoval.md (24.10)
  content/GettingStarted/Migrate/SCALEZFSFlagRemoval.md
Labels: Technical Writer Review (LM)

#3086 PD-1461 / 25.04 / Pd 1461 home directory content updates
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  static/images/SCALE/Credentials/AddUserHomeDirAuth.png
  static/images/SCALE/Credentials/AddUserHomeDirAuthSCALE.png
  static/images/SCALE/Credentials/AddUserHomeDirPerm.png
  static/images/SCALE/Credentials/AddUserHomeDirPermSCALE.png
Labels: Technical Writer Review (LM), Re-Review

#3122 PD-1399 / 24.10 / PD-1399 Terminating an Active Running Job Snippet
  content/SCALEUIReference/TopToolbar/TasksScreens.md
  static/includes/TerminateActiveRunningJob.md
Labels: Technical Writer Review (MJ), Re-Review

#3126 PD-1379 / 25.04 / PD-1379 Update Jobs Content
  static/images/SCALE/Dashboard/JobsAbort.png
  static/images/SCALE/Dashboard/JobsMenu.png
  static/images/SCALE/Dashboard/TasksScreen.png
  static/includes/Jobs.md
Labels: Technical Writer Review (LM)

#3128 PD-1378 / 24.10 / PD-1378-clarify-auto-unlock-behaviors-for-dataset-encryption-with-key-vs-password
  content/SCALETutorials/Datasets/EncryptionSCALE.md
Labels: Technical Writer Review (MJ)

#3125 PD-1397 / 25.04 / Pd 1397 update d raid content
  content/References/dRAIDprimer.md
  static/includes/CreatePool.md
  static/includes/dRaidGroupLayout.md
  words-to-ignore.txt
Labels: Technical Writer Review (LM), Re-Review

#3127 PD-1463 / 25.04 / PD-1463 Update Apps Content
  content/SCALE/SCALEUIReference/Apps/_index.md
  content/TruenasApps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md
  content/TruenasApps/EnterpriseApps/MinIO/ConfigMinioEnterpriseSNMD.md
  content/TruenasApps/EnterpriseApps/MinIO/_index.md
  content/TruenasApps/EnterpriseApps/_index.md
  content/TruenasApps/StableApps/_index.md
  content/TruenasApps/_index.md
  static/images/SCALE/Apps/AppsDeleteAppDialog.png
  static/images/SCALE/Apps/AppsSettingScreen.png
  static/includes/apps/AppsInstallWizardSettings.md
  words-to-ignore.txt
Labels: Technical Writer Review (LM), Re-Review

#3131 PD-1444 / 13.0 / PD-1444 Adding NPIV content to the Fibre Channel Article
  content/CORETutorials/JailsPluginsVMs/VirtualMachines/SettingUpNPIV.md
  content/CORETutorials/Sharing/iSCSI/SettingUpFibreChannel.md
  static/includes/NPIV.md
Labels: Version Specific, Review (TM)

#3129 PD-1359 / 25.04 / PD-1359 Update Dashboard Images and Content
  content/SCALE/SCALETutorials/Dashboard/_index.md
  content/SCALE/SCALEUIReference/SCALEDashboard.md
  static/images/SCALE/Dashboard/DashboardBackupTasks.png
  static/images/SCALE/Dashboard/DashboardCPUWidget.png
  static/images/SCALE/Dashboard/DashboardInConfigMode.png
  static/images/SCALE/Dashboard/DashboardMainHAScreen.png
  static/images/SCALE/Dashboard/DashboardMainScreen.png
  static/images/SCALE/Dashboard/DashboardNetworkWidget.png
  static/images/SCALE/Dashboard/DashboardNetworkWidgetGroupOptions.png
  static/images/SCALE/Dashboard/DashboardPoolWidget.png
  static/images/SCALE/Dashboard/DashboardStorageWidget.png
  static/images/SCALE/Dashboard/WidgetEditorAddNew.png
  static/images/SCALE/Dashboard/WidgetEditorExistingWidget.png
Labels: Technical Writer Review (LM)

#3133 PD-1374 / 24.04 / updated snippet
  static/includes/RootToAdminUserAccount.md
Labels: Technical Writer Review (MJ)

#3132 PD-1444 / 13.0 / Pd 1444 update fibre channel article w npiv conten
  static/includes/NPIV.md
Labels: Review (TM)

#3123 PD-1369 / 25.04 / Pd 1369 update custom app
  content/SCALE/SCALETutorials/Shares/AddingNFSShares.md
  content/SCALE/SCALEUIReference/Apps/InstallCustomAppScreens.md
  content/SCALE/SCALEUIReference/Apps/_index.md
  content/SCALE/SCALEUIReference/DataProtection/ReplicationScreensSCALE.md
  content/SCALE/SCALEUIReference/Shares/NFSSharesScreens.md
  content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md
  content/TruenasApps/CommunityApps/jellyfin.md
  content/TruenasApps/EnterpriseApps/Syncthing.md
  content/TruenasApps/EnterpriseApps/_index.md
  content/TruenasApps/StableApps/InstallPiHoleApp.md
  content/TruenasApps/UsingCustomApp.md
  content/TruenasApps/_index.md
  layouts/shortcodes/codeblock.html
  static/images/SCALE/Apps/AppsDiscoverScreen.png
  static/images/SCALE/Apps/AppsDiscoverScreenHeaderAndSearch.png
  static/images/SCALE/Apps/AppsInstallNvidiaDrivers.png
  static/images/SCALE/Apps/AppsSettingScreen.png
  static/images/SCALE/Apps/CustomAppDetails.png
  static/images/SCALE/Apps/InstallAppStorageConfigSMBOption.png
  static/images/SCALE/Apps/InstallCustomAppAddHostPathVol.png
  static/images/SCALE/Apps/InstallCustomAppAddMemoryBackedVol.png
  static/images/SCALE/Apps/InstallCustomAppAddPortalConfiguration.png
  static/images/SCALE/Apps/InstallCustomAppAddResourceLimits.png
  static/images/SCALE/Apps/InstallCustomAppAddSMB.png
  static/images/SCALE/Apps/InstallCustomAppAddStorageVolumes.png
  static/images/SCALE/Apps/InstallCustomAppAddixVolume.png
  static/images/SCALE/Apps/InstallCustomAppApplicationName.png
  static/images/SCALE/Apps/InstallCustomAppContainerEntrypoint.png
  static/images/SCALE/Apps/InstallCustomAppContainerImages.png
  static/images/SCALE/Apps/InstallCustomAppNetworking.png
  static/images/SCALE/Apps/InstallCustomAppScreenNameAndImage.png
  static/images/SCALE/Apps/InstallCustomAppScreenStorage.png
  static/images/SCALE/Apps/InstallCustomAppSecurityContextConfiguration.png
  static/images/SCALE/Apps/InstallCustomAppTOC.png
  static/images/SCALE/Apps/InstallCustomAppYAML.png
  static/includes/CustomAppEE.md
  static/includes/apps/AppInstallWizardACLConfiguration.md
  static/includes/apps/AppWizardStorageSMBOption.md
  static/includes/apps/AppsCustomApp.md
  static/includes/apps/AppsFileSharing.md
  static/includes/apps/AppsPoolOrDataset.md
  static/includes/apps/CustomAppEE.md
  static/includes/apps/CustomAppIntro.md
  static/includes/apps/YAMLWarning.md
  words-to-ignore.txt
Labels: Technical Writer Review (MJ), Re-Review, backport-24.10

#3135 Expand syslog configuration doc into general MW configuration
  content/Recommendations/TCMiddlewareConfguration.md
  words-to-ignore.txt
Labels: Technical Writer Review (MJ)

#3134 PD-1459 / 25.04 / PD-1359 Create REST API Deprecation Notice
  content/SCALE/API/_index.md
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
  static/includes/RESTAPIDeprecationNotice.md
Labels: Technical Writer Review (LM), backport-24.10

#3139 Backport some of Zack's PRs to 3.0 branch
  content/AdminGuide/Admin/LDAPServers.md
  content/AdminGuide/Admin/SAML/SAMLGA.md
  content/Recommendations/IPv6.md
  content/Recommendations/Performance.md
  content/Recommendations/Syslog.md
  content/TCGettingStarted/Install/InstallTCDocker.md
  content/TCGettingStarted/Install/UpdateDocker.md
  content/TCGettingStarted/TCReleaseNotes.md
  static/custom.css
  static/images/TrueCommand/Administration/AddLDAPDefault.png
  static/images/TrueCommand/Administration/AddLDAPGroup.png
  static/images/TrueCommand/Administration/AddLDAPGroupToTeam.png
  static/images/TrueCommand/Administration/AddLDAPServerScreen.png
  static/images/TrueCommand/Administration/AddRecipientScreen.png
  static/images/TrueCommand/Administration/AdministrationAlertRecipientsWidget.png
  static/images/TrueCommand/Administration/AdministrationCAs.png
  static/images/TrueCommand/Administration/AdministrationCertificateAuthoritiesWidget.png
  static/images/TrueCommand/Administration/AdministrationCertificates.png
  static/images/TrueCommand/Administration/AdministrationCertificatesWidget.png
  static/images/TrueCommand/Administration/AdministrationConfigLDAP.png
  static/images/TrueCommand/Administration/AdministrationConfigTelemetry.png
  static/images/TrueCommand/Administration/AdministrationLDAPServersWidget.png
  static/images/TrueCommand/Administration/ConfigurationScreenSSLOptions.png
  static/images/TrueCommand/Administration/MailingListConfigureScreen.png
  static/images/TrueCommand/Administration/OpenSourceLicensesWindow.png
  static/images/TrueCommand/tc-three-system-perf.png
  words-to-ignore.txt
Labels: Version Specific, Technical Writer Review (MJ)

#3109 PD-1446 / 25.04 / PD-1446 Update Active Directory Content
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigADSCALE.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/ActiveDirectory.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/_index.md
  static/images/SCALE/Credentials/ActiveDirectoryAdvancedOptions.png
  static/images/SCALE/Credentials/ActiveDirectoryBasicOptions.png
  static/images/SCALE/Credentials/ActiveDirectoryBasicOptionsEditScreen.png
  static/images/SCALE/Credentials/ActiveDirectoryWidget.png
  static/images/SCALE/Credentials/DirServicesAdvancedSettingsWidgets.png
  static/images/SCALE/Credentials/DirectoryServicesADandLDAPWidgets.png
  static/images/SCALE/Credentials/DirectoryServicesScreen.png
  static/images/SCALE/Credentials/SelelectCertificateStore.png
  static/images/SCALE/SystemSettings/LocalizationSettingsScreen.png
  static/includes/DirectoryServiceAccessAdmonition.md
Labels: Re-Review, backport-24.10

#3144 PD-1430 / 24.04 / PD-1430 Update 24.04 Migration Articles with Approved Migration Path
  content/GettingStarted/Migrate/ComponentNaming.md
  content/GettingStarted/Migrate/MigrateCOREHAtoSCALEHA.md
  content/GettingStarted/Migrate/MigratePrep.md
  content/GettingStarted/Migrate/MigratingFromCORE.md
  content/GettingStarted/Migrate/SCALEZFSFlagRemoval.md
  content/GettingStarted/Migrate/_index.md
  static/includes/MigrateCOREtoSCALEWarning.md
Labels: Version Specific, Technical Writer Review (LM)

#3157 Update Security.md
  content/Solutions/Optimizations/Security.md
Labels: Technical Writer Review (MJ)

#3154 PD-1449 / 24.04 / PD-1449-add-24.04.2.3-known-issue
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Technical Writer Review (MJ)

#3143 Fix duration value in TC MW config doc
  content/Recommendations/Syslog.md
  content/Recommendations/TCMiddlewareConfguration.md
Labels: Technical Writer Review (MJ)

#3152 PD-1517 / 25.04 / PD-1517 Update Apps GPU Content
  content/SCALE/SCALEUIReference/Apps/_index.md
  content/TruenasApps/_index.md
  static/images/SCALE/Apps/InstallAppResourceConfigurationGPU.png
  static/images/SCALE/Apps/ResourcesConfiguration.png
  static/images/SCALE/Apps/ResourcesConfigurationAllocateGPU.png
  words-to-ignore.txt
Labels: backport-24.10

#3145 1430 24.10 migration article updates
  content/GettingStarted/Migrate/ComponentNaming.md
  content/GettingStarted/Migrate/MigrateCOREHAtoSCALEHA.md
  content/GettingStarted/Migrate/MigratePrep.md
  content/GettingStarted/Migrate/MigratingFromCORE.md
  content/GettingStarted/Migrate/SCALEZFSFlagRemoval.md
  content/GettingStarted/Migrate/_index.md
  static/includes/MigrateCOREtoSCALE24_04.md
  static/includes/WhatDoesNotMigrate.md
Labels: Version Specific, Technical Writer Review (MJ)

#3148 PD-1430 / 25.04 / PD-1430 Update CORE to SCALE Migration Content in Master
  content/SCALE/GettingStarted/Migrate/_index.md
  static/includes/MigrateCOREtoSCALE24_04.md
Labels: Version Specific

#3169 24.10 known issue with ES24 shelves
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific

#3167 PD-1527 / 25.04 / Pd 1527 review raid z expansion
  content/References/ExtensionCalculator.md
  content/SCALE/SCALETutorials/Storage/ManagePoolsScale.md
  static/includes/ExpandedVdevReporting.md
  words-to-ignore.txt
Labels: Technical Writer Review (MJ), Re-Review, backport-24.10

#3170 PD-1527 / 24.10 / Pd 1527 review raid z expansion (by DjP-iX)
  content/SCALETutorials/Storage/ManagePoolsScale.md
  static/includes/ExpandedVdevReporting.md
  words-to-ignore.txt
Labels: Review (TM)

#3173 PD-1502 / None / Pd 1502 update smb share purpose presets descriptions
  content/SCALE/SCALETutorials/Shares/SMB/_index.md
  content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md
  static/includes/SMBPurposePresets.md
Labels: Technical Writer Review (LM)

#3175 Update 24.10.0 SCALEReleaseNotes.md - known issue with ghost boot-drive exported
  content/GettingStarted/SCALEReleaseNotes.md
  words-to-ignore.txt
Labels: Version Specific

#3171 PD-1509 / 24.10 / Replaced All Instances of "Token Lifetime"
  content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  static/includes/AccessSettingsWidget.md
Labels: Technical Writer Review (MJ), backport-25.04
