Repository truenas/documentation, pull requests merged in 2024-04, with the labels that each got.

#2616 Update General Network Articles - Master
  content/SCALE/GettingStarted/Install/InstallEnterpriseHASCALE.md
  content/SCALE/SCALETutorials/Network/AddingGlobalConf.md
  content/SCALE/SCALETutorials/Network/ConfigureStaticRoutes.md
  content/SCALE/SCALETutorials/Network/ManageNetworkSettingsHA.md
  content/SCALE/SCALETutorials/Network/ManagingGlobalConfig.md
  static/images/SCALE/Network/GlobalConfigAllowSpecificServiceOptions.png
  static/images/SCALE/Network/GlobalConfigHostAndDomainNameSettings.png
  static/images/SCALE/Network/GlobalConfigNameserverSettings.png
  static/images/SCALE/Network/GlobalConfigOutboundSettings.png
  static/includes/ConfigureController1Networking.md
  static/includes/EnterpriseHANetworkIPs.md
Labels: Technical Writer Review (TR)

#2618 Update General Network Articles - 24.04
  content/GettingStarted/Install/InstallEnterpriseHASCALE.md
  content/SCALETutorials/Network/AddingGlobalConf.md
  content/SCALETutorials/Network/ConfigureStaticRoutes.md
  content/SCALETutorials/Network/ManageNetworkSettingsHA.md
  content/SCALETutorials/Network/ManagingGlobalConfig.md
  static/images/SCALE/Network/GlobalConfigAllowSpecificServiceOptions.png
  static/images/SCALE/Network/GlobalConfigHostAndDomainNameSettings.png
  static/images/SCALE/Network/GlobalConfigNameserverSettings.png
  static/images/SCALE/Network/GlobalConfigOutboundSettings.png
  static/includes/ConfigureController1Networking.md
  static/includes/EnterpriseHANetworkIPs.md
Labels: Technical Writer Review (TR)

#2620 Update Apps Articles - Master
  content/SCALE/SCALETutorials/Apps/AppsAdvancedSettings.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/_index.md
  content/SCALE/SCALETutorials/Apps/EnterpriseApps/_index.md
  content/SCALE/SCALETutorials/Apps/UsingCatalogs.md
Labels: Technical Writer Review (TR)

#2619 Update App Articles - 24.04
  content/SCALETutorials/Apps/AppsAdvancedSettings.md
  content/SCALETutorials/Apps/CommunityApps/_index.md
  content/SCALETutorials/Apps/EnterpriseApps/_index.md
  content/SCALETutorials/Apps/UsingCatalogs.md
  static/includes/AddEnterpriseTrain.md
Labels: Technical Writer Review (TR)

#2622 Update Storage UI Articles - Master
  content/SCALE/SCALEUIReference/Storage/DevicesScreensSCALE.md
  content/SCALE/SCALEUIReference/Storage/DisksScreen.md
  content/SCALE/SCALEUIReference/Storage/PoolCreateWizardScreens.md
  content/SCALE/SCALEUIReference/Storage/_index.md
Labels: Technical Writer Review (TR)

#2621 Update Storage UI Reference Articles - 24.04
  content/SCALEUIReference/Storage/DevicesScreensSCALE.md
  content/SCALEUIReference/Storage/DisksScreen.md
  content/SCALEUIReference/Storage/PoolCreateWizardScreens.md
  content/SCALEUIReference/Storage/_index.md
Labels: Technical Writer Review (TR)

#2630 Use fixed dataset name in sandboxes setup (port to 24.04)
  content/SCALETutorials/Apps/Sandboxes.md
  static/images/SCALE/Datasets/SandboxDatasetCreate.png
  static/images/SCALE/SystemSettings/JailmakerInitScriptCreate.png
Labels: Technical Writer Review (TR)

#2629 Use fixed dataset name in Sandboxes setup
  content/SCALE/SCALETutorials/Apps/Sandboxes.md
  static/images/SCALE/Datasets/SandboxDatasetCreate.png
  static/images/SCALE/SystemSettings/JailmakerInitScriptCreate.png
Labels: Technical Writer Review (TR)

#2627 Update Creating Storj-TrueNAS SCALE Account - Master
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddStorjCloudSyncTask.md
Labels: Technical Writer Review (TR)

#2626 Update Creating Storj-TrueNAS SCALE Account
  content/SCALETutorials/DataProtection/CloudSyncTasks/AddStorjCloudSyncTask.md
Labels: Technical Writer Review (TR)

#2624 Update Dataset UI Articles - 24.04
  content/SCALEUIReference/Datasets/EditACLScreens.md
  content/SCALEUIReference/Datasets/EncryptionUISCALE.md
  content/SCALEUIReference/Datasets/QuotaScreens.md
  content/SCALEUIReference/Datasets/SnapshotsScreens.md
  content/SCALEUIReference/Datasets/ZvolsScreensScale.md
  content/SCALEUIReference/Datasets/_index.md
  static/images/SCALE/Datasets/AddZvolScreen.png
  static/includes/CloneAndPromoteSnapshotDataset.md
Labels: Technical Writer Review (TR)

#2633 Change Mentions of /nonexistent in Local User Articles and Replication Snippets - Master
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
  static/includes/BasicReplicationProcess.md
  static/includes/ReplicationCreateDatasetAndAdminHomeDirSteps.md
Labels: Technical Writer Review (TR)

#2632 Update manage local users scale.md 24.04
  content/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
  static/images/SCALE/Credentials/AddUserHomeDirPermSCALE.png
  static/includes/BasicReplicationProcess.md
  static/includes/ReplicationCreateDatasetAndAdminHomeDirSteps.md
Labels: Technical Writer Review (TR)

#2636 Update manage local users scale.md 24.04
  content/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
Labels: Technical Writer Review (TR)

#2634 Updates to Datasets Tutorials - 24.04
  content/SCALETutorials/Datasets/AddManageZvols.md
  content/SCALETutorials/Datasets/CreatingSnapshots.md
  content/SCALETutorials/Datasets/DatasetsSCALE.md
  content/SCALETutorials/Datasets/EncryptionSCALE.md
  content/SCALETutorials/Datasets/ManageQuotas.md
  content/SCALETutorials/Datasets/ManageSnapshotsSCALE.md
  content/SCALETutorials/Datasets/PermissionsSCALE.md
  static/images/SCALE/Datasets/DownloadEncryptionKeyForPool.png
  static/images/SCALE/Datasets/ViewRootDatasetPermissionsWidget.png
  static/images/SCALE/Storage/DownloadEncryptionKeyForPool.png
  static/includes/CreateDatasetSCALE.md
  static/includes/DatasetPresetOptions.md
Labels: Technical Writer Review (TR)

#2640 Update AdvancedSettingsScreen.md
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
Labels: Technical Writer Review (TR), Backport Requested

#2641 Update AdvancedSettingsScreen.md (24,04 backport)
  content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
Labels: Version Specific, Technical Writer Review (TR)

#2631 Update Storage Tutorials - Master
  content/SCALE/SCALETutorials/Storage/CreatePoolWizard.md
  content/SCALE/SCALETutorials/Storage/FusionPoolsScale.md
  content/SCALE/SCALETutorials/Storage/ImportPoolScale.md
  content/SCALE/SCALETutorials/Storage/ManagePoolsScale.md
  content/SCALE/SCALETutorials/Storage/_index.md
  static/images/SCALE/Storage/ExportDisconnectPoolWindow.png
  static/images/SCALE/Storage/PoolCreationWizard.png
  static/includes/CreatePool.md
  static/includes/PoolCreationWizardCommonSettings.md
Labels: Technical Writer Review (TR)

#2628 Update Storage Tutorials - 24.04
  content/SCALETutorials/Storage/CreatePoolWizard.md
  content/SCALETutorials/Storage/FusionPoolsScale.md
  content/SCALETutorials/Storage/ImportPoolScale.md
  content/SCALETutorials/Storage/ManagePoolsScale.md
  content/SCALETutorials/Storage/_index.md
  static/images/SCALE/Storage/ExportDisconnectPoolWindow.png
  static/images/SCALE/Storage/PoolCreationWizard.png
  static/includes/CreatePool.md
  static/includes/PoolCreationWizardCommonSettings.md
Labels: Technical Writer Review (TR)

#2642 Update jenkins pipeline to fix pagefind glob
  jenkins/update-24.04
Labels: Version Specific, Technical Writer Review (TR)

#2638 Update virtualization articles master
  content/SCALE/GettingStarted/Configure/VMandAppConfigSCALE.md
  content/SCALE/SCALETutorials/Datasets/AddManageZvols.md
  content/SCALE/SCALETutorials/Virtualization/AccessingNASFromVM.md
  content/SCALE/SCALETutorials/Virtualization/AddManageVMDevicesSCALE.md
  content/SCALE/SCALETutorials/Virtualization/CreatingManagingVMsSCALE.md
  content/SCALE/SCALETutorials/Virtualization/_index.md
  content/SCALE/SCALEUIReference/VirtualizationScreens.md
  content/Solutions/Optimizations/Security.md
  static/images/SCALE/Virtualization/EditVMCPUandMemory.png
  static/images/SCALE/Virtualization/EditVMGeneralSettings.png
  static/images/SCALE/Virtualization/EditVMGpuSettings.png
  static/images/SCALE/Virtualization/LoginScreenSCALE.png
  static/images/SCALE/Virtualization/ViewRootDatasetPermissionsWidget.png
  static/includes/VMCPUandMemorySettings.md
  static/includes/VMGPUSettings.md
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#2637 Update virtualization articles 24.04
  content/GettingStarted/Configure/VMandAppConfigSCALE.md
  content/SCALETutorials/Datasets/AddManageZvols.md
  content/SCALETutorials/Virtualization/AccessingNASFromVM.md
  content/SCALETutorials/Virtualization/AddManageVMDevicesSCALE.md
  content/SCALETutorials/Virtualization/CreatingManagingVMsSCALE.md
  content/SCALETutorials/Virtualization/_index.md
  content/SCALEUIReference/VMCPUandMemorySettings.md
  content/SCALEUIReference/VMGPUSettings.md
  content/SCALEUIReference/VirtualizationScreens.md
  static/images/SCALE/Virtualization/CloneVMDialog.png
  static/images/SCALE/Virtualization/EditVMCPUandMemory.png
  static/images/SCALE/Virtualization/EditVMGeneralSettings.png
  static/images/SCALE/Virtualization/EditVMGpuSettings.png
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#2648 Pd 1066 review scale installer screens text
  content/SCALE/GettingStarted/Install/InstallEnterpriseHASCALE.md
  content/SCALE/GettingStarted/Install/InstallingSCALE.md
  static/images/SCALE/Install/SCALEInstallDriveScreen.png
  static/images/SCALE/Install/SCALEInstallLegacyBoot.png
  static/images/SCALE/Install/SCALEInstallMainScreen.png
  static/images/SCALE/Install/SCALEInstallPartitionScreen.png
  static/images/SCALE/Install/SCALEInstallWarningScreen.png
  static/images/SCALE/Install/SCALEInstallerConsoleSetupAdminAccount.png
  static/images/SCALE/Install/SCALEInstallerConsoleSetupAdminPassword.png
  static/includes/SCALEInstallerProcedure.md
Labels: Technical Writer Review (MJ)

#2647 Update cloud sync articles master
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddCloudSyncTasks.md
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddGooglePhotosCloudSyncTask.md
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddStorjCloudSyncTask.md
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/CloudSyncTaskGoogleDrive.md
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/_index.md
  content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  static/images/SCALE/DataProtection/AddCloudSyncTaskPushControlAdvancedEncrypt.png
  static/images/SCALE/DataProtection/AddCloudSyncTaskPushControlAdvancedOptions.png
  static/images/SCALE/DataProtection/AddCloudSyncTaskPushTransferRemote.png
  static/images/SCALE/DataProtection/CloudSyncTaskWidgeNoTasks.png
  static/images/SCALE/DataProtection/CloudSyncTaskWidget.png
  static/images/SCALE/DataProtection/CloudSyncTaskWidgetNoTasks.png
  static/images/SCALE/DataProtection/CloudSyncTaskWizardProviderScreen.png
  static/images/SCALE/DataProtection/CloudSyncTaskWizardWhatandWhenScreen.png
  static/images/SCALE/DataProtection/CloudSyncTasksScreen.png
  static/images/SCALE/DataProtection/CloudSyncTasksScreenTaskDetails.png
  static/images/SCALE/DataProtection/RsyncTaskWidget.png
  static/includes/AddCloudSyncTaskSteps3-8.md
  static/includes/CreateCloudSyncTaskScale.md
Labels: Review (TM)

#2649 Update Cloud Sync Task Articles - 24.04
  content/SCALETutorials/DataProtection/CloudSyncTasks/AddCloudSyncTasks.md
  content/SCALETutorials/DataProtection/CloudSyncTasks/AddGooglePhotosCloudSyncTask.md
  content/SCALETutorials/DataProtection/CloudSyncTasks/AddStorjCloudSyncTask.md
  content/SCALETutorials/DataProtection/CloudSyncTasks/CloudSyncTaskGoogleDrive.md
  content/SCALETutorials/DataProtection/CloudSyncTasks/_index.md
  content/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  static/images/SCALE/DataProtection/AddCloudSyncTaskPushControlAdvancedEncrypt.png
  static/images/SCALE/DataProtection/AddCloudSyncTaskPushControlAdvancedOptions.png
  static/images/SCALE/DataProtection/AddCloudSyncTaskPushTransferRemote.png
  static/images/SCALE/DataProtection/CloudSyncTaskWidgeNoTasks.png
  static/images/SCALE/DataProtection/CloudSyncTaskWidget.png
  static/images/SCALE/DataProtection/CloudSyncTaskWidgetNoTasks.png
  static/images/SCALE/DataProtection/CloudSyncTaskWizardProviderScreen.png
  static/images/SCALE/DataProtection/CloudSyncTaskWizardWhatandWhenScreen.png
  static/images/SCALE/DataProtection/CloudSyncTasksScreen.png
  static/images/SCALE/DataProtection/CloudSyncTasksScreenTaskDetails.png
  static/images/SCALE/DataProtection/FileExplorerFolderOptions.png
  static/images/SCALE/DataProtection/RsyncTaskWidget.png
  static/includes/AddCloudSyncTaskSteps3-8.md
  static/includes/CreateCloudSyncTaskScale.md
Labels: Review (TM)

#2651 Pd 1110 update docs hub forum links
  README.md
  content/CORE/CORETutorials/Getting Support.md
  content/CORE/CORETutorials/Tasks/CreatingInitShutdownScripts.md
  content/Hardware/LegacyHardware/FNCertified/Multipath.md
  content/References/ZFSPrimer.md
  content/References/_index.md
  content/SCALE/GettingStarted/Getting Support/_index.md
  content/SCALE/GettingStarted/Install/InstallPrepHomeUsers.md
  content/SCALE/GettingStarted/Install/InstallPrepNonEnterprise.md
  content/SCALE/GettingStarted/Migrate/SCALEZFSFlagRemoval.md
  content/SCALE/SCALEUIReference/SCALEDashboard.md
  content/SCALE/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  content/TrueCommand/TCGettingStarted/Support.md
  layouts/partials/menu-nextprev.html
  layouts/partials/site-header.html
  static/includes/CommunityForums.md
  static/includes/iXsystemsSupportContact.md
Labels: Review (TM)

#2652 Pd 1110 update forum links 24.04
  README.md
  content/GettingStarted/Getting Support/_index.md
  content/GettingStarted/Install/InstallPrepHomeUsers.md
  content/GettingStarted/Install/InstallPrepNonEnterprise.md
  content/GettingStarted/Migrate/SCALEZFSFlagRemoval.md
  content/SCALEUIReference/SCALEDashboard.md
  content/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  layouts/partials/menu-nextprev.html
  layouts/partials/site-header.html
  static/includes/CommunityForums.md
  static/includes/iXsystemsSupportContact.md
Labels: Review (TM)

#2653 Pd 1110 update forum links 23.10
  README.md
  content/GettingStarted/Getting Support/GetSupportSCALE.md
  content/GettingStarted/Migrate/SCALEZFSFlagRemoval.md
  content/SCALEUIReference/SCALEDashboard.md
  content/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  layouts/partials/menu-nextprev.html
  layouts/partials/site-header.html
  static/includes/CommunityForums.md
  static/includes/iXsystemsSupportContact.md
Labels: Review (TM)

#2654 Pd 1110 update forum links 22.12
  README.md
  content/GettingStarted/Getting Support/GetSupportSCALE.md
  content/GettingStarted/Migrate/SCALEZFSFlagRemoval.md
  content/SCALEUIReference/SCALEDashboard.md
  content/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  layouts/partials/menu-nextprev.html
  layouts/partials/site-header.html
  static/includes/iXsystemsSupportContact.md
Labels: Review (TM)

#2655 Pd 1110 update forum links 13.0
  README.md
  content/CORETutorials/Getting Support.md
  content/CORETutorials/Tasks/CreatingInitShutdownScripts.md
  layouts/partials/menu-nextprev.html
  layouts/partials/site-header.html
  static/includes/COREFeatureSupport.md
  static/includes/iXsystemsSupportContact.md
Labels: Review (TM)

#2656 Pd 1110 update forum links 2.3
  README.md
  content/Introduction/Support.md
  layouts/partials/menu-nextprev.html
  layouts/partials/site-header.html
  static/includes/iXsystemsSupportContact.md
Labels: Review (TM)

#2657 Pd 1110 update forum links 3.0
  README.md
  content/TCGettingStarted/Support.md
  layouts/partials/menu-nextprev.html
  layouts/partials/site-header.html
  static/includes/iXsystemsSupportContact.md
Labels: Review (TM)

#2660 Pd 1108 fix browser tab titling
  layouts/_default/baseof.html
  layouts/partials/head/custom.html
  static/favicon/TN-favicon-16x16.png
Labels: Review (TM)

#2658 Update rsync task articles master
  content/SCALE/SCALETutorials/DataProtection/RsyncTasksSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/RsyncTasksScreensSCALE.md
  static/images/SCALE/DataProtection/AddRsyncTaskSourceAndRemoteSettings.png
  static/images/SCALE/DataProtection/AddRsyncTaskSourceRemoteModule.png
  static/images/SCALE/DataProtection/AddRsyncTaskSourceRemoteSSH.png
  static/images/SCALE/DataProtection/RsyncTaskLogDialog.png
  static/images/SCALE/DataProtection/RsyncTasksScreen.png
  static/includes/AdvancedScheduler.md
Labels: Review (TM)

#2659 Update Rsync Task Articles - 24.04
  content/SCALETutorials/DataProtection/RsyncTasksSCALE.md
  content/SCALEUIReference/DataProtection/RsyncTasksScreensSCALE.md
  static/images/SCALE/DataProtection/AddRsyncTaskSourceAndRemoteSettings.png
  static/images/SCALE/DataProtection/AddRsyncTaskSourceRemoteSSH.png
  static/images/SCALE/DataProtection/RsyncTaskLogDialog.png
  static/images/SCALE/DataProtection/RsyncTasksScreen.png
Labels: Review (TM)

#2664 Backport Advanced Settings Article Changes to 23.10
  content/SCALETutorials/SystemSettings/Advanced/ManageGlobal2FASCALE.md
  content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
Labels: Review (TM)

#2662 Update Advanced Settings Article - 24.04
  content/SCALETutorials/SystemSettings/Advanced/ManageGlobal2FASCALE.md
  content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  static/includes/ConfigureSystemAuditSCALE.md
Labels: Review (TM)

#2661 Update Advanced Settings Articles
  content/SCALE/SCALETutorials/SystemSettings/Advanced/ManageGlobal2FASCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  static/includes/ConfigureSystemAuditSCALE.md
Labels: Review (TM)

#2667 Pd 1108 fix browser tab titling 24.04
  layouts/_default/baseof.html
  layouts/partials/head/custom.html
  layouts/partials/head/favicons.html
  static/favicon/TN-favicon-16x16.png
  static/favicon/tn-favicon.svg
Labels: Review (TM)

#2668 Pd 1108 fix browser tab titling 23.10
  layouts/_default/baseof.html
  layouts/partials/head/custom.html
  layouts/partials/head/favicons.html
  static/favicon/TN-favicon-16x16.png
  static/favicon/tn-favicon.svg
Labels: Review (TM)

#2669 Pd 1108 fix browser tab titling 22.12
  layouts/_default/baseof.html
  layouts/partials/head/custom.html
  layouts/partials/head/favicons.html
  static/favicon/TN-favicon-16x16.png
  static/favicon/tn-favicon.svg
Labels: Review (TM)

#2670 Pd 1108 fix browser tab titling 13.0
  layouts/_default/baseof.html
  layouts/partials/head/custom.html
  layouts/partials/head/favicons.html
  static/favicon/TN-favicon-16x16.png
  static/favicon/tn-favicon.svg
Labels: Review (TM)

#2671 Pd 1108 fix browser tab titling 3.0
  layouts/_default/baseof.html
  layouts/partials/head/custom.html
  layouts/partials/head/favicons.html
  static/favicon/TN-favicon-16x16.png
  static/favicon/tn-favicon.svg
Labels: Review (TM)

#2672 Pd 1108 fix browser tab titling 2.3
  layouts/_default/baseof.html
  layouts/partials/head/custom.html
  layouts/partials/head/favicons.html
  static/favicon/TN-favicon-16x16.png
  static/favicon/tn-favicon.svg
Labels: Review (TM)

#2674 Update Replication Tasks UI Ref Article - Master
  content/SCALE/SCALEUIReference/DataProtection/ReplicationScreensSCALE.md
  static/images/SCALE/DataProtection/ReplicationTaskNewSSHConnection.png
  static/images/SCALE/DataProtection/ReplicationTaskWizardWhatAndWhereAllSettings.png
  static/images/SCALE/DataProtection/ReplicationWizardCreateSSHConnection.png
  static/images/SCALE/DataProtection/ReplicationWizardWhatAndWhere.png
Labels: Review (TM)

#2676 Update replication task articles 24.04
  content/SCALEUIReference/DataProtection/ReplicationScreensSCALE.md
  static/images/SCALE/DataProtection/ReplicationTaskNewSSHConnection.png
  static/images/SCALE/DataProtection/ReplicationTaskWizardWhatAndWhereAllSettings.png
Labels: Review (TM)

#2677 PD-1091 Create Syslog Tutorial and Update UI Ref
  content/CORE/CORETutorials/SystemConfiguration/SettingUpSyslogServer.md
  content/CORE/UIReference/System/Advanced.md
  static/images/CORE/System/SystemAdvancedSyslogTransportTLS.png
  static/includes/SystemAdvancedFields.md
Labels: Technical Writer Review (DP)

#2678 Pd 1042 core min io app migration tutorial main
  content/CORE/CORETutorials/JailsPluginsVMs/Plugins/MinIOPlugin.md
  content/SCALE/GettingStarted/Migrate/MigratePrep.md
  content/Solutions/MigratingToTrueNAS.md
  content/Solutions/MinioCOREtoSCALE.md
  content/Solutions/Optimizations/_index.md
  static/images/Solutions/MinIOAppStorage.png
  static/images/Solutions/MinIOBucketVisible.png
  static/images/Solutions/MinIODatasetPermissions.png
  words-to-ignore.txt
Labels: Review (TM)

#2643 Pd 982 24.04.0 release follow up (for master branch)
  content/SCALE/GettingStarted/DataMigrationSyncthing.md
  content/SCALE/SCALETutorials/Apps/EnterpriseApps/Syncthing.md
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
Labels: Version Specific, Review (TM)

#2687 Update Software Releases Upgrade Paths
  content/TrueNASUpgrades/_index.md
Labels: Review (TM)

#2692 Add VM & IPv6 Known Issue to 24.04 release notes
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific

#2694 PD-1123: Fix printview generation for 24.04 Getting Started Guide
  layouts/_default/baseof.print.html
Labels: Version Specific, Backport Requested

#2686 Pd 1093 building documenation locally from main branch fails
  content/SCALE/GettingStarted/Migrate/MigratePrep.md
  content/SCALE/SCALECLIReference/Storage/CLIScrub.md
  content/SCALE/SCALECLIReference/System/CLIBoot.md
  content/SCALE/SCALECLIReference/System/CLIBootenv.md
  content/SCALE/SCALECLIReference/System/CLITrueCommand.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/Immich.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/InstallPiHoleApp.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/jellyfin.md
  content/SCALE/SCALETutorials/Apps/UsingCustomApp.md
  content/SCALE/SCALETutorials/ConfigReportsScale.md
  content/SCALE/SCALETutorials/Shares/MixedModeShares.md
  content/SCALE/SCALETutorials/Storage/Disks/SLOGOverprovisionSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Advanced/ManageGPUSCALE.md
  content/SCALE/SCALEUIReference/Apps/InstallCustomAppScreens.md
  content/SCALE/SCALEUIReference/ReportingScreensSCALE.md
  content/Solutions/Integrations/VMware/DeployTNinVMWare.md
  content/Solutions/Optimizations/Security.md
  content/TrueCommand/TCGettingStarted/UserAccounts.md
  static/includes/BrowsingSnapshotCollections1.md
  static/includes/ClusterSetup.md
  static/includes/MinIODatasetRequirements.md
Labels: Technical Writer Review (MJ)

#2690 PD-1093-building-documenation-locally-from-main-branch-fails-3.0
  content/TCGettingStarted/UserAccounts.md
Labels: Technical Writer Review (MJ)

#2683 Update MigratePrep.md
  content/GettingStarted/Migrate/MigratePrep.md
Labels: Version Specific

#2695 Update MigratePrep.md
  content/SCALE/GettingStarted/Migrate/MigratePrep.md
  content/SCALE/SCALETutorials/Shares/MixedModeShares.md
Labels: Technical Writer Review (MJ)

#2684 Update MigratePrep.md
  content/GettingStarted/Migrate/MigratePrep.md
Labels: Version Specific, Technical Writer Review (MJ)

#2697 Pd 1100 eol x series content
  content/Hardware/LegacyHardware/XSeries/BSG.md
  content/Hardware/LegacyHardware/XSeries/HANetworking.md
  content/Hardware/LegacyHardware/XSeries/NetworkPortIDs.md
  content/Hardware/LegacyHardware/XSeries/SOV.md
  content/Hardware/LegacyHardware/XSeries/Stencils.md
  content/Hardware/LegacyHardware/XSeries/_index.md
  content/Hardware/Notices/EndOfLifeAnnouncements.md
  content/Hardware/XSeries.md
  content/Hardware/_index.md
  static/images/Hardware/XSeries/XSeriesBSG.png
  static/images/Hardware/XSeries/XSeriesFront.png
  static/images/Hardware/XSeries/XSeriesHANetworking.png
  static/images/Hardware/XSeries/XSeriesSOV.png
  static/images/Hardware/XSeries/XSeriesStencil.png
Labels: Technical Writer Review (MJ)

#2685 Pd 1109 consolidate notices component articles under product families
  content/Hardware/MSeries.md
  content/Hardware/Notices/1300WPowerSupply.md
  content/Hardware/Notices/ComponentArticles/LSI9300Timeout.md
  content/Hardware/Notices/ComponentArticles/_index.md
  content/Hardware/Notices/NVDIMMUpdate.md
  content/Hardware/Notices/SB327.md
  content/Hardware/Notices/WDSMR.md
  content/Hardware/Notices/_index.md
  content/Hardware/RSeries.md
  static/images/Hardware/HardDrive.png
  static/images/Hardware/LSI9300xxFirmwareUpdatev1_0.png
  static/images/Hardware/Lock.png
  static/images/Hardware/NetworkPortID.png
  static/images/Hardware/Notices.png
  static/images/Hardware/Power.png
  static/images/Hardware/Update.png
  static/images/Hardware/ZseriesFront.png
  static/images/ixsystems_logo-logo-full-color-rgb.png
  static/images/ixsystemsbw.png
  words-to-ignore.txt
Labels: Technical Writer Review (MJ)
