Repository truenas/documentation, pull requests merged in 2024-09, with the labels that each got.

#2995 Update vCenterPlugin.md
  content/Solutions/Integrations/VMware/vCenterPlugin.md
Labels: Technical Writer Review (MJ)

#3025 Clarify TrueCommand Cloud alert-settings
  content/UserGuide/Alerts/AlertManage.md
Labels: Technical Writer Review (TR)

#3021 Pd 1375 min io enterprise and stable app updates
  content/TruenasApps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md
  content/TruenasApps/EnterpriseApps/MinIO/ConfigMinioEnterpriseSNMD.md
  content/TruenasApps/EnterpriseApps/MinIO/_index.md
  content/TruenasApps/_index.md
  static/images/SCALE/Apps/AppsDiscoverScreen.png
  static/images/SCALE/Apps/InstallMinIOAddMultiModeMNMD.png
  static/images/SCALE/Apps/InstallMinIOEnterprise.png
  static/images/SCALE/Apps/InstallMinIOEnterpriseMinioConfig.png
  static/images/SCALE/Apps/InstallMinIOEnterpriseStorageConfig.png
  static/images/SCALE/Apps/InstallMinIOEnterpriseStorageConfigSettings.png
  static/images/SCALE/Apps/InstallMinIOLoggingEnableLogSearch.png
  static/images/SCALE/Apps/InstallMinIONetworkConfig.png
  static/images/SCALE/Apps/InstallSyncthingAppWizard.png
  static/images/SCALE/Apps/MinIOEnterpriseInstalled.png
  static/images/SCALE/Apps/MinIOS3AppInfoScreen.png
  static/images/SCALE/Apps/MinioEnterpriseInfoScreen.png
  static/images/SCALE/Apps/SyncthingAppDetailsScreen.png
  static/images/SCALE/Apps/SyncthingEnterpriseAppDetailsScreen.png
  static/includes/AddMinioEnterpriseTrain.md
  static/includes/AddMultipleAppInstancesAndNaming.md
  static/includes/AppUserAndGroupConfig.md
  static/includes/AppsDockerCompose.md
  static/includes/MinIOEnterpriseFirstSteps.md
  static/includes/MinIOEnterpriseMinIOConfig.md
  static/includes/MinIOEnterpriseMultiModeBeforeYouBegin.md
  static/includes/MinIOEnterpriseMultiModeConfig.md
  static/includes/MinIOEnterpriseMultiModeConfig2.md.md
  static/includes/MinIOEnterpriseMultiModeConfig3.md
  static/includes/MinIOEnterpriseMultiModeConfigMNMD.md
  static/includes/MinIOEnterpriseNetworkConfig.md
  static/includes/MinIOEnterpriseStorageConfig.md
  static/includes/MinIoEnterpriseConfig1.md
  static/includes/MinIoEnterpriseConfig2.md
  static/includes/MinIoEnterpriseConfig3.md
  static/includes/MinIoEnterpriseConfig4.md
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#3023 PD-1418 24.04.2.1 Hot Patch Updates
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  static/includes/SCALEUpgradePaths.md
Labels: Version Specific, Review (TM)

#3037 24.04.2.2 Release Notes
  content/GettingStarted/SCALEReleaseNotes.md
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  static/includes/SCALEUpgradePaths.md
Labels: Version Specific, Technical Writer Review (TR)

#3039 24.04.2.2 release followup (24.10 branch)
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  static/includes/SCALEUpgradePaths.md
Labels: Version Specific, Technical Writer Review (TR)

#3033 PD-1452 / 24.10 / PD-1452 Backport Changes in PD-1380 to 24.10 Branch
  content/GettingStarted/Configure/SetUpBackupScale.md
  content/SCALETutorials/Credentials/BackupCredentials/AddSSHConnectionKeyPair.md
  content/SCALETutorials/DataProtection/RsyncTasksSCALE.md
  static/includes/AddManualSSHConnection.md
  static/includes/AddSSHConnection.md
Labels: Version Specific, Technical Writer Review (DP), Technical Writer Review (LM), Re-Review

#3045 Republish "24.04.2.2 Release Notes""
  content/GettingStarted/SCALEReleaseNotes.md
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  static/includes/SCALEUpgradePaths.md
Labels: Technical Writer Review (LM)

#3036 PD-1414 / 24.10 / PD-1414-point-2-c-is-very-badly-worded
  static/includes/AddManualSSHConnection.md
Labels: Technical Writer Review (MJ)

#3040 Add IQN allowed character convention to iSCSI ref snippet
  static/includes/iSCSIRef.md
Labels: Technical Writer Review (MJ), backport-24.10

#3041 Add IQN allowed character convention to iSCSI ref snippet (24.10)
  static/includes/iSCSIRef.md
Labels: Version Specific, Technical Writer Review (MJ)

#3053 PD-1420 / 25.04 / Pd1420 remove all remaining cli related documentation from the scale tutorials
  content/CORE/CORETutorials/DirectoryServices/ActiveDirectory.md
  content/CORE/CORETutorials/Storage/SED.md
  content/CORE/CORETutorials/Storage/Snapshots.md
  content/CORE/CORETutorials/Tasks/RunningSMARTTests.md
  content/CORE/GettingStarted/Install.md
  content/References/SMB.md
  content/References/ZFSDeduplication.md
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/_index.md
  content/SCALE/SCALETutorials/DataProtection/CreatingVMwareSnapshots.md
  content/SCALE/SCALETutorials/Storage/Disks/SEDScale.md
  content/Solutions/Integrations/Containers.md
  content/Solutions/Optimizations/Networking.md
  content/TruenasApps/Sandboxes.md
  static/includes/BrowsingSnapshotCollections1.md
  static/includes/TNDataCollection.md
Labels: Technical Writer Review (MJ)

#3054 PD-1426 / 13.0 / Pd 1426 plugins are broken clarify 13 0 13 3 docs for free bsd eo l feature status
  content/CORETutorials/JailsPluginsVMs/Jails/AccessingJailsUsingSSH.md
  content/CORETutorials/JailsPluginsVMs/Jails/CreatingJails.md
  content/CORETutorials/JailsPluginsVMs/Jails/InstallingJailSoftware.md
  content/CORETutorials/JailsPluginsVMs/Jails/ManagingJails.md
  content/CORETutorials/JailsPluginsVMs/Jails/SettingUpJailStorage.md
  content/CORETutorials/JailsPluginsVMs/Jails/_index.md
  content/CORETutorials/JailsPluginsVMs/Plugins/CreatingCustomPlugin.md
  content/CORETutorials/JailsPluginsVMs/Plugins/ManagingPlugins.md
  content/CORETutorials/JailsPluginsVMs/Plugins/MinIOPlugin.md
  content/CORETutorials/JailsPluginsVMs/Plugins/_index.md
  content/CORETutorials/JailsPluginsVMs/UpdateJailsPlugins.md
  content/CORETutorials/JailsPluginsVMs/_index.md
  content/UIReference/JailsPluginsVMs/Jails/JailsScreens.md
  content/UIReference/JailsPluginsVMs/Jails/_index.md
  content/UIReference/JailsPluginsVMs/Plugins/PluginsScreens.md
  content/UIReference/JailsPluginsVMs/Plugins/_index.md
  content/UIReference/JailsPluginsVMs/_index.md
  static/includes/COREFeatureSupport.md
Labels: Technical Writer Review (MJ)

#3055 PD-1426 / 13.3 / Pd 1426 plugins are broken clarify 13 0 13 3 docs for free bsd eo l feature
  static/includes/COREFeatureSupport.md
Labels: Technical Writer Review (MJ)

#3052 PD-1415 / 25.04 / Pd 1415 address sudo permissions with rootless login
  content/SCALE/SCALETutorials/Credentials/AdminRoles.md
  content/SCALE/SCALETutorials/Credentials/ManageLocalGroups.md
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  static/includes/AddAdminGroup.md
  static/includes/AddAdminUserAccount.md
  static/includes/AdminAccountSecurity.md
  static/includes/AdminSudo.md
Labels: Technical Writer Review (MJ), backport-24.10

#3057 PD-1466: (NAS-130436) pool expand on disk replace procedure
  content/SCALETutorials/Storage/ManagePoolsScale.md
  content/SCALEUIReference/Storage/_index.md
Labels: Technical Writer Review (MJ)

#3063 Update scale-releases.yaml (master)
  data/properties/scale-releases.yaml
Labels: backport-24.10

#3059 PD-1117: Add AI-Powered Search widget to Docs Hub (Master - Backport to active branches)
  layouts/partials/site-header.html
Labels: backport-24.10, backport-24.04, backport-23.10, backport-13.3, backport-13.0, backport-3.0

#3065 PD-1117 / 24.10 / Add AI-Powered Search widget to Docs Hub (Master - Backport …
  layouts/partials/site-header.html
Labels: backport-24.10, backport-24.04, backport-23.10, backport-13.3, backport-13.0, backport-3.0

#3078 PD-1474 / 24.04 / PD-1474-make-version-switcher-consistent-across-branches
  layouts/partials/docs-nav.html
Labels: backport-23.10, backport-13.3, backport-13.0, backport-3.0

#3058 PD-1415 / 25.04 / Pd 1415 address sudo permissions with rootless login (by DjP-iX) (by bugclerk)
  content/SCALE/SCALETutorials/Credentials/AdminRoles.md
  content/SCALE/SCALETutorials/Credentials/ManageLocalGroups.md
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  static/includes/AddAdminGroup.md
  static/includes/AddAdminUserAccount.md
  static/includes/AdminAccountSecurity.md
  static/includes/AdminSudo.md
Labels: Review (TM)

#3083 PD-1487 / 25.04 / replace minio plugin and migration content with EoL statement (master)
  content/CORE/CORETutorials/JailsPluginsVMs/Plugins/MinIOPlugin.md
  content/SCALE/GettingStarted/Migrate/MigratePrep.md
  content/Solutions/MinioCOREtoSCALE.md
  static/includes/S3Deprecation.md
  words-to-ignore.txt
Labels: Technical Writer Review (MJ), Re-Review

#3084 PD-1487 / 13.0 / Backport master branch changes and make additional 13.0 spec…
  content/CORETutorials/JailsPluginsVMs/Plugins/MinIOPlugin.md
  content/CORETutorials/Services/ConfiguringS3.md
  content/CORETutorials/Services/S3forMinIO.md
  content/GettingStarted/COREReleaseNotes.md
  content/GettingStarted/Deprecations.md
  content/UIReference/Services/S3Screen.md
  static/includes/S3Deprecation.md
Labels: Version Specific

#3085 PD-1487 / 13.3 / Backport to 13.3 master branch changes and make additional 13.3 spec…
  content/CORETutorials/JailsPluginsVMs/Plugins/MinIOPlugin.md
  content/CORETutorials/Services/ConfiguringS3.md
  content/CORETutorials/Services/S3forMinIO.md
  content/GettingStarted/COREReleaseNotes.md
  content/GettingStarted/Deprecations.md
  content/UIReference/Services/S3Screen.md
  static/includes/S3Deprecation.md
Labels: Version Specific, Technical Writer Review (MJ)
