Repository truenas/documentation, pull requests merged in 2024-06, with the labels that each got.

#2809 Pd 1161 expand usage collection documentation
  content/SCALE/GettingStarted/UserAgreements/DataCollectionStatement.md
  content/SCALE/SCALETutorials/SystemSettings/General/GeneralSettings.md
  content/SCALE/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  static/includes/SystemGeneralFields.md
  static/includes/TNDataCollection.md
Labels: Technical Writer Review (MJ)

#2812 Rework CORErelease notes for generic nightlies
  content/CORE/GettingStarted/COREReleaseNotes.md
Labels: Technical Writer Review (TR)

#2813 Follow up: Rework CORErelease notes for generic nightlies
  content/CORE/GettingStarted/COREReleaseNotes.md
Labels: Technical Writer Review (TR)

#2815 Pd 1128 expand cautions on custom catalog content
  content/SCALE/SCALETutorials/Apps/UsingCatalogs.md
  content/SCALE/SCALEUIReference/Apps/_index.md
  static/includes/ThirdPartyCatalogs.md
Labels: Technical Writer Review (TR)

#2816 Add known issue with apps connectivity to 24.04.1.1 notes
  content/GettingStarted/SCALEReleaseNotes.md
  words-to-ignore.txt
Labels: Version Specific, Technical Writer Review (TR)

#2820 Update README.md with specific Hugo version
  README.md
Labels: Technical Writer Review (TR)

#2821 Pd 1167 master 24 04 and 23 10 docs add content to apps about unversioned updating
  content/SCALE/SCALETutorials/Apps/AppSecurity/CloudflareTunnel.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/AddStorjNode.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/Chia.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/Collabora.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/Immich.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/InstallNetdataApp.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/InstallNextCloudMedia.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/InstallPiHoleApp.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/InstallWGEasyApp.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/MinIOApp/MinIOClustering.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/MinIOApp/MinioManualUpdate.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/MinIOApp/_index.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/PrometheusApp.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/Rsyncd.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/SyncthingCharts.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/TFTP-HPAApp.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/WebDAV.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/_index.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/ddns-updater.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/jellyfin.md
  content/SCALE/SCALETutorials/Apps/_index.md
  static/includes/AppsUnversioned.md
  static/includes/CommunityAppsContribute.md
Labels: Technical Writer Review (MJ)

#2822 Pd 1167 master 24 04 and 23 10 docs add content to apps about unversioned updating (port to 23.10)
  content/SCALETutorials/Apps/CommunityApps/AddStorjNode.md
  content/SCALETutorials/Apps/CommunityApps/Chia.md
  content/SCALETutorials/Apps/CommunityApps/Collabora.md
  content/SCALETutorials/Apps/CommunityApps/InstallNetdataApp.md
  content/SCALETutorials/Apps/CommunityApps/InstallNextCloudMedia.md
  content/SCALETutorials/Apps/CommunityApps/InstallPiHoleApp.md
  content/SCALETutorials/Apps/CommunityApps/InstallWGEasyApp.md
  content/SCALETutorials/Apps/CommunityApps/MinIOApp/MinIOClustering.md
  content/SCALETutorials/Apps/CommunityApps/MinIOApp/MinioManualUpdate.md
  content/SCALETutorials/Apps/CommunityApps/MinIOApp/_index.md
  content/SCALETutorials/Apps/CommunityApps/PrometheusApp.md
  content/SCALETutorials/Apps/CommunityApps/Rsyncd.md
  content/SCALETutorials/Apps/CommunityApps/SyncthingCharts.md
  content/SCALETutorials/Apps/CommunityApps/TFTP-HPAApp.md
  content/SCALETutorials/Apps/CommunityApps/WebDAV.md
  content/SCALETutorials/Apps/CommunityApps/_index.md
  content/SCALETutorials/Apps/CommunityApps/ddns-updater.md
  content/SCALETutorials/Apps/_index.md
  static/includes/AppsUnversioned.md
  static/includes/CommunityAppsContribute.md
Labels: Technical Writer Review (MJ)

#2823 Pd 1167 master 24 04 and 23 10 docs add content to apps about unversioned updating (port to 24.04)
  content/SCALETutorials/Apps/AppSecurity/CloudflareTunnel.md
  content/SCALETutorials/Apps/CommunityApps/AddStorjNode.md
  content/SCALETutorials/Apps/CommunityApps/Chia.md
  content/SCALETutorials/Apps/CommunityApps/Collabora.md
  content/SCALETutorials/Apps/CommunityApps/Immich.md
  content/SCALETutorials/Apps/CommunityApps/InstallNetdataApp.md
  content/SCALETutorials/Apps/CommunityApps/InstallNextCloudMedia.md
  content/SCALETutorials/Apps/CommunityApps/InstallPiHoleApp.md
  content/SCALETutorials/Apps/CommunityApps/InstallWGEasyApp.md
  content/SCALETutorials/Apps/CommunityApps/MinIOApp/MinIOClustering.md
  content/SCALETutorials/Apps/CommunityApps/MinIOApp/MinioManualUpdate.md
  content/SCALETutorials/Apps/CommunityApps/MinIOApp/_index.md
  content/SCALETutorials/Apps/CommunityApps/PrometheusApp.md
  content/SCALETutorials/Apps/CommunityApps/Rsyncd.md
  content/SCALETutorials/Apps/CommunityApps/SyncthingCharts.md
  content/SCALETutorials/Apps/CommunityApps/TFTP-HPAApp.md
  content/SCALETutorials/Apps/CommunityApps/WebDAV.md
  content/SCALETutorials/Apps/CommunityApps/_index.md
  content/SCALETutorials/Apps/CommunityApps/ddns-updater.md
  content/SCALETutorials/Apps/CommunityApps/jellyfin.md
  content/SCALETutorials/Apps/_index.md
  static/includes/AppsUnversioned.md
  static/includes/CommunityAppsContribute.md
Labels: Technical Writer Review (MJ)

#2831 Revert "Update docs-nav.html"
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#2853 PD-1202-update-sandbox-tutorial-for-jlmkr-v-2-0-0-script-manually-create-alias
  content/SCALE/SCALETutorials/Apps/Sandboxes.md
Labels: Review (TM)

#2854 Pd 1246 replace smb aux param suggestion with audit feature reference
  content/SCALE/SCALETutorials/SystemSettings/AuditingSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/SMBServiceSCALE.md
Labels: Review (TM)

#2855 PD-1202-follow-up
  content/SCALE/SCALETutorials/Apps/Sandboxes.md
Labels: Technical Writer Review (MJ)

#2856 Pd 1183 add additional info about how to clear the log from ipmi to get rid of the alert
  content/SCALE/SCALETutorials/Network/SettingUpIPMI.md
  content/SCALE/SCALEUIReference/SystemSettings/AlertsSettingsServiceScreen.md
  static/includes/AlertsCategories.md
  static/includes/IPMISELAlert.md
Labels: Technical Writer Review (MJ)

#2857 Pd 1238 publish thin provisioning reference
  content/CORE/UIReference/Storage/Pools/ZvolsScreen.md
  content/References/ThinProvisioning.md
  content/SCALE/SCALEUIReference/Datasets/ZvolsScreensScale.md
  content/Solutions/Integrations/Veeam.md
  static/images/Reference/SparseZvolScreencap.png
  words-to-ignore.txt
Labels: Technical Writer Review (MJ)

#2864 (24.04) PD-1259: Duplicated text in SCALE hardware guide
  static/includes/TNHardwareGuide.md
Labels: Version Specific

#2865 Pd 1181 review scale article content for opportunities to organically add seo terms
  content/SCALE/GettingStarted/Configure/FirstTimeLogin.md
  content/SCALE/GettingStarted/Configure/SetUpBackupScale.md
  content/SCALE/GettingStarted/Configure/SetUpSharing.md
  content/SCALE/GettingStarted/Configure/SetUpStorageScale.md
  content/SCALE/GettingStarted/Configure/UIConfigurationSCALE.md
  content/SCALE/GettingStarted/Configure/VMandAppConfigSCALE.md
  content/SCALE/GettingStarted/Install/ConsoleSetupMenuScale.md
  content/SCALE/GettingStarted/Install/InstallEnterpriseHASCALE.md
  content/SCALE/GettingStarted/Install/InstallPrepEnterprise.md
  content/SCALE/GettingStarted/Install/InstallPrepHomeUsers.md
  content/SCALE/GettingStarted/Install/InstallPrepNonEnterprise.md
  content/SCALE/GettingStarted/Install/InstallingSCALE.md
  content/SCALE/GettingStarted/Migrate/MigratePrep.md
  content/SCALE/GettingStarted/Migrate/MigratingFromCORE.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/jellyfin.md
  content/SCALE/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md
  content/SCALE/SCALETutorials/ConfigReportsScale.md
  content/SCALE/SCALETutorials/Credentials/AdminRoles.md
  content/SCALE/SCALETutorials/DataProtection/CreatingVMwareSnapshots.md
  content/SCALE/SCALETutorials/DataProtection/RsyncTasksSCALE.md
  content/SCALE/SCALETutorials/DataProtection/SMARTTestsSCALE.md
  content/SCALE/SCALETutorials/Datasets/DatasetsSCALE.md
  content/SCALE/SCALETutorials/Datasets/EncryptionSCALE.md
  content/SCALE/SCALETutorials/Datasets/ManageQuotas.md
  content/SCALE/SCALETutorials/Datasets/PermissionsSCALE.md
  content/SCALE/SCALETutorials/Network/Interfaces/SettingUpBridge.md
  content/SCALE/SCALETutorials/Network/Interfaces/SettingUpStaticIPs.md
  content/SCALE/SCALETutorials/Network/SettingUpIPMI.md
  content/SCALE/SCALETutorials/Shares/AddingNFSShares.md
  content/SCALE/SCALETutorials/Storage/CreatePoolWizard.md
  content/SCALE/SCALETutorials/Storage/Disks/SEDScale.md
  content/SCALE/SCALETutorials/Storage/ManagePoolsScale.md
  content/SCALE/SCALETutorials/SystemSettings/AuditingSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/General/GeneralSettings.md
  content/SCALE/SCALETutorials/SystemSettings/General/ManageSysConfigSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/ManageBootEnvironSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/FTPServiceSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Services/UPSServicesSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/UpdateSCALE.md
  content/SCALE/SCALETutorials/Virtualization/AccessingNASFromVM.md
  content/SCALE/SCALEUIReference/Credentials/Certificates/CSRScreensSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/PeriodicSnapshotTasksScreensSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/ReplicationScreensSCALE.md
  content/SCALE/SCALEUIReference/SCALEDashboard.md
  content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md
  content/SCALE/SCALEUIReference/Shares/iSCSISharesScreens.md
  content/SCALE/SCALEUIReference/Storage/_index.md
  content/SCALE/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/UpdateScreensSCALE.md
  content/SCALE/SCALEUIReference/VirtualizationScreens.md
  static/includes/SharingAdminRole.md
Labels: Technical Writer Review (MJ)
