Repository truenas/documentation, pull requests merged in 2024-02, with the labels that each got.

#2447 Pd 927 expand content passing system resources through to deployed apps
  content/SCALE/SCALETutorials/Apps/CommunityApps/Immich.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/jellyfin.md
  content/SCALE/SCALETutorials/Apps/_index.md
  content/SCALE/SCALETutorials/SystemSettings/Advanced/ManageGPUSCALE.md
  content/SCALE/SCALEUIReference/Apps/InstallCustomAppScreens.md
  content/SCALE/SCALEUIReference/Apps/_index.md
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  static/images/SCALE/Apps/ResourcesConfiguration.png
  static/images/SCALE/Apps/ResourcesConfigurationAllocateGPU.png
  static/images/SCALE/SystemSettings/AdvancedSettingIsolatedGPUDeviceWidget.png
  static/images/SCALE/SystemSettings/IsolatedGPUPCIIDsSelect.png
Labels: Review (TM)

#2457 Pd 833 review aws cloud sync tutorials core scale
  content/CORE/CORETutorials/Tasks/CreatingCloudSyncTasks.md
  content/CORE/UIReference/System/CloudCredentials.md
  content/SCALE/SCALETutorials/Credentials/BackupCredentials/AddCloudCredentials.md
  content/SCALE/SCALEUIReference/Credentials/BackupCredentials/CloudCredentialScreens.md
Labels: Review (TM)

#2464 PD-928 Behavior change in nfs.config `servers` field
  content/SCALE/SCALETutorials/SystemSettings/Services/NFSServiceSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md
  static/images/SCALE/SystemSettings/ServicesNFSSettingsScreen.png
Labels: Review (TM)

#2453 PD-980: 24.04-BETA.1 Release Notes (Don't merge before release)
  content/SCALE/GettingStarted/Migrate/MigrateCOREHAtoSCALEHA.md
  content/SCALE/GettingStarted/Migrate/MigratePrep.md
  content/SCALE/GettingStarted/Migrate/MigratePrepEnterprise.md
  content/SCALE/GettingStarted/Migrate/MigratingFromCORE.md
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigLDAPSCALE.md
  content/SCALE/_index.md
  content/_includes/24.04FeatureList.md
  content/_includes/24.04UpgradeMethods.md
  content/_includes/MigrateCOREtoSCALEWarning.md
  content/_includes/MigrateCoreServicesToCobia.md
  content/_includes/RootToAdminUserAccount.md
  layouts/shortcodes/section-cards.html
  words-to-ignore.txt
Labels: Version Specific

#2482 PD-1020: review and clarify SMB1 deprecation caution.
  content/References/SMB.md
  content/SCALE/GettingStarted/Configure/SetUpSharing.md
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBHomeShare.md
  content/SCALE/SCALETutorials/Shares/SMB/_index.md
  content/SCALE/SCALETutorials/SystemSettings/Services/SMBServiceSCALE.md
  content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/SMBServicesScreen.md
  content/_includes/SMBShareMSDOSalert.md
Labels: Technical Writer Review (DP)

#2484 PD-1020: Backport SMB1 warning clarification (23.10 branch)
  content/GettingStarted/Configure/SetUpSharing.md
  content/SCALETutorials/Shares/SMB/AddSMBHomeShare.md
  content/SCALETutorials/Shares/SMB/AddSMBShares.md
  content/SCALETutorials/SystemSettings/Services/SMBServiceSCALE.md
  content/SCALEUIReference/Shares/SMBSharesScreens.md
  content/SCALEUIReference/SystemSettings/Services/SMBServicesScreen.md
  content/_includes/SMBShareMSDOSalert.md
Labels: Version Specific

#2485 PD-1020: Backport SMB1 warning clarification (22.12 branch)
  content/GettingStarted/Configure/SetUpSharing.md
  content/SCALETutorials/Shares/SMB/AddSMBHomeShare.md
  content/SCALETutorials/Shares/SMB/AddSMBShares.md
  content/SCALETutorials/SystemSettings/Services/SMBServiceSCALE.md
  content/SCALEUIReference/Shares/SMBSharesScreens.md
  content/SCALEUIReference/SystemSettings/Services/SMBServicesScreen.md
  content/_includes/SMBShareMSDOSalert.md
Labels: Version Specific

#2488 PD-1013: backport style improvements and update 3.0 branch pagefind implementation
  jenkins/update-3.0
  static/js/search.js
Labels: Version Specific

#2490 PD-1013: More search cleanup
  static/js/search.js
Labels: Version Specific

#2491 PD-1013: Reset 3.0 branch to lunr.js search
  jenkins/update-3.0
  static/js/search.js
Labels: Version Specific

#2493 PD-1013: Retry pagefind on TC 3.0 branch
  jenkins/update-3.0
  layouts/_default/baseof.html
  layouts/_default/baseof.print.html
  layouts/search/list.html
  static/custom.css
  static/js/search.js
Labels: Version Specific

#2501 Pd 1010 update advanced replication article and index
  content/SCALE/SCALETutorials/DataProtection/Replication/AdvancedReplication/UseAdvancedReplicationSCALE.md
  content/SCALE/SCALETutorials/DataProtection/Replication/AdvancedReplication/_index.md
  content/_includes/BasicReplicationProcess.md
  content/_includes/ReplicationCreateDatasetAndAdminHomeDirSteps.md
  content/_includes/ReplicationIndexContentSCALE.md
  content/_includes/ReplicationIntroSCALE.md
  words-to-ignore.txt
Labels: Review (TM)

#2499 Pd 1011 update core to scale migration articles
  content/SCALE/GettingStarted/Migrate/MigrateCOREHAtoSCALEHA.md
  content/SCALE/GettingStarted/Migrate/MigratePrep.md
  content/SCALE/GettingStarted/Migrate/MigratingFromCORE.md
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/_includes/AddAdminUserAccount.md
  content/_includes/MigrateCoreServicesToCobia.md
  content/_includes/RootToAdminUserAccount.md
  static/images/SCALE/Credentials/AddAuxiliaryGroupAdminUserSettings.png
  words-to-ignore.txt
Labels: Review (TM)
