Repository truenas/documentation, pull requests merged in 2024-05, with the labels that each got.

#2699 Pd 1100 eol x series content
  content/Hardware/LegacyHardware/XSeries.md
  content/Hardware/LegacyHardware/XSeries/BSG.md
  content/Hardware/LegacyHardware/XSeries/HANetworking.md
  content/Hardware/LegacyHardware/XSeries/NetworkPortIDs.md
  content/Hardware/LegacyHardware/XSeries/SOV.md
  content/Hardware/LegacyHardware/XSeries/Stencils.md
  content/Hardware/LegacyHardware/XSeries/_index.md
Labels: Technical Writer Review (TR)

#2703 Update api docs 13.3
  content/CORETutorials/SettingUIPreferences.md
  content/UIReference/ReportingGraphs.md
  content/UIReference/Sharing/iSCSI/FibreChannel.md
  content/UIReference/Storage/SnapshotsScreen.md
  content/UIReference/TopMenu/UIPreferences.md
  static/api/core_websocket_api.html
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#2704 Backport Resilvering Updates to 13.3
  content/CORETutorials/Tasks/UsingResilverPriority.md
  content/GettingStarted/SharingStorage.md
  content/UIReference/Storage/SnapshotsScreen.md
  static/includes/ResilverPriority.md
  static/includes/ResilverPrioritySetWhen.md
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#2705 Backport MinIO App Migration Tutorial to 13.3
  content/CORETutorials/JailsPluginsVMs/Plugins/MinIOPlugin.md
  static/images/CORE/Plugins/MinioMountPoint.png
  static/includes/S3Deprecation.md
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#2701 Pd 1068 acme dns authenticators 13.0
  content/CORETutorials/SystemConfiguration/ConfiguringACMEDNS.md
  content/UIReference/System/ACMEDNS.md
Labels: Technical Writer Review (TR)

#2707 Pd 1136 update 24 04 release notes guidance on user home directory change
  content/GettingStarted/SCALEReleaseNotes.md
  content/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALETutorials/Shares/SMB/AddSMBHomeShare.md
  static/includes/24.04HomeDirectory.md
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#2702 Pd 1068 acme dns authenticators 13.3
  content/CORETutorials/ChangingDefaultShell.md
  content/CORETutorials/SystemConfiguration/ConfiguringACMEDNS.md
  content/CoreSecurityReports/SMB1Advisory.md
  content/UIReference/System/ACMEDNS.md
  words-to-ignore.txt
Labels: Technical Writer Review (TR), Technical Writer Review (MJ)

#2711 Update SettingUpLetsEncryptCertificates.md
  content/SCALE/SCALETutorials/Credentials/Certificates/SettingUpLetsEncryptCertificates.md
Labels: Technical Writer Review (TR)

#2713 PD-1088 Update CORE Email Article Content - 13.3
  content/CORETutorials/SystemConfiguration/ConfiguringtheSystemEmail.md
  content/UIReference/System/Email.md
  static/includes/EmailOptionsSMTP.md
  static/includes/SystemEmailFields.md
Labels: Technical Writer Review (TR)

#2712 PD-1088 Update CORE Email Article Content - Master
  content/CORE/CORETutorials/SystemConfiguration/ConfiguringtheSystemEmail.md
  content/CORE/UIReference/System/Email.md
  static/includes/EmailOptionsSMTP.md
  static/includes/SystemEmailFields.md
Labels: Technical Writer Review (TR)

#2719 Update core-releases.yaml (13.3 branch backport)
  data/properties/core-releases.yaml
Labels: Version Specific

#2716 Pd 1046 archive 22 12 documentation 22.12
  content/_index.md
  i18n/en.yaml
  layouts/partials/docs-nav.html
  layouts/partials/page-header.html
Labels: Technical Writer Review (TR)

#2717 Pd 1046 archive 22 12 documentation
  content/Archive.md
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#2722 Pd 1046 archive 22 12 documentation 24.04
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#2723 Pd 1046 archive 22 12 documentation 23.10
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#2724 Pd 1046 archive 22 12 documentation 13.3
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#2726 Pd 1046 archive 22 12 documentation 3.0
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#2728 Add anticipated feature
  static/includes/24.10FeatureList.md
Labels: Technical Writer Review (TR)

#2727 Pd 1046 archive 22 12 documentation 2.3
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#2721 Pd 1106 follow up 24.04
  content/GettingStarted/SCALEReleaseNotes.md
  layouts/shortcodes/UpgradePaths.html
  static/includes/SCALEUpgradePaths.md
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#2710 Pd 1106 13 3 beta 1 release notes main
  content/CORE/CORETutorials/UpdatingTrueNAS/UpdatingCORE.md
  content/CORE/CORETutorials/UpdatingTrueNAS/UpdatingENTERPRISE.md
  content/CORE/CORETutorials/UpdatingTrueNAS/UpdatingSoftwareforaMajorVersion.md
  content/CORE/CORETutorials/UpdatingTrueNAS/_index.md
  content/CORE/GettingStarted/COREReleaseNotes.md
  content/CORE/GettingStarted/Deprecations.md
  content/CORE/GettingStarted/Install.md
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
  content/Solutions/Integrations/Veeam.md
  content/TrueNASUpgrades/_index.md
  content/_archive/COREReleaseNotes/12.0/12.0U6.md
  content/_archive/COREReleaseNotes/12.0/12.0U7.md
  content/_archive/COREReleaseNotes/12.0/12.0U8.1.md
  content/_archive/COREReleaseNotes/12.0/12.0U8.md
  data/properties/core-releases.yaml
  layouts/shortcodes/UpgradePaths.html
  static/api/core_rest_api.html
  static/api/core_websocket_api.html
  static/images/CORE/DownloadLatest.png
  static/includes/13.3Overview.md
  static/includes/COREUpgradePaths.md
  static/includes/EarlyReleaseWarning.md
  static/includes/SCALEUpgradePaths.md
  words-to-ignore.txt
Labels: Version Specific

#2734 Pd 1153 refresh the home page
  content/_index.md
  layouts/_default/baseof.html
  static/images/Software_Status_Icon_2.png
Labels: Technical Writer Review (TR)

#2735 Pd 1131 clean up references to true nas console in scale local users tutorial
  content/SCALE/SCALECLIReference/_index.md
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/UseScaleShell.md
  content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
  static/includes/AddAdminUserAccount.md
Labels: Technical Writer Review (TR)

#2730 Pd 1155 add trivial alias
  content/search/_index.md
  static/js/search.js
Labels: Technical Writer Review (TR)

#2733 13.3-BETA1 Port updates to 13.3
  content/GettingStarted/COREReleaseNotes.md
  data/properties/core-releases.yaml
Labels: Technical Writer Review (TR)

#2736 Pd 1131 clean up references to true nas console in scale local users tutorial 24.04
  content/SCALECLIReference/_index.md
  content/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALETutorials/SystemSettings/UseScaleShell.md
  content/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
  static/includes/AddAdminUserAccount.md
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#2737 Update COREReleaseNotes.md
  content/CORE/GettingStarted/COREReleaseNotes.md
Labels: Technical Writer Review (TR)

#2739 Mermaid rescue 24.04
  content/GettingStarted/SCALEReleaseNotes.md
  layouts/shortcodes/UpgradePaths.html
  static/includes/SCALEUpgradePaths.md
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#2740 Mermaid rescue 13.3
  content/GettingStarted/COREReleaseNotes.md
  layouts/shortcodes/UpgradePaths.html
  static/includes/COREUpgradePaths.md
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#2741 Pd 1122 review any storj logos in docs and update
  content/SCALE/SCALETutorials/Apps/CommunityApps/AddStorjNode.md
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddStorjCloudSyncTask.md
  layouts/partials/site-header.html
  static/images/SCALE/DataProtection/StorjAccessManagementScreen.png
  static/images/SCALE/DataProtection/StorjAddBucket.png
  static/images/SCALE/DataProtection/StorjAddNewBucket.png
  static/images/SCALE/DataProtection/StorjBucketAdded.png
  static/images/SCALE/DataProtection/StorjCreateABucketScreen.png
  static/images/SCALE/DataProtection/StorjCreateAccessDownloadedEncryptionPassphrase.png
  static/images/SCALE/DataProtection/StorjCreateAccessEncryptionDialog.png
  static/images/SCALE/DataProtection/StorjCreateAccessSelectBuckets.png
  static/images/SCALE/DataProtection/StorjCreateAccessSelectDuration.png
  static/images/SCALE/DataProtection/StorjCreateAccessSelectEncryptionOptions.png
  static/images/SCALE/DataProtection/StorjCreateAccessWindow.png
  static/images/SCALE/DataProtection/StorjCreateNewTrueNASAccount.png
  static/images/SCALE/DataProtection/StorjCreateS3Access.png
  static/images/SCALE/DataProtection/StorjEncryptYourBucketScreen.png
  static/images/SCALE/DataProtection/StorjGenerateAPassphraseScreen.png
  static/images/SCALE/DataProtection/StorjMainDashboard.png
  static/images/SCALE/DataProtection/StorjNewBucketScreen.png
  static/images/SCALE/DataProtection/StorjS3ConfirmDetails.png
  static/images/SCALE/DataProtection/StorjS3CredentialsGenerated.png
  static/images/SCALE/DataProtection/StorjSignInScreen.png
  static/images/SCALE/Login/StorjHostaNode.png
  static/includes/CloudServiceProvidersCORE.md
  static/includes/CloudServiceProvidersSCALE.md
Labels: Technical Writer Review (TR)

#2745 Update ConfigureController1Networking.md
  static/includes/ConfigureController1Networking.md
Labels: Technical Writer Review (TR)

#2742 PD-1138-remove-ssh-service-tuning-recommendations
  content/CORE/CORETutorials/Services/ConfiguringSSH.md
Labels: Technical Writer Review (TR)

#2743 PD-1138-remove-ssh-service-tuning-recommendations-13.3
  content/CORETutorials/Services/ConfiguringSSH.md
Labels: Technical Writer Review (TR)

#2744 Pd 1053 update data ingest content for smb alternate data streams support
  content/SCALE/GettingStarted/DataMigrationSyncthing.md
  content/Solutions/MigratingToTrueNAS.md
  layouts/shortcodes/section-cards.html
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#2746 Add Enterprise-specific issue box
  layouts/shortcodes/enterprise-error.html
Labels: Technical Writer Review (TR), Backport Requested

#2747 Create enterprise-error.html (24.04 backport)
  layouts/shortcodes/enterprise-error.html
Labels: Version Specific, Technical Writer Review (TR)

#2748 Add enterprise-error shortcode (13.3 backport)
  content/GettingStarted/COREReleaseNotes.md
  layouts/shortcodes/enterprise-error.html
Labels: Version Specific, Technical Writer Review (TR)

#2753 PD-1162-add-known-issue-to-24-04-0-release-notes-about-swap-and-performance-issues
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Technical Writer Review (TR)

#2757 PD-1162-add-known-issue-to-24-04-0-release-notes-about-swap-and-performance-issues
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Technical Writer Review (TR)

#2750 PD-1124 Update Hardware Guide Snippet
  static/includes/TNHardwareGuide.md
Labels: Technical Writer Review (DP)

#2752 PD-1124 Backport TNHardwareGuide.md Changes to 24.04
  static/includes/TNHardwareGuide.md
Labels: Technical Writer Review (DP)

#2754 PD-1151 Update Nextcloud Tutoiral
  content/SCALE/SCALETutorials/Apps/CommunityApps/InstallNextCloudMedia.md
  static/images/SCALE/Apps/AppsAddNextcloudDatasets.png
  static/images/SCALE/Apps/InstallNextcloudAddExtraHostPathVolume.png
  static/images/SCALE/Apps/InstallNextcloudConfigAddInstallffmpetCommand.png
  static/images/SCALE/Apps/InstallNextcloudConfigUsernamePassword.png
  static/images/SCALE/Apps/InstallNextcloudEnableHostPath.png
  static/images/SCALE/Apps/InstallNextcloudScreen.png
  static/images/SCALE/Apps/InstallNextcloudStorageConfigPostgressHostPaths.png
  static/images/SCALE/Apps/LocateNextcloudAppWidget.png
  static/images/SCALE/Datasets/AppsAddNextcloudDatasets.png
Labels: Technical Writer Review (DP)

#2776 Update SCALEInstallerProcedure.md
  static/includes/SCALEInstallerProcedure.md
Labels: Version Specific, Technical Writer Review (TR)

#2772 PD-1179 Update Hardware _index.md Articles With SEO
  content/Hardware/ExpansionShelves.md
  content/Hardware/FSeries.md
  content/Hardware/HSeries.md
  content/Hardware/MSeries.md
  content/Hardware/MiniFamily.md
  content/Hardware/RSeries.md
  layouts/shortcodes/prodintro.html
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#2779 Update iXsystemsSupportContact.md
  static/includes/iXsystemsSupportContact.md
Labels: Technical Writer Review (TR)

#2775 Pd 1023 port 13.3
  content/CORETutorials/CommunityGuides/_index.md
  content/CORETutorials/JailsPluginsVMs/Jails/_index.md
  content/CORETutorials/JailsPluginsVMs/Plugins/_index.md
  content/CORETutorials/JailsPluginsVMs/VirtualMachines/_index.md
  content/CORETutorials/JailsPluginsVMs/_index.md
  content/CORETutorials/Network/Interfaces/_index.md
  content/CORETutorials/Network/_index.md
  content/CORETutorials/Services/_index.md
  content/CORETutorials/Sharing/SMB/_index.md
  content/CORETutorials/Sharing/_index.md
  content/CORETutorials/Sharing/iSCSI/_index.md
  content/CORETutorials/Storage/Pools/_index.md
  content/CORETutorials/SystemConfiguration/CreatingCAsandCertificates/_index.md
  content/CORETutorials/_index.md
  content/CoreSecurityReports/_index.md
  content/GettingStarted/UserAgreements/_index.md
  content/GettingStarted/_index.md
  content/UIReference/Accounts/_index.md
  content/UIReference/DirectoryServices/_index.md
  content/UIReference/JailsPluginsVMs/_index.md
  content/UIReference/Network/_index.md
  content/UIReference/Services/_index.md
  content/UIReference/Sharing/_index.md
  content/UIReference/Sharing/iSCSI/_index.md
  content/UIReference/Storage/Pools/_index.md
  content/UIReference/Storage/_index.md
  content/UIReference/System/_index.md
  content/UIReference/Tasks/_index.md
  content/UIReference/TopMenu/_index.md
  content/UIReference/_index.md
  layouts/_default/baseof.print.html
  layouts/partials/print/content.html
  layouts/partials/print/render.html
  layouts/shortcodes/releaselist.html
Labels: Technical Writer Review (TR)

#2777 PD-1158-re-add-core-12-0-to-upgrade-paths-and-release-lists
  static/includes/COREUpgradePaths.md
Labels: Technical Writer Review (TR)

#2778 Pd 1158 port re add core 12 0 to upgrade paths and release lists 13.3
  data/properties/core-releases.yaml
  static/includes/COREUpgradePaths.md
Labels: Technical Writer Review (TR)

#2780 PD-1178-replace-gold-support-number-on-support-contact-snippets-24.04
  static/includes/iXsystemsSupportContact.md
Labels: Technical Writer Review (TR)

#2781 PD-1178-replace-gold-support-number-on-support-contact-snippets-23.10
  static/includes/iXsystemsSupportContact.md
Labels: Technical Writer Review (TR)

#2782 PD-1178-replace-gold-support-number-on-support-contact-snippets-22.12
  static/includes/iXsystemsSupportContact.md
Labels: Technical Writer Review (TR)

#2783 PD-1178-replace-gold-support-number-on-support-contact-snippets-3.0
  static/includes/iXsystemsSupportContact.md
Labels: Technical Writer Review (TR)

#2784 PD-1178-replace-gold-support-number-on-support-contact-snippets-2.3
  static/includes/iXsystemsSupportContact.md
Labels: Technical Writer Review (TR)

#2785 PD-1178-replace-gold-support-number-on-support-contact-snippets-13.3
  static/includes/iXsystemsSupportContact.md
Labels: Technical Writer Review (TR)

#2786 PD-1178-replace-gold-support-number-on-support-contact-snippets-13.0
  static/includes/iXsystemsSupportContact.md
Labels: Technical Writer Review (TR)

#2790 Update ReportingScreensSCALE.md
  content/SCALE/SCALEUIReference/ReportingScreensSCALE.md
Labels: Technical Writer Review (TR)

#2789 Fix document issues in Master
  content/SCALE/SCALEUIReference/Credentials/Certificates/CertificatesScreensSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/PeriodicSnapshotTasksScreensSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/ReplicationScreensSCALE.md
  content/SCALE/SCALEUIReference/Datasets/EncryptionUISCALE.md
  static/images/SCALE/Virtualization/CloneVMDialog.png
Labels: Technical Writer Review (TR)

#2797 24.04.1 Known Issue with Apps Service start
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific

#2799 (24.04) Update SCALEUpgradePaths.md
  data/properties/scale-releases.yaml
  static/includes/SCALEUpgradePaths.md
Labels: Version Specific

#2803 Update release dates for 24.04.2 and 24.10 anticipated releases.
  data/properties/scale-releases.yaml
Labels: Technical Writer Review (TR)

#2804 (24.04 docs) Update Enterprise apps messaging with single-source snippet
  content/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md
  content/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseSNMD.md
  content/SCALETutorials/Apps/EnterpriseApps/MinIO/_index.md
  content/SCALETutorials/Apps/EnterpriseApps/Syncthing.md
  content/SCALETutorials/Apps/EnterpriseApps/_index.md
  static/includes/SCALEEnterpriseApps.md
Labels: Version Specific, Technical Writer Review (TR)

#2802 Single-source and clarify Enterprise app messaging (backporting needed)
  content/SCALE/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md
  content/SCALE/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseSNMD.md
  content/SCALE/SCALETutorials/Apps/EnterpriseApps/MinIO/_index.md
  content/SCALE/SCALETutorials/Apps/EnterpriseApps/Syncthing.md
  content/SCALE/SCALETutorials/Apps/EnterpriseApps/_index.md
  static/includes/SCALEEnterpriseApps.md
Labels: Backport Requested

#2805 (23.10 docs) Update Enterprise apps messaging with single-source snippet
  content/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md
  content/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseSNMD.md
  content/SCALETutorials/Apps/EnterpriseApps/MinIO/_index.md
  content/SCALETutorials/Apps/EnterpriseApps/Syncthing.md
  content/SCALETutorials/Apps/EnterpriseApps/_index.md
  static/includes/SCALEEnterpriseApps.md
Labels: Version Specific

#2806 13.3 branch cleanups
  content/API/_index.md
  content/CORETutorials/ManagingTLSCiphers.md
  content/CORETutorials/UpdatingTrueNAS/_index.md
  content/GettingStarted/COREReleaseNotes.md
  content/GettingStarted/UserAgreements/COREEULA.md
  content/GettingStarted/UserAgreements/EnterpriseEULA.md
  content/GettingStarted/UserAgreements/SofDevLifecycle.md
  content/UIReference/Network/GlobalConfigScreen.md
  content/UIReference/Network/NetworkSummaryScreen.md
  content/UIReference/ReportingGraphs.md
  content/UIReference/Services/DynamicDNSScreen.md
  content/UIReference/Services/SNMPScreen.md
  content/UIReference/Services/ServicesSSH.md
  content/UIReference/Sharing/AFPShareScreen.md
  content/UIReference/Sharing/NFSShareScreen.md
  content/UIReference/Sharing/SMBShareScreen.md
  content/UIReference/Sharing/WebDAVShareScreen.md
  content/UIReference/Sharing/iSCSI/FibreChannel.md
  content/UIReference/Sharing/iSCSI/_index.md
  content/UIReference/Sharing/iSCSI/iSCSIShare.md
  content/UIReference/Storage/DisksScreens.md
  content/UIReference/Storage/Pools/_index.md
  content/UIReference/System/BootScreen.md
  content/UIReference/System/General.md
  content/UIReference/System/KMIP.md
  content/UIReference/System/Reporting.md
  content/UIReference/System/SSHKeypairs.md
  content/UIReference/Tasks/_index.md
  content/UIReference/TopMenu/UIPreferences.md
  content/_index.md
  jenkins/update-core-13.3
  static/js/search.js
Labels: Version Specific, Technical Writer Review (TR)

#2807 Expand debug generate with SCALE CLI (midcli) instruction
  static/includes/CreateDebugSCALE.md
Labels: Technical Writer Review (TR)
