Repository truenas/documentation, pull requests merged in 2024-07, with the labels that each got.

#2866 PD-1219-remove-references-to-special-vdev-hot-spare-support
  static/includes/FusionPools.md
Labels: Technical Writer Review (MJ)

#2848 PD-1125 Create IPv6 Configuration and Reference Content
  content/References/IPv6.md
  content/SCALE/SCALETutorials/Network/ConfigureIPv6.md
  content/SCALE/SCALETutorials/Network/Interfaces/ManagingInterfaces.md
  content/SCALE/SCALETutorials/Network/ManagingGlobalConfig.md
  static/images/SCALE/Network/ConfigureIPv6InterfaceWithConsoleSetupMenu.png
  words-to-ignore.txt
Labels: Technical Writer Review (DP)

#2869 Add 13.0 Known issue and workaround
  content/GettingStarted/COREReleaseNotes.md
Labels: Version Specific

#2868 PD-1180-investigate-implementing-slug-for-docs-website-ur-ls
  content/CORE/CORETutorials/SystemConfiguration/ManagingBootEnvironments.md
  content/CORE/CORETutorials/SystemConfiguration/MirroringtheBootPool.md
  content/CORE/CORETutorials/SystemConfiguration/SettingtheSystemDataset.md
Labels: Technical Writer Review (MJ)

#2870 Port Add Route53 action names to SettingUpLetsEncryptCertificates.md to Master
  content/SCALE/SCALETutorials/Credentials/Certificates/SettingUpLetsEncryptCertificates.md
Labels: Review (TM)

#2871 PD-1262: 13.0-U6.2 release notes
  content/GettingStarted/COREReleaseNotes.md
  words-to-ignore.txt
Labels: Version Specific, Technical Writer Review (MJ)

#2863 Pd 1271 create content on contributing to apps
  content/SCALE/SCALETutorials/Apps/AppContributions.md
Labels: Technical Writer Review (DP)

#2874 Pd 1208 review in detail the rsync task creation via ssh mode
  content/SCALE/SCALETutorials/DataProtection/RsyncTasksSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/RsyncTasksScreensSCALE.md
Labels: Technical Writer Review (MJ)

#2873 PD-1203 Updates to Storj App Content
  content/SCALE/SCALETutorials/Apps/CommunityApps/AddStorjNode.md
  static/images/SCALE/Apps/InstallApplicationsStorjSCALE.png
  static/images/SCALE/Apps/InstallStojConfigurationScreen.png
  static/images/SCALE/Apps/InstallStorjAppConfigSCALE.png
  static/images/SCALE/Apps/InstallStorjAppNameSCALE.png
  static/images/SCALE/Apps/InstallStorjAppNetworkingSCALE.png
  static/images/SCALE/Apps/InstallStorjAppScreen.png
  static/images/SCALE/Apps/InstallStorjAppStorageSCALE.png
  static/images/SCALE/Apps/InstallStorjNetworkConfig.png
  static/images/SCALE/Apps/InstallStorjStorageACLEntry.png
  static/images/SCALE/Apps/LocateStorjAppWidget.png
  static/images/SCALE/Apps/StorjAppDetailsScreen.png
  static/images/SCALE/Datasets/AddDatasetStorjSCALE.png
Labels: Technical Writer Review (DP)

#2876 PD-1264-fix-ambiguity-with-ftp-documentation
  content/SCALE/SCALETutorials/SystemSettings/Services/FTPServiceSCALE.md
Labels: Technical Writer Review (MJ)

#2888 Update SCALEUpgradePaths.md
  static/includes/SCALEUpgradePaths.md
Labels: Review (TM)

#2867 Adjusted Google SAML TrueCommand attribute options
  content/TrueCommand/AdminGuide/Admin/SAML/SAMLGA.md
Labels: Technical Writer Review (MJ)

#2889 Clarify AddSMBHomeShare.md
  content/SCALETutorials/Shares/SMB/AddSMBHomeShare.md
Labels: Review (TM)

#2890 Port AddSMBHomeShare.md updates from 24.04
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBHomeShare.md
Labels: Review (TM)

#2903 Pd 1234 update security site header footer 3.0
  config.toml
  layouts/partials/site-footer.html
  layouts/partials/site-header.html
  static/favicon/Discord-Logo-White.png
  static/favicon/TN-favicon-32x32.png
  static/favicon/TNEnt-favicon-32x32.png
  static/favicon/Where_To_Buy_Icon_White.webp
  static/favicon/f-series.png
  static/favicon/github.png
  static/favicon/h-series.png
  static/images/TrueNAS_Open_Enterprise_Storage.png
Labels: Technical Writer Review (MJ)

#2907 AuditingSCALE.md - fix Unlink Events text (24.04)
  content/SCALETutorials/SystemSettings/AuditingSCALE.md
Labels: Version Specific

#2895 PD 1254 update-images-for-metadata-and-dedup-to-show-having-layout-drop-downs
  static/images/SCALE/Storage/PoolCreationWizardDedupScreen.png
  static/images/SCALE/Storage/PoolCreationWizardMetadataScreen.png
Labels: Technical Writer Review (DP)

#2896 Pd 1254 update images for metadata and dedup to show having layout drop downs-24.04
  static/images/SCALE/Storage/PoolCreationWizardDedupScreen.png
  static/images/SCALE/Storage/PoolCreationWizardMetadataScreen.png
Labels: Technical Writer Review (DP)

#2909 Pd 1163 expand local build contributing content
  README.md
  content/Contributing/Documentation/ContentUpdate.md
Labels: Technical Writer Review (MJ)

#2893 Pd 1257 backup to google photos must select albums as destination folder
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/AddGooglePhotosCloudSyncTask.md
  content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  static/images/SCALE/DataProtection/CloudSyncTaskWizardProviderScreen.png
  static/images/SCALE/DataProtection/CloudSyncTaskWizardWhatandWhenScreen.png
  static/images/SCALE/DataProtection/GooglePhotosAPIAddCloudCredentials.png
  static/images/SCALE/DataProtection/GooglePhotosAPIAddCredentials.png
  static/images/SCALE/DataProtection/GooglePhotosAPIAddTestingUser.png
  static/images/SCALE/DataProtection/GooglePhotosAPIAppInformation.png
  static/images/SCALE/DataProtection/GooglePhotosAPIClickEnable.png
  static/images/SCALE/DataProtection/GooglePhotosAPICopyIDandSecret.png
  static/images/SCALE/DataProtection/GooglePhotosAPICreateExternal.png
  static/images/SCALE/DataProtection/GooglePhotosAPICreateOAuthClientID.png
  static/images/SCALE/DataProtection/GooglePhotosAPIDeveloperContactInformation.png
  static/images/SCALE/DataProtection/GooglePhotosAPIEnableAPIsandServices.png
  static/images/SCALE/DataProtection/GooglePhotosAPINewProject.png
  static/images/SCALE/DataProtection/GooglePhotosAPIPhotosLibraryAPISearch.png
  static/images/SCALE/DataProtection/GooglePhotosAPIPublish.png
  static/images/SCALE/DataProtection/GooglePhotosAPIrcloneConfig.png
  static/images/SCALE/DataProtection/GooglePhotosAPIrcloneConfig2.png
  static/images/SCALE/DataProtection/GooglePhotosAPIrcloneConfig3.png
  static/includes/CreateCloudSyncTaskScale.md
Labels: Technical Writer Review (MJ)

#2918 PD-1292: fix missing favicon in 13.0 docs
  static/favicon/phone_menu_25_sq.webp
Labels: Version Specific

#2912 PD-1292: fix a broken link on TC 3.0 docs home page
  content/_index.md
Labels: Version Specific

#2913 PD-1292: fix broken links in version 13.3 docs
  content/API/_index.md
  content/CORETutorials/Storage/Pools/ManagingPools.md
  static/includes/COREDocsSections.md
Labels: Version Specific

#2915 PD-1292: fix broken link in 23.10 docs
  content/GettingStarted/Migrate/MigratingFromCORE.md
Labels: Version Specific

#2916 PD-1292: fix broken image links on 22.12 docs
  content/SCALETutorials/Shares/SMB/AddSMBShares.md
  static/favicon/phone_menu_25_sq.webp
Labels: Version Specific

#2914 PD-1292: fix broken links in 24.04 docs
  content/GettingStarted/Migrate/MigratingFromCORE.md
  content/SCALETutorials/Apps/AppSecurity/CloudflareTunnel.md
Labels: Version Specific

#2917 PD-1292: Add missing favicon to 23.10 docs
  static/favicon/phone_menu_25_sq.webp
Labels: Version Specific

#2921 PD-1292: image fixes for TC 3.0 docs branch
  static/images/TrueCommand/Cloud/TrueCommandCloudConnectAPIKey.png
  static/includes/TCCloudConnectSystems.md
Labels: Version Specific

#2924 (24.04) Update pnpm action to v4 for external contrib workflow
  .github/workflows/build-external-contrib.yml
Labels: Version Specific

#2925 (13.3) Update pnpm action to v4 for external contrib workflow
  .github/workflows/build-external-contrib.yml
Labels: Version Specific

#2927 (3.0) Update pnpm action to v4 for external contrib workflow
  .github/workflows/build-external-contrib.yml
Labels: Version Specific

#2929 (24.04) Add known issue about NUT service behavior and upstream update
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific

#2906 Pd 1284 update content on toolbar settings menu
  content/SCALE/SCALETutorials/SystemSettings/Advanced/ManageGlobal2FASCALE.md
  content/SCALE/SCALEUIReference/TopToolbar/Settings/2FAScreenSCALE.md
  content/SCALE/SCALEUIReference/TopToolbar/_index.md
  static/images/SCALE/SystemSettings/UserTwoFactorAuthenticationActionsScreen.png
  static/includes/TopToolbar.md
Labels: Technical Writer Review (DP)

#2922 PD-1126 Update IPv6 Configuration Content
  content/SCALE/SCALETutorials/Network/ConfigureIPv6.md
Labels: Technical Writer Review (DP)

#2932 Pd 1250 ldap legacy samba schema removal
  content/CORE/CORETutorials/DirectoryServices/LDAP.md
  content/CORE/CORETutorials/Sharing/SMB/_index.md
  content/CORE/UIReference/DirectoryServices/LDAPScreen.md
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
  content/SCALE/SCALETutorials/Shares/SMB/_index.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/Idmap.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/LDAP.md
  static/images/SCALE/Credentials/LDAPAdvancedOptionsSettings.png
Labels: Review (TM)

#2905 Pd 1061 update dashboard articles with new dashboard
  content/SCALE/GettingStarted/Configure/FirstTimeLogin.md
  content/SCALE/SCALETutorials/Dashboard/SCALETimeSync.md
  content/SCALE/SCALETutorials/Dashboard/_index.md
  content/SCALE/SCALEUIReference/SCALEDashboard.md
  content/SCALE/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  static/images/SCALE/Dashboard/BackupTasksExample.png
  static/images/SCALE/Dashboard/DashboardAppWidget.png
  static/images/SCALE/Dashboard/DashboardBackupTasks.png
  static/images/SCALE/Dashboard/DashboardBackupTasksEmpty.png
  static/images/SCALE/Dashboard/DashboardCPUWidget.png
  static/images/SCALE/Dashboard/DashboardCPUWidgetSCALE.png
  static/images/SCALE/Dashboard/DashboardConfigureScreenSCALE.png
  static/images/SCALE/Dashboard/DashboardHASystemInformationWidgets.png
  static/images/SCALE/Dashboard/DashboardHelpWidget.png
  static/images/SCALE/Dashboard/DashboardHelpWidgetSCALE.png
  static/images/SCALE/Dashboard/DashboardInConfigMode.png
  static/images/SCALE/Dashboard/DashboardInterfaceWidget.png
  static/images/SCALE/Dashboard/DashboardInterfaceWidgetSCALE.png
  static/images/SCALE/Dashboard/DashboardMainScreen.png
  static/images/SCALE/Dashboard/DashboardMainScreenSCALE.png
  static/images/SCALE/Dashboard/DashboardMemoryWidget.png
  static/images/SCALE/Dashboard/DashboardMemoryWidgetSCALE.png
  static/images/SCALE/Dashboard/DashboardNetworkWidget.png
  static/images/SCALE/Dashboard/DashboardNetworkWidgetGroupOptions.png
  static/images/SCALE/Dashboard/DashboardNetworkWidgetSCALE.png
  static/images/SCALE/Dashboard/DashboardPoolWidget.png
  static/images/SCALE/Dashboard/DashboardStorageWidget.png
  static/images/SCALE/Dashboard/DashboardStorageWidgetSCALE.png
  static/images/SCALE/Dashboard/DashboardSystemInfoWidget.png
  static/images/SCALE/Dashboard/DashboardSystemInfoWidgetGeneric.png
  static/images/SCALE/Dashboard/DashboardSystemInfoWidgetSCALE.png
  static/images/SCALE/Dashboard/DashboardSytemInfoWidgetTimeSync.png
  static/images/SCALE/Dashboard/WidgetEditorAddNew.png
  static/images/SCALE/Dashboard/WidgetEditorExistingWidget.png
Labels: Technical Writer Review (DP)

#2931 Pd 1057 new content for expanding a raidz storage pool
  content/References/ExtensionCalculator.md
  content/SCALE/SCALETutorials/Storage/Disks/ReplacingDisks.md
  content/SCALE/SCALETutorials/Storage/ManagePoolsScale.md
  layouts/shortcodes/extension-calculator.html
  static/custom.css
  static/images/Reference/RaidzExpansion.png
  static/images/SCALE/Storage/DevicesExtend.png
  static/images/SCALE/Storage/ExtendVdev.png
  static/includes/24.10FeatureList.md
  words-to-ignore.txt
Labels: Technical Writer Review (TR), Technical Writer Review (MJ)

#2937 Update SCALEDashboard.md (image fix)
  content/SCALE/SCALEUIReference/SCALEDashboard.md
Labels: Technical Writer Review (MJ)

#2939 external link and https review
  LICENSE.md
  content/CORE/CORETutorials/Storage/ImportDisk.md
  content/CORE/UIReference/Services/AFPScreen.md
  content/CORE/UIReference/Services/SMBScreen.md
  content/CORE/UIReference/Services/UPSScreen.md
  content/References/L2ARC.md
  content/SCALE/SCALETutorials/Apps/CommunityApps/ddns-updater.md
  content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
  content/SCALE/SCALEUIReference/Storage/DisksScreen.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/UPSServicesScreenSCALE.md
  content/Solutions/Integrations/Containers.md
  content/Solutions/Integrations/Veeam.md
  src/icons/arrow_back.svg
  src/icons/arrow_left_alt.svg
  src/icons/arrow_right_alt.svg
  src/icons/bitbucket.svg
  src/icons/bookmark.svg
  src/icons/cloud_off.svg
  src/icons/code.svg
  src/icons/date.svg
  src/icons/download.svg
  src/icons/email.svg
  src/icons/git.svg
  src/icons/github.svg
  src/icons/gitlab.svg
  src/icons/heart.svg
  src/icons/keyborad_arrow_down.svg
  src/icons/keyborad_arrow_left.svg
  src/icons/keyborad_arrow_right.svg
  src/icons/link.svg
  src/icons/menu.svg
  src/icons/notification.svg
  src/icons/path.svg
  src/icons/person.svg
  src/icons/search.svg
  src/icons/shield.svg
  src/icons/tags.svg
  static/favicon/tn-favicon.svg
  static/images/UserProvided/Pastedimage20221021020856.png
  static/images/UserProvided/Pastedimage20221024004224.png
  static/images/UserProvided/Pastedimage20221024004241.png
  static/images/UserProvided/Pastedimage20221107154856.png
  static/includes/COREshellOptions.md
  static/includes/S3Deprecation.md
  static/includes/ServiceUPSFields.md
  static/includes/ServicesAFPFields.md
  static/includes/ServicesSMBFields.md
  static/includes/SharingAFPAddFields.md
  static/ixsystems_logo_130_30.svg
  static/js/lunr.min.js
  static/truenas_open_storage-logo-full-color-rgb-1.svg
  themes/hugo-geekdoc/assets/sprites/geekdoc.svg
Labels: Technical Writer Review (MJ)

#2936 (13.0) Quick url fix
  static/includes/iSCSIRef.md
Labels: Version Specific, Technical Writer Review (MJ)

#2940 Pd 1294 scrub all mentions of suggestion tickets from the docs hub
  CONTRIBUTING.md
  content/CORE/CORETutorials/Getting Support.md
  content/Contributing/IssueReporting/FeatureRequests.md
  content/Contributing/IssueReporting/JiraIssueReporting.md
  content/SCALE/GettingStarted/Getting Support/FileIssueSCALE.md
  content/SCALE/SCALEUIReference/TopToolbar/_index.md
  static/images/Contribute/FeatureRequest.png
  static/images/Contribute/FeatureRequestVote.png
  static/images/SCALE/Dashboard/FeedbackWindow.png
  static/images/SCALE/Dashboard/FeedbackWindowEnterpriseBugReport.png
  static/includes/CreateFeatureRequest.md
  static/includes/CreateJiraSuggestion.md
  static/includes/FeedbackWindow.md
  static/includes/FileIssueTicketSCALE.md
  static/includes/TopToolbar.md
Labels: Technical Writer Review (MJ)
