Repository truenas/documentation, pull requests merged in 2024-03, with the labels that each got.

#2511 Pd 917 admin user roles content updates
  content/SCALE/GettingStarted/Configure/FirstTimeLogin.md
  content/SCALE/GettingStarted/Configure/UIConfigurationSCALE.md
  content/SCALE/GettingStarted/Install/ConsoleSetupMenuScale.md
  content/SCALE/SCALETutorials/Credentials/AdminRoles.md
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALE/SCALETutorials/Credentials/RootlessLogin.md
  content/SCALE/SCALETutorials/DataProtection/Replication/AdvancedReplication/ReplicationWithEncryptionSCALE.md
  content/SCALE/SCALETutorials/DataProtection/Replication/LocalReplicationSCALE.md
  content/SCALE/SCALETutorials/DataProtection/Replication/RemoteReplicationSCALE.md
  content/SCALE/SCALEUIReference/Credentials/LocalGroupsScreens.md
  content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
  content/_includes/AddAdminUserAccount.md
  content/_includes/CreateAdminDisableRoot.md
  content/_includes/RootLoginWarnSCALE.md
  content/_includes/RootToAdminUserAccount.md
  content/_includes/TopToolbar.md
  static/images/SCALE/Credentials/AddGroupGIDConfigSCALE.png
  static/images/SCALE/Credentials/AddNewPrivilegeScreen.png
  static/images/SCALE/Credentials/AllUsersScreenBuiltInSCALE.png
  static/images/SCALE/Credentials/AllUsersScreenSCALE.png
  static/images/SCALE/Credentials/EditGroup.png
  static/images/SCALE/Credentials/GroupsListedExpandedSCALE.png
  static/images/SCALE/Credentials/GroupsListedSCALE.png
  static/images/SCALE/Credentials/PrivilegesScreen.png
  static/images/SCALE/Credentials/UserScreenUserDetails.png
  static/images/SCALE/Dashboard/DashboardMainScreenSCALE.png
  static/images/SCALE/Dashboard/TopToolbar.png
  static/images/SCALE/Login/FirstTimeLoginInstallOpt3SCALE.png
Labels: Review (TM)

#2510 PD-1054: (Cobia Docs) Update SNMP tutorial to include MIB
  content/SCALETutorials/SystemSettings/Services/SNMPServiceSCALE.md
Labels: Version Specific

#2515 Pd 1037 virtual machine instructions for networking incomplete
  content/SCALE/SCALETutorials/Virtualization/AccessingNASFromVM.md
  content/SCALE/SCALETutorials/Virtualization/CreatingManagingVMsSCALE.md
  content/SCALE/SCALEUIReference/VirtualizationScreens.md
  content/_includes/NetworkBridgeSCALE.md
  static/images/SCALE/Virtualization/VMEditDeviceSecondaryNIC.png
  static/images/SCALE/Virtualization/VMTestNetworkChangesConfirm.png
  words-to-ignore.txt
Labels: Review (TM)

#2498 Pd 1031 TC 3.0.1 documentation
  content/TCGettingStarted/TCReleaseNotes.md
  content/_includes/LifecycleTable.md
  content/_includes/ReleaseScheduleWarning.md
  data/properties/tc-releases.yaml
  layouts/shortcodes/releaselist.html
  words-to-ignore.txt
Labels: Version Specific

#2538 PD-1044: 24.04 branch publish to 22.12 branch
  layouts/partials/docs-nav.html
Labels: Version Specific

#2537 PD-1044: 24.04 branch publish to 2.3 branch
  layouts/partials/docs-nav.html
Labels: Version Specific

#2536 PD-1044: 24.04 branch publish to 3.0 branch
  layouts/partials/docs-nav.html
Labels: Version Specific

#2535 PD-1044: 24.04 Branch publish to 13.0 branch
  layouts/partials/docs-nav.html
Labels: Version Specific

#2534 PD-1044: 24.04 branch publish to 23.10 branch
  layouts/partials/docs-nav.html
Labels: Version Specific

#2552 PD-1087: port small format fix to 24.04 branch
  content/GettingStarted/Install/InstallEnterpriseHASCALE.md
Labels: Version Specific

#2556 PD-1080: backport changes to 24.04 branch
  content/SCALETutorials/Apps/UsingCatalogs.md
  content/SCALETutorials/ConfigReportsScale.md
  content/SCALEUIReference/Apps/_index.md
  content/SCALEUIReference/ReportingScreensSCALE.md
  static/images/SCALE/Reporting/CPUReportingUsageTemp.png
  static/images/SCALE/Reporting/DiskReportingIO.png
  static/images/SCALE/Reporting/MemoryReportingPhysSwap.png
  static/images/SCALE/Reporting/NetworkReportingIntTraffic.png
  static/images/SCALE/Reporting/SystemReportingProcessUptime.png
  static/images/SCALE/Reporting/ZFSReportingActualHitsHitsRate.png
  static/includes/netdatareporting.md
  words-to-ignore.txt
Labels: Version Specific

#2580 Pd 1096 issue on min io mnmd tutorial
  content/SCALE/SCALETutorials/Apps/EnterpriseApps/MinIO/_index.md
  static/includes/MinIOEnterpriseStorageConfig.md
  static/includes/MinIoEnterpriseConfig1.md
Labels: Technical Writer Review (TR)

#2581 Pd 1096 issue on min io mnmd tutorial (24.04)
  content/SCALETutorials/Apps/EnterpriseApps/MinIO/_index.md
  static/includes/MinIOEnterpriseStorageConfig.md
  static/includes/MinIoEnterpriseConfig1.md
Labels: Technical Writer Review (TR)

#2586 Update TrueCommand LDAP documentation for 3.0.1
  content/TrueCommand/AdminGuide/Admin/LDAPServers.md
  static/images/TrueCommand/Administration/AddLDAPDefault.png
  static/images/TrueCommand/Administration/AddLDAPGroup.png
  static/images/TrueCommand/Administration/AddLDAPGroupToTeam.png
  static/images/TrueCommand/Administration/AddLDAPServerScreen.png
Labels: Community, Technical Writer Review (TR)

#2587 PD-1071 Update main Apps index content
  content/SCALE/SCALETutorials/Apps/_index.md
  static/images/SCALE/Apps/AppsDiscoverScreen.png
  static/images/SCALE/Apps/AppsInstalledAppsScreenNoApp.png
  static/images/SCALE/Apps/AppsInstalledAppsScreenNoApps.png
  static/images/SCALE/Apps/AppsManageContainerImages.png
  static/images/SCALE/Apps/AppsServiceNotConfigured.png
  static/images/SCALE/Apps/DiscoverAppsScreenFilterOptions.png
  static/images/SCALE/Apps/InstalledAppsScreenWithApps.png
  static/images/SCALE/Apps/MinIOS3AppInfoScreen.png
Labels: Technical Writer Review (TR)

#2588 Update LDAPServers.md
  content/TrueCommand/AdminGuide/Admin/LDAPServers.md
Labels: Technical Writer Review (MJ)

#2598 PD-1040 Update SMB Share Screen Export Recycle Bin Setting Content
  content/UIReference/Sharing/SMBShareScreen.md
Labels: Technical Writer Review (TR)

#2599 Updates to installation articles 24.04 Branch
  content/GettingStarted/Install/InstallingSCALE.md
  static/includes/SCALEInstallerProcedure.md
Labels: Technical Writer Review (TR)

#2590 Pd 1086 ad udp caution to nfs articles
  content/SCALE/SCALETutorials/Shares/AddingNFSShares.md
  content/SCALE/SCALETutorials/SystemSettings/Services/NFSServiceSCALE.md
  content/SCALE/SCALEUIReference/Shares/NFSSharesScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md
  static/includes/NFSServiceUDPWarning.md
Labels: Technical Writer Review (TR)

#2591 PD-1086 Backport UDP Protocl and NFS Snippet to 23.10
  content/SCALETutorials/Shares/AddingNFSShares.md
  content/SCALETutorials/SystemSettings/Services/NFSServiceSCALE.md
  content/SCALEUIReference/Shares/NFSSharesScreens.md
  content/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md
  static/includes/NFSServiceUDPWarning.md
Labels: Technical Writer Review (TR)

#2592 PD-1086 Backport UDP Protocol and NFS Snippet to 24.04
  content/SCALETutorials/Shares/AddingNFSShares.md
  content/SCALETutorials/SystemSettings/Services/NFSServiceSCALE.md
  content/SCALEUIReference/Shares/NFSSharesScreens.md
  content/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md
  static/includes/NFSServiceUDPWarning.md
Labels: Technical Writer Review (TR)

#2596 PD-1040 Update Export Recycle Bin Information
  content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md
Labels: Technical Writer Review (TR)

#2597 PD-1040 Update Export Recycle Bin Content Backport to 24.04
  content/SCALEUIReference/Shares/SMBSharesScreens.md
Labels: Technical Writer Review (TR)

#2593 PD-1081 Add Automatic Config File Backup Content
  content/SCALE/SCALETutorials/SystemSettings/General/ManageSysConfigSCALE.md
Labels: Technical Writer Review (TR)

#2594 PD-1081 Backport Config File Automatic Backup Content to 24.40
  content/SCALETutorials/SystemSettings/General/ManageSysConfigSCALE.md
Labels: Technical Writer Review (TR)

#2595 PD-1081 Backport Config File Backup Content to 23.10
  content/SCALETutorials/SystemSettings/General/ManageSysConfigSCALE.md
Labels: Technical Writer Review (TR)

#2601 Update FirstTimeLogin.md and Snippets - Master
  content/SCALE/GettingStarted/Configure/FirstTimeLogin.md
  static/images/SCALE/Login/LoginScreenSCALE.png
  static/includes/Jobs.md
Labels: Technical Writer Review (TR)

#2602 Update FirstTimeLogin.md and snippets Backport to 24.04
  content/GettingStarted/Configure/FirstTimeLogin.md
  static/images/SCALE/Login/LoginScreenSCALE.png
  static/includes/Jobs.md
Labels: Technical Writer Review (TR)
