Repository truenas/documentation, pull requests merged in 2025-01, with the labels that each got.

#3378 PD-1613 / 25.04 / Pd 1613 update truecloud backup article content
  content/SCALE/SCALETutorials/DataProtection/TrueCloudTasks.md
  content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/TrueCloudBackupTasksScreen.md
  static/images/SCALE/Apps/AddTrueCloudTaskAdvancedOption.png
  static/images/SCALE/Apps/AddTrueCloudTaskAdvancedOptions.png
  static/images/SCALE/DataProtection/AddTrueCloudTaskAdvancedOptions.png
  static/includes/StorjBucket.md
Labels: Re-Review, backport-24.10

#3400 Add VM startup known issue to 24.10.1 known issues
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific

#3370 PD-1617 / 25.04 / Pd 1617 create asigra tutoral update solutions article
  content/TruenasApps/EnterpriseApps/AsigraApp.md
  static/images/SCALE/Apps/AddEnvironmentVariable.png
  static/images/SCALE/Apps/AsigraAppDetailsScreen.png
  static/images/SCALE/Apps/AsigraAppRunning.png
  static/images/SCALE/Apps/AsigraConnectToDS-Operator.png
  static/images/SCALE/Apps/AsigraDS-OperatorAddLicenseServer.png
  static/images/SCALE/Apps/AsigraDS-OperatorAddaDS-SystemWindow.png
  static/images/SCALE/Apps/AsigraNewCustomerInfoScreen.png
  static/images/SCALE/Apps/DS-OperatorInitializationOption.png
  static/images/SCALE/Apps/InstallAsigraResourcesConfig.png
  static/images/SCALE/Apps/InstallAsigraScreen.png
  static/images/SCALE/Apps/InstallAsigraStorageConfigPostgresDataAutoPerms.png
  static/images/SCALE/Apps/InstallAsigraStorageDataACLandACESettings.png
  static/includes/apps/InstallWizardEnvironVariablesSettings.md
Labels: Technical Writer Review (LM), Re-Review

#3396 PD-1622 / 25.04 / PD-1622-HomeAssistant
  content/TruenasApps/StableApps/HomeAssistantApp.md
  static/images/SCALE/Apps/AddHomeAssistantStorageConfigs.png
  static/images/SCALE/Apps/DiscoverScreenHomeAssistant.png
  static/images/SCALE/Apps/HomeAssistantAddDevices.png
  static/images/SCALE/Apps/HomeAssistantDashboard.png
  static/images/SCALE/Apps/HomeAssistantInformationScreen.png
  static/images/SCALE/Apps/HomeAssistantSignUpScreen.png
  static/images/SCALE/Apps/InstallHomeAssistantResourcesConfig.png
  static/images/SCALE/Apps/InstallHomeAssistantScreen.png
Labels: Technical Writer Review (TR)

#3398 PD-1662 / 25.04 / PD-1662-update-SSH-2-fa-tutorial
  content/SCALE/SCALETutorials/SystemSettings/Services/SSHServiceSCALE.md
Labels: Technical Writer Review (DP), Re-Review

#3403 PD-1610 / 25.04 / Pd 1610 update docs hub and security hub header footer styling to match parent true nas com
  config.toml
  content/Hardware/_index.md
  content/SCALE/GettingStarted/Migrate/ComponentNaming.md
  layouts/partials/site-footer.html
  layouts/partials/site-header.html
  layouts/partials/toc-panel.html
  static/custom.css
  static/favicon/tc-full.png
  static/images/TN_Open_Enterprise_Storage_White_Version.png
  static/images/Truenas_icon.png
  static/images/chat.svg
  static/images/full-rgb.png
  static/images/truenas-logo-mark.png
Labels: Review (TM), backport-24.10, backport-24.04, backport-23.10, backport-13.3, backport-13.0, backport-3.0

#3409 PD-1610 / 13.0 / Pd 1610 update docs hub and security hub header footer styling to match parent true nas com (by DjP-iX)
  config.toml
  layouts/partials/site-footer.html
  layouts/partials/site-header.html
  static/custom.css
  static/favicon/tc-full.png
  static/images/TN_Open_Enterprise_Storage_White_Version.png
  static/images/Truenas_icon.png
  static/images/chat.svg
  static/images/full-rgb.png
  static/images/truenas-logo-mark.png
Labels: Review (TM)

#3410 PD-1610 / 13.3 / Pd 1610 update docs hub and security hub header footer styling to match parent true nas com (by DjP-iX)
  config.toml
  layouts/partials/site-footer.html
  layouts/partials/site-header.html
  layouts/partials/toc-panel.html
  static/custom.css
  static/favicon/tc-full.png
  static/images/TN_Open_Enterprise_Storage_White_Version.png
  static/images/Truenas_icon.png
  static/images/chat.svg
  static/images/full-rgb.png
  static/images/truenas-logo-mark.png
Labels: Review (TM)

#3411 PD-1610 / 23.10 / Pd 1610 update docs hub and security hub header footer styling to match parent true nas com (by DjP-iX)
  config.toml
  layouts/partials/site-footer.html
  layouts/partials/site-header.html
  static/custom.css
  static/favicon/tc-full.png
  static/images/TN_Open_Enterprise_Storage_White_Version.png
  static/images/Truenas_icon.png
  static/images/chat.svg
  static/images/full-rgb.png
  static/images/truenas-logo-mark.png
Labels: Review (TM)

#3413 PD-1610 / 24.10 / Pd 1610 update docs hub and security hub header footer styling to match parent true nas com (by DjP-iX)
  config.toml
  layouts/partials/site-footer.html
  layouts/partials/site-header.html
  layouts/partials/toc-panel.html
  static/custom.css
  static/favicon/tc-full.png
  static/images/TN_Open_Enterprise_Storage_White_Version.png
  static/images/Truenas_icon.png
  static/images/chat.svg
  static/images/full-rgb.png
  static/images/truenas-logo-mark.png
Labels: Review (TM)

#3414 PD-1610 / 3.0 / Pd 1610 update docs hub and security hub header footer styling to match parent true nas com (by DjP-iX)
  config.toml
  layouts/partials/site-footer.html
  layouts/partials/site-header.html
  layouts/partials/toc-panel.html
  static/custom.css
  static/favicon/tc-full.png
  static/images/TN_Open_Enterprise_Storage_White_Version.png
  static/images/Truenas_icon.png
  static/images/chat.svg
  static/images/full-rgb.png
  static/images/truenas-logo-mark.png
Labels: Review (TM)

#3416 Quick writeup of SED migration issue for 24.10
  content/GettingStarted/SCALEReleaseNotes.md
  static/includes/WhatDoesNotMigrate.md
Labels: Version Specific

#3420 Fix image call typo
  content/GettingStarted/Install/InstallEnterpriseHASCALE.md
Labels: Version Specific

#3421 PD-1648 / 25.04 / Pd 1648 update encryption documentation
  content/SCALE/SCALETutorials/Datasets/DatasetsSCALE.md
  content/SCALE/SCALETutorials/Datasets/EncryptionSCALE.md
  content/SCALE/SCALETutorials/Storage/CreatePoolWizard.md
  content/SCALE/SCALETutorials/SystemSettings/Advanced/_index.md
  content/SCALE/SCALEUIReference/Datasets/EncryptionUISCALE.md
  content/SCALE/SCALEUIReference/Datasets/ZvolsScreensScale.md
  content/SCALE/SCALEUIReference/Datasets/_index.md
  content/SCALE/SCALEUIReference/Storage/PoolCreateWizardScreens.md
  static/includes/CreatePool.md
  static/includes/EncryptionRootLevel.md
  static/includes/EncryptionWarning.md
Labels: backport-24.10

#3419 Add nvidia plex passthru known issue (24.10.1)
  content/GettingStarted/SCALEReleaseNotes.md
  words-to-ignore.txt
Labels: Version Specific, Technical Writer Review (TR)

#3415 PD-1631 / 25.04 / Pd 1631 add smb limitations to tutorials and UI ref
  content/SCALE/SCALETutorials/Shares/SMB/_index.md
  static/includes/SMBLimitations.md
Labels: Technical Writer Review (LM), Re-Review, backport-25.04, backport-24.10, backport-24.04

#3418 PD-1693 / 25.04 / PD-1693 Update Group Articles (by micjohnson777)
  content/SCALE/SCALETutorials/Credentials/ManageLocalGroups.md
  content/SCALE/SCALEUIReference/Credentials/LocalGroupsScreens.md
  static/images/SCALE/Credentials/AddGroupScreen.png
Labels: Technical Writer Review (LM), Re-Review

#3429 PD-1725 / 25.04 / PD-1725-wrong-image
  static/images/SCALE/Network/NetworkInterfacesBridgeSCALE.png
Labels: backport-24.10

#3427 PD-1651 / 25.04 / PD-1651-update-vm-migration
  content/SCALE/GettingStarted/Migrate/MigratePrep.md
  content/SCALE/GettingStarted/Migrate/MigratingFromCORE.md
  static/includes/COREMigratesList.md
Labels: Re-Review, backport-24.10, backport-24.04, backport-23.10, backport-22.12

#3426 PD-1680 / 25.04 / Pd 1680 user linked api tokens
  content/SCALE/SCALETutorials/TopToolbar/ManagingAPIKeys.md
  content/SCALE/SCALEUIReference/TopToolbar/Settings/APIKeysScreen.md
  static/images/SCALE/Dashboard/APIKeyCopy.png
  static/images/SCALE/Dashboard/APIKeyExpires.png
  static/images/SCALE/Dashboard/APIKeysDelete.png
  static/images/SCALE/Dashboard/APIKeysEdit.png
  static/images/SCALE/Dashboard/APIKeysScreen.png
  static/includes/25.04FeatureList.md
  static/includes/APIKeyWarn.md
Labels: Technical Writer Review (LM), Re-Review

#3405 Update nginx-proxy-manager.md
  content/TruenasApps/CommunityApps/nginx-proxy-manager.md
Labels: Technical Writer Review (DP)

#3440 Update MigrateCOREtoSCALE24_04.md
  static/includes/MigrateCOREtoSCALE24_04.md
Labels: Technical Writer Review (LM), backport-24.10

#3442 PD-1602 / 25.04 / Pd 1602 community container vm experimental feature documentation
  content/SCALE/GettingStarted/Configure/VMandAppConfigSCALE.md
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
  content/SCALE/SCALETutorials/Virtualization/AddManageVMDevicesSCALE.md
  content/SCALE/SCALETutorials/Virtualization/_index.md
  content/SCALE/SCALEUIReference/VirtualizationScreens.md
  static/includes/25.04FeatureList.md
  static/includes/25.04Virtualization.md
  static/includes/Incus.md
  static/includes/MigratingVMs.md
Labels: Technical Writer Review (LM)

#3447 Update UsingCustomApp.md
  content/TruenasApps/UsingCustomApp.md
Labels: Technical Writer Review (TR)

#3448 PD-1479 / 25.04 / PD-1479 Apps Update Collabora
  content/TruenasApps/StableApps/Collabora.md
  content/TruenasApps/StableApps/InstallNextCloudMedia.md
  static/images/SCALE/Apps/CollaboraDashboard.png
  static/images/SCALE/Apps/CollaboraInformationScreen.png
  static/images/SCALE/Apps/CollaboraInstallDictionaries.png
  static/images/SCALE/Apps/CollaboraInstallExtraParameters.png
  static/images/SCALE/Apps/CollaboraInstallStorage.png
  static/images/SCALE/Apps/CollaboraSignInScreen.png
  static/images/SCALE/Apps/DiscoverScreenCollabora.png
  static/images/SCALE/Apps/InstallCollaboraResourcesConfig.png
  static/images/SCALE/Apps/InstallCollaboraScreen.png
  static/includes/apps/CollaboraNextcloudConnection.md
Labels: Technical Writer Review (TR)

#3436 PD-1685 / 25.04 / PD-1685-update-email-content
  content/SCALE/SCALETutorials/SystemSettings/General/SettingUpSystemEmail.md
  content/SCALE/SCALEUIReference/TopToolbar/Alerts/EmailScreens.md
  static/images/SCALE/SystemSettings/EmailOptionsOutlookOAuth.png
  static/images/SCALE/SystemSettings/EmailOptionsOutlookOAuthApplied.png
  static/images/SCALE/SystemSettings/EmailOutlookAuthorization.png
  static/images/SCALE/SystemSettings/EmailOutlookSignIn.png
  static/includes/EmailOptions.md
  static/includes/EmailOptionsOutlook.md
Labels: Technical Writer Review (TR), Re-Review

#3450 PD-1745-implementing-i-pv-6-link-in-first-paragraph-is-broken-404
  content/SCALETutorials/Network/ConfigureIPv6.md
Labels: Technical Writer Review (LM), backport-25.04

#3455 25.04-PD-1745-implementing-i-pv-6-link-in-first-paragraph-is-broken-404
  content/SCALE/SCALETutorials/Network/ConfigureIPv6.md
Labels: Technical Writer Review (LM)

#3441 13.0-U6.6 release notes
  content/GettingStarted/COREReleaseNotes.md
Labels: Version Specific

#3449 Update 24.10 ui ref screen and notes for updated "settings" option in 24.10.2
  content/SCALEUIReference/Apps/_index.md
Labels: Version Specific, Technical Writer Review (TR)

#3460 PD-1684 / 25.04 / PD-1684-hardware-guide-should-warn-about-smr-drives
  static/includes/TNHardwareGuide.md
Labels: Technical Writer Review (TR), backport-24.10, backport-13.3, backport-13.0

#3451 PD-1576 / 25.04 / PD-1576-update-users-content
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
  static/images/SCALE/Credentials/UsersAPIKeysButton.png
  static/images/SCALE/Credentials/UsersAPIKeysMenu.png
Labels: Technical Writer Review (TR)

#3464 NAS-133538-fromemail-must-be-specified-when-setting-up-o-auth-for-outlook-mail
  content/SCALE/SCALETutorials/SystemSettings/General/SettingUpSystemEmail.md
  static/includes/EmailOptionsOutlook.md
Labels: Technical Writer Review (TR)

#3465 PD-1684 / 13.0 / PD-1684-hardware-guide-should-warn-about-smr-drives (by DjP-iX)
  static/includes/SoftwareStatusPage.md
  static/includes/TNHardwareGuide.md
Labels: Technical Writer Review (TR)

#3466 PD-1684 / 13.3 / PD-1684-hardware-guide-should-warn-about-smr-drives (by DjP-iX)
  static/includes/TNHardwareGuide.md
Labels: Technical Writer Review (TR)

#3467 PD-1684 / 24.10 / PD-1684-hardware-guide-should-warn-about-smr-drives (by DjP-iX)
  static/includes/TNHardwareGuide.md
Labels: Technical Writer Review (TR)

#3292 PD-1556 / 25.04 / Pd 1556 revise app tutorial template
  content/Contributing/Applications/AppArticleTemplate.md
  content/Contributing/Applications/_index.md
  static/includes/apps/InstallAppsStorageConfig.md
Labels: Re-Review

#3428 PD-1612 / 25.04 / PD-1612-document-new-fields-for-disk-replacement
  content/SCALE/SCALETutorials/Storage/Disks/ReplacingDisks.md
  content/SCALE/SCALEUIReference/Storage/DevicesScreensSCALE.md
  static/images/SCALE/Storage/ReplacingDiskDialog.png
Labels: Technical Writer Review (MJ), Re-Review

#3463 PD-1706 / 25.04 / PD-1706-document-new-cloud-backup-option
  content/SCALE/SCALEUIReference/DataProtection/TrueCloudBackupTasksScreen.md
  static/images/SCALE/DataProtection/AddTrueCloudTaskAdvancedOptions.png
Labels: Technical Writer Review (TR), Technical Writer Review (DP), backport-24.10

#3458 13.0-U6.7 release notes
  content/GettingStarted/COREReleaseNotes.md
Labels: Version Specific

#3457 Add 13.0-U6.6 and 13.0-U6.7 to 13.3 branch data files
  data/properties/core-downloads.yaml
  data/properties/core-releases.yaml
  static/includes/COREUpgradePaths.md
Labels: Version Specific

#3471 PD-1575 / 25.04 / Pd 1575 enterprise rdma support in nfs
  content/SCALE/SCALETutorials/Shares/AddingNFSShares.md
  static/images/SCALE/SystemSettings/ServicesNFSSettingsScreen.png
  static/includes/25.04FeatureList.md
Labels: Technical Writer Review (LM)

#3469 PD-1409 / 25.04 / Pd 1409 update cloud sync task articles
  content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/_index.md
  content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  static/images/SCALE/DataProtection/AddCloudSyncTaskPushTransferRemote.png
  static/images/SCALE/DataProtection/CloudSyncTaskWidget.png
  static/images/SCALE/DataProtection/CloudSyncTaskWizardWhatandWhenScreen.png
  static/images/SCALE/DataProtection/EditCloudSyncTaskControlAdvanced.png
Labels: Technical Writer Review (LM)

#3477 PD-1458 / 25.04 / PD-1458-document-new-certificate-ca-field
  content/SCALE/SCALETutorials/Credentials/Certificates/AddCAsSCALE.md
  content/SCALE/SCALEUIReference/Credentials/Certificates/CAScreensSCALE.md
  static/images/SCALE/Credentials/AddCertificateAuthorityScreen.png
Labels: Technical Writer Review (TR)

#3476 PD-1700 / 25.04 / Pd 1700 add stig tutorial
  content/SCALE/SCALETutorials/SystemSettings/Advanced/_index.md
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  static/images/SCALE/SystemSettings/AccessSettingsScreen.png
  static/images/SCALE/SystemSettings/SecurityFIPSSTIGRebootDialog.png
  static/images/SCALE/SystemSettings/SystemAdvancedSecurityWidget.png
  static/images/SCALE/SystemSettings/SystemSecurityScreen.png
  static/images/SCALE/SystemSettings/TokenSettingsScreen.png
  static/includes/AccessSettingsWidget.md
Labels: Technical Writer Review (TR)

#3431 PD-1601 / 25.04 / Pd 1601 update docs for new versioned api
  content/SCALE/API/_index.md
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
  content/SCALE/SCALETutorials/Credentials/ManageLocalGroups.md
  content/SCALE/SCALETutorials/Shares/SMB/_index.md
  content/SCALE/SCALETutorials/SystemSettings/Advanced/_index.md
  content/SCALE/SCALETutorials/TopToolbar/ManagingAPIKeys.md
  content/SCALE/SCALEUIReference/Credentials/LocalGroupsScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  content/SCALE/SCALEUIReference/TopToolbar/Settings/APIKeysScreen.md
  content/SCALE/SCALEUIReference/TopToolbar/Settings/_index.md
  static/images/SCALE/Credentials/AddGroupScreen.png
  static/images/SCALE/Dashboard/APIKeyExpires.png
  static/images/SCALE/Network/NetworkInterfacesBridgeSCALE.png
  static/includes/25.04FeatureList.md
  static/includes/APIDocs.md
  static/includes/APIKeyMigrate.md
  static/includes/APIKeyWarn.md
  static/includes/API_AD.md
  static/includes/RESTAPIDeprecationNotice.md
  static/includes/SMBLimitations.md
Labels: Technical Writer Review (MJ), Re-Review

#3459 PD-1659 / 25.04 / PD-1659 Update iSCSI UI Ref Article
  content/SCALE/SCALETutorials/Shares/iSCSI/AddingISCSIShares.md
  content/SCALE/SCALEUIReference/Shares/iSCSISharesScreens.md
  static/images/SCALE/Shares/AddAuthorizedAccessScreen.png
  static/images/SCALE/Shares/AddExtentScreenDeviceType.png
  static/images/SCALE/Shares/AddExtentScreenFileType.png
  static/images/SCALE/Shares/AddInitiatorScreen.png
  static/images/SCALE/Shares/AddPortalScreen.png
  static/images/SCALE/Shares/AddiSCSITargetScreen.png
  static/images/SCALE/Shares/DeleteiSCSITargetdialog.png
  static/images/SCALE/Shares/DelteExtentDialog.png
  static/images/SCALE/Shares/EditISCSITargetScreen.png
  static/images/SCALE/Shares/EditInitiatorScreen.png
  static/images/SCALE/Shares/EditPortalScreen.png
  static/images/SCALE/Shares/ISCSIExtentAssociateDialog.png
  static/images/SCALE/Shares/RemoveExtentAssociationDialog.png
  static/images/SCALE/Shares/StartiCSIServicedialog.png
  static/images/SCALE/Shares/iSCSAuthorizedAccessScreen.png
  static/images/SCALE/Shares/iSCSIBlockSharesWidget.png
  static/images/SCALE/Shares/iSCSIExtentsScreen.png
  static/images/SCALE/Shares/iSCSIGlobalConfigurationScreen.png
  static/images/SCALE/Shares/iSCSIInitiatorsScreen.png
  static/images/SCALE/Shares/iSCSIPortalsScreen.png
  static/images/SCALE/Shares/iSCSITargetsScreen.png
  static/images/SCALE/Shares/iSCSIWizardExtendFileType.png
  static/images/SCALE/Shares/iSCSIWizardExtentCreateNewDevice.png
  static/images/SCALE/Shares/iSCSIWizardProtocolOptionsCreateNewPortal.png
  static/images/SCALE/Shares/iSCSIWizardTargetScreen.png
  static/includes/iSCSIConfigurationScreens.md
  static/includes/iscsiAuthorizedAccess.md
  static/includes/iscsiExtents.md
  static/includes/iscsiInitiatorsGroups.md
  static/includes/iscsiPortals.md
  static/includes/iscsiTargets.md
Labels: Technical Writer Review (TR)

#3474 PD-1692 / 25.04 / Pd 1692 document remote assistance app
  content/TruenasApps/EnterpriseApps/AsigraApp.md
  content/TruenasApps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md
  content/TruenasApps/EnterpriseApps/MinIO/ConfigMinioEnterpriseSNMD.md
  content/TruenasApps/EnterpriseApps/MinIO/_index.md
  content/TruenasApps/EnterpriseApps/RemoteAssist.md
  content/TruenasApps/EnterpriseApps/Syncthing.md
  content/TruenasApps/EnterpriseApps/_index.md
  static/images/SCALE/Apps/InstallRemoteAssist.png
  static/includes/apps/EnterpriseApps.md
Labels: Technical Writer Review (MJ), Re-Review

#3472 PD-1419 / 25.04 / PD-1419 Add Session Expiration Information to Auditing and System Acc…
  content/SCALE/SCALETutorials/SystemSettings/AuditingSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
Labels: Technical Writer Review (LM), Re-Review

#3401 PD-1613 / 24.10 / Pd 1613 update truecloud backup article content (by micjohnson777)
  content/SCALETutorials/DataProtection/TrueCloudTasks.md
  content/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  content/SCALEUIReference/DataProtection/TrueCloudBackupTasksScreen.md
  static/images/SCALE/Apps/AddTrueCloudTaskAdvancedOption.png
  static/images/SCALE/Apps/AddTrueCloudTaskAdvancedOptions.png
  static/includes/StorjBucket.md
Labels: backport-25.04

#3478 PD-1702 / 25.04 / Pd 1702 convert sed content to primarily enterprise
  content/SCALE/SCALETutorials/Storage/Disks/SEDScale.md
  content/SCALE/SCALETutorials/SystemSettings/Advanced/ManageSEDsSCALE.md
  content/SCALE/SCALEUIReference/Storage/DisksScreen.md
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  static/images/SCALE/Storage/EditDiskScreen.png
  static/includes/SEDEnterprise.md
  static/includes/SEDEnterpriseAdmonition.md
  static/includes/SEDGlobalPW.md
  static/includes/SEDIndividualPWs.md
Labels: Re-Review

#3470 Release notes for 13.3-U1.1 maintenance release
  content/GettingStarted/COREReleaseNotes.md
  data/properties/core-downloads.yaml
  data/properties/core-releases.yaml
  static/includes/COREUpgradePaths.md
Labels: Version Specific, Technical Writer Review (MJ)
