Repository truenas/documentation, pull requests merged in 2025-06, with the labels that each got.

#3881 backport idmap update
  content/SCALE/SCALETutorials/Instances/_index.md
Labels: Technical Writer Review (LM)

#3840 PD-1977 / 24.10 / Pd 1977 update initial debug file content (by micjohnson777)
  content/GettingStarted/Configure/SetUpBackupScale.md
  content/GettingStarted/Configure/UIConfigurationSCALE.md
  static/includes/ConfigRestrictions.md
  static/includes/DownloadSystemConfigFileSCALE.md
Labels: Technical Writer Review (DP), Re-Review

#3885 Update ReplicationScreensSCALE.md
  content/SCALEUIReference/DataProtection/ReplicationScreensSCALE.md
Labels: Technical Writer Review (TR)

#3889 Update _index.md
  content/SCALETutorials/Network/Interfaces/_index.md
Labels: backport-25.10

#3888 PD-2052 / 25.04 / add notice about auxiliary params to various areas
  content/SCALETutorials/SystemSettings/Services/SSHServiceSCALE.md
  content/SCALETutorials/SystemSettings/Services/UPSServicesSCALE.md
  content/SCALEUIReference/Credentials/DirectoryServices/LDAP.md
  content/SCALEUIReference/DataProtection/RsyncTasksScreensSCALE.md
  content/SCALEUIReference/Shares/SMBSharesScreens.md
  content/SCALEUIReference/SystemSettings/Services/FTPServiceScreenSCALE.md
  content/SCALEUIReference/SystemSettings/Services/SNMPServiceScreenSCALE.md
  content/SCALEUIReference/SystemSettings/Services/SSHServiceScreenSCALE.md
  content/SCALEUIReference/SystemSettings/Services/UPSServicesScreenSCALE.md
  static/includes/auxiliary-parameters-caution.md
Labels: Technical Writer Review (MJ), backport-25.10

#3891 Update _index.md
  content/SCALE/SCALETutorials/Network/Interfaces/_index.md
Labels: Technical Writer Review (MJ)

#3892 PD-1976 / 25.04 / PD-1976-document-how-to-grant-permissions-to-root-in-unprivileged-con… (by linzi-ix)
  content/SCALETutorials/Datasets/PermissionsSCALE.md
Labels: Technical Writer Review (MJ)

#3895 PD-2055 Windows Using Sha 256 checksum command is wrong
  content/GettingStarted/Install/InstallingSCALE.md
Labels: Technical Writer Review (LM)

#3717 Hardware Section Updates
  content/Hardware/ExpansionShelves.md
  content/Hardware/LegacyHardware/RSeries/_index.md
  content/Hardware/RSeries.md
  static/images/Hardware/ExpansionShelves/ES24FStencil.png
  static/images/Hardware/ExpansionShelves/ES24Stencil.png
  static/images/Hardware/ExpansionShelves/ExpansionShelvesFront.png
  words-to-ignore.txt
Labels: Technical Writer Review (MJ)

#3901 PD-2041 / 25.10 / PD-2041-documentation-about-legacy-afp-shares-is-incorrect
  content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md
Labels: Technical Writer Review (TR), backport-25.04

#3905 Update SSHCredentialScreens.md
  content/SCALE/SCALEUIReference/Credentials/BackupCredentials/SSHCredentialScreens.md
Labels: Technical Writer Review (TR)

#3908 PD-2041 / 25.04 / PD-2041-documentation-about-legacy-afp-shares-is-incorrect (by linzi-ix)
  content/SCALEUIReference/Shares/SMBSharesScreens.md
Labels: Technical Writer Review (MJ)

#3912 PD-1912 / 25.04 / update Disk related content for SMART change (ref and tutorial)
  content/SCALETutorials/Storage/Disks/_index.md
  content/SCALEUIReference/Storage/DisksScreen.md
  static/images/SCALE/DataProtection/SMARTTestResultsofDiskExpanded.png
  static/images/SCALE/Storage/BulkEditDisksScreen.png
  static/images/SCALE/Storage/DiskScreenExpandedDiskWithWipeOption.png
  static/images/SCALE/Storage/EditDiskScreen.png
  static/images/SCALE/Storage/StorageDashboardWithPool.png
Labels: Version Specific, Technical Writer Review (TR)

#3913 PD-1822 / 25.10 / PD-1822
  static/includes/TopToolbar.md
Labels: Technical Writer Review (TR)

#3914 PD-1776 / 24.10 / PD-1776 Add section for replacing disk or disks 'in place'
  content/SCALETutorials/Storage/Disks/ReplacingDisks.md
Labels: Technical Writer Review (MJ)

#3910 PD-2053 / 25.04 / PD-2053 Refresh SDLC content
  content/GettingStarted/SCALEReleaseNotes.md
  content/GettingStarted/UserAgreements/SoftwareDevelopmentLifeCycleSCALE.md
  static/includes/LifecycleTable.md
  static/includes/SoftwareStatusPage.md
  static/includes/TNLifecycle.md
Labels: Technical Writer Review (MJ), Re-Review, backport-25.10
