Repository truenas/documentation, pull requests merged in 2025-07, with the labels that each got.

#3945 AD Fix Release Follow-Up 25.04
  data/properties/core-releases.yaml
  data/properties/scale-releases.yaml
  static/includes/SCALEUpgradePaths.md
Labels: Review (TM)

#3931 PD-2091 / 25.10 / Pd 2091 veeam smb with fast clone content
  content/SCALE/SCALETutorials/Shares/SMB/_index.md
  content/Solutions/Integrations/Veeam.md
  static/includes/SMBPurposePresets.md
Labels: Technical Writer Review (LM), Re-Review, backport-25.04

#3957 PD-2098 / 25.10 / Update docs-nav.html
  layouts/partials/docs-nav.html
Labels: backport-25.04, backport-24.10, backport-24.04, backport-13.3, backport-13.0, backport-3.0

#3981 PD-2098 / 22.12 / Pd 2098 investigate 404 error list provided from marketing 22.12
  content/SCALETutorials/Apps/Docker.md
  content/SCALEUIReference/Apps/LaunchDockerImageScreens.md
Labels: Technical Writer Review (LM)

#3974 Update TrueCloudTasks.md
  content/SCALETutorials/DataProtection/TrueCloudTasks.md
Labels: Technical Writer Review (LM)

#3972 PD-1811: Add release summary location and template
  release-summary/25.10-BETA.1.release-notes.md
  release-summary/release-summary-template.md
Labels: Technical Writer Review (MJ)

#3991 PD-2146 / 25.04 / Pd 2146 update ssh auxiliary parameters warnings
  content/GettingStarted/SCALEReleaseNotes.md
  content/SCALETutorials/SystemSettings/Services/SSHServiceSCALE.md
  content/SCALEUIReference/SystemSettings/Services/SSHServiceScreenSCALE.md
  data/properties/scale-releases.yaml
  static/includes/UpgradeNotesBoilerplate.md
  static/includes/auxiliary-parameters-ssh.md
Labels: backport-25.10

#3992 PD-2146 / 25.10 / Pd 2146 update ssh auxiliary parameters warnings (by DjP-iX)
  content/SCALE/SCALETutorials/SystemSettings/Services/SSHServiceSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/SSHServiceScreenSCALE.md
  data/properties/scale-releases.yaml
  static/includes/UpgradeNotesBoilerplate.md
  static/includes/auxiliary-parameters-ssh.md
Labels: Review (TM)

#3995 PD-2117 / 25.04 / Pd 2117 incorrect smb preset listed (by DjP-iX)
  content/SCALETutorials/Network/ContainerNASBridge.md
  static/includes/DatasetPresetOptions.md
Labels: Technical Writer Review (LM)
