Repository truenas/documentation, pull requests merged in 2025-10, with the labels that each got.

#4192 PD-1967 / 25.10 / Pd 1967 fix changelog table
  static/js/csv-changelog-tab-init.js
  static/js/csv-changelog-table.js
Labels: backport-26.04

#4187 PD-2254 / 26.04 / Pd 2254 smb shadow copies additional explanation
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBShadowCopies.md
Labels: Technical Writer Review (MJ), backport-25.10

#4190 PD-2147 / 25.10 / Update ManageInitShutdownSCALE.md (by linzi-ix)
  content/SCALETutorials/SystemSettings/Advanced/ManageInitShutdownSCALE.md
  content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
Labels: Technical Writer Review (MJ)

#4202 PD-2254 / 25.10 / Pd 2254 smb shadow copies additional explanation (by DjP-iX)
  content/SCALETutorials/Shares/SMB/AddSMBShadowCopies.md
Labels: Technical Writer Review (LM)

#4203 PD-2231 / 25.10 / PD-2231-we-should-set-user-expectations-appropriately-for-managing-co… (by linzi-ix)
  content/SCALETutorials/SystemSettings/ManageBootEnvironSCALE.md
  content/SCALEUIReference/SystemSettings/SystemBootScreensSCALE.md
  static/includes/BootPoolRecoveryProcess.md
Labels: Technical Writer Review (MJ), Re-Review
