Repository truenas/documentation, pull requests merged in 2025-03, with the labels that each got.

#3558 PD-1695 / 25.04 / PD-1695-clarify-true-cloud-password-encryption
  content/SCALETutorials/DataProtection/TrueCloudTasks.md
Labels: Technical Writer Review (TR)

#3561 PD-1792 / 25.10 / port ssh password updates to master/25.10
  content/SCALE/SCALETutorials/SystemSettings/Advanced/ManageGlobal2FASCALE.md
  static/includes/BasicReplicationProcess.md
Labels: Technical Writer Review (TR)

#3560 PD-1792 / 25.04 / update ssh password text (25.04)
  content/SCALETutorials/SystemSettings/Advanced/ManageGlobal2FASCALE.md
  static/includes/BasicReplicationProcess.md
Labels: Version Specific, Technical Writer Review (TR)

#3559 PD-1792 / 24.10 / find and fix outdated references to password login toggles in the SSH Service screen (24.10)
  content/SCALETutorials/SystemSettings/Advanced/ManageGlobal2FASCALE.md
  static/includes/BasicReplicationProcess.md
Labels: Version Specific, Technical Writer Review (TR)

#3557 PD-1781 / 25.04 / PD-1781-update-data-protection-content
  content/SCALETutorials/DataProtection/TrueCloudTasks.md
  static/images/SCALE/DataProtection/TrueCloudTaskSuccess.png
Labels: Technical Writer Review (TR)

#3555 PD-1552 / 25.10 / PD-1552 Add Close Without Saving Content to UIConfigurationSCALE.md
  content/SCALE/GettingStarted/Configure/UIConfigurationSCALE.md
  static/images/SCALE/Dashboard/CloseWithoutSavingChangesDialog.png
Labels: Technical Writer Review (LM)

#3563 PD-1577 / 25.04 / PD-1577-update-about-ref-content
  static/images/SCALE/Dashboard/AboutWindow.png
Labels: Review (TM), Re-Review

#3549 PD-1674 / 25.10 / PD-1674-custom-app-ui-ref-update
  static/images/SCALE/Apps/ConvertToCustomAppConfirm.png
  static/images/SCALE/Apps/ConvertToCustomAppMenu.png
  static/images/SCALE/Apps/CustomAppEditWindow.png
  static/includes/apps/CustomAppIntro.md
Labels: Technical Writer Review (MJ), Re-Review, backport-25.04

#3568 PD-1687 / 25.10 / Update DeveloperMode.md
  content/SCALE/SCALETutorials/SystemSettings/Advanced/DeveloperMode.md
Labels: Technical Writer Review (LM), backport-25.04

#3573 PD-1791 / 3.0 / PD-1791 Update TC SMTP Configuration Information
  content/UserGuide/Alerts/AlertManage.md
Labels: Review (TM)

#3571 PD-1763 / 25.10 / Pd 1763 update system general articles
  content/SCALE/SCALETutorials/SystemSettings/General/GeneralSettings.md
  content/SCALE/SCALETutorials/SystemSettings/General/SettingUpSystemEmail.md
  content/SCALE/SCALETutorials/SystemSettings/General/_index.md
  content/SCALE/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  static/images/SCALE/SystemSettings/EmailOptionsSMTP.png
  static/images/SCALE/SystemSettings/GeneralSettingsSCALESupportLicenseComplete.png
  static/images/SCALE/SystemSettings/SaveConfigurationWindow.png
  static/images/SCALE/SystemSettings/SendFeedbackReportABugWindow.png
  static/images/SCALE/SystemSettings/SystemGeneralAddNTPServer.png
  static/images/SCALE/SystemSettings/SystemGeneralGuiSettings.png
  static/images/SCALE/SystemSettings/SystemGeneralLocalizationSettings.png
  static/images/SCALE/SystemSettings/SystemGeneralScreen.png
  static/includes/AdvancedSettingsWarningSCALE.md
  static/includes/EmailOptions.md
  static/includes/EmailOptionsGmail.md
  static/includes/EmailOptionsOutlook.md
  static/includes/EmailOptionsSMTP.md
  static/includes/FeedbackWindow.md
  static/includes/InitShutdownWarning.md
Labels: Review (TM), backport-25.04

#3556 PD-1783 / 25.10 / PD-1783 Update EncryptionSCALE.md Tutorial
  content/SCALE/SCALETutorials/Datasets/EncryptionSCALE.md
Labels: Review (TM), backport-25.04, backport-24.10

#3554 PD-1551 / 25.10 / PD-1551 Update the Group Screens and Tutorial Articles
  content/SCALE/SCALETutorials/Credentials/ManageLocalGroups.md
  content/SCALE/SCALEUIReference/Credentials/LocalGroupsScreens.md
  static/images/SCALE/Credentials/AddGroupScreen.png
Labels: Technical Writer Review (LM)

#3580 D 1817 24.04 message kubernetes migration and 24 10 apps update cutoff
  content/SCALETutorials/Apps/_index.md
  content/SCALEUIReference/Apps/_index.md
  static/custom.css
  static/includes/AppsHostIP.md
  static/includes/AppsSupportTimeline.md
  words-to-ignore.txt
Labels: Technical Writer Review (LM)

#3583 Update opengraph.html
  layouts/partials/microformats/opengraph.html
Labels: Technical Writer Review (LM)

#3577 PD-1817 / None / Pd 1817 master message kubernetes migration and 24 10 apps update cutoff
  content/SCALE/SCALEUIReference/Apps/_index.md
  content/TruenasApps/_index.md
  static/custom.css
  static/includes/AppsHostIP.md
  static/includes/AppsSupportTimeline.md
  static/includes/AppsUnversionedAdmonition.md
  static/includes/UpgradeNotesBoilerplate.md
  words-to-ignore.txt
Labels: Technical Writer Review (MJ), Re-Review

#3581 PD-1673 / 25.10 / Pd 1673 apps UI content updates
  content/SCALE/SCALEUIReference/Apps/_index.md
  content/TruenasApps/_index.md
  static/images/SCALE/Apps/AppsDeleteAppDialog.png
  static/images/SCALE/Apps/AppsPodShellScreen.png
  static/images/SCALE/Apps/ChooseShellDetailsDialog.png
  static/images/SCALE/Apps/CreateDockerRegistry.png
  static/images/SCALE/Apps/CreateDockerRegistryOther.png
  static/images/SCALE/Apps/DockerRegistriesScreen.png
Labels: Technical Writer Review (MJ), Re-Review, backport-25.04

#3578 D 1817 24.10 message kubernetes migration and 24 10 apps update cutoff
  content/GettingStarted/SCALEReleaseNotes.md
  content/SCALEUIReference/Apps/_index.md
  static/custom.css
  static/includes/AppsHostIP.md
  static/includes/AppsSupportTimeline.md
  static/includes/UpgradeNotesBoilerplate.md
  words-to-ignore.txt
Labels: Technical Writer Review (LM), Re-Review

#3592 Update opengraph compatibility further (25.04)
  layouts/partials/microformats/opengraph.html
  static/images/open-enterprise-storage--logo-full-color-rgb-large.png
Labels: Version Specific

#3582 PD-1657 / 25.10 / Pd 1657 document system de registration from true command cloud
  content/AdminGuide/Systems.md
  content/TCGettingStarted/Install/InstallTCCloud.md
  content/UserGuide/SystemManagement/SingleSystem/SingleSystemSettings.md
  static/images/TrueCommand/Cloud/CloudSubscriptionServiceDetails.png
  static/images/TrueCommand/Cloud/CloudSubscriptionServiceDetailsWireGuardClient.png
  static/includes/TCCloudConnectSystems.md
Labels: Technical Writer Review (LM)

#3593 Update docs-nav.html 25.04
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#3594 Update opengraph compatibility further (24.10)
  layouts/partials/microformats/opengraph.html
  static/images/open-enterprise-storage--logo-full-color-rgb-large.png
Labels: Version Specific, Technical Writer Review (TR)

#3596 Update docs-nav.html 24.04
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#3595 Update docs-nav.html-24.10
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#3597 Update docs-nav.html 13.3
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#3598 Update docs-nav.html 13.0
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#3602 Add cli warning
  static/includes/IncusExperimental.md
  static/includes/InstanceWarning.md
Labels: Technical Writer Review (TR), backport-25.10

#3600 Update opengraph compatibility further (24.04)
  layouts/partials/microformats/opengraph.html
  static/images/open-enterprise-storage--logo-full-color-rgb-large.png
Labels: Version Specific, Technical Writer Review (TR)

#3601 Update opengraph compatibility further (13.0)
  layouts/partials/microformats/opengraph.html
  static/images/open-enterprise-storage--logo-full-color-rgb-large.png
Labels: Version Specific, Technical Writer Review (TR)

#3603 Add cli warning master
  static/includes/IncusExperimental.md
  static/includes/InstanceWarning.md
Labels: Technical Writer Review (TR)

#3605 Update opengraph compatibility further (tc 3.0)
  layouts/partials/microformats/opengraph.html
  static/images/open-enterprise-storage--logo-full-color-rgb-large.png
Labels: Version Specific, Technical Writer Review (TR)

#3586 PD-1673 / 25.04 / Pd 1673 apps UI content updates (by DjP-iX)
  content/SCALEUIReference/Apps/_index.md
  static/images/SCALE/Apps/AppsDeleteAppDialog.png
  static/images/SCALE/Apps/AppsPodShellScreen.png
  static/images/SCALE/Apps/ChooseShellDetailsDialog.png
  static/images/SCALE/Apps/CreateDockerRegistry.png
  static/images/SCALE/Apps/CreateDockerRegistryOther.png
  static/images/SCALE/Apps/DockerRegistriesScreen.png
Labels: Technical Writer Review (TR)

#3604 Update opengraph compatibility further (13.3)
  layouts/partials/microformats/opengraph.html
  static/images/open-enterprise-storage--logo-full-color-rgb-large.png
Labels: Version Specific, Technical Writer Review (TR)

#3579 PD-1750 / 25.10 / Pd 1750 update true cloud backup and cloud sync task content
  content/SCALE/SCALETutorials/DataProtection/TrueCloudTasks.md
  content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  content/SCALE/SCALEUIReference/DataProtection/TrueCloudBackupTasksScreen.md
  static/images/SCALE/DataProtection/AddCloudSyncTaskPushControlAdvancedOptions.png
  static/images/SCALE/DataProtection/AddTrueCloudTaskAdvancedOptions.png
  static/images/SCALE/DataProtection/AddTrueCloudTaskBasicOptions.png
Labels: Technical Writer Review (LM), Re-Review

#3606 R50BMPUM
  content/Hardware/RSeries.md
  static/images/Hardware/RSeries/R50BMPUM.png
Labels: Technical Writer Review (TR)

#3607 PD-1826 / 25.10 / update some time machine quota references
  content/References/SMB.md
  content/SCALE/SCALETutorials/Shares/SMB/SetUpBasicTimeMachineSMBShare.md
  content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#3565 PD-1464 / 25.10 / Pd 1464 expand security content with web locations of software calls
  content/References/DefaultPorts.md
  content/Solutions/Optimizations/Security.md
  content/TruenasApps/CommunityApps/Immich.md
  content/TruenasApps/StableApps/storj.md
  static/includes/apps/InstallWizardDefaultPorts.md
Labels: Review (TM), Re-Review

#3550 PD-1789 / 25.10 / Pd 1789 update smb article content
  content/SCALE/GettingStarted/Configure/VMandAppConfigSCALE.md
  content/SCALE/SCALETutorials/Shares/MixedModeShares.md
  content/SCALE/SCALETutorials/Shares/SMB/AddSMBHomeShare.md
  content/SCALE/SCALETutorials/Shares/SMB/SMBPrivateDatasetShare.md
  content/SCALE/SCALETutorials/Shares/SMB/_index.md
  content/SCALE/SCALEUIReference/Datasets/_index.md
  content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md
  static/images/SCALE/Datasets/DeleteDatasetChildDataset.png
  static/images/SCALE/Datasets/DeleteDatasetChildUsingAService.png
  static/images/SCALE/Datasets/DeleteDatasetParentDataset.png
  static/images/SCALE/Shares/AddPrivateSMBShareAdvancedOptions.png
  static/includes/SMBPurposePresets.md
Labels: Technical Writer Review (TR), Re-Review

#3608 PD-1766 / 25.10 / Pd 1766 improve footer behavior
  layouts/partials/site-footer.html
  static/custom.css
Labels: Technical Writer Review (MJ), backport-25.04, backport-24.10, backport-24.04, backport-13.3, backport-13.0, backport-3.0

#3613 PD-1766 / 13.0 / Pd 1766 improve footer behavior (by DjP-iX)
  layouts/partials/site-footer.html
  static/custom.css
Labels: Technical Writer Review (TR)

#3614 PD-1766 / 13.3 / Pd 1766 improve footer behavior (by DjP-iX)
  layouts/partials/site-footer.html
  static/custom.css
Labels: Technical Writer Review (TR)

#3616 PD-1766 / 24.10 / Pd 1766 improve footer behavior (by DjP-iX)
  layouts/partials/site-footer.html
  static/custom.css
Labels: Technical Writer Review (TR)

#3617 PD-1766 / 25.04 / Pd 1766 improve footer behavior (by DjP-iX)
  layouts/partials/site-footer.html
  static/custom.css
Labels: Technical Writer Review (TR)

#3618 PD-1766 / 3.0 / Pd 1766 improve footer behavior (by DjP-iX)
  layouts/partials/site-footer.html
  static/custom.css
Labels: Technical Writer Review (TR)

#3621 PD-1839 / 25.04 / add clarification about SMB lease change (25.04)
  content/GettingStarted/SCALEReleaseNotes.md
  content/SCALETutorials/Shares/MixedModeShares.md
Labels: Version Specific, Technical Writer Review (TR)

#3610 PD-1825 / 25.10 / add small groupings to TrueNAS version selector (backports n…
  layouts/partials/docs-nav.html
  static/custom.css
Labels: Technical Writer Review (TR), Technical Writer Review (MJ), Backport Requested, backport-25.04, backport-24.10, backport-24.04, backport-13.3, backport-13.0, backport-3.0

#3612 PD-1825 / 25.10 / update home page boxes for more distinction between Community and Enterprise (master only)
  layouts/shortcodes/section-cards.html
  static/images/Truenas_community_edition_logos_2025_Logo_Full_Color_Rgb_1-29-25.png
  static/images/Truenas_enterprise_logo_2025_Logo_Full_Color_Rgb_1-29-25.png
Labels: Version Specific, Technical Writer Review (TR), Technical Writer Review (MJ)

#3574 PD-1763 / 25.04 / Pd 1763 update system general articles (by micjohnson777)
  content/SCALETutorials/SystemSettings/General/GeneralSettings.md
  content/SCALETutorials/SystemSettings/General/SettingUpSystemEmail.md
  content/SCALETutorials/SystemSettings/General/_index.md
  content/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  static/images/SCALE/SystemSettings/EmailOptionsSMTP.png
  static/images/SCALE/SystemSettings/GeneralSettingsSCALESupportLicenseComplete.png
  static/images/SCALE/SystemSettings/SaveConfigurationWindow.png
  static/images/SCALE/SystemSettings/SendFeedbackReportABugWindow.png
  static/images/SCALE/SystemSettings/SystemGeneralAddNTPServer.png
  static/images/SCALE/SystemSettings/SystemGeneralGuiSettings.png
  static/images/SCALE/SystemSettings/SystemGeneralLocalizationSettings.png
  static/images/SCALE/SystemSettings/SystemGeneralScreen.png
  static/includes/AdvancedSettingsWarningSCALE.md
  static/includes/EmailOptions.md
  static/includes/EmailOptionsGmail.md
  static/includes/EmailOptionsOutlook.md
  static/includes/EmailOptionsSMTP.md
  static/includes/FeedbackWindow.md
  static/includes/InitShutdownWarning.md
Labels: Technical Writer Review (TR)

#3575 PD-1783 / 24.10 / PD-1783 Update EncryptionSCALE.md Tutorial (by micjohnson777)
  .github/CODEOWNERS
  content/SCALETutorials/Datasets/EncryptionSCALE.md
Labels: Technical Writer Review (TR)

#3576 PD-1783 / 25.04 / PD-1783 Update EncryptionSCALE.md Tutorial (by micjohnson777)
  content/SCALETutorials/Datasets/EncryptionSCALE.md
Labels: Technical Writer Review (TR)

#3629 PD-1825 / 13.0 / add small groupings to TrueNAS version selector (backports n… (by Mrt134)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#3630 PD-1825 / 13.3 / add small groupings to TrueNAS version selector (backports n… (by Mrt134)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#3631 PD-1825 / 24.04 / add small groupings to TrueNAS version selector (backports n… (by Mrt134)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#3632 PD-1825 / 24.10 / add small groupings to TrueNAS version selector (backports n… (by Mrt134)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#3633 PD-1825 / 25.04 / add small groupings to TrueNAS version selector (backports n… (by Mrt134)
  layouts/partials/docs-nav.html
  static/custom.css
Labels: Technical Writer Review (TR)

#3634 PD-1825 / 3.0 / add small groupings to TrueNAS version selector (backports n… (by Mrt134)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#3623 PD-1753 / 25.04 / PD-1753-document-type-option-for-sysctls
  content/SCALETutorials/SystemSettings/Advanced/_index.md
  content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  static/images/SCALE/SystemSettings/AddSysctlConfigScreen.png
Labels: Technical Writer Review (TR)

#3636 Add small groupings to TrueNAS version selector (13.3 cleanup)
  layouts/partials/docs-nav.html
  static/custom.css
Labels: Technical Writer Review (TR)

#3637 PD-1825 / 3.0 / add small groupings to TrueNAS version selector (final polish)
  layouts/partials/docs-nav.html
  static/custom.css
Labels: Technical Writer Review (TR)

#3639 PD-1825 / 24.04 / add small groupings to TrueNAS version selector (final polish)
  layouts/partials/docs-nav.html
  static/custom.css
Labels: Technical Writer Review (TR)

#3619 PD-1728 / 25.10 / Pd 1728 reorganize truenas apps general info content
  content/Contributing/Applications/_index.md
  content/SCALE/SCALEUIReference/Apps/_index.md
  content/TruenasApps/CommunityApps/_index.md
  content/TruenasApps/EnterpriseApps/_index.md
  content/TruenasApps/ManagingApps.md
  content/TruenasApps/StableApps/_index.md
  content/TruenasApps/Support-Definitions.md
  content/TruenasApps/UsingTrains.md
  content/TruenasApps/_index.md
  static/custom.css
  static/images/SCALE/Apps/AppsManageContainerImages.png
  static/images/SCALE/Apps/DeleteImage.png
  static/includes/apps/AppCatalogs.md
  static/includes/apps/Apps-Community-Support.md
  static/includes/apps/AppsDatasets.md
  static/includes/apps/AppsIntro.md
  static/includes/apps/AppsManageImages.md
  static/includes/apps/AppsPool.md
  static/includes/apps/EnterpriseApps.md
  static/includes/apps/HostPathACL.md
  static/includes/apps/InstallWizardSettingsOverview.md
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#3622 PD-1789 / 25.04 / Pd 1789 update smb article content (by micjohnson777)
  content/GettingStarted/Configure/VMandAppConfigSCALE.md
  content/SCALETutorials/Shares/MixedModeShares.md
  content/SCALETutorials/Shares/SMB/AddSMBHomeShare.md
  content/SCALETutorials/Shares/SMB/SMBPrivateDatasetShare.md
  content/SCALETutorials/Shares/SMB/_index.md
  content/SCALEUIReference/Datasets/_index.md
  content/SCALEUIReference/Shares/SMBSharesScreens.md
  static/includes/SMBPurposePresets.md
Labels: Technical Writer Review (TR)

#3626 PD-1814 / 25.10 / Pd 1814 improve UI reference
  content/SCALE/SCALETutorials/Instances/_index.md
  content/SCALE/SCALETutorials/Network/ContainerNASBridge.md
  content/SCALE/SCALEUIReference/InstancesScreens.md
  static/includes/InstanceEnvironmentSettings.md
  static/includes/InstanceImageFilenames.md
  static/includes/InstanceProxySettings.md
  static/includes/MacvlanHost.md
  static/includes/NetworkBridgeSCALE.md
Labels: Technical Writer Review (TR), backport-25.04, backported

#3627 PD-1814 / 25.04 / Pd 1814 improve UI reference (by DjP-iX)
  content/GettingStarted/Migrate/MigratingFromCORE.md
  content/SCALETutorials/Instances/_index.md
  content/SCALETutorials/Network/ContainerNASBridge.md
  content/SCALETutorials/SystemSettings/Services/SSHServiceSCALE.md
  content/SCALEUIReference/InstancesScreens.md
  static/includes/InstanceEnvironmentSettings.md
  static/includes/InstanceImageFilenames.md
  static/includes/InstanceProxySettings.md
  static/includes/MacvlanHost.md
  static/includes/NetworkBridgeSCALE.md
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#3624 PD-1802 / 25.10 / Pd 1802 add iscsi info to migrate prep.md in master
  content/SCALE/GettingStarted/Migrate/MigratePrep.md
Labels: Technical Writer Review (TR)

#3625 PD-1802 / 25.04 / PD-1802 Add iSCSI info to MigratePrep.md
  content/GettingStarted/Migrate/MigratePrep.md
Labels: Technical Writer Review (TR)

#3620 PD-1839 / 25.10 / add Time Machine compatibility note
  content/SCALE/SCALETutorials/Shares/MixedModeShares.md
Labels: Technical Writer Review (MJ)

#3585 Update MigratingVMs.md
  static/includes/MigratingVMs.md
Labels: Technical Writer Review (MJ), Re-Review

#3640 PD-1801 / 25.10 / PD-1801 Update Pool Creation Content
  content/SCALE/SCALEUIReference/Storage/PoolCreateWizardScreens.md
  static/includes/CreatePool.md
  static/includes/PoolCreationWizardCommonSettings.md
Labels: Technical Writer Review (TR)

#3641 PD-1559 / 25.04 / PD-1559-alert-services-field-updates
  static/images/SCALE/SystemSettings/AddAlertServiceEmailScreen.png
  static/images/SCALE/SystemSettings/AddAlertServiceSplunkOnCallScreen.png
  static/images/SCALE/SystemSettings/AddAlertServiceVictorOpsScreen.png
  static/images/SCALE/SystemSettings/AlertSettingsCertificates.png
  static/images/SCALE/SystemSettings/AlertSettingsKMIP.png
  static/images/SCALE/SystemSettings/AlertSettingsNetwork.png
  static/images/SCALE/SystemSettings/AlertSettingsScreen.png
  static/images/SCALE/SystemSettings/AlertSettingsUPS.png
  static/includes/AlertsTypes.md
Labels: Technical Writer Review (TR)

#3648 PD-1853 / 13.0 / PD-1853 Fix Command in line 23 of NPIV.md Snippet
  static/includes/NPIV.md
Labels: backport-13.3

#3655 PD-1759 / 25.04 / PD-1759-update-enclosure-content
  static/images/SCALE/SystemSettings/ViewEnclosureDiskDetailsMini.png
  static/images/SCALE/SystemSettings/ViewEnclosureDiskInfo.png
  static/images/SCALE/SystemSettings/ViewEnclosureFront.png
  static/images/SCALE/SystemSettings/ViewEnclosureScreenMini.png
Labels: backport-25.10
