Repository truenas/documentation, pull requests merged in 2025-08, with the labels that each got.

#4002 NAS-136947: Add early note about Nvidia driver change in 25.10 nightlies
  content/SCALE/GettingStarted/SCALEReleaseNotes.md
Labels: Technical Writer Review (MJ)

#4001 Add 25.04.2 known issues
  content/GettingStarted/SCALEReleaseNotes.md
  words-to-ignore.txt
Labels: Technical Writer Review (MJ)

#3999 PD-1996 / None / Pd 1996 update release schedule 25.04
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
Labels: Version Specific

#3954 PD-2047 / 25.04 / PD-2047-document-new-network-global-config-option-allow-all-except (by linzi-ix)
  content/SCALETutorials/Network/ManagingGlobalConfig.md
  content/SCALEUIReference/Network/GlobalConfigurationScreens.md
  static/images/SCALE/Network/GlobalConfigOutboundSettings.png
Labels: Technical Writer Review (MJ), Re-Review

#4019 PD-2131 / 13.3 / Pd 2131 no indication to add user to ftp group (by DjP-iX)
  content/CORETutorials/Services/ConfiguringFTP.md
Labels: Technical Writer Review (TR)

#4006 PD-1999 / 25.10 / Pd 1999 update storage and dataset content
  content/SCALE/SCALETutorials/Datasets/AddManageZvols.md
  content/SCALE/SCALETutorials/Storage/Disks/ReplacingDisks.md
  content/SCALE/SCALETutorials/Storage/Disks/SEDScale.md
  content/SCALE/SCALETutorials/Storage/Disks/_index.md
  content/SCALE/SCALETutorials/Storage/ManagePoolsScale.md
  content/SCALE/SCALEUIReference/Datasets/EncryptionUISCALE.md
  content/SCALE/SCALEUIReference/Datasets/ZvolsScreensScale.md
  content/SCALE/SCALEUIReference/Datasets/_index.md
  content/SCALE/SCALEUIReference/Storage/DevicesScreensSCALE.md
  content/SCALE/SCALEUIReference/Storage/DisksScreen.md
  content/SCALE/SCALEUIReference/Storage/_index.md
  static/images/SCALE/Datasets/AddDatasetEncryptionKey.png
  static/images/SCALE/Datasets/AddDatasetEncryptionPassphrase.png
  static/images/SCALE/Datasets/AddDatasetOtherOptionsAdvanced1.png
  static/images/SCALE/Datasets/AddDatasetOtherOptionsAdvanced2.png
  static/images/SCALE/Datasets/AddDatasetQuotasManagement.png
  static/images/SCALE/Datasets/AddDatasetScreenBasicOptions.png
  static/images/SCALE/Datasets/AddZvolScreen.png
  static/images/SCALE/Datasets/DatasetEncryptionWidget.png
  static/images/SCALE/Datasets/DatasetPermissionsNFSv4EditOptions.png
  static/images/SCALE/Datasets/DatasetPermissionsWidgetNFSv4.png
  static/images/SCALE/Datasets/DatasetPermissionsWidgetRoot.png
  static/images/SCALE/Datasets/DatasetUsageWidgetNotShared.png
  static/images/SCALE/Datasets/DatasetWidgetsSystemDataset.png
  static/images/SCALE/Datasets/DatasetsDataProtectionWidget.png
  static/images/SCALE/Datasets/DatasetsScreen.png
  static/images/SCALE/Datasets/DatasetsScreenWithZvolWidgets.png
  static/images/SCALE/Datasets/DatasetsSpaceManagementWidget.png
  static/images/SCALE/Datasets/DatasetsUsageWidgetSystemDataset.png
  static/images/SCALE/Datasets/DeleteDatasetWindow.png
  static/images/SCALE/Datasets/DeleteZvolWindow.png
  static/images/SCALE/Datasets/DetailsWidgetChildDataset.png
  static/images/SCALE/Datasets/DetailsWidgetRootSystemDataset.png
  static/images/SCALE/Datasets/DetailstWidgetSystemDataset.png
  static/images/SCALE/Datasets/ZvolDataProtectionWidget.png
  static/images/SCALE/Datasets/ZvolDetailsWidget.png
  static/images/SCALE/Datasets/ZvolEncryptionWidget.png
  static/images/SCALE/Datasets/ZvolSpaceManagementWidget.png
  static/images/SCALE/Storage/AddToPoolWindow.png
  static/images/SCALE/Storage/ConfigureScheduledScrubScreen.png
  static/images/SCALE/Storage/DataVdevExpanded.png
  static/images/SCALE/Storage/DevicesDiskDegraded.png
  static/images/SCALE/Storage/DiskInfoWidget.png
  static/images/SCALE/Storage/DiskScreenExpandedDiskWithWipeOption.png
  static/images/SCALE/Storage/EditDiskScreen.png
  static/images/SCALE/Storage/MainDashboardPoolAndStorageWidgetsDegraded.png
  static/images/SCALE/Storage/ReplacingDiskDialog.png
  static/images/SCALE/Storage/StorageDashboardDiskHealthWidget.png
  static/images/SCALE/Storage/StorageDashboardUsageWidget.png
  static/images/SCALE/Storage/StorageDashboardVDEVWidget.png
  static/images/SCALE/Storage/StorageDashboardWithPool.png
  static/images/SCALE/Storage/StoragePoolWidgetsDegradedState.png
  static/images/SCALE/Storage/VDEVDiskWidgets.png
  static/images/SCALE/Storage/VDEVScreen.png
  static/images/SCALE/Storage/VDEVScreenExpanded.png
  static/images/SCALE/Storage/ZFSInfoWidgetWithExtendRemove.png
  static/images/SCALE/Storage/ZvolInfoWidget.png
  static/includes/EncryptionSettings.md
Labels: Technical Writer Review (TR)

#4023 PD-2124 / 25.10 / PD-2124-update-smb-share-content-for-updated-behavior
  content/SCALE/SCALETutorials/Shares/SMB/_index.md
  content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md
Labels: Technical Writer Review (TR)

#3947 Pd 1903 add nvme-of reference and tutorial content
  content/SCALE/SCALETutorials/Shares/NVMe-oF/Managing-NVMe-of-Subsystems.md
  content/SCALE/SCALETutorials/Shares/NVMe-oF/_index.md
  content/SCALE/SCALEUIReference/Shares/_index.md
  content/SCALE/SCALEUIReference/Shares/nvme-of-screens.md
  static/images/SCALE/Shares/AddHostScreen.png
  static/images/SCALE/Shares/AddHostScreenRequireAuthentication.png
  static/images/SCALE/Shares/AddNamespaceScreenZvolTab.png
  static/images/SCALE/Shares/AddNewFileToNamespace.png
  static/images/SCALE/Shares/AddPortScreen.png
  static/images/SCALE/Shares/AddSubSystemAccess.png
  static/images/SCALE/Shares/AddSubsystemAccessWithAllowedHosts.png
  static/images/SCALE/Shares/AddSubsystemWhatToShare.png
  static/images/SCALE/Shares/AddZvolScreen.png
  static/images/SCALE/Shares/AddZvolScreenEncryption.png
  static/images/SCALE/Shares/AddZvolScreenKeyEncryption.png
  static/images/SCALE/Shares/AddZvolScreenPassphraseEncryption.png
  static/images/SCALE/Shares/AssoicatedHostsWiidgetWithHost.png
  static/images/SCALE/Shares/DeleteHostDialog.png
  static/images/SCALE/Shares/DeleteNamespaceDialog.png
  static/images/SCALE/Shares/DeleteNamespaceFromFile.png
  static/images/SCALE/Shares/DeletePortDialog.png
  static/images/SCALE/Shares/DeleteSubsystemDialog.png
  static/images/SCALE/Shares/EditNamespaceExistingFileTab.png
  static/images/SCALE/Shares/EditNamespaceNewFileTab.png
  static/images/SCALE/Shares/EditNamespaceScreenZvolTab.png
  static/images/SCALE/Shares/EditPortScreen.png
  static/images/SCALE/Shares/ManageHostsWindow.png
  static/images/SCALE/Shares/ManagePortsDialog.png
  static/images/SCALE/Shares/NVMe-oFScreenWithSubsystems.png
  static/images/SCALE/Shares/NVMe-oFScreenWithoutSubsystems.png
  static/images/SCALE/Shares/NVMeoFGlobalConfigurationScreen.png
  static/images/SCALE/Shares/RemoveFromSubsystem.png
  static/images/SCALE/Shares/SharesScreenWithNVMeRunning.png
  static/images/SCALE/Shares/SharingDashboardNoShares.png
  static/images/SCALE/Shares/SubsystemAssociatedHostsWidget.png
  static/images/SCALE/Shares/SubsystemDetailsWidget.png
  static/images/SCALE/Shares/SubsystemNamespacesWidget.png
  static/images/SCALE/Shares/SubsystemPortsWidget.png
  static/images/SCALE/Shares/UseExistingFileInEditNamespace.png
  static/includes/Add-Zvol-To-NVMe-oF-Namespace.md
  static/includes/NVMe-oFAddPortsMenu.md
  static/includes/NVMe-of-Overview.md
  static/includes/NVMe-of-Structure.md
Labels: Technical Writer Review (DP), Re-Review

#3973 PD-2114 / 25.10 / PD-2114-changes-to-groups-may-not-take-effect-in-nfs-for-up-to-10-min
  content/SCALE/SCALETutorials/Shares/AddingNFSShares.md
  content/SCALE/SCALETutorials/SystemSettings/Services/NFSServiceSCALE.md
  content/SCALE/SCALEUIReference/Shares/NFSSharesScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md
  static/includes/NFSUpdateTime.md
Labels: Technical Writer Review (DP), Re-Review

#4047 PD-1997 / 26.04 / PD-1997-update-explorer-related-content-for-updated-create-dataset-op…
  static/images/SCALE/Shares/AddNFSSharePath.png
  static/images/SCALE/Shares/AddPrivateSMBShare.png
  static/images/SCALE/Shares/AddSMBPath.png
  static/images/SCALE/Shares/iSCSIWizardExtentScreenFCAddNew.png
Labels: Review (TM), backport-25.10

#4044 PD-2000 / 25.10 / PD-2000-document-recipient-configuration-for-emails
  content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/General/SettingUpSystemEmail.md
  content/SCALE/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  static/images/SCALE/SystemSettings/EditAlertServiceEmailScreen.png
  static/images/SCALE/SystemSettings/EmailOptionsGmailOAuth.png
  static/images/SCALE/SystemSettings/EmailOptionsGmailOAuthApplied.png
  static/includes/AlertsTypes.md
Labels: Review (TM), Re-Review, backport-25.10

#4050 PD-2000 / 25.10 / PD-2000-document-recipient-configuration-for-emails (by linzi-ix)
  content/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
  content/SCALETutorials/SystemSettings/General/SettingUpSystemEmail.md
  content/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  static/images/SCALE/SystemSettings/EditAlertServiceEmailScreen.png
  static/images/SCALE/SystemSettings/EmailOptionsGmailOAuth.png
  static/images/SCALE/SystemSettings/EmailOptionsGmailOAuthApplied.png
  static/includes/AlertsTypes.md
Labels: Review (TM)

#4051 PD-1966 / 26.04 / Pd 1966 update changelog table
  CSV-TABLE-SETUP.md
  scripts/combine-changelogs.py
  static/js/csv-changelog-table.js
Labels: backport-26.04

#4039 PD-2003 / 25.10 / PD-2003-rework-scrub-related-content
  content/References/ConceptsAndTerms.md
  content/References/ZFSDeduplication.md
  content/SCALE/SCALETutorials/DataProtection/SMARTTestsSCALE.md
  content/SCALE/SCALETutorials/DataProtection/ScrubTasksSCALE.md
  content/SCALE/SCALETutorials/Storage/ManagePoolsScale.md
  content/SCALE/SCALETutorials/SystemSettings/General/SettingUpSystemEmail.md
  content/SCALE/SCALEUIReference/DataProtection/ScrubTasksScreensSCALE.md
  content/SCALE/SCALEUIReference/Storage/_index.md
  static/images/SCALE/DataProtection/PriorityResilveringForm.png
  static/images/SCALE/DataProtection/ScrubPoolDialog.png
  static/images/SCALE/DataProtection/ScrubTaskEditSCALE.png
  static/images/SCALE/Storage/StorageHealthWidget.png
  words-to-ignore.txt
Labels: Technical Writer Review (MJ), Re-Review

#4040 PD-2065 / 25.10 / PD-2065-directory-services-content-updates
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigADSCALE.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigFreeIPA.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigIDmapSCALE.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigIPASCALE.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigKerberosSCALE.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigLDAPSCALE.md
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/_index.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/ActiveDirectory.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/IPA.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/Idmap.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/KerberosRealms.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/KerberosSettings.md
  content/SCALE/SCALEUIReference/Credentials/DirectoryServices/_index.md
  static/images/SCALE/Credentials/ActiveDirectoryBasicOptions.png
  static/images/SCALE/Credentials/IPABasicConfigOptions.png
  static/images/SCALE/Credentials/IPAFinalConfigOptions.png
  static/images/SCALE/Credentials/LDAPBasicOptionsSettings.png
  static/images/SCALE/Credentials/TrustedDomainsConfiguration.png
Labels: Technical Writer Review (MJ), Re-Review, backport-25.10

#4042 PD-2180 / 25.04 / Pd 2180 25 04 2 3 maintenance release docs
  content/GettingStarted/SCALEReleaseNotes.md
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  static/includes/SCALEUpgradePaths.md
  words-to-ignore.txt
Labels: Version Specific

#4055 PD-1970 / 25.04 / PD-1970-port-version-switcher
  layouts/partials/docs-nav.html
Labels: Review (TM), backport-24.10, backport-13.3, backport-13.0, backport-3.0

#4070 PD-2192 / 26.04 / fix version select behavior for 25.10 version option
  layouts/partials/docs-nav.html
Labels: backport-25.04, backport-24.10, backport-13.3, backport-13.0, backport-3.0, backport-25.10

#4058 PD-1966 / 25.10 / Pd 1966 25 10 beta 1 release docs
  CSV-TABLE-SETUP.md
  content/GettingStarted/SCALEReleaseNotes.md
  content/SCALETutorials/Credentials/Certificates/CertificatesSCALE.md
  content/SCALETutorials/Shares/NVMe-oF/_index.md
  content/SCALEUIReference/Storage/DisksScreen.md
  content/_index.md
  data/properties/component_versions.yaml
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  layouts/partials/toc-panel.html
  static/data/25.10-BETA.1-changelog.csv
  static/data/25.10-changelog.csv
  static/data/changelog-versions.json
  static/icons/fiber-new.svg
  static/icons/history.svg
  static/icons/warning.svg
  static/images/truenas-community-edition-logo-blue.png
  static/images/truenas-community-edition-logo-white.png
  static/images/truenas-enterprise-logo-logo-blue.png
  static/images/truenas-enterprise-logo-logo-white-rgb-900px-w-72ppi.png
  static/includes/25.04Virtualization.md
  static/includes/25.10FeatureList.md
  static/includes/25.10UpgradeMethods.md
  static/includes/APIDocs.md
  static/includes/RESTAPIDeprecationNotice.md
  static/includes/SCALEUpgradePaths.md
  static/includes/apps-market-ad-banner.md
  static/js/csv-changelog-init.js
  static/js/csv-changelog-tab-init.js
  static/js/csv-changelog-table.js
  static/js/linkable-tabs.js
  words-to-ignore.txt
Labels: Version Specific

#4062 PD-2174 / 26.04 / Pd 2174 acme content updates
  content/SCALE/SCALETutorials/Credentials/Certificates/AddACMESCALE.md
  content/SCALE/SCALETutorials/Credentials/Certificates/AddCSRsSCALE.md
  content/SCALE/SCALEUIReference/Credentials/Certificates/ACMEDNSAuthScreensSCALE.md
  static/images/SCALE/Credentials/ACMEDNS-AuthentictorsWidget.png
  static/images/SCALE/Credentials/DeleteDNSAuthenticator.png
Labels: Technical Writer Review (TR), backport-25.10

#4083 PD-2154 / 26.04 / PD-2154 Updates to Storage Tutorials
  content/SCALE/SCALETutorials/Storage/Disks/SEDScale.md
  content/SCALE/SCALETutorials/Storage/FusionPoolsScale.md
  content/SCALE/SCALETutorials/Storage/ManagePoolsScale.md
  content/SCALE/SCALEUIReference/Storage/DevicesScreensSCALE.md
  static/images/SCALE/Storage/AddToPoolExistingPoolWindow.png
  static/includes/FusionPoolsCommonContent.md
  static/includes/FusionPoolsIntro.md
Labels: Technical Writer Review (TR)
