Repository truenas/documentation, pull requests merged in 2025-05, with the labels that each got.

#3766 PD-1832 / 25.04 / master branch updates from instances dev work (by Mrt134)
  content/SCALETutorials/Instances/_index.md
  content/SCALEUIReference/InstancesScreens.md
  static/images/SCALE/Virtualization/InstanceStopOptions.png
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#3767 PD-1885 / 25.04 / Document Enterprise settings for admin password rules (by Mrt134)
  content/SCALETutorials/SystemSettings/Advanced/_index.md
  content/SCALETutorials/SystemSettings/_index.md
  content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  static/images/SCALE/SystemSettings/SystemAdvancedSecurityWidget.png
  static/images/SCALE/SystemSettings/SystemSecurityScreen.png
Labels: Technical Writer Review (TR)

#3769 PD-1906 / 25.10 / Pd 1906 update apps truenas com resource article styling
  layouts/partials/toc-panel.html
  static/custom.css
Labels: backport-25.04, backport-24.10, backport-24.04, backport-13.3, backport-13.0, backport-3.0, backport-25.10

#3772 PD-1906 / 13.3 / Pd 1906 update apps truenas com resource article styling (by DjP-iX)
  layouts/partials/toc-panel.html
  static/custom.css
Labels: Review (TM)

#3773 PD-1906 / 24.04 / Pd 1906 update apps truenas com resource article styling (by DjP-iX)
  layouts/partials/toc-panel.html
  static/custom.css
Labels: Review (TM)

#3774 PD-1906 / 24.10 / Pd 1906 update apps truenas com resource article styling (by DjP-iX)
  layouts/partials/toc-panel.html
  static/custom.css
Labels: Review (TM)

#3775 PD-1906 / 25.04 / Pd 1906 update apps truenas com resource article styling (by DjP-iX)
  layouts/partials/toc-panel.html
  static/custom.css
Labels: Review (TM)

#3777 PD-1906 / 3.0 / Pd 1906 update apps truenas com resource article styling (by DjP-iX)
  layouts/partials/toc-panel.html
  static/custom.css
Labels: Review (TM)

#3778 Fix link in AppsMarket.md
  static/includes/apps/AppsMarket.md
Labels: Review (TM)

#3789 PD-1914 / 25.10 / PD-1914 Correct Time Conversion in Session Settings
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
Labels: backport-25.04

#3790 PD-1914 / 24.10 / PD-1914 Manual Backport of Session Timeout Correction
  content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
Labels: Review (TM)

#3792 PD-1914 / 25.04 / PD-1914 Correct Time Conversion in Session Settings (by micjohnson777)
  content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
Labels: Review (TM)

#3796 Update scale-releases.yaml
  data/properties/scale-releases.yaml
Labels: Review (TM)

#3794 Update MultipleInterfacesOnNetwork.md
  static/includes/MultipleInterfacesOnNetwork.md
Labels: Review (TM)

#3795 25.04 - Update MultipleInterfacesOnNetwork.md
  static/includes/MultipleInterfacesOnNetwork.md
Labels: Review (TM)

#3761 PD-1907 / 25.10 / Pd 1907 update contributing apps docs content for new website
  content/Contributing/Applications/AppArticleTemplate.md
  content/Contributing/Applications/_index.md
  static/images/Contribute/AppsFrontMatterExample.png
  static/includes/apps/InstallAppsStorageConfig.md
  static/includes/apps/InstallAppsStorageConfig2.md
  static/includes/apps/InstallWizardHostNetworkSettings.md
  static/includes/apps/InstallWizardLabelsConfiguration.md
  static/includes/apps/InstallWizardResourceConfig.md
  static/includes/apps/InstallWizardStorageACLConfig.md
  static/includes/apps/InstallWizardStorageSMBOption.md
  static/includes/apps/InstallWizardUserAndGroupConfig.md
Labels: Technical Writer Review (MJ), Review (TM), Re-Review

#3797 PD-1704 / 25.10 / Pd 1704 create audit UI ref article
  content/SCALE/SCALEUIReference/SystemSettings/AuditScreen.md
  static/images/SCALE/SystemSettings/AuditAdvancedSearch.png
  static/images/SCALE/SystemSettings/AuditScreen.png
Labels: Technical Writer Review (LM), backport-25.04

#3804 PD-1847 / 25.10 / PD-1847 Add Web UI Contributions Guide to /docs/contributing
  content/Contributing/WebUICode.md
  words-to-ignore.txt
Labels: Technical Writer Review (MJ)

#3799 PD-1703 / 25.10 / Pd 1703 update auditing content
  content/SCALE/SCALETutorials/SystemSettings/AuditingSCALE.md
Labels: Technical Writer Review (LM), backport-25.04

#3784 PD-1908 / 24.10 / Pd 1908 decommission apps content from docs hub 24.10
  content/GettingStarted/Configure/UIConfigurationSCALE.md
  content/GettingStarted/Configure/VMandAppConfigSCALE.md
  content/GettingStarted/DataMigrationSyncthing.md
  content/GettingStarted/SCALEReleaseNotes.md
  content/SCALETutorials/DataProtection/RsyncTasksSCALE.md
  content/SCALETutorials/Datasets/EncryptionSCALE.md
  content/SCALETutorials/SystemSettings/Advanced/ManageGPUSCALE.md
  content/SCALETutorials/SystemSettings/ManageBootEnvironSCALE.md
  content/SCALETutorials/Virtualization/_index.md
  content/SCALEUIReference/Apps/InstallCustomAppScreens.md
  content/_index.md
  data/menu/more.yml
  layouts/partials/docs-nav.html
  layouts/shortcodes/section-cards.html
  static/includes/24.10FeatureList.md
  static/includes/NetdataUI.md
Labels: Technical Writer Review (MJ)

#3788 PD-1908 / 3.0 / Pd-1908 backport docs nav update
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (MJ), backport-13.3, backport-13.0

#3807 PD-1974 / 25.10 / PD-1974-update-content-about-account-groups-naming
  content/SCALE/SCALETutorials/Credentials/ManageLocalGroups.md
  content/SCALE/SCALEUIReference/Credentials/LocalGroupsScreens.md
Labels: Technical Writer Review (MJ), backport-25.04

#3809 PD-1994 / 25.04 / PD-1994-Update-App-IP-Support-Lists
  static/includes/AppsHostIP.md
Labels: backport-24.10, backport-25.10

#3812 PD-1974 / 25.04 / PD-1974-update-content-about-account-groups-naming (by linzi-ix)
  content/SCALETutorials/Credentials/ManageLocalGroups.md
  content/SCALEUIReference/Credentials/LocalGroupsScreens.md
Labels: Re-Review

#3822 PD-2014 / 25.04 / Pd 2014 update the community migrations article or release notes
  content/GettingStarted/Migrate/MigrateCOREHAtoSCALEHA.md
  content/GettingStarted/Migrate/MigratingFromCORE.md
  static/includes/MigrateCOREtoSCALE24_04.md
Labels: Technical Writer Review (LM), backport-24.10, backport-25.10

#3821 PD-1973 / 25.04 / Pd 1973 24 10 2 2 follow up 25.04
  data/properties/scale-releases.yaml
  static/includes/AppsHostIP.md
  static/includes/AppsSupportTimeline.md
  static/includes/SCALEUpgradePaths.md
Labels: Technical Writer Review (LM), backport-24.04

#3817 PD-1896 / 25.04 / PD-1896-archive-24-04-docs-25.04
  layouts/partials/docs-nav.html
Labels: backport-24.10, backport-13.3, backport-13.0, backport-3.0

#3814 PD-1994 / 25.10 / PD-1994-Update-App-IP-Support-Lists (by DjP-iX)
  static/includes/AppsHostIP.md
Labels: Technical Writer Review (LM)

#3830 Pd-1973-Fix-actions-required
  static/includes/AppsSupportTimeline.md
Labels: backport-25.04, backport-24.04, backport-25.10

#3818 PD-1892-update-ui-ref-for-account-create-username-to-move-from-allowed-to-not-allowed
  content/SCALE/SCALEUIReference/Credentials/LocalGroupsScreens.md
  content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
Labels: Re-Review, backport-25.04

#3824 PD-2014 / 25.10 / Pd 2014 update the community migrations article or release notes (by DjP-iX)
  content/SCALE/GettingStarted/Migrate/MigrateCOREHAtoSCALEHA.md
  content/SCALE/GettingStarted/Migrate/MigratingFromCORE.md
  static/includes/MigrateCOREtoSCALE24_04.md
Labels: Review (TM)

#3836 PD-1973 / 24.04 / Pd 1973 24.04 part deux
  content/SCALETutorials/Credentials/ManageLocalGroups.md
  content/SCALEUIReference/Credentials/LocalGroupsScreens.md
  data/properties/scale-releases.yaml
  static/includes/AppsHostIP.md
  static/includes/AppsSupportTimeline.md
  static/includes/SCALEUpgradePaths.md
Labels: Review (TM)

#3815 PD-1896 / 24.04 / Pd 1896 archive 24 04 docs
  content/_index.md
  i18n/en.yaml
  layouts/partials/docs-nav.html
  layouts/partials/page-header.html
  scripts/cleanup_log.txt
  static/includes/24.04FeatureList.md
  static/includes/_index.md
Labels: Review (TM)

#3828 PD-1896 / 24.10 / PD-1896-archive-24-04-docs-25.04 (by DjP-iX)
  layouts/partials/docs-nav.html
Labels: Review (TM)

#3829 PD-1896 / 3.0 / PD-1896-archive-24-04-docs-25.04 (by DjP-iX)
  layouts/partials/docs-nav.html
Labels: Review (TM)

#3793 PD-1977 / 25.10 / Pd 1977 update initial debug file content
  content/SCALE/GettingStarted/Configure/SetUpBackupScale.md
  content/SCALE/GettingStarted/Configure/UIConfigurationSCALE.md
  static/includes/DownloadSystemConfigFileSCALE.md
Labels: Technical Writer Review (LM), Re-Review, backport-25.04, backport-24.10

#3838 PD-2015: Add Header and More menu entries for API Docs Site
  data/menu/more.yml
  layouts/partials/site-header.html
  static/icons/API-Icon.svg
  themes/hugo-geekdoc/layouts/partials/menu-bundle.html
Labels: Technical Writer Review (MJ), backport-25.04, backport-24.10, backport-24.04, backport-13.3, backport-13.0, backport-3.0

#3843 PD-2015 / 25.10 / fix up api docs icon as an asset sprite
  assets/sprites/api-icon.svg
  data/menu/more.yml
Labels: backport-25.04, backport-24.10, backport-13.3, backport-13.0, backport-3.0

#3850 PD-2015 / 25.04 / Add Header and More menu entries for API Docs Site (#3838)
  data/menu/more.yml
  layouts/partials/site-header.html
  static/icons/API-Icon.svg
  themes/hugo-geekdoc/layouts/partials/menu-bundle.html
Labels: backport-24.10, backport-13.3, backport-13.0, backport-3.0

#3859 (13.0) change api-icon to sprite
  assets/sprites/api-icon.svg
  data/menu/more.yml
Labels: Technical Writer Review (MJ)

#3802 PD-1421 / 25.10 / PD-1421 Update API Docs Content
  content/SCALE/API/_index.md
  content/SCALE/SCALETutorials/TopToolbar/ManagingAPIKeys.md
  static/images/SCALE/Dashboard/APIDocsTableOfContentsScreen.png
  static/images/SCALE/Dashboard/APIKeysScreen.png
  static/includes/APIKeyWarn.md
Labels: backport-25.04

#3855 PD-1994 / 25.04 / Pd 1994 25 04 1 release docs
  content/GettingStarted/Migrate/MigrateCOREHAtoSCALEHA.md
  content/GettingStarted/Migrate/MigratePrep.md
  content/GettingStarted/Migrate/MigratingFromCORE.md
  content/GettingStarted/Migrate/_index.md
  content/GettingStarted/SCALEReleaseNotes.md
  content/SCALETutorials/Instances/_index.md
  data/properties/component_versions.yaml
  data/properties/scale-releases.yaml
  scripts/cleanup_log.txt
  static/images/SCALE/Dashboard/TasksFailed.png
  static/images/SCALE/Reporting/ZFSReportingARCSizeResult.png
  static/images/SCALE/SystemSettings/SecurityFIPSSTIGRestartDialog.png
  static/includes/25.04UpgradeMethods.md
  static/includes/EnterpriseMigrationSupport.md
  static/includes/InstancesManagingProxies.md
  static/includes/MigrateCOREtoSCALE24_04.md
  static/includes/MigratingVMs.md
  static/includes/SCALEUpgradePaths.md
  static/includes/_index.md
  words-to-ignore.txt
Labels: Version Specific

#3872 Corrected Fangtooth paths
  data/properties/scale-downloads.yaml
Labels: Technical Writer Review (LM)

#3873 PD-2017 / 25.10 / PD-2017-document-new-endpoint-option-for-cloud-sync-credentials
  content/SCALE/SCALEUIReference/Credentials/BackupCredentials/CloudCredentialScreens.md
  static/includes/AddStorjCloudCredential.md
Labels: backport-25.04
