Repository truenas/documentation, pull requests merged in 2025-02, with the labels that each got.

#3481 PD-1771 / 25.04 / PD-1771-document-security-concern-for-users-with-custom-scripts
  content/SCALE/SCALETutorials/SystemSettings/Advanced/ManageCronJobsSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  content/Solutions/Optimizations/Security.md
  static/includes/CustomScriptWarning.md
Labels: Technical Writer Review (TR)

#3483 NAS-133983: update 24.10 relnotes terminology
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific, Technical Writer Review (MJ)

#3484 NAS-133983 - changelog term rework (24.04)
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific, Technical Writer Review (MJ)

#3485 NAS-133983: relnotes headers rework (23.10)
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific, Technical Writer Review (MJ)

#3445 PD-1073 / 25.04 / PD-1055 Add Veeam Immutability Solutions Article
  content/Solutions/Integrations/VeeamImmutability.md
  content/TruenasApps/EnterpriseApps/MinIO/_index.md
Labels: Technical Writer Review (DP), Re-Review

#3495 Update SCALEReleaseNotes.md
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Technical Writer Review (MJ)

#3438 PD-1055 / 25.04 / Pd 1055 add fast deduplication content
  content/References/ZFSDeduplication.md
  content/SCALE/SCALETutorials/Datasets/DatasetsSCALE.md
  content/SCALE/SCALETutorials/Storage/ManagePoolsScale.md
  content/SCALE/SCALEUIReference/Storage/_index.md
  static/images/SCALE/Storage/DedupPruneDialog.png
  static/images/SCALE/Storage/DedupPruneDialogAge.png
  static/images/SCALE/Storage/DedupQutoaDialog.png
  static/images/SCALE/Storage/DedupQutoaDialogCustom.png
  static/images/SCALE/Storage/DedupWarningDialog.png
  static/images/SCALE/Storage/StorageDashboardZFSHealthWidget.png
  static/images/SCALE/Storage/StorageDashboardZFSHealthWidgetWithDedup.png
  words-to-ignore.txt
Labels: Technical Writer Review (LM), Re-Review

#3500 Update linkding.md
  content/TruenasApps/CommunityApps/linkding.md
Labels: Technical Writer Review (DP)

#3493 PD-1606 / 24.10 / PD-1606-backport-navigation
  layouts/partials/docs-nav.html
Labels: backport-24.04, backport-23.10, backport-13.3, backport-13.0, backport-3.0

#3489 PD-1460 / 25.04 / PD-1460-replication-task-status-reword
  content/SCALE/SCALEUIReference/DataProtection/ReplicationScreensSCALE.md
Labels: Technical Writer Review (MJ), Re-Review

#3511 PD-1744 / 25.10 / Update TNDataCollection.md
  static/includes/TNDataCollection.md
Labels: Review (TM), backport-25.04

#3513 PD-1744 / 25.04 / Update TNDataCollection.md (by DjP-iX)
  static/includes/TNDataCollection.md
Labels: Technical Writer Review (TR)

#3509 PD-1738 / 25.10 / PD-1738 - fix image typo for emby app
  content/TruenasApps/StableApps/EmbyApp.md
Labels: Technical Writer Review (TR)

#3501 PD-1752 / 25.10 / Pd-1752-document-one-drive-cloud-sync-option
  content/SCALE/SCALETutorials/Credentials/BackupCredentials/AddCloudCredentials.md
  content/SCALE/SCALEUIReference/Credentials/BackupCredentials/CloudCredentialScreens.md
  static/images/SCALE/Credentials/CloudCredentialsMicrosoftOneDrive.png
  static/includes/CloudServiceProvidersSCALE.md
Labels: Technical Writer Review (TR)

#3514 Rework 23.10 header for archival
  content/_index.md
  i18n/en.yaml
  layouts/partials/docs-nav.html
  layouts/partials/page-header.html
  static/includes/23.10FeatureList.md
Labels: Version Specific, Technical Writer Review (TR)

#3515 Remove archived 23.10 docs links from the version selector (25.04)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#3517 Remove archived 23.10 docs links from the version selector (3.0)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#3518 Remove archived 23.10 docs links from the version selector (13.0)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#3519 Remove archived 23.10 docs links from the version selector (13.3)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#3520 Archive 2310 from 24.04 branch (24.04)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#3521 Remove archived 23.10 docs links from the version selector (24.10)
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (TR)

#3516 Update TCReleaseNotes.md (compatible versions)
  content/TCGettingStarted/TCReleaseNotes.md
Labels: Technical Writer Review (TR)

#3528 PD-1755 / 24.10 / Pd 1755 move cleanup script and run 24.10
  scripts/cleanup.ps1
  scripts/cleanup_log.txt
  static/images/CORE/Storage/StoragePoolsOptionsEditPermissionsACLPresetHome.png
  static/images/SCALE/Apps/AddTrueCloudTaskAdvancedOption.png
  static/images/SCALE/Apps/AppsInstallNvidiaDrivers.png
  static/images/SCALE/Apps/CustomAppDetails.png
  static/images/SCALE/Apps/InstallAppResourceConfigurationGPU.png
  static/images/SCALE/Apps/InstallAppStorageConfigSMBOption.png
  static/images/SCALE/Apps/InstallCustomAppAddStorageVolumes.png
  static/images/SCALE/Apps/InstallCustomAppAddWorkloadDetails.png
  static/images/SCALE/Apps/InstallCustomAppContainerEnvironmentVariables.png
  static/images/SCALE/Apps/InstallCustomAppNetworkingAddExternalInterfaces.png
  static/images/SCALE/Apps/InstallCustomAppNetworkingDNSConfig.png
  static/images/SCALE/Apps/InstallCustomAppPortForwarding.png
  static/images/SCALE/Apps/InstallCustomAppScalingUpgradePolicy.png
  static/images/SCALE/CLI/DigCommandOutput.png
  static/images/SCALE/Credentials/DigCommandOutput.png
  static/images/SCALE/Credentials/DirServicesAdvancedSettingsScreen.png
  static/images/SCALE/Credentials/DirectoryServicesADandLDAPWidgets.png
  static/images/SCALE/Credentials/LocalizationSCALE.png
  static/images/SCALE/Credentials/SelelectCertificateStore.png
  static/images/SCALE/DataProtection/AddTrueCloudTask.png
  static/images/SCALE/DataProtection/AdvancedAddReplicationTaskGeneralTransportSSH+NETCAT.png
  static/images/SCALE/DataProtection/StorjAddBucket.png
  static/images/SCALE/DataProtection/StorjBucketAdded.png
  static/images/SCALE/DataProtection/StorjCreateABucketScreen.png
  static/images/SCALE/DataProtection/StorjEncryptYourBucketScreen.png
  static/images/SCALE/Datasets/StoragePoolsOptionsEditPermissionsACLPresetHome.png
  static/images/SCALE/Storage/DevicesExtend.png
  static/images/SCALE/SystemSettings/SidegradeInstallManualUpdate.png
  static/images/SCALE/SystemSettings/SidegradeRestart.png
  static/images/SCALE/SystemSettings/SidegradeSaveConfig.png
  static/images/SCALE/SystemSettings/SidegradeSetInstallFile.png
  static/images/SCALE/ZFSFeatureFlagsRemovalExample1.png
  static/images/SCALE/ZFSFeatureFlagsRemovalExample2.png
  static/images/SCALE/ZFSFeatureFlagsRemovalExample3.png
  static/images/SCALE/ZFSFeatureFlagsRemovalExample4.png
  static/includes/CustomAppEE.md
  static/includes/EarlyReleaseWarning.md
  static/includes/apps/AppInstallWizardACLConfiguration.md
  static/includes/apps/AppWizardStorageSMBOption.md
  static/includes/apps/AppsBestPractices.md
  static/includes/apps/AppsCustomApp.md
  static/includes/apps/AppsDatasets.md
  static/includes/apps/AppsPool.md
  static/includes/apps/MinIODatasetRequirements.md
Labels: Technical Writer Review (LM)

#3487 PD-1603 / 25.04 / Pd 1603 create fibre channel articles
  content/SCALE/GettingStarted/Migrate/MigratePrep.md
  content/SCALE/SCALETutorials/Shares/iSCSI/SettingUpFibreChannel.md
  content/SCALE/SCALEUIReference/Shares/FibreChannelScreens.md
  content/SCALE/SCALEUIReference/Shares/iSCSISharesScreens.md
  static/images/SCALE/Shares/AddiSCSITargetFC.png
  static/images/SCALE/Shares/ChangeNumberofVirtualPortsDialog.png
  static/images/SCALE/Shares/EditiSCSITargetFC.png
  static/images/SCALE/Shares/GlobalTargetConfigurationScreeninHA.png
  static/images/SCALE/Shares/SharesScreenFC.png
  static/images/SCALE/Shares/iSCSAuthorizedAccessScreenFC.png
  static/images/SCALE/Shares/iSCSIExtentsScreenFC.png
  static/images/SCALE/Shares/iSCSIFibreChannelPortsScreen.png
  static/images/SCALE/Shares/iSCSIInitiatorsScreenFC.png
  static/images/SCALE/Shares/iSCSIPortalsScreenFC.png
  static/images/SCALE/Shares/iSCSITargetsScreenwFC.png
  static/images/SCALE/Shares/iSCSIWizardExtentScreenFCAddNew.png
  static/images/SCALE/Shares/iSCSIWizardProtocolOptionsScreenCreateNewVirtualPort.png
  static/images/SCALE/Shares/iSCSIWizardProtocolOptionsScreenFC.png
  static/images/SCALE/Shares/iSCSIWizardTargetScreenFC.png
  static/includes/TargetiSCSIGroupSettings.md
  static/includes/iSCSIAddEditAuthorizedAccesssScreens.md
  static/includes/iSCSIAddEditExtentSettings.md
  static/includes/iSCSIAddEditPortalsScreens.md
  static/includes/iSCSIAddInitiatorSettings.md
  static/includes/iSCSIDeleteExtent.md
  static/includes/iSCSIEditInitiatorSettings.md
  static/includes/iSCSIExtentScreens.md
  static/includes/iSCSIGlobalConfigurationScreen.md
  static/includes/iSCSIRemoveExtentAssociation.md
  static/includes/iSCSITargetAssociate.md
  static/includes/iSCSITargetDelete.md
  static/includes/iSCSIWizardExtentScreen.md
Labels: Technical Writer Review (TR), backport-25.04

#3522 PD-1755 / 25.10 / Pd 1755 create placeholders
  content/Solutions/Integrations/Nextcloud.md
  content/TruenasApps/AppSecurity/CloudflareTunnel.md
  content/TruenasApps/CommunityApps/Rsyncd.md
  content/TruenasApps/CommunityApps/WebDAV.md
  content/TruenasApps/CommunityApps/calibre-web.md
  content/TruenasApps/CommunityApps/calibre.md
  content/TruenasApps/CommunityApps/dozzle.md
  content/TruenasApps/CommunityApps/duplicati.md
  content/TruenasApps/CommunityApps/eclipse-mosquitto.md
  content/TruenasApps/CommunityApps/esphome.md
  content/TruenasApps/CommunityApps/filestash.md
  content/TruenasApps/CommunityApps/gaseous-server.md
  content/TruenasApps/CommunityApps/gitea-act-runner.md
  content/TruenasApps/CommunityApps/glances.md
  content/TruenasApps/CommunityApps/handbrake-web.md
  content/TruenasApps/CommunityApps/heimdall.md
  content/TruenasApps/CommunityApps/iconik-storage-gateway.md
  content/TruenasApps/CommunityApps/influxdb.md
  content/TruenasApps/CommunityApps/invoice-ninja.md
  content/TruenasApps/CommunityApps/it-tools.md
  content/TruenasApps/CommunityApps/jackett.md
  content/TruenasApps/CommunityApps/jelu.md
  content/TruenasApps/CommunityApps/lyrion-music-server.md
  content/TruenasApps/CommunityApps/minecraft-bedrock.md
  content/TruenasApps/CommunityApps/octoprint.md
  content/TruenasApps/CommunityApps/open-speed-test.md
  content/TruenasApps/CommunityApps/postgres.md
  content/TruenasApps/CommunityApps/romm.md
  content/TruenasApps/CommunityApps/satisfactory-server.md
  content/TruenasApps/CommunityApps/scrutiny.md
  content/TruenasApps/CommunityApps/steam-headless.md
  content/TruenasApps/CommunityApps/tftpd-hpa.md
  content/TruenasApps/CommunityApps/tianji.md
  content/TruenasApps/CommunityApps/umami.md
  content/TruenasApps/CommunityApps/uptime-kuma.md
  content/TruenasApps/CommunityApps/urbackup.md
  content/TruenasApps/CommunityApps/wyze-bridge.md
  content/TruenasApps/CommunityApps/zigbee2mqtt.md
  content/TruenasApps/EnterpriseApps/Syncthing.md
  content/TruenasApps/EnterpriseApps/asigra-ds-system.md
  content/TruenasApps/EnterpriseApps/ix-remote-assist.md
  content/TruenasApps/StableApps/Collabora.md
  content/TruenasApps/StableApps/Photoprism.md
  content/TruenasApps/StableApps/diskoverdata.md
  content/TruenasApps/StableApps/elastic-search.md
  content/TruenasApps/StableApps/emby.md
  content/TruenasApps/StableApps/home-assistant.md
  content/TruenasApps/StableApps/netdata.md
  content/TruenasApps/StableApps/nextcloud.md
  content/TruenasApps/StableApps/pihole.md
  content/TruenasApps/StableApps/plex.md
  content/TruenasApps/StableApps/prometheus.md
  content/TruenasApps/StableApps/storj.md
  content/TruenasApps/StableApps/syncthing.md
  content/TruenasApps/StableApps/wg-easy.md
  content/TruenasApps/_index.md
  scripts/generate_app_docs.py
  static/includes/CreatePool.md
Labels: Technical Writer Review (TR)

#3536 PD-1603 / 25.10 / PD-1603 Fix Image Spelling in Fibre Channel Screens
  content/SCALE/SCALEUIReference/Shares/FibreChannelScreens.md
  static/images/SCALE/Shares/iSCSIAuthorizedAccessScreenFC.png
  static/images/SCALE/Shares/iSCSITargetsScreensFC.png
Labels: Technical Writer Review (TR)

#3535 PD-1603 / 25.04 / Pd 1603 create fibre channel articles (by micjohnson777)
  content/SCALETutorials/Shares/SettingUpFibreChannel.md
  content/SCALEUIReference/Shares/FibreChannelScreens.md
  content/SCALEUIReference/Shares/iSCSISharesScreens.md
  static/images/SCALE/Shares/AddiSCSITargetFC.png
  static/images/SCALE/Shares/ChangeNumberofVirtualPortsDialog.png
  static/images/SCALE/Shares/EditiSCSITargetFC.png
  static/images/SCALE/Shares/GlobalTargetConfigurationScreeninHA.png
  static/images/SCALE/Shares/SharesScreenFC.png
  static/images/SCALE/Shares/iSCSAuthorizedAccessScreenFC.png
  static/images/SCALE/Shares/iSCSIAuthorizedAccessScreenFC.png
  static/images/SCALE/Shares/iSCSIExtentsScreenFC.png
  static/images/SCALE/Shares/iSCSIFibreChannelPortsScreen.png
  static/images/SCALE/Shares/iSCSIInitiatorsScreenFC.png
  static/images/SCALE/Shares/iSCSIPortalsScreenFC.png
  static/images/SCALE/Shares/iSCSITargetsScreensFC.png
  static/images/SCALE/Shares/iSCSIWizardExtentScreenFCAddNew.png
  static/images/SCALE/Shares/iSCSIWizardProtocolOptionsScreenCreateNewVirtualPort.png
  static/images/SCALE/Shares/iSCSIWizardProtocolOptionsScreenFC.png
  static/images/SCALE/Shares/iSCSIWizardTargetScreenFC.png
  static/includes/iSCSIAddEditAuthorizedAccesssScreens.md
  static/includes/iSCSIAddEditExtentSettings.md
  static/includes/iSCSIAddEditPortalsScreens.md
  static/includes/iSCSIAddInitiatorSettings.md
  static/includes/iSCSIDeleteExtent.md
  static/includes/iSCSIEditInitiatorSettings.md
  static/includes/iSCSIExtentScreens.md
  static/includes/iSCSIGlobalConfigurationScreen.md
  static/includes/iSCSIRemoveExtentAssociation.md
  static/includes/iSCSITargetAssociate.md
  static/includes/iSCSITargetDelete.md
  static/includes/iSCSIWizardExtentScreen.md
Labels: Technical Writer Review (TR)

#3531 Update DeveloperMode.md to mention boot enviornment name
  content/SCALE/SCALETutorials/SystemSettings/Advanced/DeveloperMode.md
Labels: Technical Writer Review (TR), Technical Writer Review (DP)

#3538 Add experimental notice to NAS users and groups descriptor in TC 3.0 docs
  content/UserGuide/SystemManagement/_index.md
Labels: Version Specific, Technical Writer Review (TR)

#3524 PD-1755 / 25.04 / Pd 1755 move cleanup script and run
  scripts/cleanup.ps1
  scripts/cleanup_log.txt
  static/images/CORE/Accounts/AddUserNamedCORE.png
  static/images/CORE/DirectoryServices/DirectoryServicesNIS.png
  static/images/CORE/Services/NFSServicesScreen.png
  static/images/CORE/Sharing/SharingSMBAdvancedOptions.png
  static/images/CORE/Storage/StorageAllPoolsDataset.png
  static/images/CORE/Storage/StoragePoolsAddDataset2.png
  static/images/CORE/System/CloudCredentialsAddCredentials.png
  static/images/CORE/System/SystemCloudCredentialsOAuthLogin.png
  static/images/CORE/System/SystemNTPServersAdd.png
  static/images/CORE/Tasks/RsyncConfigure.png
  static/images/CORE/Tasks/TasksCloudSyncAdd.png
  static/includes/MakeDirectory.md
  static/includes/apps/InstallWizardDefaultPorts.md
Labels: Technical Writer Review (LM), Re-Review

#3539 PD-1689 / 25.10 / Pd 1689 update nextcloud app tutorial
  content/Contributing/Applications/AppArticleTemplate.md
  content/Contributing/Applications/_index.md
  content/TruenasApps/StableApps/nextcloud.md
  static/images/SCALE/Apps/InstallAppStorageConfigurationACLandACESettings.png
  static/images/SCALE/Apps/InstallNextcloudConfig1.png
  static/images/SCALE/Apps/InstallWizardPostgresDatasetAutomaticPermissions.png
  static/includes/apps/BeforeYouBeginAddAppDatasets.md
  static/includes/apps/InstallWizardPostgresStorageAutomaticPermissions.md
  static/includes/apps/InstallWizardStorageACLConfig.md
Labels: Technical Writer Review (TR)

#3544 Update plex-auto-languages.md
  content/TruenasApps/CommunityApps/plex-auto-languages.md
Labels: Review (TM)

#3547 PD-1805 / 25.10 / samba auth rename (master)
  content/SCALE/GettingStarted/Configure/SetUpSharing.md
  content/SCALE/SCALETutorials/Credentials/ManageLocalGroups.md
  content/SCALE/SCALETutorials/Shares/SMB/_index.md
Labels: Technical Writer Review (MJ)

#3546 PD-1805 / 25.04 / samba authentication rename (25.04)
  content/GettingStarted/Configure/SetUpSharing.md
  content/SCALETutorials/Credentials/ManageLocalGroups.md
  content/SCALETutorials/Shares/SMB/_index.md
Labels: Version Specific

#3545 PD-1805 / 24.10 / Update credentials > Samba Authentication field name (24.10 branch)
  content/GettingStarted/Configure/SetUpSharing.md
  content/SCALETutorials/Credentials/ManageLocalGroups.md
  content/SCALETutorials/Shares/SMB/_index.md
  content/SCALEUIReference/Credentials/LocalGroupsScreens.md
Labels: Version Specific, Technical Writer Review (MJ)

#3543 PD-1803 / 25.10 / Clarify Apps Support Tiers
  assets/sprites/support.svg
  content/TruenasApps/AppSecurity/CloudflareTunnel.md
  content/TruenasApps/CommunityApps/Chia.md
  content/TruenasApps/CommunityApps/WebDAV.md
  content/TruenasApps/CommunityApps/_index.md
  content/TruenasApps/CommunityApps/tftpd-hpa.md
  content/TruenasApps/EnterpriseApps/asigra-ds-system.md
  content/TruenasApps/StableApps/_index.md
  content/TruenasApps/StableApps/diskoverdata.md
  content/TruenasApps/StableApps/emby.md
  content/TruenasApps/StableApps/netdata.md
  content/TruenasApps/StableApps/nextcloud.md
  content/TruenasApps/StableApps/plex.md
  content/TruenasApps/StableApps/prometheus.md
  content/TruenasApps/Support-Definitions.md
  static/includes/apps/Apps-Community-Support.md
  static/includes/apps/EnterpriseApps.md
  words-to-ignore.txt
Labels: Technical Writer Review (DP), Re-Review
