Repository truenas/documentation, pull requests merged in 2025-04, with the labels that each got.

#3646 PD-1844 / 25.10 / Pd 1844 train docs team on administrative scripts
  content/TruenasApps/CommunityApps/arti.md
  content/TruenasApps/CommunityApps/authelia.md
  content/TruenasApps/CommunityApps/codegate.md
  content/TruenasApps/CommunityApps/flood.md
  content/TruenasApps/CommunityApps/i2p.md
  content/TruenasApps/CommunityApps/jdownloader2.md
  content/TruenasApps/CommunityApps/kasm-workspaces.md
  content/TruenasApps/CommunityApps/kerberos-agent.md
  content/TruenasApps/CommunityApps/mariadb.md
  content/TruenasApps/CommunityApps/monero-wallet-rpc.md
  content/TruenasApps/CommunityApps/monerod.md
  content/TruenasApps/CommunityApps/monitee-agent.md
  content/TruenasApps/CommunityApps/nzbget.md
  content/TruenasApps/CommunityApps/onlyoffice-document-server.md
  content/TruenasApps/CommunityApps/scrypted.md
  content/TruenasApps/CommunityApps/stirling-pdf.md
  content/TruenasApps/CommunityApps/unmanic.md
  scripts/cleanup_log.txt
  static/images/CORE/System/Login2FA.png
  static/images/Hardware/ExpansionShelves/ES12BSG.png
  static/images/Hardware/RSeries/R50BSG.png
  static/images/Hardware/RSeries/RSeriesBSG.png
  static/images/SCALE/Apps/AddNextcloudParentDatasetNetdataUserACL.png
  static/images/SCALE/Apps/AddPostgres_DataACLPermissions.png
  static/images/SCALE/Apps/AppsTrainSettingsScreen.png
  static/images/SCALE/Apps/InstallNextcloudStorageDataACLandACESettings.png
  static/images/SCALE/Apps/SetPostgres_dataACLtoPOSIX.png
  static/images/TrueNAS_Open_Enterprise_Storage.png
  static/images/truenas_enterprise-logo-full-color-rgb.png
  static/includes/25.04FeatureList.md
  static/includes/ThirdPartyCatalogs.md
Labels: Technical Writer Review (TR)

#3657 PD-1760 / 25.04 / PD-1760-traverse-permissions-are-difficult-to-understand
  static/includes/AddNewSMBShareGroupAndACE.md
Labels: Technical Writer Review (DP), Re-Review

#3652 PD-1667 / 25.04 / PD-1667-investigate-and-document-disk-replacement-procedure-for-non-hotswappable-systems
  content/SCALETutorials/Storage/Disks/ReplacingDisks.md
Labels: Technical Writer Review (MJ), Re-Review, backport-24.10

#3661 PD-1697 / 25.04 / PD-1697-fix-smart-tests-advanced-scheduler-docs
  static/includes/SCALEAdvancedScheduler.md
Labels: Technical Writer Review (TR), backport-24.10

#3663 PD-1753 / 25.10 / Pd 1753 add preparing install media option instructions
  content/SCALE/GettingStarted/Install/InstallingSCALE.md
  static/includes/Rufus.md
  static/includes/Ventoy.md
Labels: Technical Writer Review (TR)

#3662 PD-1667 / 24.10 / PD-1667-investigate-and-document-disk-replacement-procedure-for-non-hotswappable-systems (by linzi-ix)
  content/SCALETutorials/Storage/Disks/ReplacingDisks.md
Labels: Technical Writer Review (TR)

#3664 PD-1697 / 24.10 / PD-1697-fix-smart-tests-advanced-scheduler-docs (by linzi-ix)
  static/includes/SCALEAdvancedScheduler.md
Labels: Technical Writer Review (TR)

#3670 Update SCALEReleaseNotes.md
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Technical Writer Review (TR)

#3669 Minor styling improvement for docsbot embed
  content/_index.md
Labels: Technical Writer Review (TR)

#3665 PD-1868 / 24.10 / PD-1868 - 24.10.2.1 release docs
  content/GettingStarted/SCALEReleaseNotes.md
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
Labels: Version Specific

#3676 Fix up some errors caught by ahrefs testing (TC 3.0 branch)
  content/UserGuide/ReplicationManagement.md
  static/includes/TCCloudConnectSystems.md
Labels: Version Specific, Technical Writer Review (TR)

#3677 Ahrefs testing fixes (master branch)
  content/SCALE/API/_index.md
  content/SCALE/SCALETutorials/Instances/_index.md
  content/SCALE/SCALETutorials/SystemSettings/General/_index.md
  content/SCALE/SCALEUIReference/InstancesScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  content/TruenasApps/CommunityApps/_index.md
  content/TruenasApps/CommunityApps/zigbee2mqtt.md
  static/images/Hardware/Minis/MiniX+BSG.png
  static/images/Hardware/Minis/MiniX+OOBM.png
  static/images/Hardware/Minis/MiniX+SOV.png
  static/images/SCALE/DataProtection/AdvancedAddReplicationTaskGeneralTransportSSH+NETCAT.png
  static/includes/AccessSettingsWidget.md
Labels: Version Specific, Technical Writer Review (TR)

#3679 PD-1872 / 24.10 / Pd 1872 review reporting content for obsolete netdata references
  content/SCALETutorials/ConfigReportsScale.md
  static/includes/NetdataUI.md
  static/includes/netdatareporting.md
Labels: Technical Writer Review (TR)

#3678 PD-1862 / 25.10 / Pd 1862 create enterprise ad content
  content/SCALE/SCALETutorials/Credentials/DirectoryServices/ConfigADSCALE.md
  content/SCALE/SCALETutorials/Credentials/ManageLocalGroups.md
  content/SCALE/SCALETutorials/SystemSettings/Advanced/_index.md
  content/SCALE/SCALEUIReference/Credentials/LocalGroupsScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  static/images/SCALE/SystemSettings/AccessSettingsScreenEnterprise.png
  static/includes/AccessSettingsWidget.md
  static/includes/AccessWidget.md
  static/includes/AddPrivilege.md
  static/includes/ConfigureAccessSettings.md
Labels: Technical Writer Review (LM), Re-Review, backport-25.04, backport-24.10

#3675 PD-1827 / 13.0 / PD-1827-improve-core-virtualization-messaging
  static/includes/COREFeatureSupport.md
Labels: Technical Writer Review (MJ), Re-Review, backport-13.3

#3672 PD-1266 / 13.0 / PD-1266 Update Rsync Task Content
  content/CORETutorials/Tasks/CreatingRsyncTasks.md
Labels: Technical Writer Review (LM), Re-Review, backport-13.3

#3642 PD-1682 / 25.10 / PD-1682 Add Postgres and run-as user ACL information
  static/includes/apps/AppsDatasets.md
  static/includes/apps/HostPathACL.md
  static/includes/apps/InstallWizardPostgresStorageAutomaticPermissions.md
Labels: Technical Writer Review (DP), Re-Review

#3684 PD-1836 / 25.04 / PD-1836-remove-proxy-field-from-instances-v-ms-content
  content/SCALETutorials/Instances/_index.md
  static/includes/InstancesManagingProxies.md
Labels: Technical Writer Review (MJ), Re-Review

#3688 PD-1848 / 25.10 / Pd 1848 follow up 25 04 0 release notes
  content/SCALE/SCALETutorials/ConfigReportsScale.md
  content/TruenasApps/CommunityApps/archisteamfarm.md
  content/TruenasApps/CommunityApps/authentik.md
  content/TruenasApps/CommunityApps/cockpit-ws.md
  content/TruenasApps/CommunityApps/code-server.md
  content/TruenasApps/CommunityApps/crafty-4.md
  content/TruenasApps/CommunityApps/forgejo.md
  content/TruenasApps/CommunityApps/karakeep.md
  content/TruenasApps/CommunityApps/mitmproxy.md
  content/TruenasApps/CommunityApps/monero-lws.md
  content/TruenasApps/CommunityApps/outline.md
  content/TruenasApps/CommunityApps/tvheadend.md
  data/properties/component_versions.yaml
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  layouts/partials/docs-nav.html
  layouts/shortcodes/component-versions.html
  layouts/shortcodes/section-cards.html
  scripts/cleanup_log.txt
  static/images/SCALE/Reporting/NetdataCredentialsDialog.png
  static/images/SCALE/Reporting/NetdataUI.png
  static/images/SCALE/Virtualization/AddVMGPU.png
  static/images/SCALE/Virtualization/AddVMInstallMedia.png
  static/images/SCALE/Virtualization/AddVMMemory.png
  static/images/SCALE/Virtualization/AddVMNetwork.png
  static/images/SCALE/Virtualization/AddVMOperSys.png
  static/images/SCALE/Virtualization/CreateInstanceScreen.png
  static/images/SCALE/Virtualization/CreateInstanceZvol.png
  static/images/SCALE/Virtualization/CreateVMWInstallMediaUploadSCALE.png
  static/images/SCALE/Virtualization/CreateVirtualMachineDisks.png
  static/images/SCALE/Virtualization/DeleteVirtualMachine.png
  static/images/SCALE/Virtualization/EditDeviceDiskScreen.png
  static/images/SCALE/Virtualization/InstancesConfigurationMenu.png
  static/images/SCALE/Virtualization/ScaleDebianVMOsSystem.png
  static/images/SCALE/Virtualization/VMAddDeviceCDROM.png
  static/images/SCALE/Virtualization/VMAddDeviceDisk.png
  static/images/SCALE/Virtualization/VMAddDeviceDisplay.png
  static/images/SCALE/Virtualization/VMAddDeviceNIC.png
  static/images/SCALE/Virtualization/VMAddDevicePCIpass.png
  static/images/SCALE/Virtualization/VMAddDeviceUSBpass.png
  static/images/SCALE/Virtualization/VMDevicesListed.png
  static/images/SCALE/Virtualization/VirtualMachinesScreenwithVMDetails.png
  static/includes/NetdataUI.md
  static/includes/SCALEUpgradePaths.md
  static/includes/netdatareporting.md
Labels: Version Specific

#3690 PD-1848 / 24.10 / Pd 1848 follow up navigation
  layouts/partials/docs-nav.html
Labels: Technical Writer Review (LM), backport-24.04, backport-13.3, backport-13.0, backport-3.0

#3696 Add notice about updater issue to 25.04.0 relnotes
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific, Technical Writer Review (LM)

#3698 (25.04.0) Remove republish notice as it is no longer relevant
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific

#3701 Pd 1862 typo fix
  content/SCALETutorials/Credentials/ManageLocalGroups.md
  static/includes/ConfigureAccessSettings.md
Labels: backport-25.04, backport-25.10

#3704 PD-1708 / 24.10 / PD-1708-windows-users-verifying-sha-256-checksums-natively (by linzi-ix)
  content/GettingStarted/Install/InstallingSCALE.md
Labels: Technical Writer Review (TR)

#3705 Add time machine/multiprotocol advisory 25.10
  content/SCALE/SCALETutorials/Shares/MixedModeShares.md
  content/SCALE/SCALETutorials/Shares/SMB/SetUpBasicTimeMachineSMBShare.md
  static/includes/TimeMachineMultiprotocol.md
Labels: Technical Writer Review (TR)

#3695 Update SettingUpVLAN.md
  content/SCALETutorials/Network/Interfaces/SettingUpVLAN.md
Labels: Technical Writer Review (MJ), backport-24.10, backport-24.04, backport-25.10

#3708 25.04.0 Escalate known issue with previous instance pool import
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific

#3709 Remove known issue escalation about importing instance pool
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific

#3668 PD-1683 / 25.10 / Pd 1683 update config file secret seed content
  content/SCALE/GettingStarted/Configure/UIConfigurationSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/General/ManageSysConfigSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/UpdateHASCALE.md
  content/SCALE/SCALETutorials/SystemSettings/UpdateSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/UpdateScreensSCALE.md
  static/includes/DownloadSystemConfigFileSCALE.md
  static/includes/SecretSeed.md
Labels: Technical Writer Review (DP), Technical Writer Review (LM), Re-Review, backport-25.04, backport-24.10

#3680 PD-1860 / 25.10 / PD-1860 Update Reporting UI Ref
  content/SCALE/SCALEUIReference/ReportingScreensSCALE.md
  static/images/SCALE/Reporting/CPUReportingSystemLoad.png
  static/images/SCALE/Reporting/CPUReportingUsageTemp.png
  static/images/SCALE/Reporting/DiskReportingIO.png
  static/images/SCALE/Reporting/DiskReportingTemperature.png
  static/images/SCALE/Reporting/DisksReportingScreen.png
  static/images/SCALE/Reporting/NetworkReportingIntTraffic.png
  static/images/SCALE/Reporting/ReportingExportersScreen.png
  static/images/SCALE/Reporting/SystemReportingProcessUptime.png
  static/images/SCALE/Reporting/UPSReportingChargingRuntime.png
  static/images/SCALE/Reporting/ZFSReportingARCSizeResult.png
Labels: Technical Writer Review (DP), Re-Review, backport-25.04, backport-24.10

#3716 Clarify some of the Apps port binding changes and disruptiveness
  static/includes/AppsHostIP.md
  static/includes/AppsSupportTimeline.md
Labels: Version Specific

#3719 Clarify App Timelines
  static/includes/AppsHostIP.md
  static/includes/AppsSupportTimeline.md
Labels: Manual Backport Required, backport-24.10

#3718 PD-1878 Modernize Veeam Documentation
  content/Solutions/Integrations/Veeam.md
Labels: Technical Writer Review (MJ)

#3721 PD-1911 / 25.10 / PD-1911 Update User Details Screenshot
  content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
  static/images/SCALE/Credentials/UserScreenUserDetails.png
Labels: Technical Writer Review (LM), backport-25.04

#3722 PD-1919 / 25.10 / PD-1919 Update Dashboard, Top Toolbar, and Tasks/Jobs Content
  content/SCALE/SCALETutorials/Storage/ManagePoolsScale.md
  content/SCALE/SCALEUIReference/SCALEDashboard.md
  content/SCALE/SCALEUIReference/TopToolbar/JobsScreens.md
  content/SCALE/SCALEUIReference/TopToolbar/_index.md
  static/images/SCALE/Dashboard/DashboardHelpWidget.png
  static/images/SCALE/Dashboard/JobsFailed.png
  static/images/SCALE/Dashboard/JobsMenu.png
  static/images/SCALE/Dashboard/JobsScreen.png
  static/includes/Jobs.md
Labels: Technical Writer Review (LM), backport-25.04

#3723 PD-1921 / 25.10 / PD-1921 Update the AuditScreen.png
  content/SCALE/SCALETutorials/SystemSettings/AuditingSCALE.md
  static/images/SCALE/SystemSettings/SystemSettingsAuditScreen.png
Labels: Technical Writer Review (LM), backport-25.04

#3710 PD-1893 / 25.10 / PD-1893 Add Additional Information on STIG
  content/SCALE/SCALETutorials/SystemSettings/Advanced/_index.md
Labels: Review (TM)

#3711 PD-1683 / 24.10 / Pd 1683 update config file secret seed content (by micjohnson777)
  content/SCALETutorials/SystemSettings/General/ManageSysConfigSCALE.md
  content/SCALETutorials/SystemSettings/UpdateHASCALE.md
  content/SCALETutorials/SystemSettings/UpdateSCALE.md
  content/SCALEUIReference/SystemSettings/UpdateScreensSCALE.md
  static/includes/DownloadSystemConfigFileSCALE.md
  static/includes/SecretSeed.md
Labels: Technical Writer Review (TR)

#3712 PD-1683 / 25.04 / Pd 1683 update config file secret seed content (by micjohnson777)
  content/GettingStarted/Configure/UIConfigurationSCALE.md
  content/SCALETutorials/SystemSettings/General/ManageSysConfigSCALE.md
  content/SCALETutorials/SystemSettings/UpdateHASCALE.md
  content/SCALETutorials/SystemSettings/UpdateSCALE.md
  content/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md
  content/SCALEUIReference/SystemSettings/UpdateScreensSCALE.md
  static/includes/DownloadSystemConfigFileSCALE.md
  static/includes/SecretSeed.md
Labels: Technical Writer Review (TR)

#3714 PD-1860 / 25.04 / PD-1860 Update Reporting UI Ref (by micjohnson777)
  content/SCALEUIReference/ReportingScreensSCALE.md
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#3713 PD-1860 / 24.10 / PD-1860 Update Reporting UI Ref (by micjohnson777)
  content/SCALEUIReference/ReportingScreensSCALE.md
  static/images/SCALE/Reporting/CPUReportingSystemLoad.png
  static/images/SCALE/Reporting/CPUReportingUsageTemp.png
  static/images/SCALE/Reporting/DiskReportingIO.png
  static/images/SCALE/Reporting/DiskReportingTemperature.png
  static/images/SCALE/Reporting/DisksReportingScreen.png
  static/images/SCALE/Reporting/NetworkReportingIntTraffic.png
  static/images/SCALE/Reporting/ReportingExportersScreen.png
  static/images/SCALE/Reporting/SystemReportingProcessUptime.png
  static/images/SCALE/Reporting/UPSReportingChargingRuntime.png
  static/images/SCALE/Reporting/ZFSReportingARCSizeResult.png
  words-to-ignore.txt
Labels: Technical Writer Review (TR)

#3715 PD-1724 / 25.04 / PD-1724-review-nfs-maproot-descriptions
  content/SCALETutorials/Shares/AddingNFSShares.md
  content/SCALEUIReference/Shares/NFSSharesScreens.md
Labels: Technical Writer Review (TR)

#3727 PD-1921 / 25.04 / PD-1921 Update the AuditScreen.png (by micjohnson777)
  content/SCALETutorials/SystemSettings/AuditingSCALE.md
  static/images/SCALE/SystemSettings/SystemSettingsAuditScreen.png
Labels: Technical Writer Review (TR)

#3736 PD-1855-update-stencil-pack-f-series
  content/Hardware/FSeries.md
Labels: Technical Writer Review (MJ)

#3735 Update MiniFamily.md
  content/Hardware/MiniFamily.md
Labels: Technical Writer Review (MJ)

#3734 PD-1859 / 25.10 / Pd 1859 zfscapacitycalculator doesnt show with dark mode
  layouts/shortcodes/capacity_calculator.html
  static/custom.css
Labels: Technical Writer Review (MJ)

#3738 Update MSeries.md
  content/Hardware/MSeries.md
Labels: Technical Writer Review (MJ)

#3739 PD-1876 / 25.10 / PD-1876-docs-search-weirdness
  layouts/search/list.html
Labels: Technical Writer Review (MJ), backport-25.04, backport-24.10, backport-24.04, backport-13.3, backport-13.0, backport-3.0

#3745 PD-1876 / 3.0 / PD-1876-docs-search-weirdness (by DjP-iX)
  layouts/search/list.html
Labels: Technical Writer Review (MJ)

#3743 PD-1876 / 24.10 / PD-1876-docs-search-weirdness (by DjP-iX)
  layouts/search/list.html
Labels: Technical Writer Review (MJ)

#3742 PD-1876 / 24.04 / PD-1876-docs-search-weirdness (by DjP-iX)
  layouts/search/list.html
Labels: Technical Writer Review (MJ)

#3748 Update SCALEReleaseNotes.md
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Review (TM)

#3741 PD-1876 / 13.3 / PD-1876-docs-search-weirdness (by DjP-iX)
  layouts/search/list.html
Labels: Technical Writer Review (MJ)

#3737 PD-1926 / 25.10 / Pd 1926 update boot environments content
  content/SCALE/SCALETutorials/SystemSettings/ManageBootEnvironSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/SystemBootScreensSCALE.md
  static/images/SCALE/SystemSettings/BootEnvironmentBatchListingSCALE.png
  static/images/SCALE/SystemSettings/BootEnvironmentListingSCALE.png
  static/images/SCALE/SystemSettings/BootPoolStatusAttachDiskSCALE.png
  static/images/SCALE/SystemSettings/BootPoolStatusListingSCALE.png
  static/images/SCALE/SystemSettings/BootPoolStatusReplaceDiskSCALE.png
  static/images/SCALE/SystemSettings/CloneBootEnvironmentSCALE.png
Labels: Review (TM), Re-Review

#3729 PD-1925 / 25.10 / PD-1925 Update Cloud Sync Task Screens Article
  content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
  static/images/SCALE/DataProtection/AddCloudSyncTaskPushControlAdvancedOptions.png
Labels: Review (TM), Re-Review, backport-25.04

#3725 PD-1923 / 25.10 / Pd 1923 update storage and dashboard screenshots
  content/SCALE/SCALEUIReference/Datasets/_index.md
  content/SCALE/SCALEUIReference/Storage/DevicesScreensSCALE.md
  content/SCALE/SCALEUIReference/Storage/_index.md
  static/images/SCALE/Storage/DevicesDiskWidgets.png
  static/images/SCALE/Storage/StorageDashboardDiskHealthWidget.png
  static/includes/StorageCompressionLevelsScale.md
Labels: Review (TM), Re-Review, backport-25.04

#3726 PD-1919 / 25.04 / PD-1919 Update Dashboard, Top Toolbar, and Tasks/Jobs Content (by micjohnson777)
  content/SCALEUIReference/TopToolbar/TasksScreens.md
  content/SCALEUIReference/TopToolbar/_index.md
  static/images/SCALE/Dashboard/JobsFailed.png
  static/images/SCALE/Dashboard/JobsMenu.png
  static/images/SCALE/Dashboard/JobsScreen.png
  static/includes/Jobs.md
Labels: Review (TM), Re-Review

#3728 PD-1924 / 25.10 / Pd 1924 update group privileges screen content
  content/SCALE/SCALEUIReference/Credentials/LocalGroupsScreens.md
  static/images/SCALE/Credentials/AddNewPrivilegeScreen.png
Labels: Review (TM), Re-Review, backport-25.04

#3752 Incus clarification
  static/includes/Incus.md
  static/includes/MigratingVMs.md
Labels: Review (TM)

#3756 Add AppsMarket banner to 25.04 apps content
  content/SCALEUIReference/Apps/InstallCustomAppScreens.md
  content/SCALEUIReference/Apps/_index.md
  static/includes/apps/AppsMarket.md
Labels: Technical Writer Review (LM)

#3757 Add Apps Market banner to 24.10 version docs
  content/SCALEUIReference/Apps/InstallCustomAppScreens.md
  content/SCALEUIReference/Apps/_index.md
  static/includes/apps/AppsMarket.md
Labels: Technical Writer Review (LM)

#3755 Update Apps Content banners to point to the new Applications Market (master)
  content/_index.md
  layouts/partials/page-header.html
  static/includes/apps/AppsMarket.md
Labels: Technical Writer Review (LM)

#3758 13.3-U1.2 release notes
  content/GettingStarted/COREReleaseNotes.md
  content/_index.md
  data/properties/core-downloads.yaml
  data/properties/core-releases.yaml
  layouts/partials/page-header.html
  static/includes/13.3FinalRelease.md
  static/includes/COREUpgradePaths.md
  words-to-ignore.txt
Labels: Version Specific, Technical Writer Review (TR)

#3760 PD-1688 / 25.10 / update NFS Sessions (master)
  content/SCALE/SCALEUIReference/Shares/NFSSharesScreens.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md
Labels: Technical Writer Review (MJ), backport-25.04

#3763 PD-1832 / 25.10 / master branch updates from instances dev work
  content/SCALE/SCALETutorials/Instances/_index.md
  content/SCALE/SCALEUIReference/InstancesScreens.md
  static/images/SCALE/Virtualization/InstanceStopOptions.png
Labels: Technical Writer Review (TR), backport-25.04

#3764 PD-1885 / 25.10 / Document Enterprise settings for admin password rules
  content/SCALE/SCALETutorials/SystemSettings/Advanced/_index.md
  content/SCALE/SCALETutorials/SystemSettings/_index.md
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
  static/images/SCALE/SystemSettings/SystemAdvancedSecurityWidget.png
  static/images/SCALE/SystemSettings/SystemSecurityScreen.png
Labels: Technical Writer Review (TR), backport-25.04

#3762 PD-1688 / 25.04 / update NFS Sessions (by Mrt134)
  content/SCALEUIReference/Shares/NFSSharesScreens.md
  content/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md
Labels: Technical Writer Review (TR)
