Repository truenas/documentation, pull requests merged in 2025-09, with the labels that each got.

#4099 Backport nvme of known issue
  content/SCALE/SCALETutorials/Shares/NVMe-oF/Managing-NVMe-of-Subsystems.md
  content/SCALE/SCALETutorials/Shares/NVMe-oF/_index.md
  static/includes/NVMeoTCPESXiLimitation.md
Labels: Technical Writer Review (LM)

#4101 PD-2173 / 26.04 / PD-2173-make-apps-market-links-more-prominent-on-the-docs-hub
  data/menu/more.yml
  static/custom.css
Labels: backport-25.04, backport-25.10

#4109 PD-2194 / 26.04 / PD-2194-services-simplification
  content/SCALE/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/SMBServicesScreen.md
  content/SCALE/SCALEUIReference/SystemSettings/Services/_index.md
  static/images/SCALE/SystemSettings/ServicesSCALE.png
Labels: Review (TM), backport-25.10

#4110 PD-2196 / 26.04 / Pd 2196 shell page simplification (by DjP-iX)
  content/SCALE/SCALETutorials/SystemSettings/UseScaleShell.md
  content/SCALE/SCALEUIReference/SystemSettings/ShellSCALE.md
  static/images/SCALE/CLI/SystemShellSCALE.png
Labels: Review (TM)

#4111 PD-2170 / 25.10 / PD-2170-mention-the-o-altroot-mnt-option-used-by-true-nas
  content/SCALETutorials/Storage/ImportPoolScale.md
Labels: Review (TM), backport-26.04

#4121 PD-2197 / 25.10 / Pd 2197 topbar item adjustments
  content/SCALETutorials/SystemSettings/General/_index.md
  content/SCALEUIReference/TopToolbar/_index.md
  layouts/shortcodes/themed-icon.html
  static/images/SCALE/Dashboard/FeedbackIcon.svg
  static/images/SCALE/Dashboard/GlobalSearchElementResult.png
  static/images/SCALE/Dashboard/JobsMenu.png
  static/images/SCALE/Dashboard/TNCIcon.svg
  static/images/SCALE/Dashboard/TNCIconActive.svg
  static/images/SCALE/Dashboard/TNCLoginScreen.png
  static/images/SCALE/Dashboard/TopToolbar.png
  static/images/SCALE/Dashboard/TrueCommandIcon.svg
  static/images/SCALE/Dashboard/TrueNASConnectDialog.png
  static/images/SCALE/Dashboard/TrueNASConnectDialogConnected.png
  static/images/SCALE/SystemSettings/ReportSimilarIssues.png
  static/includes/DirectoryServicesMonitor.md
  static/includes/FeedbackWindow.md
  static/includes/Jobs.md
  static/includes/StatusOfTrueCommand.md
  static/includes/TNCService.md
  static/includes/TopToolbar.md
  static/includes/UsingGlobalSearch.md
Labels: Review (TM)

#4096 PD-2211 / 25.04 / Pd 2211 25 04 2 4 release notes
  content/GettingStarted/SCALEReleaseNotes.md
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  static/includes/SCALEUpgradePaths.md
Labels: Version Specific

#4129 PD-2182 / 26.04 / Pd 2182 api docs site review display styling for minor release api version options
  data/properties/scale-releases.yaml
  layouts/shortcodes/releaselist.html
Labels: Review (TM)

#4131 PD-2211 / 25.10 / Pd 2211 25 04 2 4 release follow up (by DjP-iX)
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  static/includes/SCALEUpgradePaths.md
Labels: Technical Writer Review (LM)

#4146 PD-2253 / 25.10 / PD-2253 Update Delete NVMe Content (by micjohnson777)
  content/SCALETutorials/Shares/NVMe-oF/Managing-NVMe-of-Subsystems.md
  content/SCALEUIReference/Shares/nvme-of-screens.md
Labels: Technical Writer Review (DP)

#4139 PD-2181 / 26.04 / PD-2181-25-10-rc-1-onwards-engineering-changes-in-the-containers-area
  content/SCALE/SCALETutorials/Containers/_index.md
  content/SCALE/SCALEUIReference/ContainersScreens.md
  static/images/SCALE/Virtualization/CreateInstanceDisksContainer.png
  static/images/SCALE/Virtualization/CreateInstanceDisksVM.png
  static/images/SCALE/Virtualization/InstancesCreateVolume.png
  static/images/SCALE/Virtualization/InstancesScreenWithInstances.png
  static/images/SCALE/Virtualization/InstancesVolumesScreen.png
  static/images/SCALE/Virtualization/MapUserGroupIDs.png
Labels: Technical Writer Review (DP), backport-25.10

#4155 archive
  content/_index.md
  data/menu/more.yml
  data/properties/core-downloads.yaml
  data/properties/core-releases.yaml
  i18n/en.yaml
  layouts/partials/docs-nav.html
  scripts/cleanup_log.txt
  static/images/Contribute/JiraSuggestionCreate.png
  static/images/Contribute/JiraSuggestionVote.png
  static/includes/13.3FinalRelease.md
  static/includes/13.3Overview.md
  static/includes/CreateJiraSuggestion.md
  static/includes/_index.md
Labels: Technical Writer Review (DP)

#4173 PD-1951 / 26.04 / Pd 1951 update certificates content with TNC info
  content/SCALE/SCALETutorials/Credentials/Certificates/CertificatesSCALE.md
  static/images/SCALE/Credentials/CertificatesScreenWithTNCCert.png
Labels: Technical Writer Review (LM), backport-25.10

#4170 PD-2241 / 26.04 / PD-2241 Add 4420 as the default and recommended port number
  content/SCALE/SCALETutorials/Shares/NVMe-oF/Managing-NVMe-of-Subsystems.md
  content/SCALE/SCALETutorials/Shares/NVMe-oF/_index.md
  content/SCALE/SCALEUIReference/Shares/nvme-of-screens.md
Labels: Technical Writer Review (LM), backport-25.10

#4172 Update InstallTCDocker.md
  content/TCGettingStarted/Install/InstallTCDocker.md
Labels: Technical Writer Review (MJ)

#4180 PD-2206 / 25.04 / Pd 2206 update content around google photos use (by DjP-iX)
  content/SCALETutorials/DataProtection/CloudSyncTasks/AddGooglePhotosCloudSyncTask.md
Labels: Technical Writer Review (LM)

#4177 PD-2241 / 25.10 / PD-2241 Add 4420 as the default and recommended port number (by micjohnson777)
  content/SCALETutorials/Shares/NVMe-oF/Managing-NVMe-of-Subsystems.md
  content/SCALETutorials/Shares/NVMe-oF/_index.md
  content/SCALEUIReference/Shares/nvme-of-screens.md
Labels: Technical Writer Review (LM)

#4144 PD-1967 / 26.04 / Pd 1967 25 10 rc 1 follow up
  data/properties/scale-downloads.yaml
  data/properties/scale-releases.yaml
  scripts/cleanup_log.txt
Labels: Version Specific

#4189 (25.10) Add blurb to upgrade notes about metric system startup time
  content/GettingStarted/SCALEReleaseNotes.md
Labels: Version Specific, Technical Writer Review (LM)

#4163 PD-2147 / 26.04 / Update ManageInitShutdownSCALE.md
  content/SCALE/SCALETutorials/SystemSettings/Advanced/ManageInitShutdownSCALE.md
  content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
Labels: Technical Writer Review (TR), Re-Review, backport-25.10
